Repository openshift/machine-config-operator, pull requests merged in 2018-08, with the labels that each got.

#12 Inits Machine Config Daemon
  Gopkg.lock
  Gopkg.toml
  cmd/machine-config-daemon/main.go
  cmd/machine-config-daemon/start.go
  cmd/machine-config-daemon/version.go
  pkg/controller/node/node_controller.go
  pkg/controller/node/node_controller_test.go
  pkg/controller/node/status.go
  pkg/controller/node/status_test.go
  pkg/daemon/constants.go
  pkg/daemon/daemon.go
  pkg/daemon/node.go
  pkg/daemon/update.go
  vendor/github.com/coreos/go-systemd/login1/dbus.go
  vendor/github.com/go-log/log/LICENSE
  vendor/github.com/go-log/log/log.go
  vendor/github.com/godbus/dbus/LICENSE
  vendor/github.com/godbus/dbus/auth.go
  vendor/github.com/godbus/dbus/auth_external.go
  vendor/github.com/godbus/dbus/auth_sha1.go
  vendor/github.com/godbus/dbus/call.go
  vendor/github.com/godbus/dbus/conn.go
  vendor/github.com/godbus/dbus/conn_darwin.go
  vendor/github.com/godbus/dbus/conn_other.go
  vendor/github.com/godbus/dbus/dbus.go
  vendor/github.com/godbus/dbus/decoder.go
  vendor/github.com/godbus/dbus/default_handler.go
  vendor/github.com/godbus/dbus/doc.go
  vendor/github.com/godbus/dbus/encoder.go
  vendor/github.com/godbus/dbus/export.go
  vendor/github.com/godbus/dbus/homedir.go
  vendor/github.com/godbus/dbus/homedir_dynamic.go
  vendor/github.com/godbus/dbus/homedir_static.go
  vendor/github.com/godbus/dbus/message.go
  vendor/github.com/godbus/dbus/object.go
  vendor/github.com/godbus/dbus/server_interfaces.go
  vendor/github.com/godbus/dbus/sig.go
  vendor/github.com/godbus/dbus/transport_darwin.go
  vendor/github.com/godbus/dbus/transport_generic.go
  vendor/github.com/godbus/dbus/transport_tcp.go
  vendor/github.com/godbus/dbus/transport_unix.go
  vendor/github.com/godbus/dbus/transport_unixcred_dragonfly.go
  vendor/github.com/godbus/dbus/transport_unixcred_freebsd.go
  vendor/github.com/godbus/dbus/transport_unixcred_linux.go
  vendor/github.com/godbus/dbus/transport_unixcred_openbsd.go
  vendor/github.com/godbus/dbus/variant.go
  vendor/github.com/godbus/dbus/variant_lexer.go
  vendor/github.com/godbus/dbus/variant_parser.go
  vendor/github.com/wking/kubernetes-drain/LICENSE
  vendor/github.com/wking/kubernetes-drain/drain.go
  vendor/k8s.io/client-go/discovery/cached/memcache.go
Labels: size/XXL

#10 Machine Config Server implementation
  Gopkg.lock
  cmd/machine-config-server/bootstrap.go
  cmd/machine-config-server/main.go
  cmd/machine-config-server/start.go
  cmd/machine-config-server/version.go
  docs/MachineConfigServer.md
  pkg/daemon/node.go
  pkg/server/api.go
  pkg/server/api_test.go
  pkg/server/bootstrap_server.go
  pkg/server/cluster_server.go
  pkg/server/server.go
  pkg/server/server_test.go
  pkg/server/testdata/kubeconfig
  pkg/server/testdata/machine-configs/test-config.yaml
  pkg/server/testdata/machine-pools/test-pool.yaml
Labels: lgtm, size/XXL

#13 *: add OWNERS file
  OWNERS
  cmd/machine-config-daemon/OWNERS
  pkg/daemon/OWNERS
Labels: approved, lgtm, size/S

#19 *: fix owners file
  OWNERS
  cmd/machine-config-daemon/OWNERS
  pkg/daemon/OWNERS
Labels: approved, lgtm, size/XS

#16 README.md: Initial build information
  README.md
Labels: approved, lgtm, size/S

#15 machine-config-daemon: Update help to reference MCD
  cmd/machine-config-daemon/main.go
Labels: approved, lgtm, size/XS

#22 README.md: Add test instructions
  README.md
Labels: approved, kind/documentation, lgtm, retest-not-required-docs-only, size/S

#25 MachineConfigs and MachineConfigPools must be cluster scoped
  cmd/machine-config-daemon/start.go
  cmd/machine-config-server/start.go
  lib/resourceapply/apiext.go
  lib/resourceapply/machineconfig.go
  lib/resourceapply/machineconfig_test.go
  manifests/etcd.machineconfigpool.yaml
  manifests/machineconfig.crd.yaml
  manifests/machineconfigcontroller/deployment.yaml
  manifests/machineconfigdaemon/daemonset.yaml
  manifests/machineconfigpool.crd.yaml
  manifests/master.machineconfigpool.yaml
  manifests/worker.machineconfigpool.yaml
  pkg/apis/machineconfiguration.openshift.io/v1/machineconfig.deepcopy.go
  pkg/apis/machineconfiguration.openshift.io/v1/types.go
  pkg/apis/machineconfiguration.openshift.io/v1/zz_generated.deepcopy.go
  pkg/controller/node/node_controller.go
  pkg/controller/node/node_controller_test.go
  pkg/controller/node/status.go
  pkg/controller/render/render_controller.go
  pkg/controller/render/render_controller_test.go
  pkg/controller/template/template_controller.go
  pkg/controller/template/template_controller_test.go
  pkg/controller/util.go
  pkg/daemon/daemon.go
  pkg/generated/clientset/versioned/typed/machineconfiguration.openshift.io/v1/fake/fake_machineconfig.go
  pkg/generated/clientset/versioned/typed/machineconfiguration.openshift.io/v1/fake/fake_machineconfigpool.go
  pkg/generated/clientset/versioned/typed/machineconfiguration.openshift.io/v1/fake/fake_machineconfiguration.openshift.io_client.go
  pkg/generated/clientset/versioned/typed/machineconfiguration.openshift.io/v1/machineconfig.go
  pkg/generated/clientset/versioned/typed/machineconfiguration.openshift.io/v1/machineconfigpool.go
  pkg/generated/clientset/versioned/typed/machineconfiguration.openshift.io/v1/machineconfiguration.openshift.io_client.go
  pkg/generated/informers/externalversions/machineconfiguration.openshift.io/v1/interface.go
  pkg/generated/informers/externalversions/machineconfiguration.openshift.io/v1/machineconfig.go
  pkg/generated/informers/externalversions/machineconfiguration.openshift.io/v1/machineconfigpool.go
  pkg/generated/listers/machineconfiguration.openshift.io/v1/expansion_generated.go
  pkg/generated/listers/machineconfiguration.openshift.io/v1/machineconfig.go
  pkg/generated/listers/machineconfiguration.openshift.io/v1/machineconfigpool.go
  pkg/operator/assets/bindata.go
  pkg/server/cluster_server.go
  pkg/server/server_test.go
  pkg/server/testdata/machine-configs/test-config.yaml
  pkg/server/testdata/machine-pools/test-pool.yaml
Labels: approved, lgtm, size/XL

#32 Bootstrap modes for MCO and MCC
  cmd/machine-config-controller/bootstrap.go
  cmd/machine-config-operator/bootstrap.go
  manifests/machineconfigcontroller/bootstrap-pod.yaml
  manifests/machineconfigcontroller/deployment.yaml
  manifests/machineconfigdaemon/daemonset.yaml
  manifests/machineconfigserver/bootstrap-pod.yaml
  pkg/controller/bootstrap/bootstrap.go
  pkg/controller/render/render_controller.go
  pkg/controller/template/template_controller.go
  pkg/operator/bootstrap.go
Labels: approved, lgtm, size/L

#27 hack/build-image.sh: Add script to build images
  README.md
  hack/build-image.sh
Labels: approved, lgtm, size/M

#34 Add MCOConfig object for MCO
  cmd/machine-config-operator/bootstrap.go
  cmd/machine-config-operator/main.go
  cmd/machine-config-operator/start.go
  install/mcoconfig.crd.yaml
  manifests/machineconfigcontroller/controllerconfig.yaml
  manifests/machineconfigcontroller/deployment.yaml
  manifests/machineconfigdaemon/daemonset.yaml
  manifests/machineconfigserver/daemonset.yaml
  manifests/scc.yaml
  pkg/apis/machineconfiguration.openshift.io/v1/types.go
  pkg/apis/machineconfiguration.openshift.io/v1/zz_generated.deepcopy.go
  pkg/generated/clientset/versioned/typed/machineconfiguration.openshift.io/v1/fake/fake_machineconfiguration.openshift.io_client.go
  pkg/generated/clientset/versioned/typed/machineconfiguration.openshift.io/v1/fake/fake_mcoconfig.go
  pkg/generated/clientset/versioned/typed/machineconfiguration.openshift.io/v1/generated_expansion.go
  pkg/generated/clientset/versioned/typed/machineconfiguration.openshift.io/v1/machineconfiguration.openshift.io_client.go
  pkg/generated/clientset/versioned/typed/machineconfiguration.openshift.io/v1/mcoconfig.go
  pkg/generated/informers/externalversions/generic.go
  pkg/generated/informers/externalversions/machineconfiguration.openshift.io/v1/interface.go
  pkg/generated/informers/externalversions/machineconfiguration.openshift.io/v1/mcoconfig.go
  pkg/generated/listers/machineconfiguration.openshift.io/v1/expansion_generated.go
  pkg/generated/listers/machineconfiguration.openshift.io/v1/mcoconfig.go
  pkg/operator/assets/bindata.go
  pkg/operator/bootstrap.go
  pkg/operator/operator.go
  pkg/operator/render.go
  pkg/operator/sync.go
Labels: approved, lgtm, size/XL
