Repository openshift/machine-config-operator, pull requests merged in 2018-09, with the labels that each got.

#39 pkg/daemon: Move wking/kubernetes-drain to openshift/kubernetes-drain
  Gopkg.lock
  Gopkg.toml
  pkg/daemon/daemon.go
  pkg/daemon/update.go
  vendor/github.com/openshift/kubernetes-drain/LICENSE
  vendor/github.com/openshift/kubernetes-drain/drain.go
Labels: approved, lgtm, size/S

#29 Minor tweaks
  pkg/daemon/daemon.go
Labels: approved, lgtm, size/S

#26 chroot to rootPrefix
  cmd/machine-config-daemon/start.go
  pkg/daemon/daemon.go
  pkg/daemon/update.go
Labels: approved, lgtm, size/M

#17 systemd enable/disable
  pkg/daemon/daemon.go
  pkg/daemon/update.go
Labels: approved, lgtm, size/M

#38 Update MCO to use images.json from ConfigMap for image resolution
  cmd/machine-config-operator/bootstrap.go
  cmd/machine-config-operator/start.go
  install/mco.images.yaml
  manifests/machineconfigcontroller/bootstrap-pod.yaml
  manifests/machineconfigcontroller/deployment.yaml
  manifests/machineconfigdaemon/daemonset.yaml
  manifests/machineconfigserver/bootstrap-pod.yaml
  manifests/machineconfigserver/daemonset.yaml
  pkg/apis/machineconfiguration.openshift.io/v1/register.go
  pkg/operator/assets/bindata.go
  pkg/operator/bootstrap.go
  pkg/operator/images.go
  pkg/operator/operator.go
  pkg/operator/render.go
Labels: approved, lgtm, size/L

#44 pkg/daemon/: Fix gofmt issues
  pkg/daemon/daemon.go
  pkg/daemon/update.go
Labels: approved, lgtm, size/XS

#42 operator: Sync OperatorStatus before and after invoking sync functions
  Gopkg.lock
  cmd/common/client_builder.go
  cmd/machine-config-operator/start.go
  pkg/operator/assets/bindata.go
  pkg/operator/operator.go
  pkg/operator/status.go
  pkg/operator/sync.go
  vendor/github.com/openshift/cluster-version-operator/LICENSE
  vendor/github.com/openshift/cluster-version-operator/lib/resourceapply/apiext.go
  vendor/github.com/openshift/cluster-version-operator/lib/resourceapply/apps.go
  vendor/github.com/openshift/cluster-version-operator/lib/resourceapply/batch.go
  vendor/github.com/openshift/cluster-version-operator/lib/resourceapply/core.go
  vendor/github.com/openshift/cluster-version-operator/lib/resourceapply/cv.go
  vendor/github.com/openshift/cluster-version-operator/lib/resourceapply/rbac.go
  vendor/github.com/openshift/cluster-version-operator/lib/resourcemerge/apiext.go
  vendor/github.com/openshift/cluster-version-operator/lib/resourcemerge/apps.go
  vendor/github.com/openshift/cluster-version-operator/lib/resourcemerge/batch.go
  vendor/github.com/openshift/cluster-version-operator/lib/resourcemerge/core.go
  vendor/github.com/openshift/cluster-version-operator/lib/resourcemerge/cv.go
  vendor/github.com/openshift/cluster-version-operator/lib/resourcemerge/meta.go
  vendor/github.com/openshift/cluster-version-operator/lib/resourcemerge/rbac.go
  vendor/github.com/openshift/cluster-version-operator/pkg/apis/apis.go
  vendor/github.com/openshift/cluster-version-operator/pkg/apis/clusterversion.openshift.io/v1/cvoconfig.go
  vendor/github.com/openshift/cluster-version-operator/pkg/apis/clusterversion.openshift.io/v1/register.go
  vendor/github.com/openshift/cluster-version-operator/pkg/apis/clusterversion.openshift.io/v1/types.go
  vendor/github.com/openshift/cluster-version-operator/pkg/apis/clusterversion.openshift.io/v1/url.go
  vendor/github.com/openshift/cluster-version-operator/pkg/apis/clusterversion.openshift.io/v1/zz_generated.deepcopy.go
  vendor/github.com/openshift/cluster-version-operator/pkg/generated/clientset/versioned/clientset.go
  vendor/github.com/openshift/cluster-version-operator/pkg/generated/clientset/versioned/doc.go
  vendor/github.com/openshift/cluster-version-operator/pkg/generated/clientset/versioned/scheme/doc.go
  vendor/github.com/openshift/cluster-version-operator/pkg/generated/clientset/versioned/scheme/register.go
  vendor/github.com/openshift/cluster-version-operator/pkg/generated/clientset/versioned/typed/clusterversion.openshift.io/v1/clusterversion.openshift.io_client.go
  vendor/github.com/openshift/cluster-version-operator/pkg/generated/clientset/versioned/typed/clusterversion.openshift.io/v1/cvoconfig.go
  vendor/github.com/openshift/cluster-version-operator/pkg/generated/clientset/versioned/typed/clusterversion.openshift.io/v1/doc.go
  vendor/github.com/openshift/cluster-version-operator/pkg/generated/clientset/versioned/typed/clusterversion.openshift.io/v1/generated_expansion.go
  vendor/github.com/openshift/cluster-version-operator/pkg/generated/clientset/versioned/typed/clusterversion.openshift.io/v1/operatorstatus.go
  vendor/github.com/openshift/cluster-version-operator/pkg/generated/listers/clusterversion.openshift.io/v1/cvoconfig.go
  vendor/github.com/openshift/cluster-version-operator/pkg/generated/listers/clusterversion.openshift.io/v1/expansion_generated.go
  vendor/github.com/openshift/cluster-version-operator/pkg/generated/listers/clusterversion.openshift.io/v1/operatorstatus.go
  vendor/github.com/openshift/cluster-version-operator/pkg/version/version.go
  vendor/k8s.io/utils/LICENSE
  vendor/k8s.io/utils/pointer/pointer.go
Labels: approved, lgtm, size/XXL

#43 Enable/Disable units
  pkg/daemon/update.go
Labels: approved, lgtm, size/M

#46 mcd: chroot after clients load
  cmd/machine-config-daemon/start.go
Labels: approved, lgtm, size/S

#40 OWNERS_ALIASES: add machine-config-daemon-approvers
  OWNERS_ALIASES
  cmd/machine-config-daemon/OWNERS
  pkg/daemon/OWNERS
Labels: approved, lgtm, size/S

#48 docs: document how a machineconfig manifest looks
  docs/MachineConfiguration.md
Labels: approved, lgtm, size/S

#49 daemon: strengthen user/group handling
  pkg/daemon/update.go
Labels: approved, lgtm, size/M

#47 discover MCOConfig from InstallConfig
  Gopkg.lock
  Gopkg.toml
  cmd/machine-config-operator/bootstrap.go
  hack/update-generated-bindata.sh
  pkg/operator/assets/bindata.go
  pkg/operator/bootstrap.go
  pkg/operator/operator.go
  pkg/operator/render.go
  pkg/operator/render_test.go
  pkg/operator/status.go
  pkg/version/version.go
  vendor/github.com/apparentlymart/go-cidr/LICENSE
  vendor/github.com/apparentlymart/go-cidr/cidr/cidr.go
  vendor/github.com/apparentlymart/go-cidr/cidr/wrangling.go
  vendor/github.com/openshift/cluster-version-operator/pkg/version/version.go
  vendor/github.com/openshift/installer/LICENSE
  vendor/github.com/openshift/installer/NOTICE
  vendor/github.com/openshift/installer/pkg/types/doc.go
  vendor/github.com/openshift/installer/pkg/types/installconfig.go
  vendor/github.com/openshift/installer/pkg/types/machinepools.go
  vendor/github.com/openshift/installer/steps/assets/aws/config.tf
  vendor/github.com/openshift/installer/steps/assets/aws/variables-aws.tf
  vendor/github.com/openshift/installer/steps/assets/base/config.tf
  vendor/github.com/openshift/installer/steps/assets/libvirt/config.tf
  vendor/github.com/openshift/installer/steps/assets/libvirt/variables-libvirt.tf
  vendor/github.com/openshift/installer/steps/bootstrap/aws/config.tf
  vendor/github.com/openshift/installer/steps/bootstrap/aws/variables-aws.tf
  vendor/github.com/openshift/installer/steps/bootstrap/libvirt/config.tf
  vendor/github.com/openshift/installer/steps/bootstrap/libvirt/variables-libvirt.tf
  vendor/github.com/openshift/installer/steps/joining_workers/aws/config.tf
  vendor/github.com/openshift/installer/steps/joining_workers/aws/variables-aws.tf
  vendor/github.com/openshift/installer/steps/joining_workers/libvirt/config.tf
  vendor/github.com/openshift/installer/steps/joining_workers/libvirt/variables-libvirt.tf
  vendor/github.com/openshift/installer/steps/masters/aws/config.tf
  vendor/github.com/openshift/installer/steps/masters/aws/variables-aws.tf
  vendor/github.com/openshift/installer/steps/masters/libvirt/config.tf
  vendor/github.com/openshift/installer/steps/masters/libvirt/variables-libvirt.tf
  vendor/github.com/openshift/installer/steps/topology/aws/config.tf
  vendor/github.com/openshift/installer/steps/topology/aws/variables-aws.tf
  vendor/github.com/openshift/installer/steps/topology/libvirt/config.tf
  vendor/github.com/openshift/installer/steps/topology/libvirt/variables-libvirt.tf
Labels: approved, lgtm, size/XXL

#41 pkg/daemon: run main loop
  pkg/daemon/daemon.go
Labels: approved, lgtm, size/M

#28 tree: add basic HACKING.md with section for MCD
  HACKING.md
Labels: approved, lgtm, retest-not-required-docs-only, size/M

#53 templates: update etcd to use podman
  pkg/controller/template/test_data/templates/aws/master/units/etcd-member-tls.service
  pkg/controller/template/test_data/templates/aws/master/units/etcd-member.service
  pkg/controller/template/test_data/templates/libvirt/master/units/etcd-member-tls.service
  pkg/controller/template/test_data/templates/libvirt/master/units/etcd-member.service
  templates/_base/master/units/etcd-member-tls.yaml
  templates/_base/master/units/etcd-member.yaml
Labels: approved, lgtm, size/M

#51 install: fix images
  install/02_images.configmap.yaml
  install/04_deployment.yaml
Labels: approved, lgtm, size/XS

#54 update for installconfig discovery
  Gopkg.lock
  pkg/operator/bootstrap.go
  pkg/operator/render_test.go
  vendor/github.com/openshift/installer/pkg/ipnet/ipnet.go
  vendor/github.com/openshift/installer/pkg/types/installconfig.go
  vendor/github.com/openshift/installer/pkg/types/machinepools.go
  vendor/github.com/openshift/installer/steps/infra/aws/config.tf
  vendor/github.com/openshift/installer/steps/infra/aws/variables-aws.tf
  vendor/github.com/openshift/installer/steps/infra/libvirt/config.tf
  vendor/github.com/openshift/installer/steps/infra/libvirt/variables-libvirt.tf
  vendor/github.com/openshift/installer/steps/masters/aws/config.tf
  vendor/github.com/openshift/installer/steps/masters/aws/variables-aws.tf
  vendor/github.com/openshift/installer/steps/masters/libvirt/config.tf
  vendor/github.com/openshift/installer/steps/masters/libvirt/variables-libvirt.tf
  vendor/github.com/openshift/installer/steps/topology/aws/config.tf
  vendor/github.com/openshift/installer/steps/topology/aws/variables-aws.tf
  vendor/github.com/openshift/installer/steps/topology/libvirt/config.tf
  vendor/github.com/openshift/installer/steps/topology/libvirt/variables-libvirt.tf
Labels: approved, lgtm, size/M

#55 templates: combine etcd-member-tls and etcd-member services
  pkg/controller/template/test_data/templates/aws/master/units/etcd-member-tls.service
  pkg/controller/template/test_data/templates/aws/master/units/etcd-member.service
  pkg/controller/template/test_data/templates/libvirt/master/units/etcd-member-tls.service
  pkg/controller/template/test_data/templates/libvirt/master/units/etcd-member.service
  templates/_base/master/units/etcd-member-tls.yaml
  templates/_base/master/units/etcd-member.yaml
Labels: approved, lgtm, size/L

#56 templates: fix extra ' from etcd-member
  pkg/controller/template/test_data/templates/aws/master/units/etcd-member.service
  pkg/controller/template/test_data/templates/libvirt/master/units/etcd-member.service
  templates/_base/master/units/etcd-member.yaml
Labels: approved, lgtm, size/XS

#57 templates: fix etcd_template
  pkg/controller/template/test_data/templates/aws/master/units/etcd-member.service
  pkg/controller/template/test_data/templates/libvirt/master/units/etcd-member.service
  templates/_base/master/units/etcd-member.yaml
Labels: approved, lgtm, size/L

#58 pkg/operator/render_test: Catch up with platformConfig -> platform
  Gopkg.lock
  pkg/operator/render_test.go
  vendor/github.com/openshift/installer/pkg/types/machinepools.go
Labels: approved, lgtm, size/S

#59 docs: clarify osImageURL pull spec
  docs/MachineConfiguration.md
Labels: approved, lgtm, size/XS

#63 add docker.io registry
  pkg/controller/template/test_data/templates/aws/master/files/-etc-containers-registries.conf
  pkg/controller/template/test_data/templates/aws/worker/files/-etc-containers-registries.conf
  pkg/controller/template/test_data/templates/libvirt/master/files/-etc-containers-registries.conf
  pkg/controller/template/test_data/templates/libvirt/worker/files/-etc-containers-registries.conf
  templates/_base/master/files/container-registries.yaml
  templates/_base/worker/files/container-registry.yaml
Labels: approved, lgtm, size/M

#65 daemon: fix inverted logic
  pkg/daemon/update.go
Labels: approved, kind/bug, lgtm, size/XS

#69 mcd: Fix clusterrole.yaml
  manifests/machineconfigdaemon/clusterrole.yaml
  pkg/operator/assets/bindata.go
Labels: approved, lgtm, size/M

#67 *: add image-references for release payload
  Dockerfile.machine-config-operator
  install/02_images.configmap.yaml
  install/image-references
  install/machineconfigoperator_00_namespace.yaml
  install/machineconfigoperator_01_mcoconfig.crd.yaml
  install/machineconfigoperator_02_images.configmap.yaml
  install/machineconfigoperator_03_rbac.yaml
  install/machineconfigoperator_04_deployment.yaml
Labels: approved, lgtm, size/M

#76 daemon: Restart watch on ErrWatchClosed
  pkg/daemon/node.go
Labels: approved, lgtm, size/S

#75 manifests/mcd: add OWNERS file
  manifests/machineconfigdaemon/OWNERS
  pkg/operator/assets/OWNERS
Labels: approved, lgtm, size/XS

#78 templates/_base/master/units/etcd-member: Block on network-online.target
  pkg/controller/template/test_data/templates/aws/master/units/etcd-member.service
  pkg/controller/template/test_data/templates/libvirt/master/units/etcd-member.service
  templates/_base/master/units/etcd-member.yaml
Labels: approved, lgtm, size/XS

#60 pkg/daemon: implement OS version validation
  manifests/machineconfigdaemon/daemonset.yaml
  pkg/daemon/daemon.go
  pkg/daemon/rpm-ostree.go
  pkg/daemon/run.go
  pkg/daemon/update.go
  pkg/operator/assets/bindata.go
Labels: approved, lgtm, size/L

#83 hack: add push-image.sh
  hack/push-image.sh
Labels: approved, lgtm, size/M

#82 daemon: Create a new watcher on error
  pkg/daemon/node.go
Labels: approved, lgtm, size/XS

#86 Use cluo style restart again
  pkg/daemon/node.go
Labels: approved, lgtm, size/S

#84 pkg/operator: remove etcd pool assets; doesn't exist
  pkg/operator/sync.go
Labels: approved, lgtm, size/XS

#77 enable parallel image pulls
  pkg/controller/template/test_data/templates/aws/master/units/kubelet.service
  pkg/controller/template/test_data/templates/aws/worker/units/kubelet.service
  pkg/controller/template/test_data/templates/libvirt/master/units/kubelet.service
  pkg/controller/template/test_data/templates/libvirt/worker/units/kubelet.service
  templates/_base/master/units/kubelet.yaml
  templates/_base/worker/units/kubelet.yaml
Labels: approved, lgtm, size/XS

#88 Fix kubelet stats summary endpoint with cri-o
  pkg/controller/template/test_data/templates/aws/master/units/kubelet.service
  pkg/controller/template/test_data/templates/aws/worker/units/kubelet.service
  pkg/controller/template/test_data/templates/libvirt/master/units/kubelet.service
  pkg/controller/template/test_data/templates/libvirt/worker/units/kubelet.service
  templates/_base/master/units/kubelet.yaml
  templates/_base/worker/units/kubelet.yaml
Labels: approved, lgtm, size/S

#89 MCD: Check what OS MCD is running on
  Gopkg.lock
  Gopkg.toml
  cmd/machine-config-daemon/start.go
  pkg/daemon/constants.go
  pkg/daemon/daemon.go
  pkg/daemon/osrelease.go
  vendor/github.com/ashcrow/osrelease/LICENSE
  vendor/github.com/ashcrow/osrelease/osrelease.go
Labels: approved, lgtm, size/L

#87 MCD: Log level clean up (daemon/update.go)
  pkg/daemon/update.go
Labels: approved, lgtm, size/M

#91 cmd/daemon: consistently capitalize log messages
  cmd/machine-config-daemon/start.go
Labels: approved, lgtm, size/XS

#92 cmd/daemon: simplify OSImageURL querying
  pkg/daemon/daemon.go
  pkg/daemon/rpm-ostree.go
  pkg/daemon/update.go
Labels: approved, lgtm, size/M

#94 MCO manifest names are too long
  install/00_namespace.yaml
  install/01_mcoconfig.crd.yaml
  install/02_images.configmap.yaml
  install/03_rbac.yaml
  install/04_deployment.yaml
Labels: approved, lgtm, size/XS

#95 install: fix namespace for images.configmap
  install/02_images.configmap.yaml
Labels: approved, lgtm, size/XS
