Repository openshift/machine-config-operator, pull requests merged in 2018-12, with the labels that each got.

#206 Various error-handling fixes
  cmd/machine-config-daemon/start.go
  pkg/daemon/daemon.go
  pkg/daemon/writer.go
Labels: approved, lgtm, size/L

#204 daemon: tweak log message
  cmd/machine-config-daemon/start.go
Labels: approved, lgtm, size/XS

#196 Use "" for "unspecified OS", tweak comments
  pkg/controller/template/render.go
  pkg/daemon/daemon.go
  pkg/daemon/update.go
Labels: approved, lgtm, size/S

#182 Update instructions to disable CVO.
  HACKING.md
Labels: approved, kind/documentation, lgtm, size/XS

#187 enable kubelet server cert bootstrapping
  pkg/controller/template/test_data/templates/aws/master/files/-etc-kubernetes-kubelet.conf
  pkg/controller/template/test_data/templates/aws/worker/files/-etc-kubernetes-kubelet.conf
  pkg/controller/template/test_data/templates/libvirt/master/files/-etc-kubernetes-kubelet.conf
  pkg/controller/template/test_data/templates/libvirt/worker/files/-etc-kubernetes-kubelet.conf
  pkg/controller/template/test_data/templates/openstack/master/files/-etc-kubernetes-kubelet.conf
  pkg/controller/template/test_data/templates/openstack/worker/files/-etc-kubernetes-kubelet.conf
  templates/_base/master/files/kubelet.yaml
  templates/_base/worker/files/kubelet.yaml
Labels: approved, lgtm, size/S

#201 debug: Send significant events to the apiserver for a node
  lib/resourceapply/rbac.go
  lib/resourcemerge/rbac.go
  lib/resourceread/rbac.go
  manifests/machineconfigdaemon/events-clusterrole.yaml
  manifests/machineconfigdaemon/events-rolebinding-default.yaml
  manifests/machineconfigdaemon/events-rolebinding-target.yaml
  pkg/daemon/daemon.go
  pkg/daemon/update.go
  pkg/operator/assets/bindata.go
  pkg/operator/sync.go
Labels: approved, lgtm, size/L

#208 template: allow multiple MachineConfigs per role
  pkg/controller/template/render.go
  pkg/controller/template/render_test.go
  templates/master/00-master/_base/files/container-registries.yaml
  templates/master/00-master/_base/files/etc-hosts.yaml
  templates/master/00-master/_base/files/etc-kubernetes-manifests-etcd-member.yaml
  templates/master/00-master/_base/files/etc-sysconfig-crio-network.yaml
  templates/master/00-master/_base/files/etcd-ca.yaml
  templates/master/00-master/_base/files/etcd-root-ca.yaml
  templates/master/00-master/_base/files/kubelet.yaml
  templates/master/00-master/_base/files/pull-secret.yaml
  templates/master/00-master/_base/files/registry-ca-cert.yaml
  templates/master/00-master/_base/files/root-ca.yaml
  templates/master/00-master/_base/files/sysctl-forward-conf.yaml
  templates/master/00-master/_base/units/kubelet.yaml
  templates/master/00-master/aws/.gitkeep
  templates/master/00-master/libvirt/.gitkeep
  templates/master/00-master/openstack/.gitkeep
  templates/worker/00-worker/_base/files/container-registry.yaml
  templates/worker/00-worker/_base/files/etc-hosts.yaml
  templates/worker/00-worker/_base/files/etc-sysconfig-crio-network.yaml
  templates/worker/00-worker/_base/files/kubelet.yaml
  templates/worker/00-worker/_base/files/pull-secret.yaml
  templates/worker/00-worker/_base/files/registry-ca-cert.yaml
  templates/worker/00-worker/_base/files/root-ca.yaml
  templates/worker/00-worker/_base/files/sysctl-forward-conf.yaml
  templates/worker/00-worker/_base/units/kubelet.yaml
  templates/worker/00-worker/aws/.gitkeep
  templates/worker/00-worker/libvirt/.gitkeep
  templates/worker/00-worker/openstack/.gitkeep
Labels: approved, lgtm, size/L

#209 daemon: Fix format message for degraded message
  pkg/daemon/writer.go
Labels: approved, lgtm, size/XS

#214 controller: requeue errors after timeout
  manifests/machineconfigcontroller/deployment.yaml
  pkg/controller/node/node_controller.go
  pkg/controller/render/render_controller.go
  pkg/controller/template/template_controller.go
  pkg/operator/assets/bindata.go
Labels: approved, lgtm, size/XS

#215 daemon: Only log to recorder in cluster driven model
  pkg/daemon/update.go
Labels: approved, lgtm, size/XS

#195 resourceread: use lib function for loading machine configs
  lib/resourceread/machineconfig.go
  lib/resourceread/machineconfig_test.go
  pkg/daemon/daemon.go
Labels: approved, lgtm, size/L

#216 daemon: Log reboot reason to systemd journal as well
  pkg/daemon/update.go
Labels: approved, lgtm, size/M

#220 templates: add memory request to etcd-member pod
  pkg/controller/template/test_data/templates/aws/master/files/-etc-kubernetes-manifests-etcd-member.yaml
  pkg/controller/template/test_data/templates/libvirt/master/files/-etc-kubernetes-manifests-etcd-member.yaml
  pkg/controller/template/test_data/templates/openstack/master/files/-etc-kubernetes-manifests-etcd-member.yaml
  templates/master/00-master/_base/files/etc-kubernetes-manifests-etcd-member.yaml
Labels: approved, lgtm, size/XS

#223 README.md: Add managing go dependencies section
  README.md
Labels: approved, kind/documentation, lgtm, size/M

#225 templates: drop files related to registry
  pkg/controller/render/render_controller.go
  pkg/controller/template/test_data/templates/aws/master/files/-etc-docker-certs.d-docker-registry.default.svc:5000-ca.crt
  pkg/controller/template/test_data/templates/aws/master/files/-etc-hosts
  pkg/controller/template/test_data/templates/aws/worker/files/-etc-docker-certs.d-docker-registry.default.svc:5000-ca.crt
  pkg/controller/template/test_data/templates/aws/worker/files/-etc-hosts
  pkg/controller/template/test_data/templates/libvirt/master/files/-etc-docker-certs.d-docker-registry.default.svc:5000-ca.crt
  pkg/controller/template/test_data/templates/libvirt/master/files/-etc-hosts
  pkg/controller/template/test_data/templates/libvirt/worker/files/-etc-docker-certs.d-docker-registry.default.svc:5000-ca.crt
  pkg/controller/template/test_data/templates/libvirt/worker/files/-etc-hosts
  pkg/controller/template/test_data/templates/openstack/master/files/-etc-docker-certs.d-docker-registry.default.svc:5000-ca.crt
  pkg/controller/template/test_data/templates/openstack/master/files/-etc-hosts
  pkg/controller/template/test_data/templates/openstack/worker/files/-etc-docker-certs.d-docker-registry.default.svc:5000-ca.crt
  pkg/controller/template/test_data/templates/openstack/worker/files/-etc-hosts
  templates/master/00-master/_base/files/etc-hosts.yaml
  templates/master/00-master/_base/files/registry-ca-cert.yaml
  templates/worker/00-worker/_base/files/etc-hosts.yaml
  templates/worker/00-worker/_base/files/registry-ca-cert.yaml
Labels: approved, lgtm, size/L

#212 kubelet: bump max pods to 250
  pkg/controller/template/test_data/templates/aws/master/files/-etc-kubernetes-kubelet.conf
  pkg/controller/template/test_data/templates/aws/worker/files/-etc-kubernetes-kubelet.conf
  pkg/controller/template/test_data/templates/libvirt/master/files/-etc-kubernetes-kubelet.conf
  pkg/controller/template/test_data/templates/libvirt/worker/files/-etc-kubernetes-kubelet.conf
  pkg/controller/template/test_data/templates/openstack/master/files/-etc-kubernetes-kubelet.conf
  pkg/controller/template/test_data/templates/openstack/worker/files/-etc-kubernetes-kubelet.conf
  templates/master/00-master/_base/files/kubelet.yaml
  templates/worker/00-worker/_base/files/kubelet.yaml
Labels: approved, lgtm, size/S

#219 MCO: update installconfig to remove admin
  Gopkg.lock
  Gopkg.toml
  pkg/operator/render_test.go
  vendor/github.com/openshift/cluster-network-operator/LICENSE
  vendor/github.com/openshift/cluster-network-operator/pkg/apis/networkoperator/v1/doc.go
  vendor/github.com/openshift/cluster-network-operator/pkg/apis/networkoperator/v1/networkconfig_types.go
  vendor/github.com/openshift/cluster-network-operator/pkg/apis/networkoperator/v1/register.go
  vendor/github.com/openshift/cluster-network-operator/pkg/apis/networkoperator/v1/zz_generated.deepcopy.go
  vendor/github.com/openshift/installer/pkg/types/aws/doc.go
  vendor/github.com/openshift/installer/pkg/types/aws/machinepool.go
  vendor/github.com/openshift/installer/pkg/types/aws/metadata.go
  vendor/github.com/openshift/installer/pkg/types/aws/platform.go
  vendor/github.com/openshift/installer/pkg/types/clustermetadata.go
  vendor/github.com/openshift/installer/pkg/types/doc.go
  vendor/github.com/openshift/installer/pkg/types/installconfig.go
  vendor/github.com/openshift/installer/pkg/types/libvirt/doc.go
  vendor/github.com/openshift/installer/pkg/types/libvirt/machinepool.go
  vendor/github.com/openshift/installer/pkg/types/libvirt/metadata.go
  vendor/github.com/openshift/installer/pkg/types/libvirt/network.go
  vendor/github.com/openshift/installer/pkg/types/libvirt/platform.go
  vendor/github.com/openshift/installer/pkg/types/machinepools.go
  vendor/github.com/openshift/installer/pkg/types/openstack/doc.go
  vendor/github.com/openshift/installer/pkg/types/openstack/machinepool.go
  vendor/github.com/openshift/installer/pkg/types/openstack/metadata.go
  vendor/github.com/openshift/installer/pkg/types/openstack/platform.go
  vendor/sigs.k8s.io/controller-runtime/LICENSE
  vendor/sigs.k8s.io/controller-runtime/pkg/runtime/scheme/scheme.go
Labels: approved, lgtm, size/XXL

#222 HACKING.md: add layered MachineConfig example
  HACKING.md
Labels: approved, lgtm, size/M

#221 daemon: Log degredation reason to journal and event too
  pkg/daemon/daemon.go
  pkg/daemon/update.go
  pkg/daemon/update_test.go
Labels: approved, lgtm, size/M

#217 HACKING.md: Tweak development instructions
  HACKING.md
Labels: approved, kind/documentation, lgtm, size/S

#189 HACKING.md: add docs for iterating without building images
  HACKING.md
Labels: approved, lgtm, size/M

#226 operator: refactor bootstrapping to allow non-bootstrap manifests
  manifests/bootstrap-pod-v2.yaml
  pkg/operator/assets/bindata.go
  pkg/operator/bootstrap.go
Labels: approved, lgtm, size/L

#218 controller: Prefix generated configs with pool type
  pkg/controller/render/hash.go
  pkg/controller/render/render_controller.go
Labels: approved, lgtm, size/XS

#205 templates: bump etcd to v3.3.10
  pkg/controller/template/test_data/templates/aws/master/files/-etc-kubernetes-manifests-etcd-member.yaml
  pkg/controller/template/test_data/templates/libvirt/master/files/-etc-kubernetes-manifests-etcd-member.yaml
  pkg/controller/template/test_data/templates/master/00-master/aws/files/-etc-kubernetes-manifests-etcd-member.yaml
  pkg/controller/template/test_data/templates/master/00-master/libvirt/files/-etc-kubernetes-manifests-etcd-member.yaml
  pkg/controller/template/test_data/templates/master/00-master/openstack/files/-etc-kubernetes-manifests-etcd-member.yaml
  pkg/controller/template/test_data/templates/openstack/master/files/-etc-kubernetes-manifests-etcd-member.yaml
  pkg/server/testdata/machine-configs/test-config.yaml
  templates/master/00-master/_base/files/etc-kubernetes-manifests-etcd-member.yaml
Labels: approved, lgtm, size/S

#231 hack: Add cluster-push-*.sh scripts
  HACKING.md
  Makefile
  hack/cluster-push-prep.sh
  hack/cluster-push.sh
Labels: approved, lgtm, size/L

#238 MCD: Remove unused error return value from reconcilable()
  pkg/daemon/daemon.go
  pkg/daemon/update.go
  pkg/daemon/update_test.go
Labels: approved, lgtm, size/M

#244 pkg/server/server_test: Use filepath.Join for path creation
  pkg/server/server_test.go
Labels: approved, lgtm, size/XS

#243 pkg/server: Drop unused etcdTemplateParam
  pkg/server/bootstrap_server.go
  pkg/server/server.go
Labels: approved, lgtm, size/S

#247 two small hack/cluster-push patches
  hack/cluster-push.sh
Labels: approved, lgtm, size/XS

#240 pkg/server/api: Return 405s for non-GET requests
  pkg/server/api.go
  pkg/server/api_test.go
Labels: approved, lgtm, size/L

#250 server: Also write state=Done annotation initially
  pkg/server/server.go
Labels: approved, lgtm, size/XS

#248 docs/OnceFrom: Add some documentation around "once-from"
  docs/OnceFrom.md
Labels: approved, lgtm, size/M

#251 OWNERS: Add myself
  OWNERS
Labels: approved, lgtm, size/XS

#253 controller: Log when we generate a MC
  pkg/controller/render/render_controller.go
Labels: approved, lgtm, size/XS

#236 Makefile: Also support specifying just e.g. `make controller`
  HACKING.md
  Makefile
Labels: approved, lgtm, size/M

#256 pkg/apis: controllerconfig needs to be cluster-scoped
  lib/resourceapply/machineconfig.go
  manifests/controllerconfig.crd.yaml
  manifests/machineconfigcontroller/controllerconfig.yaml
  pkg/apis/machineconfiguration.openshift.io/v1/types.go
  pkg/controller/node/node_controller.go
  pkg/controller/render/render_controller.go
  pkg/controller/template/template_controller.go
  pkg/controller/template/template_controller_test.go
  pkg/generated/clientset/versioned/typed/machineconfiguration.openshift.io/v1/controllerconfig.go
  pkg/generated/clientset/versioned/typed/machineconfiguration.openshift.io/v1/fake/fake_controllerconfig.go
  pkg/generated/clientset/versioned/typed/machineconfiguration.openshift.io/v1/fake/fake_machineconfiguration.openshift.io_client.go
  pkg/generated/clientset/versioned/typed/machineconfiguration.openshift.io/v1/machineconfiguration.openshift.io_client.go
  pkg/generated/informers/externalversions/machineconfiguration.openshift.io/v1/controllerconfig.go
  pkg/generated/informers/externalversions/machineconfiguration.openshift.io/v1/interface.go
  pkg/generated/listers/machineconfiguration.openshift.io/v1/controllerconfig.go
  pkg/generated/listers/machineconfiguration.openshift.io/v1/expansion_generated.go
  pkg/operator/assets/bindata.go
Labels: approved, lgtm, size/L

#261 Makefile: Fix `make deploy-daemon`
  Makefile
Labels: approved, lgtm, size/XS

#245 daemon: Rework state management for updates
  cmd/machine-config-daemon/start.go
  pkg/daemon/daemon.go
  pkg/daemon/update.go
Labels: approved, lgtm, size/L

#262 daemon: Add retries around fetching annotations
  pkg/daemon/node.go
Labels: approved, lgtm, size/S
