Repository openshift/machine-config-operator, pull requests merged in 2018-10, with the labels that each got.

#96 migrate to kubelet config file
  pkg/controller/template/test_data/templates/aws/master/files/-etc-kubernetes-kubelet.conf
  pkg/controller/template/test_data/templates/aws/master/units/kubelet.service
  pkg/controller/template/test_data/templates/aws/worker/files/-etc-kubernetes-kubelet.conf
  pkg/controller/template/test_data/templates/aws/worker/units/kubelet.service
  pkg/controller/template/test_data/templates/libvirt/master/files/-etc-kubernetes-kubelet.conf
  pkg/controller/template/test_data/templates/libvirt/master/units/kubelet.service
  pkg/controller/template/test_data/templates/libvirt/worker/files/-etc-kubernetes-kubelet.conf
  pkg/controller/template/test_data/templates/libvirt/worker/units/kubelet.service
  templates/_base/master/files/kubelet.yaml
  templates/_base/master/units/kubelet.yaml
  templates/_base/worker/files/kubelet.yaml
  templates/_base/worker/units/kubelet.yaml
Labels: approved, lgtm, size/L

#106 Revert "templates: change etcd-member to notify type"
  pkg/controller/template/test_data/templates/aws/master/units/etcd-member.service
  pkg/controller/template/test_data/templates/libvirt/master/units/etcd-member.service
  templates/_base/master/units/etcd-member.yaml
Labels: approved, lgtm, size/L

#107 kubelet: fix the clusterDNS property within the config
  pkg/controller/template/test_data/templates/aws/master/files/-etc-kubernetes-kubelet.conf
  pkg/controller/template/test_data/templates/aws/worker/files/-etc-kubernetes-kubelet.conf
  pkg/controller/template/test_data/templates/libvirt/master/files/-etc-kubernetes-kubelet.conf
  pkg/controller/template/test_data/templates/libvirt/worker/files/-etc-kubernetes-kubelet.conf
  templates/_base/master/files/kubelet.yaml
  templates/_base/worker/files/kubelet.yaml
Labels: approved, lgtm, size/S

#108 sign for the local etcd service name that cluster-network apiservers use
  pkg/controller/template/render.go
  pkg/controller/template/render_test.go
  pkg/controller/template/test_data/templates/aws/master/units/etcd-member.service
  pkg/controller/template/test_data/templates/libvirt/master/units/etcd-member.service
Labels: approved, lgtm, size/XS

#111 Update hacking doc to handle CVO
  HACKING.md
Labels: approved, lgtm, size/XS

#113 remove SCC from machine-config-operator
  cmd/machine-config-operator/start.go
  lib/resourceapply/security.go
  lib/resourcemerge/security.go
  lib/resourceread/security.go
  manifests/scc.yaml
  pkg/operator/assets/bindata.go
  pkg/operator/operator.go
  pkg/operator/sync.go
Labels: approved, lgtm, size/L

#114 install: give mco run level 50
  install/0000_50_machine-config-operator_00_namespace.yaml
  install/0000_50_machine-config-operator_01_mcoconfig.crd.yaml
  install/0000_50_machine-config-operator_02_images.configmap.yaml
  install/0000_50_machine-config-operator_03_rbac.yaml
  install/0000_50_machine-config-operator_04_deployment.yaml
Labels: approved, lgtm, size/XS

#112 Add OpenStack as a valid platform
  pkg/apis/machineconfiguration.openshift.io/v1/types.go
  pkg/controller/template/render.go
  pkg/controller/template/render_test.go
  pkg/controller/template/test_data/controller_config_openstack.yaml
  pkg/controller/template/test_data/templates/openstack/master/files/-etc-containers-registries.conf
  pkg/controller/template/test_data/templates/openstack/master/files/-etc-docker-certs.d-docker-registry.default.svc:5000-ca.crt
  pkg/controller/template/test_data/templates/openstack/master/files/-etc-hosts
  pkg/controller/template/test_data/templates/openstack/master/files/-etc-kubernetes-ca.crt
  pkg/controller/template/test_data/templates/openstack/master/files/-etc-kubernetes-kubelet.conf
  pkg/controller/template/test_data/templates/openstack/master/files/-etc-ssl-etcd-ca.crt
  pkg/controller/template/test_data/templates/openstack/master/files/-etc-ssl-etcd-root-ca.crt
  pkg/controller/template/test_data/templates/openstack/master/files/-etc-sysconfig-crio-network
  pkg/controller/template/test_data/templates/openstack/master/units/etcd-member.service
  pkg/controller/template/test_data/templates/openstack/master/units/kubelet.service
  pkg/controller/template/test_data/templates/openstack/worker/files/-etc-containers-registries.conf
  pkg/controller/template/test_data/templates/openstack/worker/files/-etc-docker-certs.d-docker-registry.default.svc:5000-ca.crt
  pkg/controller/template/test_data/templates/openstack/worker/files/-etc-hosts
  pkg/controller/template/test_data/templates/openstack/worker/files/-etc-kubernetes-ca.crt
  pkg/controller/template/test_data/templates/openstack/worker/files/-etc-kubernetes-kubelet.conf
  pkg/controller/template/test_data/templates/openstack/worker/files/-etc-sysconfig-crio-network
  pkg/controller/template/test_data/templates/openstack/worker/units/kubelet.service
  pkg/operator/render.go
  templates/openstack/.gitkeep
  vendor/github.com/openshift/installer/pkg/ipnet/ipnet.go
  vendor/github.com/openshift/installer/pkg/types/installconfig.go
  vendor/github.com/openshift/installer/pkg/types/machinepools.go
Labels: approved, lgtm, size/L

#100 Turn rpm-ostree code into a client
  cmd/machine-config-daemon/start.go
  pkg/daemon/daemon.go
  pkg/daemon/rpm-ostree.go
  pkg/daemon/rpm-ostree_test.go
  pkg/daemon/update.go
  pkg/daemon/update_test.go
Labels: approved, lgtm, size/L

#109 daemon: restructure the process function
  pkg/daemon/daemon.go
Labels: approved, lgtm, size/M

#102 daemon/fsclient: Wraps file system operations
  cmd/machine-config-daemon/start.go
  pkg/daemon/daemon.go
  pkg/daemon/fsclient.go
  pkg/daemon/fsclient_test.go
  pkg/daemon/update.go
Labels: approved, lgtm, size/L

#118 templates: add flannel-dns-hack.service for masters
  pkg/controller/template/test_data/templates/aws/master/units/flannel-dns-hack.service
  pkg/controller/template/test_data/templates/libvirt/master/units/flannel-dns-hack.service
  pkg/controller/template/test_data/templates/openstack/master/units/flannel-dns-hack.service
  templates/_base/master/units/flannel-dns-hack.yaml
Labels: approved, lgtm, size/M

#119 operator: add mco cli flags to mco bootstrap
  cmd/machine-config-operator/bootstrap.go
  pkg/operator/bootstrap.go
  pkg/operator/images.go
  pkg/operator/operator.go
  pkg/operator/render.go
Labels: approved, lgtm, size/M

#120 templates: fix missing Install section for flannel-dns-hac.service
  pkg/controller/template/test_data/templates/aws/master/units/flannel-dns-hack.service
  pkg/controller/template/test_data/templates/libvirt/master/units/flannel-dns-hack.service
  pkg/controller/template/test_data/templates/openstack/master/units/flannel-dns-hack.service
  templates/_base/master/units/flannel-dns-hack.yaml
Labels: approved, lgtm, size/S

#122 daemon: don't try to reconcile file appends
  pkg/daemon/update.go
Labels: approved, lgtm, size/S

#123 template: use systemd-sysctl to force net.bridges to use iptables on masters
  pkg/controller/template/test_data/templates/aws/master/files/-etc-modules-load.d-bridge.conf
  pkg/controller/template/test_data/templates/aws/master/files/-etc-sysctl.d-bridge.conf
  pkg/controller/template/test_data/templates/aws/master/units/flannel-dns-hack.service
  pkg/controller/template/test_data/templates/libvirt/master/files/-etc-modules-load.d-bridge.conf
  pkg/controller/template/test_data/templates/libvirt/master/files/-etc-sysctl.d-bridge.conf
  pkg/controller/template/test_data/templates/libvirt/master/units/flannel-dns-hack.service
  pkg/controller/template/test_data/templates/openstack/master/files/-etc-modules-load.d-bridge.conf
  pkg/controller/template/test_data/templates/openstack/master/files/-etc-sysctl.d-bridge.conf
  pkg/controller/template/test_data/templates/openstack/master/units/flannel-dns-hack.service
  templates/_base/master/files/modules-load-bridge-conf.yaml
  templates/_base/master/files/sysctl-bridge-conf.yaml
  templates/_base/master/units/flannel-dns-hack.yaml
Labels: approved, lgtm, size/L

#121 daemon: exit early if node is degraded
  pkg/daemon/daemon.go
Labels: approved, lgtm, size/S

#117 daemon/update_test.go: Add TestReconcilable
  pkg/daemon/update_test.go
Labels: approved, lgtm, size/L

#129 daemon: just sit quietly if node is degraded
  pkg/daemon/daemon.go
Labels: approved, lgtm, size/XS

#131 daemon: allow no state label to be set on node
  pkg/daemon/daemon.go
  pkg/daemon/node.go
Labels: approved, lgtm, size/S

#124 daemon: also check file mode when comparing
  pkg/daemon/daemon.go
  pkg/daemon/update.go
Labels: approved, lgtm, size/M

#134 daemon: Add WriteFiles to FsClient
  pkg/daemon/fsclient.go
  pkg/daemon/fsclient_test.go
Labels: approved, lgtm, size/S

#135 Take ownership of the bootstrapping CSR cluster roles from KubeCoreOperator
  manifests/machineconfigserver/csr-approver-role-binding.yaml
  manifests/machineconfigserver/csr-bootstrap-role-binding.yaml
  manifests/machineconfigserver/csr-renewal-role-binding.yaml
  pkg/operator/assets/bindata.go
  pkg/operator/sync.go
Labels: approved, lgtm, size/L

#133 kubelet: enable readOnlyPort for 10255
  pkg/controller/template/test_data/templates/aws/master/files/-etc-kubernetes-kubelet.conf
  pkg/controller/template/test_data/templates/aws/worker/files/-etc-kubernetes-kubelet.conf
  pkg/controller/template/test_data/templates/libvirt/master/files/-etc-kubernetes-kubelet.conf
  pkg/controller/template/test_data/templates/libvirt/worker/files/-etc-kubernetes-kubelet.conf
  pkg/controller/template/test_data/templates/openstack/master/files/-etc-kubernetes-kubelet.conf
  pkg/controller/template/test_data/templates/openstack/worker/files/-etc-kubernetes-kubelet.conf
  templates/_base/master/files/kubelet.yaml
  templates/_base/worker/files/kubelet.yaml
Labels: approved, lgtm, size/S

#136 daemon: error out early if we can't talk to rpm-ostree
  pkg/daemon/daemon.go
Labels: approved, lgtm, size/XS

#139 daemon: Add ReadFile to FsClient
  pkg/daemon/fsclient.go
  pkg/daemon/fsclient_test.go
  pkg/daemon/rpm-ostree_test.go
Labels: approved, lgtm, size/M

#140 MCD: update hacking doc
  HACKING.md
Labels: approved, lgtm

#144 update hacking.md with oc commands and check for successful deployment.
  HACKING.md
Labels: approved, lgtm, size/S

#147 HACKING.md: Remove kube commands
  HACKING.md
Labels: approved, lgtm, size/S

#146 templates: switch kubelet systemd unit to type notify
  pkg/controller/template/test_data/templates/aws/master/units/kubelet.service
  pkg/controller/template/test_data/templates/aws/worker/units/kubelet.service
  pkg/controller/template/test_data/templates/libvirt/master/units/kubelet.service
  pkg/controller/template/test_data/templates/libvirt/worker/units/kubelet.service
  pkg/controller/template/test_data/templates/openstack/master/units/kubelet.service
  pkg/controller/template/test_data/templates/openstack/worker/units/kubelet.service
  templates/_base/master/units/kubelet.yaml
  templates/_base/worker/units/kubelet.yaml
Labels: approved, lgtm, size/XS

#145 mcd: fix race condition for annotation updates
  pkg/daemon/daemon.go
  pkg/daemon/node.go
Labels: approved, lgtm, size/M

#130 daemon: use informers to check for updates
  cmd/machine-config-daemon/start.go
  pkg/daemon/daemon.go
  pkg/daemon/node.go
Labels: approved, lgtm, size/L

#143 etcd boostrapping using dns
  Dockerfile.setup-etcd-environment
  cmd/setup-etcd-environment/main.go
  docs/MachineConfigServer.md
  hack/build-image.sh
  manifests/machineconfigcontroller/controllerconfig.yaml
  pkg/apis/machineconfiguration.openshift.io/v1/types.go
  pkg/controller/template/render.go
  pkg/controller/template/render_test.go
  pkg/controller/template/template_controller_test.go
  pkg/controller/template/test_data/templates/aws/master/units/etcd-member.service
  pkg/controller/template/test_data/templates/aws/master/units/setup-etcd-environment.service
  pkg/controller/template/test_data/templates/libvirt/master/units/etcd-member.service
  pkg/controller/template/test_data/templates/libvirt/master/units/setup-etcd-environment.service
  pkg/controller/template/test_data/templates/openstack/master/units/etcd-member.service
  pkg/controller/template/test_data/templates/openstack/master/units/setup-etcd-environment.service
  pkg/operator/assets/bindata.go
  pkg/operator/operator.go
  pkg/operator/render.go
  pkg/operator/render_test.go
  pkg/server/api.go
  pkg/server/server.go
  pkg/server/server_test.go
  templates/_base/master/units/etcd-member.yaml
  templates/_base/master/units/setup-etcd-environment.yaml
Labels: approved, lgtm, size/XL

#138 pkg/daemon: remove annotation equality test from validation
  pkg/daemon/daemon.go
Labels: approved, lgtm, size/XS
