Repository openshift/machine-config-operator, pull requests merged in 2018-11, with the labels that each got.

#151 daemon: Adapt to OS being pre-pivoted
  pkg/daemon/daemon.go
  pkg/daemon/rpm-ostree.go
  pkg/daemon/update.go
Labels: approved, lgtm, size/S

#154 cmd/setup-etcd-environment: add version information
  cmd/setup-etcd-environment/main.go
  cmd/setup-etcd-environment/run.go
  cmd/setup-etcd-environment/version.go
Labels: approved, lgtm, size/L

#155 templates: use cluster-name.base-domain for etcd srv search
  pkg/controller/template/test_data/templates/aws/master/units/setup-etcd-environment.service
  pkg/controller/template/test_data/templates/libvirt/master/units/setup-etcd-environment.service
  pkg/controller/template/test_data/templates/openstack/master/units/setup-etcd-environment.service
  templates/_base/master/units/setup-etcd-environment.yaml
Labels: approved, lgtm, size/XS

#156 templates: fix etcd discovery-srv endpoint
  pkg/controller/template/render.go
  pkg/controller/template/render_test.go
  pkg/controller/template/test_data/templates/aws/master/units/etcd-member.service
  pkg/controller/template/test_data/templates/libvirt/master/units/etcd-member.service
  pkg/controller/template/test_data/templates/openstack/master/units/etcd-member.service
  templates/_base/master/units/etcd-member.yaml
Labels: approved, lgtm, size/M

#148 deploy etcd as static pod
  pkg/controller/template/test_data/templates/aws/master/files/-etc-kubernetes-manifests-etcd-member.yaml
  pkg/controller/template/test_data/templates/aws/master/units/etcd-member.service
  pkg/controller/template/test_data/templates/aws/master/units/setup-etcd-environment.service
  pkg/controller/template/test_data/templates/libvirt/master/files/-etc-kubernetes-manifests-etcd-member.yaml
  pkg/controller/template/test_data/templates/libvirt/master/units/etcd-member.service
  pkg/controller/template/test_data/templates/libvirt/master/units/setup-etcd-environment.service
  pkg/controller/template/test_data/templates/openstack/master/files/-etc-kubernetes-manifests-etcd-member.yaml
  pkg/controller/template/test_data/templates/openstack/master/units/etcd-member.service
  pkg/controller/template/test_data/templates/openstack/master/units/setup-etcd-environment.service
  templates/_base/master/files/etc-kubernetes-manifests-etcd-member.yaml
  templates/_base/master/units/etcd-member.yaml
  templates/_base/master/units/setup-etcd-environment.yaml
Labels: approved, lgtm, size/XL

#158 MCO move sources for certs used by etcd
  cmd/machine-config-operator/bootstrap.go
  cmd/machine-config-operator/main.go
  cmd/machine-config-operator/start.go
  pkg/controller/template/test_data/templates/aws/master/files/-etc-kubernetes-manifests-etcd-member.yaml
  pkg/controller/template/test_data/templates/aws/master/files/-etc-kubernetes-static-pod-resources-etcd-member-ca.crt
  pkg/controller/template/test_data/templates/aws/master/files/-etc-kubernetes-static-pod-resources-etcd-member-root-ca.crt
  pkg/controller/template/test_data/templates/libvirt/master/files/-etc-kubernetes-manifests-etcd-member.yaml
  pkg/controller/template/test_data/templates/libvirt/master/files/-etc-kubernetes-static-pod-resources-etcd-member-ca.crt
  pkg/controller/template/test_data/templates/libvirt/master/files/-etc-kubernetes-static-pod-resources-etcd-member-root-ca.crt
  pkg/controller/template/test_data/templates/openstack/master/files/-etc-kubernetes-manifests-etcd-member.yaml
  pkg/controller/template/test_data/templates/openstack/master/files/-etc-kubernetes-static-pod-resources-etcd-member-ca.crt
  pkg/controller/template/test_data/templates/openstack/master/files/-etc-kubernetes-static-pod-resources-etcd-member-root-ca.crt
  pkg/operator/operator.go
  templates/_base/master/files/etc-kubernetes-manifests-etcd-member.yaml
  templates/_base/master/files/etcd-ca.yaml
  templates/_base/master/files/etcd-root-ca.yaml
Labels: approved, lgtm, size/M

#126 daemon: Run once mode
  cmd/machine-config-daemon/start.go
  pkg/daemon/daemon.go
  pkg/daemon/fsclient.go
  pkg/daemon/fsclient_test.go
  pkg/daemon/update.go
Labels: approved, lgtm, size/L

#163 mcd: Add CentOS to OS whitelist
  pkg/daemon/constants.go
  pkg/daemon/osrelease.go
Labels: approved, lgtm, size/XS

#172 MCD: Fix once-from start
  cmd/machine-config-daemon/start.go
Labels: approved, lgtm, size/XS

#171 MCD: Fix ValidPath function
  pkg/daemon/daemon.go
  pkg/daemon/daemon_test.go
Labels: approved, lgtm, size/S

#168 daemon: Only check osImageURL on RHCOS
  pkg/daemon/daemon.go
  pkg/daemon/update.go
Labels: approved, lgtm, size/M

#174 *: fix mcd docker files
  Dockerfile.machine-config-daemon
  Dockerfile.machine-config-daemon.rhel7
Labels: approved, lgtm

#175 OWNERS: Yifan has moved on to other things :(
  OWNERS
Labels: approved, lgtm, size/XS

#178 Clean up some network sysctls
  pkg/controller/template/test_data/templates/aws/master/files/-etc-modules-load.d-bridge.conf
  pkg/controller/template/test_data/templates/aws/master/files/-etc-sysctl.d-bridge.conf
  pkg/controller/template/test_data/templates/aws/master/files/-etc-sysctl.d-forward.conf
  pkg/controller/template/test_data/templates/aws/worker/files/-etc-sysctl.d-forward.conf
  pkg/controller/template/test_data/templates/libvirt/master/files/-etc-modules-load.d-bridge.conf
  pkg/controller/template/test_data/templates/libvirt/master/files/-etc-sysctl.d-bridge.conf
  pkg/controller/template/test_data/templates/libvirt/master/files/-etc-sysctl.d-forward.conf
  pkg/controller/template/test_data/templates/libvirt/worker/files/-etc-sysctl.d-forward.conf
  pkg/controller/template/test_data/templates/openstack/master/files/-etc-modules-load.d-bridge.conf
  pkg/controller/template/test_data/templates/openstack/master/files/-etc-sysctl.d-bridge.conf
  pkg/controller/template/test_data/templates/openstack/master/files/-etc-sysctl.d-forward.conf
  pkg/controller/template/test_data/templates/openstack/worker/files/-etc-sysctl.d-forward.conf
  templates/_base/master/files/modules-load-bridge-conf.yaml
  templates/_base/master/files/sysctl-bridge-conf.yaml
  templates/_base/master/files/sysctl-forward-conf.yaml
  templates/_base/worker/files/sysctl-forward-conf.yaml
Labels: approved, lgtm, size/L

#169 Ignition parse
  cmd/machine-config-daemon/start.go
  pkg/daemon/daemon.go
  pkg/daemon/update.go
Labels: approved, lgtm, size/M

#180 accept unencoded configmaps
  pkg/operator/operator.go
Labels: approved, lgtm, size/XS

#173 Sync pull secret from `kube-system/coreos-pull-secret` to disk
  cmd/machine-config-controller/bootstrap.go
  cmd/machine-config-operator/bootstrap.go
  lib/resourcemerge/machineconfig.go
  lib/resourcemerge/meta.go
  manifests/bootstrap-pod.yaml
  manifests/machineconfigcontroller/clusterrole.yaml
  manifests/machineconfigcontroller/controllerconfig.yaml
  pkg/apis/machineconfiguration.openshift.io/v1/types.go
  pkg/apis/machineconfiguration.openshift.io/v1/zz_generated.deepcopy.go
  pkg/controller/bootstrap/bootstrap.go
  pkg/controller/template/render.go
  pkg/controller/template/render_test.go
  pkg/controller/template/template_controller.go
  pkg/controller/template/template_controller_test.go
  pkg/controller/template/test_data/controller_config_aws.yaml
  pkg/controller/template/test_data/controller_config_libvirt.yaml
  pkg/controller/template/test_data/controller_config_openstack.yaml
  pkg/controller/template/test_data/templates/aws/master/files/-var-lib-kubelet-config.json
  pkg/controller/template/test_data/templates/aws/worker/files/-var-lib-kubelet-config.json
  pkg/controller/template/test_data/templates/libvirt/master/files/-var-lib-kubelet-config.json
  pkg/controller/template/test_data/templates/libvirt/worker/files/-var-lib-kubelet-config.json
  pkg/controller/template/test_data/templates/openstack/master/files/-var-lib-kubelet-config.json
  pkg/controller/template/test_data/templates/openstack/worker/files/-var-lib-kubelet-config.json
  pkg/operator/assets/bindata.go
  pkg/operator/bootstrap.go
  pkg/operator/operator.go
  pkg/operator/render.go
  templates/_base/master/files/pull-secret.yaml
  templates/_base/worker/files/pull-secret.yaml
Labels: approved, lgtm, size/L

#181 controller: pull secret should always be compacted
  pkg/controller/template/template_controller.go
  pkg/controller/template/template_controller_test.go
Labels: approved, lgtm, size/M

#179 daemon: Unify onceFrom usage to one switch
  cmd/machine-config-daemon/start.go
  pkg/daemon/constants.go
  pkg/daemon/daemon.go
Labels: approved, lgtm, size/L

#184 pkg/controller: disable kubelet readonly port
  pkg/controller/template/test_data/templates/aws/master/files/-etc-kubernetes-kubelet.conf
  pkg/controller/template/test_data/templates/aws/worker/files/-etc-kubernetes-kubelet.conf
  pkg/controller/template/test_data/templates/libvirt/master/files/-etc-kubernetes-kubelet.conf
  pkg/controller/template/test_data/templates/libvirt/worker/files/-etc-kubernetes-kubelet.conf
  pkg/controller/template/test_data/templates/openstack/master/files/-etc-kubernetes-kubelet.conf
  pkg/controller/template/test_data/templates/openstack/worker/files/-etc-kubernetes-kubelet.conf
  templates/_base/master/files/kubelet.yaml
  templates/_base/worker/files/kubelet.yaml
Labels: approved, lgtm, size/S

#190 server: serve on both insecure and secure ports
  cmd/machine-config-server/bootstrap.go
  cmd/machine-config-server/main.go
  cmd/machine-config-server/start.go
  pkg/controller/bootstrap/bootstrap.go
  pkg/controller/render/render_controller.go
  pkg/server/api.go
Labels: approved, lgtm, size/M

#191 hack: change override env for version in build-go.sh
  hack/build-go.sh
Labels: approved, lgtm, size/XS

#192 hack: fix version env
  hack/build-go.sh
Labels: approved, lgtm, size/XS

#194 OWNERS: add more OS folks
  OWNERS
  OWNERS_ALIASES
Labels: approved, lgtm, size/XS
