Repository openshift/machine-config-operator, pull requests merged in 2019-08, with the labels that each got.

#973 OpenStack: Set owners for OpenStack templates
  OWNERS_ALIASES
  templates/common/openstack/OWNERS
  templates/master/00-master/openstack/OWNERS
  templates/master/01-master-container-runtime/openstack/OWNERS
  templates/master/01-master-kubelet/openstack/OWNERS
  templates/worker/00-worker/openstack/OWNERS
  templates/worker/01-worker-container-runtime/openstack/OWNERS
  templates/worker/01-worker-kubelet/openstack/OWNERS
Labels: approved, lgtm, size/M

#740 openstack: Add coredns, mdns-publisher and haproxy static pods
  manifests/openstack/coredns-corefile.tmpl
  manifests/openstack/coredns.yaml
  manifests/openstack/keepalived.conf.tmpl
  manifests/openstack/keepalived.yaml
  pkg/controller/template/render.go
  pkg/controller/template/test_data/controller_config_openstack.yaml
  pkg/operator/assets/bindata.go
  pkg/operator/bootstrap.go
  pkg/operator/render.go
  templates/common/openstack/files/openstack-NetworkManager-kni-conf.yaml
  templates/common/openstack/files/openstack-coredns-corefile.yaml
  templates/common/openstack/files/openstack-coredns-db.yaml
  templates/common/openstack/files/openstack-coredns.yaml
  templates/common/openstack/files/openstack-keepalived.yaml
  templates/common/openstack/files/openstack-mdns-publisher.yaml
  templates/master/00-master/openstack/files/dhcp-dhclient-conf.yaml
  templates/master/00-master/openstack/files/openstack-haproxy-haproxy.yaml
  templates/master/00-master/openstack/files/openstack-haproxy.yaml
  templates/master/00-master/openstack/files/openstack-keepalived-keepalived.yaml
  templates/master/00-master/openstack/files/openstack-mdns-config.yaml
  templates/worker/00-worker/openstack/files/NetworkManager-non-virtual-ip-prepender.yaml
  templates/worker/00-worker/openstack/files/dhcp-dhclient-conf.yaml
  templates/worker/00-worker/openstack/files/openstack-keepalived-keepalived.yaml
  templates/worker/00-worker/openstack/files/openstack-mdns-config.yaml
  templates/worker/00-worker/openstack/files/openstack-non-virtual-ip.yaml
Labels: 4.2, approved, lgtm, size/XXL

#1028 Bug 1737120: fold images: remove stale refs to mc* images in install/image-references
  install/image-references
Labels: approved, bugzilla/valid-bug, lgtm, size/S

#1029 node_controller: Check scheduler config on Node changes.
  pkg/controller/node/node_controller.go
Labels: approved, lgtm, size/L

#1026 baremetal - haproxy static pod, run haproxy process if cfg file exist
  templates/master/00-master/baremetal/files/baremetal-haproxy.yaml
Labels: approved, lgtm, size/XS

#1035 OpenStack: update approvers
  OWNERS_ALIASES
Labels: approved, lgtm, size/XS

#1034 pkg/server: Increase verbosity of server launching
  pkg/server/api.go
Labels: approved, lgtm, size/XS

#1033 pkg/daemon: daemon.go comment fixes
  pkg/daemon/daemon.go
Labels: approved, lgtm, size/S

#1025 hack: Don't error out on cluster-push.sh by default
  hack/cluster-push.sh
Labels: approved, lgtm, size/XS

#1036 vendor: use openshift forks for kube and kubelet
  Gopkg.lock
  Gopkg.toml
  vendor/k8s.io/api/core/v1/types.go
  vendor/k8s.io/api/core/v1/types_swagger_doc_generated.go
  vendor/k8s.io/api/extensions/v1beta1/types.go
  vendor/k8s.io/apiextensions-apiserver/pkg/apis/apiextensions/types.go
  vendor/k8s.io/apiextensions-apiserver/pkg/apis/apiextensions/v1beta1/types.go
  vendor/k8s.io/apiextensions-apiserver/pkg/features/kube_features.go
  vendor/k8s.io/apimachinery/pkg/api/meta/restmapper.go
  vendor/k8s.io/apimachinery/pkg/runtime/types.go
  vendor/k8s.io/client-go/informers/extensions/v1beta1/interface.go
  vendor/k8s.io/client-go/informers/extensions/v1beta1/networkpolicy.go
  vendor/k8s.io/client-go/informers/generic.go
  vendor/k8s.io/client-go/kubernetes/typed/extensions/v1beta1/extensions_client.go
  vendor/k8s.io/client-go/kubernetes/typed/extensions/v1beta1/fake/fake_extensions_client.go
  vendor/k8s.io/client-go/kubernetes/typed/extensions/v1beta1/fake/fake_networkpolicy.go
  vendor/k8s.io/client-go/kubernetes/typed/extensions/v1beta1/generated_expansion.go
  vendor/k8s.io/client-go/kubernetes/typed/extensions/v1beta1/networkpolicy.go
  vendor/k8s.io/client-go/listers/extensions/v1beta1/expansion_generated.go
  vendor/k8s.io/client-go/listers/extensions/v1beta1/networkpolicy.go
  vendor/k8s.io/client-go/rest/config.go
  vendor/k8s.io/client-go/tools/cache/mutation_detector.go
  vendor/k8s.io/client-go/tools/cache/reflector.go
  vendor/k8s.io/client-go/tools/clientcmd/client_config.go
  vendor/k8s.io/client-go/tools/clientcmd/config.go
  vendor/k8s.io/client-go/tools/clientcmd/loader.go
  vendor/k8s.io/code-generator/cmd/client-gen/generators/client_generator.go
  vendor/k8s.io/code-generator/cmd/informer-gen/generators/generic.go
  vendor/k8s.io/code-generator/cmd/informer-gen/generators/packages.go
  vendor/k8s.io/code-generator/cmd/lister-gen/generators/lister.go
  vendor/k8s.io/kubelet/config/v1beta1/types.go
  vendor/k8s.io/kubelet/config/v1beta1/zz_generated.deepcopy.go
  vendor/k8s.io/kubernetes/pkg/apis/core/v1/helper/qos/qos.go
  vendor/k8s.io/kubernetes/pkg/features/kube_features.go
  vendor/k8s.io/kubernetes/pkg/kubelet/apis/config/types.go
  vendor/k8s.io/kubernetes/pkg/kubelet/apis/config/v1beta1/defaults.go
  vendor/k8s.io/kubernetes/pkg/kubelet/apis/config/v1beta1/zz_generated.conversion.go
  vendor/k8s.io/kubernetes/pkg/kubelet/apis/config/zz_generated.deepcopy.go
  vendor/k8s.io/kubernetes/pkg/kubelet/types/pod_update.go
Labels: approved, lgtm, size/XL

#1042 Makefile: increase test-e2e timeout to 120m
  Makefile
  test/e2e/mcd_test.go
Labels: approved, lgtm, size/XS

#1043 baremetal: keepalived to pass cluster-config.yml to runtimecfg
  manifests/baremetal/keepalived.yaml
  pkg/operator/assets/bindata.go
Labels: approved, lgtm, size/S

#1047 templates: Don't run machine-config-daemon-host on BYO RHEL
  templates/common/_base/units/machine-config-daemon-host.service
Labels: approved, lgtm, size/XS

#1041 openstack: import HAproxy config fixes from BM
  templates/master/00-master/openstack/files/openstack-haproxy-haproxy.yaml
  templates/master/00-master/openstack/files/openstack-haproxy.yaml
Labels: approved, lgtm, size/XS

#1050 openstack: keepalived to pass cluster-config.yml to runtimecfg
  manifests/openstack/keepalived.yaml
  pkg/operator/assets/bindata.go
Labels: approved, lgtm, size/S

#1045 pkg/operator/sync.go: udpate the namespace for trust configmap
  pkg/operator/sync.go
Labels: approved, lgtm, size/S

#1049 Bug 1738831: pkg/controller/node: resync all pools for a node
  pkg/controller/node/node_controller.go
  pkg/controller/node/node_controller_test.go
Labels: approved, bugzilla/valid-bug, lgtm, size/L

#1031 cmd: add gcp-routes-controllers to manage the routes service to prevent blackholes
  Dockerfile
  Dockerfile.rhel7
  Gopkg.lock
  Gopkg.toml
  cmd/gcp-routes-controller/main.go
  cmd/gcp-routes-controller/run.go
  cmd/gcp-routes-controller/version.go
  pkg/controller/template/constants.go
  pkg/operator/bootstrap.go
  pkg/operator/sync.go
  templates/master/00-master/gcp/files/etc-kubernetes-manifests-gcp-routes-controller.yaml
  vendor/github.com/InVisionApp/go-health/LICENSE
  vendor/github.com/InVisionApp/go-health/checkers/http.go
  vendor/github.com/InVisionApp/go-health/checkers/reachable.go
  vendor/github.com/InVisionApp/go-health/checkers/sql.go
  vendor/github.com/InVisionApp/go-health/health.go
  vendor/github.com/InVisionApp/go-health/safe.go
  vendor/github.com/InVisionApp/go-logger/LICENSE
  vendor/github.com/InVisionApp/go-logger/log.go
Labels: approved, lgtm, size/XXL

#1040 Revert "openstack: Allow to run MCO changes independently of the installer patches"
  pkg/controller/template/render.go
Labels: approved, lgtm, size/S

#1053 gcp: add resource requests to gcp-routes-controller to make sure it is not in BestEffortQoS
  templates/master/00-master/gcp/files/etc-kubernetes-manifests-gcp-routes-controller.yaml
Labels: approved, lgtm, size/XS

#1052 Bug 1737575: DR: use observed directories vs assumptions for backup_etcd_client_certs
  templates/master/00-master/_base/files/usr-local-bin-openshift-recovery-tools-sh.yaml
Labels: approved, bugzilla/valid-bug, lgtm, size/M

#989 [release-4.1] Bug 1726866: mcc: fix ignition validation to validate entire ign config
  pkg/controller/render/render_controller.go
  pkg/controller/render/render_controller_test.go
  test/e2e/mcd_test.go
Labels: approved, bugzilla/valid-bug, cherry-pick-approved, lgtm, size/M

#1059 Baremetal: enable Haproxy events logging after Haproxy container being restarted
  templates/master/00-master/baremetal/files/baremetal-haproxy.yaml
Labels: approved, lgtm, size/XS

#1062 Bug 1738857: use internal URI for recovery kubeconfig
  templates/master/00-master/_base/files/usr-local-bin-openshift-kubeconfig-gen.yaml
Labels: approved, bugzilla/valid-bug, lgtm, size/XS

#1068 Bug 1743621: pkg/daemon: error early if updating FIPS on non-RHCOS
  pkg/daemon/update.go
Labels: approved, bugzilla/valid-bug, lgtm, size/XS

#1055 [release-4.1] Bug 1740147: DR: use observed directories vs assumptions for backup_etcd_client_certs
  pkg/controller/template/test_data/templates/master/00-master/aws/files/-usr-local-bin-openshift-recovery-tools
  pkg/controller/template/test_data/templates/master/00-master/libvirt/files/-usr-local-bin-openshift-recovery-tools
  pkg/controller/template/test_data/templates/master/00-master/none/files/-usr-local-bin-openshift-recovery-tools
  pkg/controller/template/test_data/templates/master/00-master/openstack/files/-usr-local-bin-openshift-recovery-tools
  pkg/controller/template/test_data/templates/master/00-master/vsphere/files/-usr-local-bin-openshift-recovery-tools
  templates/master/00-master/_base/files/usr-local-bin-openshift-recovery-tools-sh.yaml
Labels: approved, bugzilla/valid-bug, cherry-pick-approved, lgtm, size/M

#1060 Bug 1712826: DR: Add pre-run checks for backup and restore scripts
  templates/master/00-master/_base/files/usr-local-bin-etcd-snapshot-backup-sh.yaml
  templates/master/00-master/_base/files/usr-local-bin-etcd-snapshot-restore-sh.yaml
Labels: approved, bugzilla/valid-bug, lgtm, size/S

#1072 Bug 1744133: Openstack - copy Haproxy container log fix from Baremetal
  templates/master/00-master/openstack/files/openstack-haproxy.yaml
Labels: approved, bugzilla/valid-bug, lgtm, size/XS

#1057 BUG 1742744: DR: set command for setup-etcd-environment
  templates/master/00-master/_base/files/usr-local-bin-etcd-member-recover-sh.yaml
  templates/master/00-master/_base/files/usr-local-share-openshift-recovery-template-etcd-generate-certs-yaml-template.yaml
Labels: approved, bugzilla/valid-bug, lgtm, size/XS

#1066 Bug 1743361: fix updating version output
  pkg/controller/render/render_controller.go
  pkg/operator/status.go
Labels: approved, bugzilla/valid-bug, lgtm, size/XS

#1069 Bug 1743487: Do not requeue a failed kubeletconfig decode
  pkg/controller/kubelet-config/errors.go
  pkg/controller/kubelet-config/kubelet_config_controller.go
Labels: approved, bugzilla/valid-bug, lgtm, size/S

#1073 Bug 1734554: provide etcd-member-add.sh for adding back a member with valid certs
  templates/master/00-master/_base/files/usr-local-bin-etcd-member-add-sh.yaml
Labels: approved, bugzilla/valid-bug, lgtm, size/M

#1075 Bug 1744580: pkg/daemon: create orig file outside of pwd for the file
  pkg/daemon/update.go
Labels: approved, bugzilla/valid-bug, lgtm, size/XS

#1064 Bug 1744764: Report degraded reason in cluster operator status
  pkg/operator/operator.go
  pkg/operator/status.go
  pkg/operator/status_test.go
  pkg/operator/sync.go
Labels: approved, bugzilla/valid-bug, lgtm, size/M

#1063 Bug 1735661: add template with default inotify.max_users settings
  templates/common/_base/files/sysctl-inotify.conf.yaml
Labels: approved, bugzilla/valid-bug, lgtm, size/XS

#1071 Bug 1729510: [release-4.1] backports for drain fixes
  Gopkg.lock
  Gopkg.toml
  Makefile
  manifests/machineconfigdaemon/clusterrole.yaml
  pkg/daemon/update.go
  pkg/operator/assets/bindata.go
  test/e2e/mcd_test.go
  vendor/github.com/openshift/kubernetes-drain/drain.go
Labels: approved, bugzilla/valid-bug, cherry-pick-approved, lgtm, size/M

#1076 Bug 1745240: pkg/operator: fix related objects for must-gather
  pkg/operator/status.go
Labels: approved, bugzilla/valid-bug, lgtm, size/XS

#1082 Bug 1745767: Fix a corner case in mergedMirrorSets
  pkg/controller/container-runtime-config/helpers.go
  pkg/controller/container-runtime-config/helpers_test.go
Labels: approved, bugzilla/valid-bug, lgtm, size/M

#1086 Bug 1741817: mcd: Add /run/machine-config-daemon-force stamp file
  pkg/daemon/constants/constants.go
  pkg/daemon/daemon.go
Labels: approved, bugzilla/valid-bug, lgtm, size/S

#1083 Bug 1743768: avoid excessive dentries due to keepalived static pod health check
  manifests/baremetal/keepalived.yaml
  manifests/openstack/keepalived.yaml
  pkg/operator/assets/bindata.go
  templates/common/baremetal/files/baremetal-keepalived.yaml
  templates/common/openstack/files/openstack-keepalived.yaml
Labels: approved, bugzilla/valid-bug, lgtm, size/S

#1056 Bug 1734554: DR: add etcd-member-remove.sh
  templates/master/00-master/_base/files/usr-local-bin-etcd-member-remove-sh.yaml
  templates/master/00-master/_base/files/usr-local-bin-openshift-recovery-tools-sh.yaml
Labels: approved, bugzilla/valid-bug, lgtm, size/L

#1092 BUG 1747124: cmd/setup-etcd-environment: add support for s390, s390x arch
  cmd/setup-etcd-environment/run.go
Labels: approved, bugzilla/valid-bug, lgtm, size/S

#1093 Bug 1747432: manifests: Add missing terminationMessagePolicy FallbackToLogsOnError
  install/0000_80_machine-config-operator_04_deployment.yaml
  manifests/bootstrap-pod-v2.yaml
  manifests/machineconfigcontroller/deployment.yaml
  manifests/machineconfigdaemon/daemonset.yaml
  manifests/machineconfigserver/daemonset.yaml
  pkg/operator/assets/bindata.go
  templates/master/00-master/_base/files/usr-local-share-openshift-recovery-template-etcd-generate-certs-yaml-template.yaml
Labels: approved, bugzilla/valid-bug, lgtm, size/S

#1087 Bug 1745192: Move registries.conf editing into a subpackage
  pkg/controller/container-runtime-config/helpers.go
  pkg/controller/container-runtime-config/helpers_test.go
  pkg/controller/container-runtime-config/registries/doc.go
  pkg/controller/container-runtime-config/registries/registries.go
  pkg/controller/container-runtime-config/registries/registries_test.go
  pkg/controller/container-runtime-config/registries/topo.go
  pkg/controller/container-runtime-config/registries/topo_test.go
Labels: approved, bugzilla/valid-bug, lgtm, size/XL

#1091 Bug 1741955: bump containerLogMaxSize to 50MB
  templates/master/01-master-kubelet/_base/files/kubelet.yaml
  templates/worker/01-worker-kubelet/_base/files/kubelet.yaml
Labels: approved, bugzilla/valid-bug, lgtm, size/XS
