Repository openshift/machine-config-operator, pull requests merged in 2019-02, with the labels that each got.

#351 operator: fix status updates on ClusterOperator
  Gopkg.lock
  Gopkg.toml
  pkg/operator/operator.go
  pkg/operator/status.go
  pkg/operator/sync.go
  pkg/operator/version.go
  vendor/github.com/openshift/api/config/v1/register.go
  vendor/github.com/openshift/api/config/v1/types.go
  vendor/github.com/openshift/api/config/v1/types_apiserver.go
  vendor/github.com/openshift/api/config/v1/types_authentication.go
  vendor/github.com/openshift/api/config/v1/types_build.go
  vendor/github.com/openshift/api/config/v1/types_cluster_operator.go
  vendor/github.com/openshift/api/config/v1/types_cluster_version.go
  vendor/github.com/openshift/api/config/v1/types_console.go
  vendor/github.com/openshift/api/config/v1/types_dns.go
  vendor/github.com/openshift/api/config/v1/types_idp.go
  vendor/github.com/openshift/api/config/v1/types_image.go
  vendor/github.com/openshift/api/config/v1/types_infrastructure.go
  vendor/github.com/openshift/api/config/v1/types_ingress.go
  vendor/github.com/openshift/api/config/v1/types_network.go
  vendor/github.com/openshift/api/config/v1/types_oauth.go
  vendor/github.com/openshift/api/config/v1/types_project.go
  vendor/github.com/openshift/api/config/v1/types_proxy.go
  vendor/github.com/openshift/api/config/v1/types_scheduling.go
  vendor/github.com/openshift/api/config/v1/types_swagger_doc_generated.go
  vendor/github.com/openshift/api/config/v1/zz_generated.deepcopy.go
  vendor/github.com/openshift/api/config/v1/zz_generated.swagger_doc_generated.go
  vendor/github.com/openshift/client-go/config/clientset/versioned/scheme/register.go
  vendor/github.com/openshift/client-go/config/clientset/versioned/typed/config/v1/apiserver.go
  vendor/github.com/openshift/client-go/config/clientset/versioned/typed/config/v1/config_client.go
  vendor/github.com/openshift/client-go/config/clientset/versioned/typed/config/v1/generated_expansion.go
  vendor/github.com/openshift/client-go/config/clientset/versioned/typed/config/v1/identityprovider.go
  vendor/github.com/openshift/client-go/config/clientset/versioned/typed/config/v1/proxy.go
  vendor/github.com/openshift/library-go/LICENSE
  vendor/github.com/openshift/library-go/pkg/config/clusteroperator/v1helpers/status.go
Labels: approved, lgtm, size/XXL

#359 Change SSH taint to annotation instead
  Gopkg.lock
  Gopkg.toml
  docs/MachineConfigDaemon.md
  pkg/daemon/constants.go
  pkg/daemon/daemon.go
  pkg/daemon/writer.go
  vendor/gopkg.in/fsnotify.v1/AUTHORS
  vendor/gopkg.in/fsnotify.v1/LICENSE
  vendor/gopkg.in/fsnotify.v1/fen.go
  vendor/gopkg.in/fsnotify.v1/fsnotify.go
  vendor/gopkg.in/fsnotify.v1/inotify.go
  vendor/gopkg.in/fsnotify.v1/inotify_poller.go
  vendor/gopkg.in/fsnotify.v1/kqueue.go
  vendor/gopkg.in/fsnotify.v1/open_mode_bsd.go
  vendor/gopkg.in/fsnotify.v1/open_mode_darwin.go
  vendor/gopkg.in/fsnotify.v1/windows.go
Labels: approved, lgtm, size/XXL

#361 e2e/testing: A few small patches
  Makefile
  pkg/controller/node/node_controller.go
  test/e2e/debuglog
Labels: approved, lgtm, size/S

#362 daemon: Handle osImageURL bootstrap
  pkg/daemon/daemon.go
  pkg/daemon/update.go
Labels: approved, lgtm, size/L

#364 HACKING.md: add paragraph to turn verbose on
  HACKING.md
Labels: approved, kind/documentation, lgtm, size/S

#329 Log operator initial sync timings
  pkg/operator/operator.go
  pkg/operator/sync.go
Labels: approved, lgtm, size/M

#377 manifests/daemon: add note about other mountpoints
  manifests/machineconfigdaemon/daemonset.yaml
Labels: approved, lgtm, size/XS

#369 pkg/daemon: idiomatic Go cleanup
  pkg/daemon/constants.go
  pkg/daemon/daemon.go
  pkg/daemon/osrelease.go
  pkg/daemon/update.go
  pkg/daemon/writer.go
Labels: approved, lgtm, size/L

#370 daemon: Bind /run/secrets/ in so we can see SA tokens
  cmd/machine-config-daemon/start.go
  pkg/daemon/daemon.go
  test/e2e/mcd_test.go
Labels: approved, lgtm, size/M

#373 pkg/daemon: check channel closing
  pkg/daemon/daemon.go
Labels: approved, kind/bug, lgtm, size/XS

#375 pkg/daemon: run login monitor for Degraded nodes
  cmd/machine-config-daemon/start.go
  pkg/daemon/daemon.go
Labels: approved, lgtm, size/S

#378 OWNERS: Rework to move everyone to toplevel, add runcom
  OWNERS
  OWNERS_ALIASES
  cmd/machine-config-daemon/OWNERS
  manifests/machineconfigdaemon/OWNERS
  pkg/daemon/OWNERS
  pkg/operator/assets/OWNERS
Labels: approved, lgtm, size/M

#384 templates: Don't hardcode /usr/local/bin for etcd
  pkg/controller/template/test_data/templates/master/00-master/aws/files/-etc-kubernetes-manifests-etcd-member.yaml
  pkg/controller/template/test_data/templates/master/00-master/libvirt/files/-etc-kubernetes-manifests-etcd-member.yaml
  pkg/controller/template/test_data/templates/master/00-master/none/files/-etc-kubernetes-manifests-etcd-member.yaml
  pkg/controller/template/test_data/templates/master/00-master/openstack/files/-etc-kubernetes-manifests-etcd-member.yaml
  pkg/server/testdata/machine-configs/test-config.yaml
  templates/master/00-master/_base/files/etc-kubernetes-manifests-etcd-member.yaml
Labels: approved, lgtm

#368 MCS: change machine-config-server ports
  cmd/machine-config-server/bootstrap.go
  cmd/machine-config-server/main.go
  cmd/machine-config-server/start.go
Labels: approved, lgtm, size/S

#387 test/e2e: add MC smoke test
  test/e2e/mcd_test.go
Labels: approved, lgtm, size/L

#394 update: Retry Drain() multiple times
  pkg/daemon/update.go
Labels: approved, lgtm, size/S

#391 Makefile: set GOCACHE=off in tests
  Makefile
Labels: approved, lgtm, size/XS

#397 Decouple consts in pkg/daemon
  pkg/controller/node/node_controller.go
  pkg/controller/node/node_controller_test.go
  pkg/controller/node/status.go
  pkg/controller/node/status_test.go
  pkg/daemon/constants.go
  pkg/daemon/constants/constants.go
  pkg/daemon/daemon.go
  pkg/daemon/node.go
  pkg/daemon/osrelease.go
  pkg/daemon/update.go
  pkg/daemon/update_test.go
  pkg/daemon/writer.go
  pkg/server/server.go
  pkg/server/server_test.go
Labels: approved, lgtm, size/L

#386 pkg/operator: lay down ClusterOperator for MCO
  install/0000_30_machine-config-operator_06_clusteroperator.yaml
  pkg/operator/sync.go
Labels: approved, lgtm, size/M

#353 templates: add priority class `system-node-critical` to etcd pod
  pkg/controller/template/test_data/templates/master/00-master/aws/files/-etc-kubernetes-manifests-etcd-member.yaml
  pkg/controller/template/test_data/templates/master/00-master/libvirt/files/-etc-kubernetes-manifests-etcd-member.yaml
  pkg/controller/template/test_data/templates/master/00-master/none/files/-etc-kubernetes-manifests-etcd-member.yaml
  pkg/controller/template/test_data/templates/master/00-master/openstack/files/-etc-kubernetes-manifests-etcd-member.yaml
  templates/master/00-master/_base/files/etc-kubernetes-manifests-etcd-member.yaml
Labels: approved, lgtm, size/S

#402 pkg/daemon: add missing defer file.Close
  pkg/daemon/update.go
Labels: approved, lgtm, size/XS

#405 daemon: Write out pending state file just before reboot
  pkg/daemon/update.go
Labels: approved, lgtm, size/XS

#403 bootstrap: Require images on command line
  cmd/machine-config-operator/bootstrap.go
  pkg/operator/images.go
  pkg/operator/operator.go
Labels: approved, lgtm, size/M

#408 daemon: Clearly log if error is from draining
  pkg/daemon/update.go
Labels: approved, lgtm, size/S

#404 image-references: Update maipo oscontainer
  install/image-references
Labels: approved, lgtm, size/XS

#412 daemon/update: Log each error before retrying
  pkg/daemon/update.go
Labels: approved, lgtm, size/XS

#411 pkg/daemon: write bytes, use buffered writer and compare bytes
  pkg/daemon/daemon.go
  pkg/daemon/daemon_test.go
  pkg/daemon/update.go
Labels: approved, lgtm, size/S

#335 Use pivot.service to perform pivot
  Gopkg.lock
  hack/build-go.sh
  pkg/daemon/rpm-ostree.go
  vendor/github.com/coreos/go-systemd/dbus/dbus.go
  vendor/github.com/coreos/go-systemd/dbus/methods.go
  vendor/github.com/coreos/go-systemd/dbus/properties.go
  vendor/github.com/coreos/go-systemd/dbus/set.go
  vendor/github.com/coreos/go-systemd/dbus/subscription.go
  vendor/github.com/coreos/go-systemd/dbus/subscription_set.go
  vendor/github.com/coreos/go-systemd/sdjournal/functions.go
  vendor/github.com/coreos/go-systemd/sdjournal/journal.go
  vendor/github.com/coreos/go-systemd/sdjournal/read.go
  vendor/github.com/coreos/pkg/LICENSE
  vendor/github.com/coreos/pkg/NOTICE
  vendor/github.com/coreos/pkg/dlopen/dlopen.go
  vendor/github.com/coreos/pkg/dlopen/dlopen_example.go
Labels: approved, lgtm, size/XXL

#413 hack/build-go: strip debuginfo from binaries
  hack/build-go.sh
Labels: approved, lgtm, size/XS

#418 [cleanup] pkg/daemon: do not use pointers to strings for errors + unexport consts
  pkg/daemon/daemon.go
  pkg/daemon/update.go
  pkg/daemon/update_test.go
Labels: approved, lgtm, size/M

#381 pkg/daemon: detect ssh accesses before daemon started
  pkg/daemon/daemon.go
Labels: approved, lgtm, size/M

#422 HACKING.md: Elaborate on testing, interacting with PRs
  docs/HACKING.md
Labels: approved, lgtm, size/M

#424 kubelet config deletions fix + example update
  examples/kubeletconfig.crd.yaml
  pkg/controller/kubelet-config/kubelet_config_controller.go
Labels: approved, lgtm, size/XS

#419 Controller logging
  pkg/controller/node/node_controller.go
  pkg/controller/node/node_controller_test.go
Labels: approved, lgtm, size/S

#427 docs: update oc commands for watching a live ci cluster
  docs/HACKING.md
Labels: approved, lgtm, size/XS

#425 docs: HACKING.md: add custom payload build section
  docs/HACKING.md
Labels: approved, lgtm, size/M

#416 pkg/daemon/update.go: check wait err and wrap it
  pkg/daemon/update.go
Labels: approved, lgtm, size/S

#423 MCS: remove legacy servers & ports
  cmd/machine-config-server/bootstrap.go
  cmd/machine-config-server/start.go
Labels: approved, lgtm, size/S

#415 mcd: remove unnecessary checks and simplify updateSSHKeys
  pkg/daemon/update.go
  pkg/daemon/update_test.go
Labels: approved, lgtm, size/M

#430 kubeletconfig: add support for observedgeneration
  pkg/controller/kubelet-config/kubelet_config_controller.go
  pkg/controller/kubelet-config/kubelet_config_controller_test.go
Labels: approved, lgtm, size/S

#431 .github: add templates for issues and PRs
  .github/ISSUE_TEMPLATE.md
  .github/PULL_REQUEST_TEMPLATE.md
Labels: approved, lgtm, size/M

#420 append kube-ca to root-ca for mco config
  cmd/machine-config-operator/bootstrap.go
  pkg/operator/bootstrap.go
  pkg/operator/operator.go
Labels: approved, lgtm, size/S

#409 daemon: Add GetNode() wrapper which retries on errors
  pkg/daemon/daemon.go
  pkg/daemon/node.go
  pkg/daemon/update.go
  pkg/daemon/writer.go
Labels: approved, lgtm, size/M

#406 pkg/operator: correctly sync status for the CVO
  pkg/operator/status.go
  pkg/operator/sync.go
Labels: approved, lgtm, size/M

#436 cmd/controller: Fix minor typo in error message
  cmd/machine-config-controller/bootstrap.go
Labels: approved, lgtm, size/XS

#434 [cleanup] pkg/controller: don't use index in ranges, use int instead of int32
  pkg/controller/node/node_controller.go
  pkg/controller/node/node_controller_test.go
  pkg/controller/node/status.go
  pkg/controller/render/render_controller.go
  pkg/controller/template/render.go
  pkg/controller/template/template_controller.go
Labels: approved, lgtm, size/M

#438 templates: remove How I did it section from PR template
  .github/PULL_REQUEST_TEMPLATE.md
Labels: approved, lgtm, size/XS

#439 pkg/operator: link related objects to clusteroperator
  pkg/operator/status.go
  test/e2e/mco_test.go
Labels: approved, lgtm, size/M

#440 README.md: fix link to HACKING.md
  README.md
Labels: approved, lgtm, size/XS

#437 kubeletconfig: fix updates, add unit test, race condition fix
  pkg/controller/kubelet-config/kubelet_config_controller.go
  pkg/controller/kubelet-config/kubelet_config_controller_test.go
Labels: approved, lgtm, size/L

#445 image: MCD depends on util-linux (mount) which is being removed from base
  Dockerfile.machine-config-daemon
  Dockerfile.machine-config-daemon.rhel7
Labels: approved, lgtm, size/XS

#446 test/e2e: check MC deployed on every node
  test/e2e/mcd_test.go
Labels: approved, lgtm, size/M

#442 MCO: clear out failing status on success and add tests
  Gopkg.lock
  Gopkg.toml
  cmd/common/client_builder.go
  cmd/machine-config-operator/start.go
  pkg/operator/operator.go
  pkg/operator/status.go
  pkg/operator/status_test.go
  pkg/operator/sync.go
  vendor/github.com/pmezard/go-difflib/LICENSE
  vendor/github.com/pmezard/go-difflib/difflib/difflib.go
  vendor/github.com/stretchr/testify/LICENSE
  vendor/github.com/stretchr/testify/assert/assertion_format.go
  vendor/github.com/stretchr/testify/assert/assertion_forward.go
  vendor/github.com/stretchr/testify/assert/assertions.go
  vendor/github.com/stretchr/testify/assert/doc.go
  vendor/github.com/stretchr/testify/assert/errors.go
  vendor/github.com/stretchr/testify/assert/forward_assertions.go
  vendor/github.com/stretchr/testify/assert/http_assertions.go
Labels: approved, kind/bug, lgtm, size/XXL

#426 server: Implement "early pivot" before the MCD comes up
  install/image-references
  pkg/controller/template/render.go
  pkg/daemon/constants/constants.go
  pkg/daemon/rpm-ostree.go
  pkg/server/bootstrap_server.go
  pkg/server/cluster_server.go
  pkg/server/server.go
  test/e2e/osimageurl_test.go
Labels: approved, lgtm, size/L

#448 pkg/daemon: ensure /home/core/.ssh is there, not just /home/core
  pkg/daemon/update.go
Labels: approved, lgtm, size/XS

#454 daemon: Don't do OS updates/pivoting on !RHCOS
  pkg/daemon/daemon.go
Labels: approved, lgtm, size/S

#456 pkg/controller: remove fmt.Println
  pkg/controller/container-runtime-config/container_runtime_config_controller.go
Labels: approved, lgtm, size/XS

#458 Fix RHEL image typo
  Dockerfile.machine-config-daemon.rhel7
Labels: approved, lgtm, size/XS

#459 bootstrap: set --kube-ca default to empty
  cmd/machine-config-operator/bootstrap.go
Labels: approved, lgtm, size/XS

#452 pkg/operator: use fake clients in unit
  cmd/common/client_builder.go
  cmd/machine-config-operator/start.go
  pkg/operator/operator.go
  pkg/operator/status.go
  pkg/operator/status_test.go
Labels: approved, lgtm, size/M

#461 Add extra filter for checking if registries have changed
  pkg/controller/container-runtime-config/container_runtime_config_controller.go
Labels: approved, lgtm, size/S

#457 pkg/controller: start informers before populating store in tests
  pkg/controller/container-runtime-config/container_runtime_config_controller_test.go
  pkg/controller/kubelet-config/kubelet_config_controller_test.go
  pkg/controller/node/node_controller_test.go
  pkg/controller/render/render_controller_test.go
  pkg/controller/template/template_controller_test.go
Labels: approved, lgtm, size/L

#466 Add unit tests for containerruntimeconfig controller
  pkg/controller/container-runtime-config/container_runtime_config_controller_test.go
Labels: approved, lgtm, size/L

#470 machineconfig: Drop osimageurl from `oc get machineconfigs`
  manifests/machineconfig.crd.yaml
  pkg/operator/assets/bindata.go
Labels: approved, lgtm, size/XS

#477 daemon: Catch SIGTERM and ignore it if we're doing an update
  manifests/machineconfigdaemon/daemonset.yaml
  pkg/daemon/daemon.go
  pkg/daemon/update.go
Labels: approved, lgtm, size/S

#463 daemon: Accept osImageURL with matching digests
  pkg/daemon/daemon.go
  pkg/daemon/daemon_test.go
  pkg/daemon/update.go
Labels: approved, lgtm, size/L

#473 Makefile: fix io redirection for image targets
  Makefile
Labels: approved, lgtm, size/XS

#474 log rpm-ostree status, and fix hack/
  cmd/machine-config-daemon/start.go
  hack/build-image.sh
  hack/cluster-push.sh
  pkg/daemon/rpm-ostree.go
  pkg/daemon/rpm-ostree_test.go
Labels: approved, lgtm, size/M

#489 pkg/controller: fix container runtime registries generation
  pkg/controller/container-runtime-config/container_runtime_config_controller.go
Labels: approved, lgtm, size/XS

#491 daemon: Uninstall SIGTERM handler just before rebooting
  pkg/daemon/update.go
Labels: approved, lgtm, size/XS

#494 Add infra-image flag to bootstrap.go as no-op
  cmd/machine-config-operator/bootstrap.go
Labels: approved, lgtm, size/XS

#495 daemon: Only print status if os == RHCOS
  cmd/machine-config-daemon/start.go
  pkg/daemon/daemon.go
Labels: approved, lgtm, size/S

#500 Add pod image to image-references
  install/image-references
Labels: approved, lgtm, size/XS

#464 pkg/daemon: stash the node object
  pkg/daemon/daemon.go
  pkg/daemon/node.go
  pkg/daemon/update.go
  pkg/daemon/writer.go
Labels: approved, lgtm, size/L

#503 Eliminate use of cpu limits
  examples/machinecontrollerconfig.deploy.yaml
  manifests/bootstrap-pod-v2.yaml
  manifests/machineconfigcontroller/deployment.yaml
  pkg/operator/assets/bindata.go
Labels: approved, lgtm, size/XS

#481 MCD: add ign validation check for mc.ignconfig
  pkg/daemon/update.go
  pkg/daemon/update_test.go
Labels: approved, lgtm, size/L

#504 Makefile: add bindata generation to update target
  Makefile
Labels: approved, lgtm, size/XS

#471 Pick image from release payload for crio.conf pause_image
  cmd/machine-config-controller/start.go
  cmd/machine-config-operator/bootstrap.go
  docs/ContainerRuntimeConfigDesign.md
  install/0000_30_machine-config-operator_02_images.configmap.yaml
  pkg/apis/machineconfiguration.openshift.io/v1/types.go
  pkg/controller/container-runtime-config/container_runtime_config_controller.go
  pkg/controller/container-runtime-config/helpers.go
  pkg/controller/template/constants.go
  pkg/controller/template/test_data/controller_config_aws.yaml
  pkg/controller/template/test_data/controller_config_libvirt.yaml
  pkg/controller/template/test_data/controller_config_none.yaml
  pkg/controller/template/test_data/controller_config_openstack.yaml
  pkg/controller/template/test_data/templates/master/01-master-container-runtime/aws/files/-etc-crio-crio.conf
  pkg/controller/template/test_data/templates/master/01-master-container-runtime/libvirt/files/-etc-crio-crio.conf
  pkg/controller/template/test_data/templates/master/01-master-container-runtime/none/files/-etc-crio-crio.conf
  pkg/controller/template/test_data/templates/master/01-master-container-runtime/openstack/files/-etc-crio-crio.conf
  pkg/controller/template/test_data/templates/worker/01-worker-container-runtime/aws/files/-etc-crio-crio.conf
  pkg/controller/template/test_data/templates/worker/01-worker-container-runtime/libvirt/files/-etc-crio-crio.conf
  pkg/controller/template/test_data/templates/worker/01-worker-container-runtime/none/files/-etc-crio-crio.conf
  pkg/controller/template/test_data/templates/worker/01-worker-container-runtime/openstack/files/-etc-crio-crio.conf
  pkg/operator/bootstrap.go
  pkg/operator/images.go
  pkg/operator/operator.go
  templates/master/01-master-container-runtime/_base/files/crio.yaml
  templates/worker/01-worker-container-runtime/_base/files/crio.yaml
Labels: approved, lgtm, size/M

#509 docs/Update-SSHKeys: fix SSH key example
  docs/Update-SSHKeys.md
Labels: approved, do-not-merge/hold, lgtm, size/S
