Repository openshift/machine-config-operator, pull requests merged in 2019-09, with the labels that each got.

#1080 Bug 1745016: [release-4.1] add base templates with default inotify.max_user settings
  pkg/controller/template/test_data/templates/master/00-master/aws/files/-etc-sysctl.d-inotify.conf
  pkg/controller/template/test_data/templates/master/00-master/libvirt/files/-etc-sysctl.d-inotify.conf
  pkg/controller/template/test_data/templates/master/00-master/none/files/-etc-sysctl.d-inotify.conf
  pkg/controller/template/test_data/templates/master/00-master/openstack/files/-etc-sysctl.d-inotify.conf
  pkg/controller/template/test_data/templates/master/00-master/vsphere/files/-etc-sysctl.d-inotify.conf
  pkg/controller/template/test_data/templates/worker/00-worker/aws/files/-etc-sysctl.d-inotify.conf
  pkg/controller/template/test_data/templates/worker/00-worker/libvirt/files/-etc-sysctl.d-inotify.conf
  pkg/controller/template/test_data/templates/worker/00-worker/none/files/-etc-sysctl.d-inotify.conf
  pkg/controller/template/test_data/templates/worker/00-worker/openstack/files/-etc-sysctl.d-inotify.conf
  pkg/controller/template/test_data/templates/worker/00-worker/vsphere/files/-etc-sysctl.d-inotify.conf
  templates/master/00-master/_base/files/sysctl-inotify.conf.yaml
  templates/worker/00-worker/_base/files/sysctl-inotify.conf.yaml
Labels: approved, bugzilla/valid-bug, cherry-pick-approved, lgtm, size/S

#1095 Bug 1747608: APIServerInternalURL fix for kubelet
  pkg/operator/sync.go
Labels: approved, bugzilla/valid-bug, lgtm, size/XS

#995 Bug 1728873: pkg/daemon: reconcile killed just prior drain+reboot
  pkg/daemon/daemon.go
  pkg/daemon/update.go
Labels: approved, bugzilla/valid-bug, cherry-pick-approved, lgtm, size/M

#1101 Bug 1748807: tuning of API LB configuration parameters
  templates/master/00-master/baremetal/files/baremetal-haproxy-haproxy.yaml
  templates/master/00-master/openstack/files/openstack-haproxy-haproxy.yaml
Labels: approved, bugzilla/valid-bug, lgtm, size/XS

#1098 Bug 1748844: vendor: use cluster-api's drain lib
  Gopkg.lock
  Gopkg.toml
  pkg/daemon/daemon.go
  pkg/daemon/update.go
  vendor/github.com/openshift/cluster-api/LICENSE
  vendor/github.com/openshift/cluster-api/pkg/drain/drain.go
Labels: approved, bugzilla/valid-bug, lgtm, size/M

#1104 Bug 1745875: Change config templates for BYOH Proxy
  templates/common/_base/files/etc-systemd-system-crio.service.d-10-default-env.conf.yaml
  templates/common/_base/files/etc-systemd-system-kubelet.service.d-10-default-env.conf.yaml
  templates/common/_base/files/etc-systemd-system-machine-config-daemon-host.service.d-10-default-env.conf.yaml
  templates/common/_base/files/etc-systemd-system-pivot.service.d-10-default-env.conf.yaml
Labels: approved, bugzilla/valid-bug, lgtm, size/S

#1103 [release-4.1] Bug 1749271: Backport mcd: Add /run/machine-config-daemon-force stampfile #1086
  pkg/daemon/constants/constants.go
  pkg/daemon/daemon.go
Labels: approved, bugzilla/valid-bug, cherry-pick-approved, lgtm, size/S

#1085 [release 4.1] Bug 1741065: Report degraded reason in cluster operator status
  pkg/operator/operator.go
  pkg/operator/status.go
  pkg/operator/status_test.go
  pkg/operator/sync.go
Labels: approved, bugzilla/valid-bug, cherry-pick-approved, lgtm, size/M

#1105 Bug 1749446: Creates alternative CNI configuration directory for the cluster network operator
  templates/common/_base/files/cleanup-cni-conf.yaml
Labels: approved, bugzilla/valid-bug, lgtm, size/XS

#1097 Bug 1748081: DR: ensure piped commands exit 0
  templates/master/00-master/_base/files/usr-local-bin-etcd-member-recover-sh.yaml
  templates/master/00-master/_base/files/usr-local-bin-openshift-recovery-tools-sh.yaml
Labels: approved, bugzilla/valid-bug, lgtm, size/S

#1108 Bug 1748081: DR: send error to stderr before exit for validate_etcd_name
  templates/master/00-master/_base/files/usr-local-bin-openshift-recovery-tools-sh.yaml
Labels: approved, bugzilla/valid-bug, lgtm, size/XS

#1099 [release-4.1] Bug 1749070: vendor: use cluster-api's drain lib
  Gopkg.lock
  Gopkg.toml
  pkg/daemon/daemon.go
  pkg/daemon/update.go
  vendor/github.com/openshift/cluster-api/LICENSE
  vendor/github.com/openshift/cluster-api/pkg/drain/drain.go
Labels: approved, bugzilla/valid-bug, cherry-pick-approved, lgtm, size/M

#1116 OpenStack: increase haproxy timeouts
  templates/master/00-master/openstack/files/openstack-haproxy-haproxy.yaml
Labels: approved, lgtm, size/S

#1117 Bug 1748798: Add backing up of client certs
  templates/master/00-master/_base/files/usr-local-bin-etcd-member-add-sh.yaml
Labels: approved, bugzilla/valid-bug, lgtm, size/XS

#1120 Bug 1752982: kubelet: remove runtimeRequestTimeout
  templates/master/01-master-kubelet/_base/files/kubelet.yaml
  templates/worker/01-worker-kubelet/_base/files/kubelet.yaml
Labels: approved, bugzilla/valid-bug, lgtm, size/XS

#1122 Bug 1753067: Create a namespace for OpenStack infra static pods
  install/0000_80_machine-config-operator_00_namespace.yaml
  manifests/openstack/coredns.yaml
  manifests/openstack/keepalived.yaml
  pkg/operator/assets/bindata.go
  templates/common/openstack/files/openstack-NetworkManager-conf.yaml
  templates/common/openstack/files/openstack-coredns.yaml
  templates/common/openstack/files/openstack-keepalived.yaml
  templates/common/openstack/files/openstack-mdns-publisher.yaml
  templates/master/00-master/baremetal/files/baremetal-haproxy.yaml
  templates/master/00-master/openstack/files/openstack-haproxy.yaml
Labels: approved, bugzilla/valid-bug, lgtm, size/M

#1123 Bug 1753411: manifests: Create namespace for static pods IPI-BM
  install/0000_80_machine-config-operator_00_namespace.yaml
Labels: approved, bugzilla/valid-bug, lgtm, size/S

#1124 Bug 1751978: templates/baremetal: Fix keepalived dysfunction on vrrp iface change
  templates/common/baremetal/files/baremetal-keepalived.yaml
Labels: approved, bugzilla/valid-bug, lgtm, size/L

#1125 Bug 1753932: OpenStack: Ensure haproxy pod has the needed resources
  templates/master/00-master/openstack/files/openstack-haproxy.yaml
Labels: approved, bugzilla/valid-bug, lgtm, size/XS

#1127 Bug 1753953: Temporarily put OpenStack infra pods into non-existing namespace
  manifests/openstack/coredns.yaml
  manifests/openstack/keepalived.yaml
  pkg/operator/assets/bindata.go
  templates/common/openstack/files/openstack-coredns.yaml
  templates/common/openstack/files/openstack-keepalived.yaml
  templates/common/openstack/files/openstack-mdns-publisher.yaml
  templates/master/00-master/baremetal/files/baremetal-haproxy.yaml
  templates/master/00-master/openstack/files/openstack-haproxy.yaml
Labels: approved, bugzilla/valid-bug, lgtm, size/S

#985 [4.3] manifests: Show machine counts in `oc get machineconfigpools` output
  manifests/machineconfigpool.crd.yaml
  pkg/operator/assets/bindata.go
Labels: 4.3, approved, lgtm, size/M

#1109 pkg/daemon: return from signal handler once signaled
  pkg/daemon/daemon.go
Labels: approved, lgtm, size/XS

#1084 ctrcfg: setup OWNERS for code and templates
  pkg/controller/container-runtime-config/OWNERS
  templates/master/01-master-container-runtime/OWNERS
  templates/worker/01-worker-container-runtime/OWNERS
Labels: approved, lgtm, size/S

#1133 Bug 1755560: Ensure ETCD_INITIAL_CLUSTER is preserved during restore
  templates/master/00-master/_base/files/usr-local-bin-etcd-snapshot-restore-sh.yaml
Labels: approved, bugzilla/valid-bug, lgtm, size/XS

#1111 pkg/daemon: add check for logger in CentOS
  pkg/daemon/daemon.go
Labels: approved, lgtm, size/XS

#1115 cmd: Unit test for setBootstrapEnv() method
  cmd/setup-etcd-environment/run_test.go
Labels: approved, lgtm, size/L

#1141 spec: Include doc/README.md directly
  machine-config-daemon.spec
Labels: approved, lgtm, size/XS

#1078 docs: update SSH docs to add keys
  docs/Update-SSHKeys.md
Labels: approved, lgtm, size/M

#1090 pkg/operator: fix DS unavailable count reporting
  pkg/operator/sync.go
Labels: approved, lgtm, size/XS

#1081 docs: add custom pools instructions
  docs/custom-pools.md
Labels: approved, lgtm, size/L

#1131 Bug 1753067: Revert: "Temporarily put OpenStack infra pods into non-existing namespace"
  manifests/openstack/coredns.yaml
  manifests/openstack/keepalived.yaml
  pkg/operator/assets/bindata.go
  templates/common/openstack/files/openstack-coredns.yaml
  templates/common/openstack/files/openstack-keepalived.yaml
  templates/common/openstack/files/openstack-mdns-publisher.yaml
  templates/master/00-master/baremetal/files/baremetal-haproxy.yaml
  templates/master/00-master/openstack/files/openstack-haproxy.yaml
Labels: approved, bugzilla/valid-bug, lgtm, size/S

#1142 Enable LatencySensitive and CustomNoUpgrade FeatureSets
  Gopkg.lock
  pkg/controller/kubelet-config/kubelet_config_features.go
  vendor/github.com/openshift/api/config/v1/doc.go
  vendor/github.com/openshift/api/config/v1/register.go
  vendor/github.com/openshift/api/config/v1/types.go
  vendor/github.com/openshift/api/config/v1/types_apiserver.go
  vendor/github.com/openshift/api/config/v1/types_build.go
  vendor/github.com/openshift/api/config/v1/types_cluster_version.go
  vendor/github.com/openshift/api/config/v1/types_dns.go
  vendor/github.com/openshift/api/config/v1/types_feature.go
  vendor/github.com/openshift/api/config/v1/types_image.go
  vendor/github.com/openshift/api/config/v1/types_ingress.go
  vendor/github.com/openshift/api/config/v1/types_network.go
  vendor/github.com/openshift/api/config/v1/types_operatorhub.go
  vendor/github.com/openshift/api/config/v1/types_proxy.go
  vendor/github.com/openshift/api/config/v1/types_scheduling.go
  vendor/github.com/openshift/api/config/v1/zz_generated.deepcopy.go
  vendor/github.com/openshift/api/config/v1/zz_generated.swagger_doc_generated.go
  vendor/github.com/openshift/api/operator/v1/types_ingress.go
  vendor/github.com/openshift/api/operator/v1/types_network.go
  vendor/github.com/openshift/api/operator/v1/zz_generated.deepcopy.go
  vendor/github.com/openshift/api/operator/v1/zz_generated.swagger_doc_generated.go
  vendor/github.com/openshift/api/operator/v1alpha1/zz_generated.deepcopy.go
Labels: approved, lgtm, size/XL
