Repository openshift/machine-config-operator, pull requests merged in 2019-12, with the labels that each got.

#1297 Disable Zincati on masters/workers
  templates/common/_base/files/etc-zincati-config.d-90-disable-feature-toml.yaml
Labels: approved, lgtm, size/XS

#1220 [fcos] Update vendoring
  go.mod
  go.sum
  vendor/golang.org/x/net/http2/pipe.go
  vendor/golang.org/x/net/http2/server.go
  vendor/golang.org/x/net/http2/transport.go
  vendor/golang.org/x/net/http2/writesched_random.go
  vendor/golang.org/x/sys/unix/sockcmsg_dragonfly.go
  vendor/golang.org/x/sys/unix/sockcmsg_linux.go
  vendor/golang.org/x/sys/unix/sockcmsg_unix.go
  vendor/golang.org/x/sys/unix/sockcmsg_unix_other.go
  vendor/golang.org/x/sys/unix/syscall_bsd.go
  vendor/golang.org/x/sys/unix/syscall_dragonfly.go
  vendor/golang.org/x/sys/unix/syscall_linux.go
  vendor/golang.org/x/sys/unix/syscall_solaris.go
  vendor/golang.org/x/sys/unix/ztypes_linux_386.go
  vendor/golang.org/x/sys/unix/ztypes_linux_amd64.go
  vendor/golang.org/x/sys/unix/ztypes_linux_arm.go
  vendor/golang.org/x/sys/unix/ztypes_linux_arm64.go
  vendor/golang.org/x/sys/unix/ztypes_linux_mips.go
  vendor/golang.org/x/sys/unix/ztypes_linux_mips64.go
  vendor/golang.org/x/sys/unix/ztypes_linux_mips64le.go
  vendor/golang.org/x/sys/unix/ztypes_linux_mipsle.go
  vendor/golang.org/x/sys/unix/ztypes_linux_ppc64.go
  vendor/golang.org/x/sys/unix/ztypes_linux_ppc64le.go
  vendor/golang.org/x/sys/unix/ztypes_linux_riscv64.go
  vendor/golang.org/x/sys/unix/ztypes_linux_s390x.go
  vendor/golang.org/x/sys/unix/ztypes_linux_sparc64.go
  vendor/golang.org/x/sys/windows/asm_windows_386.s
  vendor/golang.org/x/sys/windows/asm_windows_amd64.s
  vendor/golang.org/x/sys/windows/asm_windows_arm.s
  vendor/golang.org/x/sys/windows/dll_windows.go
  vendor/golang.org/x/sys/windows/mksyscall.go
  vendor/golang.org/x/sys/windows/registry/mksyscall.go
  vendor/golang.org/x/sys/windows/security_windows.go
  vendor/golang.org/x/sys/windows/syscall_windows.go
  vendor/golang.org/x/sys/windows/types_windows.go
  vendor/golang.org/x/sys/windows/zsyscall_windows.go
  vendor/golang.org/x/tools/go/analysis/diagnostic.go
  vendor/golang.org/x/tools/go/analysis/passes/asmdecl/asmdecl.go
  vendor/golang.org/x/tools/go/analysis/passes/printf/printf.go
  vendor/golang.org/x/tools/go/analysis/validate.go
  vendor/golang.org/x/tools/go/gcexportdata/gcexportdata.go
  vendor/golang.org/x/tools/go/internal/gcimporter/iexport.go
  vendor/golang.org/x/tools/go/internal/gcimporter/iimport.go
  vendor/golang.org/x/tools/go/packages/golist.go
  vendor/golang.org/x/tools/go/packages/golist_overlay.go
  vendor/golang.org/x/tools/go/ssa/func.go
  vendor/golang.org/x/tools/internal/gopathwalk/walk.go
  vendor/golang.org/x/tools/internal/imports/fix.go
  vendor/golang.org/x/tools/internal/imports/mod.go
  vendor/golang.org/x/tools/internal/imports/mod_cache.go
  vendor/golang.org/x/tools/internal/span/parse.go
  vendor/golang.org/x/tools/internal/span/span.go
  vendor/golang.org/x/tools/internal/span/token.go
  vendor/golang.org/x/tools/internal/span/token111.go
  vendor/golang.org/x/tools/internal/span/token112.go
  vendor/golang.org/x/tools/internal/span/uri.go
  vendor/golang.org/x/tools/internal/span/utf16.go
  vendor/modules.txt
Labels: approved, lgtm, size/XXL

#1279 [FCOS] Pull MCD image and extract binary if it doesn't exists
  templates/common/_base/units/machine-config-daemon-pull.service
Labels: approved, lgtm, size/XS

#1285 Bug 1775647: pkg/daemon: randomize pivot container name
  pkg/daemon/pivot/types/imageinspection.go
  pkg/daemon/rpm-ostree.go
Labels: approved, bugzilla/valid-bug, lgtm, size/S

#1277 docs/README: fix broken links
  docs/README.md
Labels: approved, lgtm, retest-not-required-docs-only, size/S

#1256 [Baremetal] Haproxy add support for IPv6 frontend
  templates/master/00-master/baremetal/files/baremetal-haproxy-haproxy.yaml
  templates/master/00-master/baremetal/files/baremetal-keepalived-keepalived.yaml
Labels: approved, lgtm, size/XS

#1278 Bug 1774369: skip setting the kubeletconfig finalizer if it is set
  pkg/controller/kubelet-config/kubelet_config_controller.go
Labels: approved, bugzilla/valid-bug, lgtm, size/XS

#1295 Bug 1777837: BAREMETAL- decrease infra pods resources
  manifests/baremetal/coredns.yaml
  manifests/baremetal/keepalived.yaml
  pkg/operator/assets/bindata.go
  templates/common/baremetal/files/baremetal-coredns.yaml
  templates/common/baremetal/files/baremetal-keepalived.yaml
  templates/common/baremetal/files/baremetal-mdns-publisher.yaml
Labels: approved, bugzilla/valid-bug, lgtm, size/S

#1299 CRI-O: add old default hook directories
  templates/master/01-master-container-runtime/_base/files/crio.yaml
  templates/worker/01-worker-container-runtime/_base/files/crio.yaml
Labels: approved, lgtm, size/S

#1010 Standardize printer column "Age" on mco CRDs.
  manifests/machineconfig.crd.yaml
  manifests/machineconfigpool.crd.yaml
  pkg/operator/assets/bindata.go
Labels: approved, lgtm, size/S

#1304 Bug 1775643: [release-4.3] Revert "*: add support for cluster-etcd-operator"
  cmd/machine-config-operator/bootstrap.go
  cmd/setup-etcd-environment/run.go
  install/0000_80_machine-config-operator_02_images.configmap.yaml
  pkg/controller/template/constants.go
  pkg/controller/template/render.go
  pkg/operator/bootstrap.go
  pkg/operator/images.go
  pkg/operator/sync.go
  templates/master/00-master/_base/files/etc-kubernetes-manifests-etcd-member.yaml
  vendor/github.com/openshift/cluster-etcd-operator/LICENSE
  vendor/github.com/openshift/cluster-etcd-operator/pkg/operator/api/scaling.go
Labels: approved, bugzilla/valid-bug, lgtm, size/XL

#1305 Bug 1777838: [release-4.3] CRI-O: add old default hook directories
  templates/master/01-master-container-runtime/_base/files/crio.yaml
  templates/worker/01-worker-container-runtime/_base/files/crio.yaml
Labels: approved, bugzilla/valid-bug, lgtm, size/S

#1296 CRI-O: Set conmon_cgroup to "pod"
  templates/master/01-master-container-runtime/_base/files/crio.yaml
  templates/worker/01-worker-container-runtime/_base/files/crio.yaml
Labels: approved, lgtm, size/XS

#1287 cmd/setup-etcd-environment: refactor and add tests
  cmd/setup-etcd-environment/run.go
  cmd/setup-etcd-environment/run_test.go
Labels: approved, lgtm, size/XL

#1310 OWNERSFILE: remove lorbuschris
  OWNERS
Labels: approved, lgtm, size/XS

#1315 FAQ: So many machine thingys
  docs/FAQ.md
Labels: approved, lgtm, retest-not-required, retest-not-required-docs-only, size/S

#1320 templates/container-storage: Add a "this is generated" note
  templates/common/_base/files/container-storage.yaml
  templates/worker/01-worker-container-runtime/_base/files/container-storage.yaml
Labels: approved, lgtm, size/L

#1327 docs/FAQ: The MCO isn't exclusive
  docs/FAQ.md
Labels: approved, lgtm, retest-not-required-docs-only, size/S

#1311 [FCOS] templates: remove /usr/share/containers/oci/hooks.d from crio config
  templates/master/01-master-container-runtime/_base/files/crio.yaml
  templates/worker/01-worker-container-runtime/_base/files/crio.yaml
Labels: approved, lgtm, size/XS

#1314 templates: remove /usr/share/containers/oci/hooks.d from crio config
  templates/master/01-master-container-runtime/_base/files/crio.yaml
  templates/worker/01-worker-container-runtime/_base/files/crio.yaml
Labels: approved, lgtm, size/XS

#1331 Bug 1782893: vendor: bring in ReservedSystemCPUs changes
  go.mod
  go.sum
  vendor/github.com/Microsoft/hcsshim/mksyscall_windows.go
  vendor/github.com/containers/storage/pkg/archive/example_changes.go
  vendor/github.com/creack/pty/types.go
  vendor/github.com/creack/pty/types_dragonfly.go
  vendor/github.com/creack/pty/types_freebsd.go
  vendor/github.com/creack/pty/types_openbsd.go
  vendor/github.com/docker/docker/profiles/seccomp/generate.go
  vendor/github.com/go-toolsmith/astcast/astcast_generate.go
  vendor/github.com/go-toolsmith/typep/simplePredicates_generate.go
  vendor/github.com/klauspost/compress/flate/gen.go
  vendor/github.com/klauspost/cpuid/private-gen.go
  vendor/github.com/ulikunitz/xz/example.go
  vendor/golang.org/x/sys/unix/mkasm_darwin.go
  vendor/golang.org/x/sys/unix/mkpost.go
  vendor/golang.org/x/sys/unix/mksyscall.go
  vendor/golang.org/x/sys/unix/mksyscall_aix_ppc.go
  vendor/golang.org/x/sys/unix/mksyscall_aix_ppc64.go
  vendor/golang.org/x/sys/unix/mksyscall_solaris.go
  vendor/golang.org/x/sys/unix/mksysctl_openbsd.go
  vendor/golang.org/x/sys/unix/mksysnum.go
  vendor/golang.org/x/sys/unix/types_aix.go
  vendor/golang.org/x/sys/unix/types_darwin.go
  vendor/golang.org/x/sys/unix/types_dragonfly.go
  vendor/golang.org/x/sys/unix/types_freebsd.go
  vendor/golang.org/x/sys/unix/types_netbsd.go
  vendor/golang.org/x/sys/unix/types_openbsd.go
  vendor/golang.org/x/sys/unix/types_solaris.go
  vendor/golang.org/x/text/unicode/bidi/gen.go
  vendor/golang.org/x/text/unicode/bidi/gen_ranges.go
  vendor/golang.org/x/text/unicode/bidi/gen_trieval.go
  vendor/golang.org/x/text/unicode/norm/maketables.go
  vendor/golang.org/x/text/unicode/norm/triegen.go
  vendor/golang.org/x/text/width/gen.go
  vendor/golang.org/x/text/width/gen_common.go
  vendor/golang.org/x/text/width/gen_trieval.go
  vendor/golang.org/x/tools/go/gcexportdata/main.go
  vendor/golang.org/x/tools/internal/imports/mkindex.go
  vendor/golang.org/x/tools/internal/imports/mkstdlib.go
  vendor/k8s.io/kubelet/config/v1beta1/types.go
  vendor/k8s.io/kubernetes/pkg/apis/core/types.go
  vendor/k8s.io/kubernetes/pkg/features/kube_features.go
  vendor/k8s.io/kubernetes/pkg/volume/BUILD
  vendor/modules.txt
Labels: approved, bugzilla/valid-bug, lgtm, size/XXL

#1332 Bug 1779348: [release-4.3] vendor: bring in ReservedSystemCPUs changes
  go.mod
  go.sum
  vendor/k8s.io/kubelet/config/v1beta1/types.go
  vendor/k8s.io/kubernetes/pkg/apis/core/types.go
  vendor/k8s.io/kubernetes/pkg/features/kube_features.go
  vendor/k8s.io/kubernetes/pkg/volume/BUILD
  vendor/modules.txt
Labels: approved, bugzilla/valid-bug, lgtm, size/XL

#1317 Bug 1769847: cmd/gcp-routes-controller: shutdown gcp routes on signal
  cmd/gcp-routes-controller/run.go
Labels: approved, bugzilla/valid-bug, lgtm, size/S

#1159 Bug 1777150: pkg/controller: allow kubelet config and runtime changes for custom pools
  pkg/controller/template/render.go
Labels: approved, bugzilla/valid-bug, lgtm, size/S

#1274 Bug 1777204: [Baremetal] verify that 'old' HAProxy processes being deleted after HAProxy reload.
  templates/master/00-master/baremetal/files/baremetal-haproxy.yaml
Labels: approved, bugzilla/valid-bug, lgtm, size/S

#1338 Bug 1779348: vendor: correctly run make go-deps
  go.mod
  go.sum
  vendor/github.com/Microsoft/hcsshim/mksyscall_windows.go
  vendor/github.com/containers/storage/pkg/archive/example_changes.go
  vendor/github.com/creack/pty/types.go
  vendor/github.com/creack/pty/types_dragonfly.go
  vendor/github.com/creack/pty/types_freebsd.go
  vendor/github.com/creack/pty/types_openbsd.go
  vendor/github.com/docker/docker/profiles/seccomp/generate.go
  vendor/github.com/go-toolsmith/astcast/astcast_generate.go
  vendor/github.com/go-toolsmith/typep/simplePredicates_generate.go
  vendor/github.com/klauspost/compress/flate/gen.go
  vendor/github.com/klauspost/cpuid/private-gen.go
  vendor/github.com/ulikunitz/xz/example.go
  vendor/golang.org/x/sys/unix/mkasm_darwin.go
  vendor/golang.org/x/sys/unix/mkpost.go
  vendor/golang.org/x/sys/unix/mksyscall.go
  vendor/golang.org/x/sys/unix/mksyscall_aix_ppc.go
  vendor/golang.org/x/sys/unix/mksyscall_aix_ppc64.go
  vendor/golang.org/x/sys/unix/mksyscall_solaris.go
  vendor/golang.org/x/sys/unix/mksysctl_openbsd.go
  vendor/golang.org/x/sys/unix/mksysnum.go
  vendor/golang.org/x/sys/unix/types_aix.go
  vendor/golang.org/x/sys/unix/types_darwin.go
  vendor/golang.org/x/sys/unix/types_dragonfly.go
  vendor/golang.org/x/sys/unix/types_freebsd.go
  vendor/golang.org/x/sys/unix/types_netbsd.go
  vendor/golang.org/x/sys/unix/types_openbsd.go
  vendor/golang.org/x/sys/unix/types_solaris.go
  vendor/golang.org/x/text/unicode/bidi/gen.go
  vendor/golang.org/x/text/unicode/bidi/gen_ranges.go
  vendor/golang.org/x/text/unicode/bidi/gen_trieval.go
  vendor/golang.org/x/text/unicode/norm/maketables.go
  vendor/golang.org/x/text/unicode/norm/triegen.go
  vendor/golang.org/x/text/width/gen.go
  vendor/golang.org/x/text/width/gen_common.go
  vendor/golang.org/x/text/width/gen_trieval.go
  vendor/golang.org/x/tools/go/gcexportdata/main.go
  vendor/golang.org/x/tools/internal/imports/mkindex.go
  vendor/golang.org/x/tools/internal/imports/mkstdlib.go
Labels: approved, bugzilla/valid-bug, lgtm, size/XXL

#1339 vendor: run make go-deps
  go.sum
Labels: approved, lgtm, size/XS

#1336 DR: save and restore kube apiserver's static pod resources
  templates/master/00-master/_base/files/usr-local-bin-etcd-snapshot-backup-sh.yaml
  templates/master/00-master/_base/files/usr-local-bin-etcd-snapshot-restore-sh.yaml
  templates/master/00-master/_base/files/usr-local-bin-openshift-recovery-tools-sh.yaml
Labels: approved, lgtm, size/M

#1343 Bug 1783448: [release-4.3] DR: save and restore kube apiserver's static pod resources
  templates/master/00-master/_base/files/usr-local-bin-etcd-snapshot-backup-sh.yaml
  templates/master/00-master/_base/files/usr-local-bin-etcd-snapshot-restore-sh.yaml
  templates/master/00-master/_base/files/usr-local-bin-openshift-recovery-tools-sh.yaml
Labels: approved, bugzilla/valid-bug, lgtm, size/M

#1211 etcd: Add initial support for an IPv6 control plane
  cmd/setup-etcd-environment/run.go
  pkg/controller/template/render.go
  templates/common/_base/files/sysctl-forward-conf.yaml
  templates/master/00-master/_base/files/etc-kubernetes-manifests-etcd-member.yaml
Labels: approved, lgtm, size/M

#1298 ovirt: reduce static pods mem/cpu requirements
  manifests/ovirt/coredns.yaml
  manifests/ovirt/keepalived.yaml
  pkg/operator/assets/bindata.go
  templates/common/ovirt/files/ovirt-coredns.yaml
  templates/common/ovirt/files/ovirt-keepalived.yaml
  templates/common/ovirt/files/ovirt-mdns-publisher.yaml
  templates/master/00-master/ovirt/files/ovirt-haproxy.yaml
Labels: approved, lgtm, size/M
