Repository openshift/machine-config-operator, pull requests merged in 2019-04, with the labels that each got.

#592 ContainerRuntimeConfig: Enable "info" debug level
  pkg/controller/container-runtime-config/helpers.go
Labels: approved, lgtm, size/XS

#581 systemd: install systemd.conf to enable CPU Accounting
  pkg/controller/template/test_data/templates/master/00-master/aws/files/-etc-systemd-system.conf.d-kubelet-cgroups.conf
  pkg/controller/template/test_data/templates/master/00-master/libvirt/files/-etc-systemd-system.conf.d-kubelet-cgroups.conf
  pkg/controller/template/test_data/templates/master/00-master/none/files/-etc-systemd-system.conf.d-kubelet-cgroups.conf
  pkg/controller/template/test_data/templates/master/00-master/openstack/files/-etc-systemd-system.conf.d-kubelet-cgroups.conf
  pkg/controller/template/test_data/templates/master/00-master/vpshere/files/-etc-systemd-system.conf.d-kubelet-cgroups.conf
  pkg/controller/template/test_data/templates/master/00-master/vsphere/files/-etc-systemd-system.conf.d-kubelet-cgroups.conf
  pkg/controller/template/test_data/templates/worker/00-worker/aws/files/-etc-systemd-system.conf.d-kubelet-cgroups.conf
  pkg/controller/template/test_data/templates/worker/00-worker/libvirt/files/-etc-systemd-system.conf.d-kubelet-cgroups.conf
  pkg/controller/template/test_data/templates/worker/00-worker/none/files/-etc-systemd-system.conf.d-kubelet-cgroups.conf
  pkg/controller/template/test_data/templates/worker/00-worker/openstack/files/-etc-systemd-system.conf.d-kubelet-cgroups.conf
  pkg/controller/template/test_data/templates/worker/00-worker/vpshere/files/-etc-systemd-system.conf.d-kubelet-cgroups.conf
  pkg/controller/template/test_data/templates/worker/00-worker/vsphere/files/-etc-systemd-system.conf.d-kubelet-cgroups.conf
  templates/master/00-master/_base/files/kubelet-cgroups.yaml
  templates/worker/00-worker/_base/files/kubelet-cgroups.yaml
Labels: approved, lgtm, size/M

#593 BUG 1694169: templates: add debug for etcd-member init
  pkg/controller/template/test_data/templates/master/00-master/aws/files/-etc-kubernetes-manifests-etcd-member.yaml
  pkg/controller/template/test_data/templates/master/00-master/libvirt/files/-etc-kubernetes-manifests-etcd-member.yaml
  pkg/controller/template/test_data/templates/master/00-master/none/files/-etc-kubernetes-manifests-etcd-member.yaml
  pkg/controller/template/test_data/templates/master/00-master/openstack/files/-etc-kubernetes-manifests-etcd-member.yaml
  pkg/controller/template/test_data/templates/master/00-master/vsphere/files/-etc-kubernetes-manifests-etcd-member.yaml
  templates/master/00-master/_base/files/etc-kubernetes-manifests-etcd-member.yaml
Labels: approved, lgtm, size/S

#596 pkg/apis: update generated deepcopy
  pkg/apis/machineconfiguration.openshift.io/v1/zz_generated.deepcopy.go
Labels: approved, lgtm, size/XS

#594 setup-etcd-environment: wait for all etcd members to be resolvable
  cmd/setup-etcd-environment/run.go
Labels: approved, lgtm, size/S

#595 skip test if not linux + hack/Makefile cleanups
  Makefile
  hack/build-go.sh
  hack/update-generated-bindata.sh
  hack/update-vendor.sh
  hack/verify-codegen.sh
  hack/verify-generated-bindata.sh
  hack/verify-style.sh
  hack/yamllint-config.yaml
  pkg/daemon/daemon_test.go
  test/e2e/debuglog
  test/e2e/mcd_test.go
Labels: approved, lgtm, size/L

#598 hack: copy file w/o preserving attributes
  hack/verify-codegen.sh
  hack/verify-generated-bindata.sh
Labels: approved, lgtm, size/XS

#517 BUG 1670700: *: add support for etcd metrics proxy
  pkg/controller/template/test_data/templates/aws/master/files/-etc-kubernetes-static-pod-resources-etcd-member-metric-ca.crt
  pkg/controller/template/test_data/templates/master/00-master/aws/files/-etc-kubernetes-manifests-etcd-member.yaml
  pkg/controller/template/test_data/templates/master/00-master/aws/files/-etc-kubernetes-static-pod-resources-etcd-member-metric-ca.crt
  pkg/controller/template/test_data/templates/master/00-master/libvirt/files/-etc-kubernetes-manifests-etcd-member.yaml
  pkg/controller/template/test_data/templates/master/00-master/libvirt/files/-etc-kubernetes-static-pod-resources-etcd-member-metric-ca.crt
  pkg/controller/template/test_data/templates/master/00-master/none/files/-etc-kubernetes-manifests-etcd-member.yaml
  pkg/controller/template/test_data/templates/master/00-master/none/files/-etc-kubernetes-static-pod-resources-etcd-member-metric-ca.crt
  pkg/controller/template/test_data/templates/master/00-master/openstack/files/-etc-kubernetes-manifests-etcd-member.yaml
  pkg/controller/template/test_data/templates/master/00-master/openstack/files/-etc-kubernetes-static-pod-resources-etcd-member-metric-ca.crt
  pkg/controller/template/test_data/templates/master/00-master/vsphere/files/-etc-kubernetes-manifests-etcd-member.yaml
  pkg/controller/template/test_data/templates/master/00-master/vsphere/files/-etc-kubernetes-static-pod-resources-etcd-member-metric-ca.crt
  pkg/operator/bootstrap.go
  templates/master/00-master/_base/files/etc-kubernetes-manifests-etcd-member.yaml
  templates/master/00-master/_base/files/etcd-metric-ca.yaml
Labels: 4.0, approved, lgtm, size/M

#605 hack: switch diff to show positive diffing
  hack/verify-codegen.sh
  hack/verify-generated-bindata.sh
Labels: approved, lgtm, size/XS

#599 pkg/operator: update LastTransitionTime when flipping conditions
  pkg/operator/status.go
  pkg/operator/status_test.go
Labels: approved, lgtm, size/M

#603 kubelet-config: fix variable shadowing
  pkg/controller/kubelet-config/kubelet_config_controller.go
Labels: approved, lgtm, size/XS

#608 Change the default crio.conf to use the values we want
  pkg/controller/template/test_data/templates/aws/master/files/-etc-sysconfig-crio-network
  pkg/controller/template/test_data/templates/aws/worker/files/-etc-sysconfig-crio-network
  pkg/controller/template/test_data/templates/libvirt/master/files/-etc-sysconfig-crio-network
  pkg/controller/template/test_data/templates/libvirt/worker/files/-etc-sysconfig-crio-network
  pkg/controller/template/test_data/templates/master/00-master/aws/files/-etc-sysconfig-crio-network
  pkg/controller/template/test_data/templates/master/00-master/libvirt/files/-etc-sysconfig-crio-network
  pkg/controller/template/test_data/templates/master/00-master/none/files/-etc-sysconfig-crio-network
  pkg/controller/template/test_data/templates/master/00-master/openstack/files/-etc-sysconfig-crio-network
  pkg/controller/template/test_data/templates/master/00-master/vsphere/files/-etc-sysconfig-crio-network
  pkg/controller/template/test_data/templates/master/01-master-container-runtime/aws/files/-etc-crio-crio.conf
  pkg/controller/template/test_data/templates/master/01-master-container-runtime/libvirt/files/-etc-crio-crio.conf
  pkg/controller/template/test_data/templates/master/01-master-container-runtime/none/files/-etc-crio-crio.conf
  pkg/controller/template/test_data/templates/master/01-master-container-runtime/openstack/files/-etc-crio-crio.conf
  pkg/controller/template/test_data/templates/master/01-master-container-runtime/vsphere/files/-etc-crio-crio.conf
  pkg/controller/template/test_data/templates/openstack/master/files/-etc-sysconfig-crio-network
  pkg/controller/template/test_data/templates/openstack/worker/files/-etc-sysconfig-crio-network
  pkg/controller/template/test_data/templates/worker/00-worker/aws/files/-etc-sysconfig-crio-network
  pkg/controller/template/test_data/templates/worker/00-worker/libvirt/files/-etc-sysconfig-crio-network
  pkg/controller/template/test_data/templates/worker/00-worker/none/files/-etc-sysconfig-crio-network
  pkg/controller/template/test_data/templates/worker/00-worker/openstack/files/-etc-sysconfig-crio-network
  pkg/controller/template/test_data/templates/worker/00-worker/vsphere/files/-etc-sysconfig-crio-network
  pkg/controller/template/test_data/templates/worker/01-worker-container-runtime/aws/files/-etc-crio-crio.conf
  pkg/controller/template/test_data/templates/worker/01-worker-container-runtime/libvirt/files/-etc-crio-crio.conf
  pkg/controller/template/test_data/templates/worker/01-worker-container-runtime/none/files/-etc-crio-crio.conf
  pkg/controller/template/test_data/templates/worker/01-worker-container-runtime/openstack/files/-etc-crio-crio.conf
  pkg/controller/template/test_data/templates/worker/01-worker-container-runtime/vsphere/files/-etc-crio-crio.conf
  templates/master/00-master/_base/files/etc-sysconfig-crio-network.yaml
  templates/master/01-master-container-runtime/_base/files/crio.yaml
  templates/worker/00-worker/_base/files/etc-sysconfig-crio-network.yaml
  templates/worker/01-worker-container-runtime/_base/files/crio.yaml
Labels: approved, lgtm, size/L

#609 Bug 1697644: operator: use openshift-config/pull-secret to fetch the pull secret for images.
  pkg/operator/operator.go
Labels: approved, lgtm, size/XS

#616 pkg/operator: fix bootstrap logging
  pkg/operator/bootstrap.go
Labels: approved, lgtm, size/S

#617 kubeletconfig: Fix error propogation of status message
  pkg/controller/kubelet-config/kubelet_config_controller.go
Labels: approved, lgtm, size/XS

#604 templates: Add a tmpfiles.d entry to delete CNI files at boot
  pkg/controller/template/test_data/templates/master/00-master/aws/files/-etc-tmpfiles.d-cleanup-cni.conf
  pkg/controller/template/test_data/templates/master/00-master/libvirt/files/-etc-tmpfiles.d-cleanup-cni.conf
  pkg/controller/template/test_data/templates/master/00-master/none/files/-etc-tmpfiles.d-cleanup-cni.conf
  pkg/controller/template/test_data/templates/master/00-master/openstack/files/-etc-tmpfiles.d-cleanup-cni.conf
  pkg/controller/template/test_data/templates/master/00-master/vsphere/files/-etc-tmpfiles.d-cleanup-cni.conf
  pkg/controller/template/test_data/templates/worker/00-worker/aws/files/-etc-tmpfiles.d-cleanup-cni.conf
  pkg/controller/template/test_data/templates/worker/00-worker/libvirt/files/-etc-tmpfiles.d-cleanup-cni.conf
  pkg/controller/template/test_data/templates/worker/00-worker/none/files/-etc-tmpfiles.d-cleanup-cni.conf
  pkg/controller/template/test_data/templates/worker/00-worker/openstack/files/-etc-tmpfiles.d-cleanup-cni.conf
  pkg/controller/template/test_data/templates/worker/00-worker/vsphere/files/-etc-tmpfiles.d-cleanup-cni.conf
  templates/master/00-master/_base/files/cleanup-cni-conf.yaml
  templates/worker/00-worker/_base/files/cleanup-cni-conf.yaml
Labels: approved, lgtm, size/M

#526 templates/master: fix typo in etcd-member yaml
  pkg/controller/template/test_data/templates/master/00-master/aws/files/-etc-kubernetes-manifests-etcd-member.yaml
  pkg/controller/template/test_data/templates/master/00-master/libvirt/files/-etc-kubernetes-manifests-etcd-member.yaml
  pkg/controller/template/test_data/templates/master/00-master/none/files/-etc-kubernetes-manifests-etcd-member.yaml
  pkg/controller/template/test_data/templates/master/00-master/openstack/files/-etc-kubernetes-manifests-etcd-member.yaml
  pkg/controller/template/test_data/templates/master/00-master/vsphere/files/-etc-kubernetes-manifests-etcd-member.yaml
  templates/master/00-master/_base/files/etc-kubernetes-manifests-etcd-member.yaml
Labels: approved, lgtm, size/S

#620 make featuregate missing consistent with default
  pkg/controller/kubelet-config/kubelet_config_features.go
Labels: approved, lgtm, size/S

#602 Add support for Azure platform
  pkg/controller/template/render.go
  pkg/operator/render.go
Labels: approved, lgtm, ok-to-test, size/XS

#624 Add more info to the container runtime config doc
  docs/ContainerRuntimeConfigDesign.md
Labels: approved, lgtm, size/S

#622 pkg/operator: clarify pool status
  pkg/operator/status.go
Labels: approved, lgtm, size/XS

#625 Bug 1698250: * : pt1 transition from MachineSelector to NodeSelector labels
  docs/MachineConfigController.md
  examples/etcd.machineconfigpool.yaml
  examples/master.machineconfigpool.yaml
  examples/worker.machineconfigpool.yaml
  lib/resourcemerge/machineconfig.go
  manifests/master.machineconfigpool.yaml
  manifests/worker.machineconfigpool.yaml
  pkg/apis/machineconfiguration.openshift.io/v1/types.go
  pkg/apis/machineconfiguration.openshift.io/v1/zz_generated.deepcopy.go
  pkg/controller/node/node_controller.go
  pkg/controller/node/node_controller_test.go
  pkg/controller/node/status.go
  pkg/operator/assets/bindata.go
  pkg/server/testdata/machine-pools/test-pool.yaml
Labels: approved, lgtm, size/M

#631 pkg/apis: avoid a double call in getting the cc
  pkg/apis/machineconfiguration.openshift.io/v1/helpers.go
  pkg/apis/machineconfiguration.openshift.io/v1/helpers_test.go
  pkg/controller/render/render_controller.go
  pkg/operator/sync.go
Labels: approved, lgtm, size/S

#607 pkg/operator: wait for cache on mcp/cc/mcp
  cmd/machine-config-operator/start.go
  pkg/operator/operator.go
Labels: approved, lgtm, size/M

#634 featuregates: remove ownerref reference on managed feature gates
  pkg/controller/kubelet-config/helpers.go
  pkg/controller/kubelet-config/kubelet_config_controller.go
  pkg/controller/kubelet-config/kubelet_config_controller_test.go
  pkg/controller/kubelet-config/kubelet_config_features.go
  pkg/controller/kubelet-config/kubelet_config_features_test.go
Labels: approved, lgtm, size/M

#635 pkg/daemon: allow skip reboot in onceFrom MCD
  cmd/machine-config-daemon/start.go
  pkg/daemon/daemon.go
  pkg/daemon/daemon_test.go
  pkg/daemon/update.go
  pkg/daemon/update_test.go
Labels: approved, lgtm, size/M

#636 Small fixes to docs and gitignore
  .gitignore
  docs/HACKING.md
Labels: approved, lgtm, size/S

#639 Bug 1698250: *: pt2 NodeSelector transition : remove all MachineSelector refs
  lib/resourcemerge/machineconfig.go
  pkg/apis/machineconfiguration.openshift.io/v1/types.go
  pkg/apis/machineconfiguration.openshift.io/v1/zz_generated.deepcopy.go
  pkg/controller/node/node_controller.go
  pkg/controller/node/node_controller_test.go
  pkg/controller/node/status.go
Labels: approved, lgtm, size/M

#640 render_controller: render on template MCs changes
  pkg/controller/render/render_controller.go
  pkg/controller/render/render_controller_test.go
Labels: approved, lgtm, size/M

#632 Bug 1686117: pkg/controller: re-sync on pull secret change
  cmd/machine-config-controller/start.go
  docs/HACKING.md
  docs/PullSecret.md
  pkg/controller/common/controller_context.go
  pkg/controller/kubelet-config/kubelet_config_features.go
  pkg/controller/template/template_controller.go
  pkg/controller/template/template_controller_test.go
Labels: approved, lgtm, size/L

#642 MCC: drop memory limit
  manifests/machineconfigcontroller/deployment.yaml
  pkg/operator/assets/bindata.go
Labels: approved, lgtm, size/XS

#643 update etcd servicing-ca location for api freeze
  pkg/operator/operator.go
Labels: approved, lgtm, size/XS

#612 pkg/daemon: add a current config on disk check
  pkg/daemon/daemon.go
Labels: approved, lgtm, size/M

#626 try to make MCD render more self-contained
  cmd/machine-config-operator/bootstrap.go
  manifests/machineconfigserver/kube-apiserver-serving-ca-configmap.yaml
  pkg/operator/assets/bindata.go
  pkg/operator/bootstrap.go
  pkg/operator/operator.go
  pkg/operator/render.go
Labels: approved, lgtm, size/M

#646 mco/templates: add azure template folder
  templates/master/00-master/azure/.gitkeep
  templates/master/01-master-container-runtime/azure/.gitkeep
  templates/master/01-master-kubelet/azure/.gitkeep
  templates/worker/00-worker/azure/.gitkeep
  templates/worker/01-worker-container-runtime/azure/.gitkeep
  templates/worker/01-worker-kubelet/azure/.gitkeep
Labels: approved, lgtm, size/XS

#649 start informers and wait for cache sync on informers
  cmd/machine-config-controller/start.go
  cmd/machine-config-operator/start.go
  pkg/controller/container-runtime-config/container_runtime_config_controller.go
  pkg/controller/kubelet-config/kubelet_config_controller.go
  pkg/controller/node/node_controller.go
  pkg/controller/render/render_controller.go
  pkg/controller/template/template_controller.go
  pkg/operator/operator.go
Labels: approved, kind/bug, lgtm, size/L

#645 pkg/daemon: add MCD skeleton tests and test prepUpdateFromCluster
  cmd/machine-config-daemon/start.go
  pkg/daemon/daemon.go
  pkg/daemon/daemon_test.go
Labels: approved, lgtm, size/L

#652 add permissions to the cluster-reader role
  install/0000_30_machine-config-operator-00_clusterreader_clusterrole.yaml
Labels: approved, lgtm, size/S

#655 etcd-member: exec the etcd binaries
  pkg/controller/template/test_data/templates/master/00-master/aws/files/-etc-kubernetes-manifests-etcd-member.yaml
  pkg/controller/template/test_data/templates/master/00-master/libvirt/files/-etc-kubernetes-manifests-etcd-member.yaml
  pkg/controller/template/test_data/templates/master/00-master/none/files/-etc-kubernetes-manifests-etcd-member.yaml
  pkg/controller/template/test_data/templates/master/00-master/openstack/files/-etc-kubernetes-manifests-etcd-member.yaml
  pkg/controller/template/test_data/templates/master/00-master/vsphere/files/-etc-kubernetes-manifests-etcd-member.yaml
  templates/master/00-master/_base/files/etc-kubernetes-manifests-etcd-member.yaml
Labels: approved, lgtm, size/S

#654 Change the ClusterStatusConditionType "Failing" to "Degraded"
  Gopkg.lock
  pkg/operator/status.go
  pkg/operator/status_test.go
  pkg/operator/sync.go
  vendor/github.com/openshift/api/config/v1/types_cluster_operator.go
  vendor/github.com/openshift/api/config/v1/types_cluster_version.go
  vendor/github.com/openshift/api/config/v1/types_feature.go
  vendor/github.com/openshift/api/config/v1/types_scheduling.go
  vendor/github.com/openshift/api/config/v1/zz_generated.swagger_doc_generated.go
Labels: approved, lgtm, size/L

#656 pkg/daemon: abstract NodeWriter to an interface
  pkg/daemon/daemon.go
  pkg/daemon/daemon_test.go
  pkg/daemon/fake_writer.go
  pkg/daemon/writer.go
Labels: approved, lgtm, size/M

#648 move etcd to openshift-etcd
  pkg/controller/template/render.go
  pkg/controller/template/render_test.go
  pkg/controller/template/test_data/templates/aws/master/files/-etc-kubernetes-manifests-etcd-member.yaml
  pkg/controller/template/test_data/templates/libvirt/master/files/-etc-kubernetes-manifests-etcd-member.yaml
  pkg/controller/template/test_data/templates/master/00-master/aws/files/-etc-kubernetes-manifests-etcd-member.yaml
  pkg/controller/template/test_data/templates/master/00-master/libvirt/files/-etc-kubernetes-manifests-etcd-member.yaml
  pkg/controller/template/test_data/templates/master/00-master/none/files/-etc-kubernetes-manifests-etcd-member.yaml
  pkg/controller/template/test_data/templates/master/00-master/openstack/files/-etc-kubernetes-manifests-etcd-member.yaml
  pkg/controller/template/test_data/templates/master/00-master/vsphere/files/-etc-kubernetes-manifests-etcd-member.yaml
  pkg/controller/template/test_data/templates/openstack/master/files/-etc-kubernetes-manifests-etcd-member.yaml
  templates/master/00-master/_base/files/etc-kubernetes-manifests-etcd-member.yaml
Labels: approved, lgtm, size/S

#597 Bug 1699134: pkg/daemon: add reason annotation key for degraded/unreconcilable and bubble up errors from render controller
  manifests/machineconfigpool.crd.yaml
  pkg/apis/machineconfiguration.openshift.io/v1/types.go
  pkg/controller/container-runtime-config/container_runtime_config_controller.go
  pkg/controller/kubelet-config/kubelet_config_controller.go
  pkg/controller/node/status.go
  pkg/controller/render/render_controller.go
  pkg/controller/render/render_controller_test.go
  pkg/daemon/constants/constants.go
  pkg/daemon/daemon.go
  pkg/daemon/writer.go
  pkg/operator/assets/bindata.go
  pkg/operator/operator.go
  pkg/operator/status.go
  pkg/operator/sync.go
  test/e2e/mcd_test.go
Labels: approved, lgtm, size/L

#658 pkg/daemon: add log about initial node annotation
  pkg/daemon/node.go
Labels: approved, lgtm, size/XS

#659 pkg/operator: fire an event when we change version
  pkg/operator/status.go
  pkg/operator/status_test.go
Labels: approved, lgtm, size/M

#663 Bug 1702832: pkg/operator: poll during master MCP sync
  pkg/operator/status.go
  pkg/operator/sync.go
Labels: approved, lgtm, size/M

#666 operator/bootstrap: fix the decoding scheme for cloud conf configmap
  pkg/operator/bootstrap.go
Labels: approved, lgtm, size/XS

#668 pkg/daemon: add more events and logging
  pkg/daemon/daemon.go
  pkg/daemon/update.go
Labels: approved, lgtm, size/XS

#667 Add node-selector annotation to namespace
  install/0000_30_machine-config-operator_00_namespace.yaml
Labels: approved, lgtm, size/XS

#671 Add etcd-quorum-guard to the machine config operator
  docs/etcd-quorum-guard.md
  install/0000_30_machine-config-operator_07_etcdquorumguard_deployment.yaml
  install/0000_30_machine-config-operator_08_etcdquorumguard_pdb.yaml
  install/image-references
Labels: approved, lgtm, size/L

#672 controller/template: put the cloudconf for kubelet behind platform gate
  pkg/controller/template/render.go
  pkg/controller/template/render_test.go
  pkg/controller/template/test_data/templates/master/01-master-kubelet/vsphere/units/kubelet.service
  pkg/controller/template/test_data/templates/worker/01-worker-kubelet/vsphere/units/kubelet.service
Labels: approved, lgtm, size/M

#677 Remove reference to etcd-quorum-guard image, and use cli instead
  install/0000_30_machine-config-operator_07_etcdquorumguard_deployment.yaml
  install/image-references
Labels: approved, lgtm, size/XS

#678 setup-etcd-environment: add hexfusion to reviewers
  cmd/setup-etcd-environment/OWNERS
Labels: approved, lgtm, size/XS

#674 Move component to an appropriate upgrade order (machine operators)
  install/0000_80_machine-config-operator_00_clusterreader_clusterrole.yaml
  install/0000_80_machine-config-operator_00_namespace.yaml
  install/0000_80_machine-config-operator_01_mcoconfig.crd.yaml
  install/0000_80_machine-config-operator_02_images.configmap.yaml
  install/0000_80_machine-config-operator_03_rbac.yaml
  install/0000_80_machine-config-operator_04_deployment.yaml
  install/0000_80_machine-config-operator_05_osimageurl.yaml
  install/0000_80_machine-config-operator_06_clusteroperator.yaml
  install/0000_80_machine-config-operator_07_etcdquorumguard_deployment.yaml
  install/0000_80_machine-config-operator_08_etcdquorumguard_pdb.yaml
Labels: approved, lgtm, size/XS

#670 pkg/daemon: roll back pending config on error
  pkg/controller/node/status.go
  pkg/daemon/daemon.go
  pkg/daemon/update.go
Labels: approved, kind/bug, lgtm, size/M

#673 Add etcd-quota-guard e2e and remove debugging code
  Makefile
  install/0000_80_machine-config-operator_07_etcdquorumguard_deployment.yaml
  test/e2e/etcdquorumguard_test.go
Labels: approved, lgtm, size/L

#676 Bug 1698456 *: use wildcard domain in DNS: SAN for etcd server certs
  cmd/setup-etcd-environment/run.go
  pkg/controller/template/render.go
  pkg/controller/template/render_test.go
  pkg/controller/template/test_data/templates/master/00-master/aws/files/-etc-kubernetes-manifests-etcd-member.yaml
  pkg/controller/template/test_data/templates/master/00-master/libvirt/files/-etc-kubernetes-manifests-etcd-member.yaml
  pkg/controller/template/test_data/templates/master/00-master/none/files/-etc-kubernetes-manifests-etcd-member.yaml
  pkg/controller/template/test_data/templates/master/00-master/openstack/files/-etc-kubernetes-manifests-etcd-member.yaml
  pkg/controller/template/test_data/templates/master/00-master/vsphere/files/-etc-kubernetes-manifests-etcd-member.yaml
Labels: approved, lgtm, size/S

#680 mcd: Allow enabling units even if no content was provided
  pkg/daemon/update.go
Labels: approved, kind/bug, lgtm, size/S

#684 docs: Link to OSUpgrades.md more, other various tweaks
  docs/MachineConfiguration.md
  docs/README.md
Labels: approved, lgtm, size/M

#686 gitattrs: flag updated template testdata as generated files
  .gitattributes
Labels: approved, lgtm, size/XS

#644 featuregates: Add default featuregates and comparison check
  pkg/controller/kubelet-config/kubelet_config_features.go
  pkg/controller/kubelet-config/kubelet_config_features_test.go
  pkg/controller/template/test_data/templates/master/01-master-kubelet/aws/files/-etc-kubernetes-kubelet.conf
  pkg/controller/template/test_data/templates/master/01-master-kubelet/libvirt/files/-etc-kubernetes-kubelet.conf
  pkg/controller/template/test_data/templates/master/01-master-kubelet/none/files/-etc-kubernetes-kubelet.conf
  pkg/controller/template/test_data/templates/master/01-master-kubelet/openstack/files/-etc-kubernetes-kubelet.conf
  pkg/controller/template/test_data/templates/master/01-master-kubelet/vsphere/files/-etc-kubernetes-kubelet.conf
  pkg/controller/template/test_data/templates/worker/01-worker-kubelet/aws/files/-etc-kubernetes-kubelet.conf
  pkg/controller/template/test_data/templates/worker/01-worker-kubelet/libvirt/files/-etc-kubernetes-kubelet.conf
  pkg/controller/template/test_data/templates/worker/01-worker-kubelet/none/files/-etc-kubernetes-kubelet.conf
  pkg/controller/template/test_data/templates/worker/01-worker-kubelet/openstack/files/-etc-kubernetes-kubelet.conf
  pkg/controller/template/test_data/templates/worker/01-worker-kubelet/vsphere/files/-etc-kubernetes-kubelet.conf
  templates/master/01-master-kubelet/_base/files/kubelet.yaml
  templates/worker/01-worker-kubelet/_base/files/kubelet.yaml
Labels: approved, lgtm, size/M
