Repository openshift/machine-config-operator, pull requests merged in 2019-07, with the labels that each got.

#892 [release-4.1] Bug 1723327: sync deployment before controllerconfig, roll out MCDs before MCC and remove pivot's reboot-needed file
  pkg/daemon/daemon.go
  pkg/daemon/rpm-ostree.go
  pkg/operator/operator.go
  pkg/operator/sync.go
Labels: approved, bugzilla/valid-bug, cherry-pick-approved, lgtm, size/M

#910 Bug 1726296: pkg/operator: handle missing proxy object
  pkg/operator/operator.go
  pkg/operator/render.go
Labels: approved, bugzilla/valid-bug, lgtm, size/S

#912 templates: only add proxy to crio, kubelet and machine-config-daemon-host
  templates/common/_base/files/etc-profile.d-proxy.sh.yaml
  templates/common/_base/files/etc-systemd-system-crio.service.d-10-default-env.conf.yaml
  templates/common/_base/files/etc-systemd-system-kubelet.service.d-10-default-env.conf.yaml
  templates/common/_base/files/etc-systemd-system-machine-config-daemon-host.service.d-10-default-env.conf.yaml
Labels: approved, lgtm, size/M

#913 pkg/operator: actually do not set proxy if empty...
  pkg/operator/render.go
Labels: approved, lgtm, size/XS

#898 API Updates
  docs/KubeletConfigDesign.md
  docs/MachineConfigController.md
  pkg/apis/apis.go
  pkg/apis/machineconfiguration.openshift.io/install.go
  pkg/apis/machineconfiguration.openshift.io/install_test.go
  pkg/apis/machineconfiguration.openshift.io/v1/register.go
  pkg/apis/machineconfiguration.openshift.io/v1/types.go
  pkg/apis/machineconfiguration.openshift.io/v1/zz_generated.deepcopy.go
  pkg/controller/kubelet-config/helpers.go
  pkg/controller/kubelet-config/kubelet_config_controller.go
  pkg/controller/kubelet-config/kubelet_config_controller_test.go
  pkg/controller/kubelet-config/kubelet_config_features.go
Labels: approved, do-not-merge/hold, lgtm, size/L

#919 CI: Add gosec to make verify
  .golangci.yml
  Makefile
Labels: approved, lgtm, size/XS

#918 golangci: Enable dupl check
  .golangci.yml
  pkg/operator/sync.go
Labels: approved, lgtm, size/XS

#899 templates/mco: update template to replace setupetcdenv image with MCO image
  pkg/operator/bootstrap.go
  pkg/operator/operator.go
  templates/master/00-master/_base/files/etc-kubernetes-manifests-etcd-member.yaml
Labels: approved, lgtm, size/XS

#924 test/e2e: More use of assert/require
  test/e2e/mcd_test.go
Labels: approved, lgtm, size/L

#925 test/e2e: add more logs to FIPS tests
  test/e2e/mcd_test.go
Labels: approved, lgtm, size/XS

#923 controller/kubelet-config: Change validation of KubeletConfiguration to compare type-cast fields instead of reflections.
  pkg/controller/kubelet-config/helpers.go
  pkg/controller/kubelet-config/kubelet_config_controller.go
Labels: approved, lgtm, size/M

#911 pkg/operator: bubble up errors during MCO initial sync
  pkg/operator/operator.go
  pkg/operator/status.go
  pkg/operator/status_test.go
  pkg/operator/sync.go
Labels: approved, lgtm, size/L

#929 *: use updated go-bindata repo
  pkg/operator/assets/bindata.go
Labels: approved, lgtm, size/L

#931 docs: clarify KubeletConfig and ContainerRuntimeConfig CR
  docs/ContainerRuntimeConfigDesign.md
  docs/KubeletConfigDesign.md
Labels: approved, lgtm, size/M

#932 OWNERS: drop jlebon
  OWNERS
Labels: approved, lgtm, size/XS

#920 pkg/operator: clarify MCO images and use better names
  cmd/machine-config-operator/bootstrap.go
  pkg/apis/machineconfiguration.openshift.io/v1/types.go
  pkg/controller/template/constants.go
  pkg/operator/bootstrap.go
  pkg/operator/images.go
  pkg/operator/operator.go
  pkg/operator/render.go
  pkg/operator/render_test.go
  pkg/operator/sync.go
  templates/master/00-master/_base/files/etc-kubernetes-manifests-etcd-member.yaml
  templates/master/01-master-container-runtime/_base/files/crio.yaml
  templates/worker/01-worker-container-runtime/_base/files/crio.yaml
Labels: approved, lgtm, size/M

#933 test/e2e: correctly check MCP status condition
  pkg/operator/operator.go
  pkg/operator/sync.go
  test/e2e/mcd_test.go
Labels: approved, lgtm, size/L

#927 CamelCase -> PascalCase
  examples/controllerconfig.crd.yaml
  examples/machineconfig.crd.yaml
  examples/machineconfigpool.crd.yaml
  install/0000_80_machine-config-operator_01_mcoconfig.crd.yaml
  manifests/controllerconfig.crd.yaml
  manifests/machineconfig.crd.yaml
  manifests/machineconfigpool.crd.yaml
  pkg/apis/machineconfiguration.openshift.io/v1/types.go
  pkg/operator/assets/bindata.go
Labels: approved, lgtm, size/S

#921 Two cleanup patches to tests/node
  pkg/controller/node/node_controller_test.go
Labels: approved, lgtm, size/L

#939 docs/hacking.md: fix osupgrades link
  docs/HACKING.md
Labels: approved, lgtm, size/XS

#794 Bug 1723928: Add script to generate bootstrap recovery kubeconfig
  pkg/controller/template/test_data/templates/master/00-master/aws/files/-usr-local-bin-recover-kubeconfig.sh
  pkg/controller/template/test_data/templates/master/00-master/libvirt/files/-usr-local-bin-recover-kubeconfig.sh
  pkg/controller/template/test_data/templates/master/00-master/none/files/-usr-local-bin-recover-kubeconfig.sh
  pkg/controller/template/test_data/templates/master/00-master/openstack/files/-usr-local-bin-recover-kubeconfig.sh
  pkg/controller/template/test_data/templates/master/00-master/vsphere/files/-usr-local-bin-recover-kubeconfig.sh
  templates/master/00-master/_base/files/usr-local-bin-openshift-kubeconfig-gen.yaml
Labels: approved, bugzilla/valid-bug, cherry-pick-approved, lgtm, size/S

#938 daemon: restrict journal queries
  pkg/daemon/daemon.go
  pkg/daemon/update.go
Labels: approved, lgtm, size/XS

#916 pkg/controller: Handle errors for cascadeDelete
  pkg/controller/container-runtime-config/container_runtime_config_controller.go
  pkg/controller/kubelet-config/kubelet_config_controller.go
Labels: approved, lgtm, size/S

#941 fold mco images/ ratchet: add new master Dockerfiles with finalized names
  Dockerfile
  Dockerfile.rhel7
Labels: approved, lgtm, size/M

#814 pkg/operator: Remove infra platform string constants
  pkg/operator/render.go
  pkg/operator/render_test.go
Labels: approved, lgtm, size/L

#922 two small MCD patches
  pkg/daemon/daemon.go
  pkg/daemon/update.go
Labels: approved, lgtm, size/S

#942 pkg/controller: Fix up node status.go docs
  pkg/controller/node/status.go
Labels: approved, lgtm, size/S

#950 dev: update push-image.sh to use new single mco image
  hack/push-image.sh
Labels: approved, lgtm, size/M

#948 dev: It's just `make image` now
  Makefile
  hack/build-image.sh
Labels: approved, lgtm, size/M

#947 build: Symlink rather than copy Dockerfiles for operator
  Dockerfile.machine-config-operator
  Dockerfile.machine-config-operator.rhel7
Labels: approved, lgtm, size/M

#957 Updated bin data
  pkg/operator/assets/bindata.go
Labels: approved, lgtm, size/XS

#958 docs: update hacking.md to reflect new commands
  docs/HACKING.md
Labels: approved, lgtm, size/M

#928 manifests/machineconfig.crd: set a minimal openAPIV3Schema
  manifests/machineconfig.crd.yaml
  pkg/operator/assets/bindata.go
Labels: approved, lgtm, size/L

#953 README: fix charset value in example MC
  docs/README.md
Labels: approved, lgtm, size/XS

#895 * : remove refs to component images & dockerfiles
  Dockerfile.machine-config-controller
  Dockerfile.machine-config-daemon
  Dockerfile.machine-config-operator
  Dockerfile.machine-config-server
  Dockerfile.setup-etcd-environment
  cmd/machine-config-operator/bootstrap.go
  install/0000_80_machine-config-operator_02_images.configmap.yaml
  pkg/operator/images.go
Labels: approved, lgtm, size/M

#960 cmd/setup-etcd-environment: add support for exporting env
  cmd/setup-etcd-environment/run.go
  templates/master/00-master/_base/files/etc-kubernetes-manifests-etcd-member.yaml
Labels: approved, lgtm, size/S

#966 pkg/operator: status.go docs
  pkg/operator/status.go
Labels: approved, lgtm, size/S

#967 controller/template: update the cloud provider value for GCP to gce
  pkg/controller/template/render.go
  pkg/controller/template/render_test.go
Labels: approved, lgtm, size/XS

#963 pkg/controller: skip image config MCs sync for custom defined pools
  manifests/master.machineconfigpool.yaml
  manifests/worker.machineconfigpool.yaml
  pkg/controller/container-runtime-config/container_runtime_config_controller.go
  pkg/operator/assets/bindata.go
  test/helpers/helpers.go
Labels: approved, lgtm, size/S

#968 pkg/daemon: log during drain
  pkg/daemon/update.go
Labels: approved, lgtm, size/S

#969 templates: fix proxy envvars set in drop-in files
  templates/common/_base/files/etc-systemd-system-crio.service.d-10-default-env.conf.yaml
  templates/common/_base/files/etc-systemd-system-kubelet.service.d-10-default-env.conf.yaml
  templates/common/_base/files/etc-systemd-system-machine-config-daemon-host.service.d-10-default-env.conf.yaml
Labels: approved, lgtm, size/M

#970 hack/cluster-push: Fix for single image
  hack/cluster-push.sh
Labels: approved, lgtm, size/XS

#977 Stop parsing our own version as semver
  cmd/machine-config-controller/bootstrap.go
  cmd/machine-config-controller/start.go
  cmd/machine-config-controller/version.go
  cmd/machine-config-daemon/start.go
  cmd/machine-config-daemon/version.go
  cmd/machine-config-operator/bootstrap.go
  cmd/machine-config-operator/start.go
  cmd/machine-config-operator/version.go
  cmd/machine-config-server/bootstrap.go
  cmd/machine-config-server/start.go
  cmd/machine-config-server/version.go
  cmd/setup-etcd-environment/run.go
  cmd/setup-etcd-environment/version.go
  pkg/controller/template/status.go
  pkg/controller/template/template_controller_test.go
  pkg/version/version.go
Labels: approved, lgtm, size/M

#972 pkg/controller: clarify platform none constant in template/render.go
  pkg/controller/template/render.go
Labels: approved, lgtm, size/XS

#971 Validate nil values in scheduler spec
  pkg/controller/node/node_controller.go
Labels: approved, lgtm, size/XS

#894 daemon/controller: handle empty ignition configs
  pkg/controller/common/helpers.go
  pkg/controller/common/helpers_test.go
  pkg/controller/render/render_controller.go
  pkg/controller/render/render_controller_test.go
  pkg/daemon/update.go
  test/e2e/mcd_test.go
  test/helpers/helpers.go
Labels: approved, lgtm, size/L

#983 openstack: baremetal: Add static pod image flags to bootstrap.go
  cmd/machine-config-operator/bootstrap.go
Labels: approved, lgtm, size/M

#959 remove component mcc/mcd/mco/mcs/setupetcdenv rhel7 dockerfiles
  Dockerfile.machine-config-controller.rhel7
  Dockerfile.machine-config-daemon.rhel7
  Dockerfile.machine-config-operator.rhel7
  Dockerfile.machine-config-server.rhel7
  Dockerfile.setup-etcd-environment.rhel7
Labels: approved, lgtm, size/M

#978 vendor: update github.com/openshift/api
  Gopkg.lock
  vendor/github.com/blang/semver/LICENSE
  vendor/github.com/blang/semver/json.go
  vendor/github.com/blang/semver/range.go
  vendor/github.com/blang/semver/semver.go
  vendor/github.com/blang/semver/sort.go
  vendor/github.com/blang/semver/sql.go
  vendor/github.com/openshift/api/config/v1/types_infrastructure.go
  vendor/github.com/openshift/api/config/v1/types_project.go
  vendor/github.com/openshift/api/config/v1/types_proxy.go
  vendor/github.com/openshift/api/config/v1/zz_generated.deepcopy.go
  vendor/github.com/openshift/api/config/v1/zz_generated.swagger_doc_generated.go
  vendor/github.com/openshift/api/operator/v1/types_network.go
  vendor/github.com/openshift/api/operator/v1/zz_generated.deepcopy.go
  vendor/github.com/openshift/api/operator/v1/zz_generated.swagger_doc_generated.go
Labels: approved, lgtm, size/XXL

#982 local dev/hacking improvements
  Makefile
  docs/HACKING.md
  hack/build-image
  hack/build-image.sh
  hack/cluster-push.sh
Labels: approved, lgtm, size/L

#990 pkg/operator: bubble up errors from pools
  pkg/operator/status.go
Labels: approved, lgtm, size/XS

#991 Tighten scheduler permissions in mco clusterrole
  manifests/machineconfigcontroller/clusterrole.yaml
  pkg/operator/assets/bindata.go
Labels: approved, lgtm, size/S

#992 pkg/operator: log when proxy isn't going to be set
  pkg/operator/render.go
Labels: approved, lgtm, size/XS

#984 Update for openshift/api changes to ImageContentSourcePolicy
  Gopkg.lock
  pkg/controller/container-runtime-config/container_runtime_config_controller_test.go
  pkg/controller/container-runtime-config/helpers.go
  pkg/controller/container-runtime-config/helpers_test.go
  pkg/controller/container-runtime-config/union.go
  pkg/controller/container-runtime-config/union_test.go
  vendor/github.com/openshift/api/operator/v1/types_network.go
  vendor/github.com/openshift/api/operator/v1/zz_generated.deepcopy.go
  vendor/github.com/openshift/api/operator/v1/zz_generated.swagger_doc_generated.go
  vendor/github.com/openshift/api/operator/v1alpha1/types_image_content_source_policy.go
  vendor/github.com/openshift/api/operator/v1alpha1/zz_generated.deepcopy.go
  vendor/github.com/openshift/api/operator/v1alpha1/zz_generated.swagger_doc_generated.go
Labels: approved, lgtm, size/XL

#980 Bug 1730562: templates: add proxy to pivot.service
  templates/common/_base/files/etc-systemd-system-pivot.service.d-10-default-env.conf.yaml
Labels: approved, bugzilla/valid-bug, lgtm, size/S

#961 Makefile: pin tools to specific versions
  Makefile
  hack/install-go-bindata.sh
Labels: approved, lgtm, size/S

#986 *: remove Dockerfile.machine-config-daemon.upstream
  Dockerfile.machine-config-daemon.upstream
Labels: approved, lgtm, size/S

#994 hack: Fix build-image script for first time MCO builds
  hack/build-image
Labels: approved, lgtm, size/S

#952 pkg/daemon: reconcile being killed by kube on drain+reboot
  pkg/daemon/daemon.go
  pkg/daemon/update.go
Labels: approved, lgtm, size/M

#987 Add baremetal and openstack additional images to image-references
  install/image-references
Labels: approved, lgtm, size/S

#965 Bug 1721586: mco: add kubelet CA rotation support
  Gopkg.lock
  cmd/machine-config-operator/start.go
  lib/resourcemerge/machineconfig.go
  pkg/apis/machineconfiguration.openshift.io/v1/types.go
  pkg/apis/machineconfiguration.openshift.io/v1/zz_generated.deepcopy.go
  pkg/controller/common/controller_context.go
  pkg/operator/bootstrap.go
  pkg/operator/operator.go
  pkg/operator/sync.go
  templates/common/_base/files/kubelet-ca.yaml
  templates/master/01-master-kubelet/_base/files/kubelet.yaml
  templates/worker/01-worker-kubelet/_base/files/kubelet.yaml
Labels: approved, bugzilla/valid-bug, lgtm, size/L

#943 Make the infra object available for template rendering
  pkg/apis/machineconfiguration.openshift.io/v1/types.go
  pkg/apis/machineconfiguration.openshift.io/v1/zz_generated.deepcopy.go
  pkg/operator/render.go
Labels: approved, lgtm, ok-to-test, size/S

#1004 Mcd encap prep cleanups 1
  pkg/daemon/daemon.go
  pkg/daemon/update.go
  pkg/daemon/update_test.go
Labels: approved, lgtm, size/M

#1003 Remove the unwanted backslash newline escape chars
  pkg/server/testdata/machine-configs/test-config.yaml
  templates/master/01-master-kubelet/_base/units/kubelet.yaml
  templates/master/01-master-kubelet/baremetal/units/kubelet.yaml
  templates/worker/01-worker-kubelet/_base/units/kubelet.yaml
Labels: approved, lgtm, ok-to-test, size/XS

#1008 docs: Note restrictions/bugs in kargs
  docs/MachineConfiguration.md
Labels: approved, lgtm, size/XS

#1006 docs/HACKING: correct link to OSUpgrades.md
  docs/HACKING.md
Labels: approved, lgtm, size/XS

#1009 pkg/operator: Change proxy logging verbosity
  pkg/operator/render.go
Labels: approved, lgtm, size/XS

#964 OpenStack: set correct hostnames for masters and workers
  templates/common/openstack/units/afterburn-hostname.yaml
Labels: approved, lgtm, size/S

#1007 test/e2e: add custom pool test
  test/e2e/mcd_test.go
Labels: approved, lgtm, size/M

#661 Enable cloud provider for OpenStack
  pkg/controller/template/render.go
  pkg/controller/template/render_test.go
Labels: 4.2, approved, lgtm, size/S

#1016 pkg/operator: support additional CA bundle
  Gopkg.lock
  cmd/machine-config-operator/bootstrap.go
  pkg/apis/machineconfiguration.openshift.io/v1/types.go
  pkg/apis/machineconfiguration.openshift.io/v1/zz_generated.deepcopy.go
  pkg/operator/bootstrap.go
  pkg/operator/sync.go
  templates/common/_base/files/additional-trust-bundle.yaml
  vendor/github.com/openshift/api/config/v1/types_apiserver.go
  vendor/github.com/openshift/api/config/v1/types_authentication.go
  vendor/github.com/openshift/api/config/v1/types_console.go
  vendor/github.com/openshift/api/config/v1/types_dns.go
  vendor/github.com/openshift/api/config/v1/types_proxy.go
  vendor/github.com/openshift/api/config/v1/zz_generated.deepcopy.go
  vendor/github.com/openshift/api/config/v1/zz_generated.swagger_doc_generated.go
Labels: approved, lgtm, size/L

#795 baremetal: Add coredns, mdns-publisher, haproxy, keepalived static pods
  cmd/machine-config-operator/bootstrap.go
  install/0000_80_machine-config-operator_02_images.configmap.yaml
  pkg/controller/template/constants.go
  pkg/controller/template/render_test.go
  pkg/controller/template/test_data/controller_config_baremetal.yaml
  pkg/operator/bootstrap.go
  pkg/operator/images.go
  pkg/operator/sync.go
  templates/common/baremetal/files/baremetal-NetworkManager-kni-conf.yaml
  templates/common/baremetal/files/baremetal-coredns-corefile.yaml
  templates/common/baremetal/files/baremetal-coredns.yaml
  templates/common/baremetal/files/baremetal-keepalived.yaml
  templates/common/baremetal/files/baremetal-mdns-publisher.yaml
  templates/master/00-master/baremetal/files/baremetal-haproxy-haproxy.yaml
  templates/master/00-master/baremetal/files/baremetal-haproxy.yaml
  templates/master/00-master/baremetal/files/baremetal-keepalived-keepalived.yaml
  templates/master/00-master/baremetal/files/baremetal-mdns-config.yaml
  templates/master/00-master/baremetal/files/dhcp-dhclient-conf.yaml
  templates/worker/00-worker/baremetal/files/NetworkManager-non-virtual-ip-prepender.yaml
  templates/worker/00-worker/baremetal/files/baremetal-keepalived-keepalived.yaml
  templates/worker/00-worker/baremetal/files/baremetal-mdns-config.yaml
  templates/worker/00-worker/baremetal/files/baremetal-non-virtual-ip.yaml
  templates/worker/00-worker/baremetal/files/dhcp-dhclient-conf.yaml
Labels: approved, lgtm, size/XL

#1012 hack: allow using Docker for development
  docs/HACKING.md
  hack/build-image
  hack/cluster-push-prep.sh
  hack/cluster-push.sh
Labels: approved, lgtm, size/M

#1018 pkg/operator: use corev1 codecs to decode configmaps
  pkg/operator/bootstrap.go
Labels: approved, lgtm, size/XS

#999 Bug 1727022: set upgradeable operator condition
  pkg/operator/status.go
  pkg/operator/status_test.go
  pkg/operator/sync.go
Labels: approved, bugzilla/valid-bug, lgtm, size/M

#1020 baremetal: fix haproxy logging
  templates/master/00-master/baremetal/files/baremetal-haproxy-haproxy.yaml
  templates/master/00-master/baremetal/files/baremetal-haproxy.yaml
Labels: approved, lgtm, size/XS

#1011 pkg/controller: allow custom pool rollback
  Makefile
  pkg/controller/node/node_controller.go
  test/e2e/mcd_test.go
Labels: approved, lgtm, size/M

#1014 Generate registries.conf using ICSP in MCC bootstrap
  pkg/controller/bootstrap/bootstrap.go
  pkg/controller/bootstrap/bootstrap_test.go
  pkg/controller/bootstrap/testdata/bootstrap/99_openshift-machineconfig_master.yaml
  pkg/controller/bootstrap/testdata/bootstrap/99_openshift-machineconfig_worker.yaml
  pkg/controller/bootstrap/testdata/bootstrap/image-content-source-policy-0.yaml
  pkg/controller/bootstrap/testdata/bootstrap/image-content-source-policy-1.yaml
  pkg/controller/bootstrap/testdata/bootstrap/machineconfigcontroller-controllerconfig.yaml
  pkg/controller/bootstrap/testdata/bootstrap/machineconfigcontroller-pull-secret
  pkg/controller/bootstrap/testdata/bootstrap/master.machineconfigpool.yaml
  pkg/controller/bootstrap/testdata/bootstrap/worker.machineconfigpool.yaml
  pkg/controller/container-runtime-config/container_runtime_config_controller.go
  pkg/controller/container-runtime-config/container_runtime_config_controller_test.go
Labels: approved, lgtm, size/L

#1022 pkg/controller/kubelet-config: fix owener reference
  pkg/controller/kubelet-config/kubelet_config_controller.go
Labels: approved, lgtm, size/XS

#1002 Render baremetal bootstrap configs
  cmd/machine-config-operator/bootstrap.go
  manifests/baremetal/coredns-corefile.tmpl
  manifests/baremetal/coredns.yaml
  manifests/baremetal/keepalived.conf.tmpl
  manifests/baremetal/keepalived.yaml
  pkg/operator/assets/bindata.go
  pkg/operator/bootstrap.go
  pkg/operator/images.go
Labels: approved, lgtm, size/XL

#1000 Bug 1732166: rotate kubelet CA rotation support [4.1]
  cmd/machine-config-operator/start.go
  lib/resourcemerge/machineconfig.go
  pkg/apis/machineconfiguration.openshift.io/v1/types.go
  pkg/apis/machineconfiguration.openshift.io/v1/zz_generated.deepcopy.go
  pkg/controller/common/controller_context.go
  pkg/controller/template/test_data/templates/master/01-master-kubelet/aws/files/-etc-kubernetes-kubelet-ca.crt
  pkg/controller/template/test_data/templates/master/01-master-kubelet/aws/units/kubelet.service
  pkg/controller/template/test_data/templates/master/01-master-kubelet/libvirt/files/-etc-kubernetes-kubelet-ca.crt
  pkg/controller/template/test_data/templates/master/01-master-kubelet/libvirt/units/kubelet.service
  pkg/controller/template/test_data/templates/master/01-master-kubelet/none/files/-etc-kubernetes-kubelet-ca.crt
  pkg/controller/template/test_data/templates/master/01-master-kubelet/none/units/kubelet.service
  pkg/controller/template/test_data/templates/master/01-master-kubelet/openstack/files/-etc-kubernetes-kubelet-ca.crt
  pkg/controller/template/test_data/templates/master/01-master-kubelet/vsphere/files/-etc-kubernetes-kubelet-ca.crt
  pkg/controller/template/test_data/templates/master/01-master-kubelet/vsphere/units/kubelet.service
  pkg/controller/template/test_data/templates/worker/01-worker-kubelet/aws/files/-etc-kubernetes-kubelet-ca.crt
  pkg/controller/template/test_data/templates/worker/01-worker-kubelet/aws/units/kubelet.service
  pkg/controller/template/test_data/templates/worker/01-worker-kubelet/libvirt/files/-etc-kubernetes-kubelet-ca.crt
  pkg/controller/template/test_data/templates/worker/01-worker-kubelet/libvirt/units/kubelet.service
  pkg/controller/template/test_data/templates/worker/01-worker-kubelet/none/files/-etc-kubernetes-kubelet-ca.crt
  pkg/controller/template/test_data/templates/worker/01-worker-kubelet/none/units/kubelet.service
  pkg/controller/template/test_data/templates/worker/01-worker-kubelet/openstack/files/-etc-kubernetes-kubelet-ca.crt
  pkg/controller/template/test_data/templates/worker/01-worker-kubelet/vsphere/files/-etc-kubernetes-kubelet-ca.crt
  pkg/controller/template/test_data/templates/worker/01-worker-kubelet/vsphere/units/kubelet.service
  pkg/operator/bootstrap.go
  pkg/operator/operator.go
  pkg/operator/sync.go
  templates/master/01-master-kubelet/_base/files/kubelet-ca.yaml
  templates/master/01-master-kubelet/_base/units/kubelet.yaml
  templates/worker/01-worker-kubelet/_base/files/kubelet-ca.yaml
  templates/worker/01-worker-kubelet/_base/units/kubelet.yaml
Labels: approved, bugzilla/valid-bug, cherry-pick-approved, lgtm, size/L

#962 vendor: update openshift/kubernetes-drain
  Gopkg.lock
  Gopkg.toml
  manifests/machineconfigdaemon/clusterrole.yaml
  pkg/operator/assets/bindata.go
  vendor/github.com/openshift/kubernetes-drain/drain.go
Labels: approved, lgtm, size/M
