Repository openshift/machine-config-operator, pull requests merged in 2019-11, with the labels that each got.

#1235 docs: note groups unsupported
  docs/MachineConfigDaemon.md
Labels: approved, lgtm, size/XS

#1237 [fcos] Fix mcd pull service
  templates/common/_base/units/machine-config-daemon-pull.service
Labels: approved, lgtm, size/XS

#1236 [fcos] templates: place /etc/pivot/kernel-args on masters/workers
  templates/common/_base/files/etc-pivot-kernel-args.yaml
Labels: approved, lgtm, size/XS

#1232 remove make binaries from Dockerfiles and use -mod=vendor when building
  Dockerfile
  Dockerfile.rhel7
  hack/build-go.sh
Labels: approved, lgtm, size/XS

#1224 cmd/machine-config-operator/bootstrap: add cluster-etcd-operator flag
  cmd/machine-config-operator/bootstrap.go
  install/0000_80_machine-config-operator_02_images.configmap.yaml
  pkg/controller/template/constants.go
  pkg/controller/template/render.go
  pkg/operator/bootstrap.go
  pkg/operator/images.go
  pkg/operator/sync.go
  templates/master/00-master/_base/files/etc-kubernetes-manifests-etcd-member.yaml
Labels: approved, lgtm, size/L

#1134 Bug 1755557: Ensure ETCD_INITIAL_CLUSTER is preserved during restore
  templates/master/00-master/_base/files/usr-local-bin-etcd-snapshot-restore-sh.yaml
Labels: approved, bugzilla/valid-bug, cherry-pick-approved, lgtm, size/XS

#1244 test/e2e: Drop TestFIPS
  test/e2e/mcd_test.go
Labels: approved, lgtm, size/L

#1238 tests: Stop bumping worker maxUnavailable to 3
  test/e2e/mcd_test.go
Labels: approved, size/S

#1221 setup-etcd-environment: support scaling from cluster-etcd-operator
  cmd/setup-etcd-environment/run.go
  go.mod
  go.sum
  templates/master/00-master/_base/files/etc-kubernetes-manifests-etcd-member.yaml
  vendor/github.com/openshift/cluster-etcd-operator/LICENSE
  vendor/github.com/openshift/cluster-etcd-operator/pkg/operator/api/scaling.go
Labels: approved, lgtm, size/L

#1223 install/telemetry: add prometheus alerts
  install/0000_90_machine-config-operator_01_prometheus-rules.yaml
  pkg/daemon/update.go
Labels: approved, lgtm, size/M

#1243 daemon: leave backup copy of encapsulated machineconfig
  pkg/daemon/constants/constants.go
  pkg/daemon/daemon.go
Labels: approved, lgtm, size/XS

#1233 daemon: Refuse to disable FIPS mode
  pkg/daemon/update.go
Labels: approved, lgtm, size/S

#1219 [Baremetal] - update haproxy statistics url
  templates/master/00-master/baremetal/files/baremetal-haproxy-haproxy.yaml
Labels: approved, lgtm, size/XS

#1245 controller: Log the exact status in conditions
  pkg/controller/node/status.go
Labels: approved, lgtm, size/XS

#1218 build-sys: Remove dead code in Makefile, fix HACKING.md typo
  Makefile
  docs/HACKING.md
Labels: approved, lgtm, size/M

#1231 Bug 1766356: templates: tell NetworkManager to ignore interfaces
  templates/common/_base/files/nm-ignore-sdn.yaml
Labels: approved, bugzilla/valid-bug, lgtm, size/XS

#1234 machineconfig.crd.yaml: add passwd schema
  manifests/machineconfig.crd.yaml
  pkg/operator/assets/bindata.go
Labels: approved, lgtm, size/M

#1209 docs: Update make target to build individual binaries
  docs/HACKING.md
Labels: approved, lgtm, size/XS

#1226 Bug 1769578: Specfile: Make `%global commit ...` overridable
  machine-config-daemon.spec
Labels: approved, bugzilla/valid-bug, lgtm, size/XS

#1251 Bug 1752144: docs: Add doc for nosmt Kernel Argument
  docs/MachineConfiguration.md
Labels: approved, bugzilla/valid-bug, lgtm, size/XS

#1252 daemon/update.go: fix FIPS check and remove day 2 support
  pkg/daemon/update.go
Labels: approved, lgtm, size/M

#1216 Update and reduce templates for CRI-O 1.16
  templates/master/01-master-container-runtime/_base/files/crio.yaml
  templates/worker/01-worker-container-runtime/_base/files/crio.yaml
Labels: approved, lgtm, size/XL

#1258 daemon/FIPS: move check to reconcilable
  pkg/daemon/update.go
Labels: approved, lgtm, size/M

#1260 Bug 1772155: install: add proper terminationMessagePolicy for etcd quorum guard pods
  install/0000_80_machine-config-operator_07_etcdquorumguard_deployment.yaml
Labels: approved, bugzilla/valid-bug, lgtm, size/XS

#1267 Bug 1766918: Exit the verify_certs loop after 60 iterations
  templates/master/00-master/_base/files/usr-local-bin-openshift-recovery-tools-sh.yaml
Labels: approved, bugzilla/valid-bug, lgtm, size/XS

#998 Bug 1736254: template/render: support vsphere platform
  pkg/controller/template/render.go
Labels: approved, bugzilla/valid-bug, lgtm, size/XS

#1169 baremetal: templates/manifests: Remove parameters from hosts plugin c…
  manifests/baremetal/coredns-corefile.tmpl
  pkg/operator/assets/bindata.go
  templates/common/baremetal/files/baremetal-coredns-corefile.yaml
Labels: approved, lgtm, size/XS

#1268 Bug 1772440: OpenStack: decrease infra pods resource consumption
  manifests/openstack/coredns.yaml
  manifests/openstack/keepalived.yaml
  pkg/operator/assets/bindata.go
  templates/common/openstack/files/openstack-coredns.yaml
  templates/common/openstack/files/openstack-keepalived.yaml
  templates/common/openstack/files/openstack-mdns-publisher.yaml
  templates/master/00-master/openstack/files/openstack-haproxy.yaml
Labels: approved, bugzilla/valid-bug, lgtm, size/M

#1255 templates/master/00-master: update recovery template to work with setup-etcd-environment
  templates/master/00-master/_base/files/usr-local-share-openshift-recovery-template-etcd-generate-certs-yaml-template.yaml
Labels: approved, lgtm, size/S

#1135 Bug 1755558: Ensure ETCD_INITIAL_CLUSTER is preserved during restore
  pkg/controller/template/test_data/templates/master/00-master/aws/files/-usr-local-bin-etcd-snapshot-restore.sh
  pkg/controller/template/test_data/templates/master/00-master/libvirt/files/-usr-local-bin-etcd-snapshot-restore.sh
  pkg/controller/template/test_data/templates/master/00-master/none/files/-usr-local-bin-etcd-snapshot-restore.sh
  pkg/controller/template/test_data/templates/master/00-master/openstack/files/-usr-local-bin-etcd-snapshot-restore.sh
  pkg/controller/template/test_data/templates/master/00-master/vsphere/files/-usr-local-bin-etcd-snapshot-restore.sh
  templates/master/00-master/_base/files/usr-local-bin-etcd-snapshot-restore-sh.yaml
Labels: approved, bugzilla/valid-bug, cherry-pick-approved, lgtm, size/XS

#1272 Bug 1770269: DR: etcdctl version should match with what is shipped with product
  templates/master/00-master/_base/files/usr-local-bin-etcd-member-add-sh.yaml
  templates/master/00-master/_base/files/usr-local-bin-etcd-member-recover-sh.yaml
  templates/master/00-master/_base/files/usr-local-bin-etcd-member-remove-sh.yaml
  templates/master/00-master/_base/files/usr-local-bin-etcd-snapshot-backup-sh.yaml
  templates/master/00-master/_base/files/usr-local-bin-etcd-snapshot-restore-sh.yaml
  templates/master/00-master/_base/files/usr-local-bin-openshift-recovery-tools-sh.yaml
Labels: approved, bugzilla/valid-bug, lgtm, size/XS

#1275 docs/MachineConfiguration: update kargs snippet
  docs/MachineConfiguration.md
Labels: approved, lgtm, size/S

#1262 Bug 1770273: Verify all containers are dead in stop_all_containers() function
  templates/master/00-master/_base/files/usr-local-bin-openshift-recovery-tools-sh.yaml
Labels: approved, bugzilla/valid-bug, lgtm, size/S

#1249 Bug 1769581: 4.2: Specfile: Make `%global commit ...` overridable
  machine-config-daemon.spec
Labels: approved, bugzilla/valid-bug, cherry-pick-approved, lgtm, size/XS

#1266 Add manifest annotations for hosted deployment exclusions
  install/0000_80_machine-config-operator_04_deployment.yaml
  install/0000_80_machine-config-operator_06_clusteroperator.yaml
  install/0000_80_machine-config-operator_07_etcdquorumguard_deployment.yaml
  install/0000_80_machine-config-operator_08_etcdquorumguard_pdb.yaml
Labels: approved, lgtm, size/S

#1263 Bug 1765759: templates/*etcd-member.yaml: give etcd-metrics container privilege
  templates/master/00-master/_base/files/etc-kubernetes-manifests-etcd-member.yaml
Labels: approved, bugzilla/valid-bug, cherry-pick-approved, lgtm, size/XS

#1280 Bug 1775009: pkg/controller: do not enqueue a nil MCP
  pkg/controller/node/node_controller.go
Labels: approved, bugzilla/valid-bug, lgtm, size/XS

#1281 Bug 1772440: OpenStack: decrease haproxy container resource consumption
  templates/master/00-master/openstack/files/openstack-haproxy.yaml
Labels: approved, bugzilla/valid-bug, lgtm, size/XS

#1283 OWNERS: Add myself (Sinny) and Jerry to be able to approve others' PRs
  OWNERS
Labels: approved, lgtm, size/XS

#1291 Bug 1777082: set vsphere as provider
  pkg/controller/template/render.go
  pkg/controller/template/render_test.go
Labels: approved, bugzilla/valid-bug, lgtm, size/XS
