Repository openshift/machine-config-operator, pull requests merged in 2019-01, with the labels that each got.

#263 docs/MCD: Update some for new model
  docs/MachineConfigDaemon.md
Labels: approved, lgtm, size/M

#164 Pass ssh keys from clusterconfig to machineconfig
  lib/resourcemerge/machineconfig.go
  pkg/apis/machineconfiguration.openshift.io/v1/types.go
  pkg/controller/template/render.go
  pkg/controller/template/render_test.go
  pkg/daemon/update.go
  pkg/daemon/update_test.go
  pkg/operator/operator.go
  pkg/operator/render.go
Labels: approved, lgtm, size/L

#272 daemon: fix deletion of stale config files
  pkg/daemon/update.go
Labels: approved, lgtm, size/S

#274 daemon: error out if failing to delete stale data
  pkg/daemon/update.go
Labels: approved, lgtm, size/M

#275 manifests: machine config daemon node selector for linux
  manifests/machineconfigdaemon/daemonset.yaml
Labels: approved, lgtm, size/XS

#271 typo fix and better bash variable handling
  hack/build-go.sh
Labels: approved, lgtm, size/XS

#281 docs: add more details about the template controller
  docs/MachineConfigController.md
Labels: approved, lgtm, size/XS

#277 docs: Describe more of what/why in README.md, devel stuff in HACKING.md
  HACKING.md
  README.md
Labels: approved, lgtm, size/L

#282 daemon: Fix load of booted OS
  pkg/daemon/daemon.go
Labels: approved, lgtm, size/XS

#265 allow operator to tie into node upgrade status
  cmd/machine-config-operator/start.go
  manifests/master.machineconfigpool.yaml
  pkg/apis/machineconfiguration.openshift.io/v1/helpers.go
  pkg/apis/machineconfiguration.openshift.io/v1/types.go
  pkg/apis/machineconfiguration.openshift.io/v1/zz_generated.deepcopy.go
  pkg/controller/common/constants.go
  pkg/controller/node/node_controller.go
  pkg/controller/node/node_controller_test.go
  pkg/controller/node/status.go
  pkg/controller/node/status_test.go
  pkg/controller/render/render_controller.go
  pkg/controller/render/render_controller_test.go
  pkg/controller/template/render.go
  pkg/operator/assets/bindata.go
  pkg/operator/operator.go
  pkg/operator/status.go
  pkg/operator/status_test.go
  pkg/operator/sync.go
  pkg/server/bootstrap_server.go
  pkg/server/cluster_server.go
  pkg/server/server_test.go
  pkg/server/testdata/machine-pools/test-pool.yaml
Labels: approved, lgtm, size/L

#279 controller: Take first non-empty osImageURL
  pkg/apis/machineconfiguration.openshift.io/v1/helpers.go
  pkg/apis/machineconfiguration.openshift.io/v1/helpers_test.go
Labels: approved, lgtm, size/M

#278 daemon/update: retry pivot 5 times on failed rc
  cmd/machine-config-daemon/start.go
  pkg/daemon/daemon.go
  pkg/daemon/node.go
  pkg/daemon/update.go
Labels: approved, lgtm, size/M

#288 operator: fix bindata
  pkg/operator/assets/bindata.go
Labels: approved, lgtm, size/XS

#115 Update SSH keys via MCD
  pkg/daemon/update.go
  pkg/daemon/update_test.go
Labels: approved, lgtm, size/L

#289 daemon: taint node when an ssh access is detected
  Gopkg.lock
  Gopkg.toml
  pkg/daemon/constants.go
  pkg/daemon/daemon.go
  pkg/daemon/writer.go
  vendor/gopkg.in/fsnotify.v1/AUTHORS
  vendor/gopkg.in/fsnotify.v1/LICENSE
  vendor/gopkg.in/fsnotify.v1/fen.go
  vendor/gopkg.in/fsnotify.v1/fsnotify.go
  vendor/gopkg.in/fsnotify.v1/inotify.go
  vendor/gopkg.in/fsnotify.v1/inotify_poller.go
  vendor/gopkg.in/fsnotify.v1/kqueue.go
  vendor/gopkg.in/fsnotify.v1/open_mode_bsd.go
  vendor/gopkg.in/fsnotify.v1/open_mode_darwin.go
  vendor/gopkg.in/fsnotify.v1/windows.go
Labels: approved, lgtm, size/XXL

#287 manifests: include pretty column prints for some CRDs
  manifests/machineconfig.crd.yaml
  manifests/machineconfigpool.crd.yaml
  pkg/operator/assets/bindata.go
Labels: approved, lgtm, size/M

#286 docs: how to update sshkeys for user "core" via mcd
  docs/MachineConfigDaemon.md
  docs/Update-SSHKeys.md
Labels: approved, lgtm, size/L

#293 daemon: fix updateSSHKeys for MC with Users unset/empty
  pkg/daemon/update.go
  pkg/daemon/update_test.go
Labels: approved, lgtm, size/S

#297 Two MCD logging patches
  pkg/daemon/daemon.go
  pkg/daemon/node.go
Labels: approved, lgtm, size/XS

#300 daemon: Drop unused `oldConfig` parameter to update function
  pkg/daemon/update.go
  pkg/daemon/update_test.go
Labels: approved, lgtm, size/S

#310 daemon: don't use type name as variable name
  pkg/daemon/daemon.go
Labels: approved, lgtm, size/S

#303 controller: Add a 5s delay before rendering MCs
  pkg/controller/render/render_controller.go
Labels: approved, lgtm, size/S

#313 Makefile: Add `test-unit`, only test pkg/ lib/ and cmd/
  Makefile
Labels: approved, lgtm, size/S

#307 kubeletconfig: add the generated-by annotation
  pkg/controller/kubelet-config/kubelet_config_controller.go
Labels: approved, lgtm, size/XS

#308 controller/tests: Avoid hardcoding SSH MC offsets
  pkg/controller/template/render_test.go
Labels: approved, lgtm, size/M

#302 Two small patches
  HACKING.md
  README.md
  hack/cluster-push.sh
Labels: approved, lgtm, size/L

#309 test/e2e: New test framework
  Makefile
  cmd/common/client_builder.go
  test/e2e/main_test.go
  test/e2e/sanity_test.go
Labels: approved, lgtm, size/M

#316 set cpu request and remove limits on pods
  install/0000_50_machine-config-operator_04_deployment.yaml
  manifests/machineconfigdaemon/daemonset.yaml
  manifests/machineconfigserver/daemonset.yaml
  pkg/controller/template/test_data/templates/master/00-master/aws/files/-etc-kubernetes-manifests-etcd-member.yaml
  pkg/controller/template/test_data/templates/master/00-master/libvirt/files/-etc-kubernetes-manifests-etcd-member.yaml
  pkg/controller/template/test_data/templates/master/00-master/none/files/-etc-kubernetes-manifests-etcd-member.yaml
  pkg/controller/template/test_data/templates/master/00-master/openstack/files/-etc-kubernetes-manifests-etcd-member.yaml
  templates/master/00-master/_base/files/etc-kubernetes-manifests-etcd-member.yaml
Labels: approved, lgtm, size/S

#321 controller/render: fix ownerRef deletion error-handling
  pkg/controller/render/render_controller.go
Labels: approved, lgtm, size/XS

#312 daemon: skip querying currentConfig if possible
  pkg/daemon/daemon.go
  pkg/daemon/update.go
Labels: approved, lgtm, size/M

#315 Provide a writable location for flexvolume plugins
  pkg/controller/template/test_data/README.md
  pkg/controller/template/test_data/templates/master/00-master/aws/files/-etc-kubernetes-kubelet-plugins-volume-exec-.dummy
  pkg/controller/template/test_data/templates/master/00-master/libvirt/files/-etc-kubernetes-kubelet-plugins-volume-exec-.dummy
  pkg/controller/template/test_data/templates/master/00-master/none/files/-etc-kubernetes-kubelet-plugins-volume-exec-.dummy
  pkg/controller/template/test_data/templates/master/00-master/openstack/files/-etc-kubernetes-kubelet-plugins-volume-exec-.dummy
  pkg/controller/template/test_data/templates/master/01-master-kubelet/aws/units/kubelet.service
  pkg/controller/template/test_data/templates/master/01-master-kubelet/libvirt/units/kubelet.service
  pkg/controller/template/test_data/templates/master/01-master-kubelet/none/units/kubelet.service
  pkg/controller/template/test_data/templates/worker/00-worker/aws/files/-etc-kubernetes-kubelet-plugins-volume-exec-.dummy
  pkg/controller/template/test_data/templates/worker/00-worker/libvirt/files/-etc-kubernetes-kubelet-plugins-volume-exec-.dummy
  pkg/controller/template/test_data/templates/worker/00-worker/none/files/-etc-kubernetes-kubelet-plugins-volume-exec-.dummy
  pkg/controller/template/test_data/templates/worker/00-worker/openstack/files/-etc-kubernetes-kubelet-plugins-volume-exec-.dummy
  pkg/controller/template/test_data/templates/worker/01-worker-kubelet/aws/units/kubelet.service
  pkg/controller/template/test_data/templates/worker/01-worker-kubelet/libvirt/units/kubelet.service
  pkg/controller/template/test_data/templates/worker/01-worker-kubelet/none/units/kubelet.service
  templates/master/00-master/_base/files/volume-plugins.yaml
  templates/master/01-master-kubelet/_base/units/kubelet.yaml
  templates/worker/00-worker/_base/files/volume-plugins.yaml
  templates/worker/01-worker-kubelet/_base/units/kubelet.yaml
Labels: approved, lgtm, size/M

#327 Update bindata for operator
  HACKING.md
  pkg/operator/assets/bindata.go
Labels: approved, lgtm, size/M

#331 mco/install: update mco run level to 30
  install/0000_30_machine-config-operator_00_namespace.yaml
  install/0000_30_machine-config-operator_01_mcoconfig.crd.yaml
  install/0000_30_machine-config-operator_02_images.configmap.yaml
  install/0000_30_machine-config-operator_03_rbac.yaml
  install/0000_30_machine-config-operator_04_deployment.yaml
  install/0000_30_machine-config-operator_05_osimageurl.yaml
Labels: approved, lgtm, size/XS

#333 kubelet: always delete cpu_manager_state
  pkg/controller/template/test_data/templates/master/01-master-kubelet/aws/units/kubelet.service
  pkg/controller/template/test_data/templates/master/01-master-kubelet/libvirt/units/kubelet.service
  pkg/controller/template/test_data/templates/master/01-master-kubelet/none/units/kubelet.service
  pkg/controller/template/test_data/templates/worker/01-worker-kubelet/aws/units/kubelet.service
  pkg/controller/template/test_data/templates/worker/01-worker-kubelet/libvirt/units/kubelet.service
  pkg/controller/template/test_data/templates/worker/01-worker-kubelet/none/units/kubelet.service
  templates/master/01-master-kubelet/_base/units/kubelet.yaml
  templates/worker/01-worker-kubelet/_base/units/kubelet.yaml
Labels: approved, lgtm, size/XS

#347 controller: Move MC garbage collection to helper function, disable it
  pkg/controller/render/render_controller.go
Labels: approved, lgtm, size/M

#348 mco: remove osimageurl logging from sync() to make mco logs readable
  pkg/operator/operator.go
Labels: approved, lgtm, size/XS

#339 report template controller's status in ControllerConfig
  cmd/machine-config-operator/start.go
  manifests/controllerconfig.crd.yaml
  pkg/apis/machineconfiguration.openshift.io/v1/helpers.go
  pkg/apis/machineconfiguration.openshift.io/v1/types.go
  pkg/apis/machineconfiguration.openshift.io/v1/zz_generated.deepcopy.go
  pkg/controller/template/status.go
  pkg/controller/template/template_controller.go
  pkg/controller/template/template_controller_test.go
  pkg/generated/clientset/versioned/typed/machineconfiguration.openshift.io/v1/controllerconfig.go
  pkg/generated/clientset/versioned/typed/machineconfiguration.openshift.io/v1/fake/fake_controllerconfig.go
  pkg/operator/assets/bindata.go
  pkg/operator/operator.go
  pkg/operator/status.go
  pkg/operator/status_test.go
  pkg/operator/sync.go
Labels: approved, lgtm, size/L

#344 Fix log output
  pkg/operator/bootstrap.go
Labels: approved, lgtm, size/XS

#340 mco: If the platform is unrecognized, treat the platform as 'none'
  pkg/controller/kubelet-config/kubelet_config_controller_test.go
  pkg/controller/template/render.go
  pkg/controller/template/render_test.go
  pkg/operator/render.go
Labels: approved, lgtm, size/L

#352 daemon: fix overwritten files
  pkg/daemon/daemon.go
  pkg/daemon/daemon_test.go
  pkg/daemon/fixtures/test1.txt
Labels: approved, lgtm, size/M
