Repository openshift/machine-config-operator, pull requests merged in 2019-05, with the labels that each got.

#693 docs/OSUpgrades.md: Various improvements
  docs/OSUpgrades.md
Labels: approved, lgtm, size/M

#685 Bug 1704706: remove openshift-sdn and multus CNI configuration files on boot
  pkg/controller/template/test_data/templates/master/00-master/aws/files/-etc-tmpfiles.d-cleanup-cni.conf
  pkg/controller/template/test_data/templates/master/00-master/libvirt/files/-etc-tmpfiles.d-cleanup-cni.conf
  pkg/controller/template/test_data/templates/master/00-master/none/files/-etc-tmpfiles.d-cleanup-cni.conf
  pkg/controller/template/test_data/templates/master/00-master/openstack/files/-etc-tmpfiles.d-cleanup-cni.conf
  pkg/controller/template/test_data/templates/master/00-master/vsphere/files/-etc-tmpfiles.d-cleanup-cni.conf
  pkg/controller/template/test_data/templates/worker/00-worker/aws/files/-etc-tmpfiles.d-cleanup-cni.conf
  pkg/controller/template/test_data/templates/worker/00-worker/libvirt/files/-etc-tmpfiles.d-cleanup-cni.conf
  pkg/controller/template/test_data/templates/worker/00-worker/none/files/-etc-tmpfiles.d-cleanup-cni.conf
  pkg/controller/template/test_data/templates/worker/00-worker/openstack/files/-etc-tmpfiles.d-cleanup-cni.conf
  pkg/controller/template/test_data/templates/worker/00-worker/vsphere/files/-etc-tmpfiles.d-cleanup-cni.conf
  templates/master/00-master/_base/files/cleanup-cni-conf.yaml
  templates/worker/00-worker/_base/files/cleanup-cni-conf.yaml
Labels: approved, lgtm, size/M

#697 adjust sigterm handler and bump test timeouts
  Makefile
  cmd/machine-config-daemon/start.go
  pkg/controller/node/node_controller.go
  pkg/controller/node/status.go
  pkg/daemon/daemon.go
  pkg/daemon/update.go
  test/e2e/mcd_test.go
Labels: approved, lgtm, size/L

#675 Bug 1703703 *: add etcd configuration file
  pkg/controller/template/test_data/templates/master/00-master/aws/files/-etc-etcd-etcd.conf
  pkg/controller/template/test_data/templates/master/00-master/aws/files/-etc-kubernetes-manifests-etcd-member.yaml
  pkg/controller/template/test_data/templates/master/00-master/libvirt/files/-etc-etcd-etcd.conf
  pkg/controller/template/test_data/templates/master/00-master/libvirt/files/-etc-kubernetes-manifests-etcd-member.yaml
  pkg/controller/template/test_data/templates/master/00-master/none/files/-etc-etcd-etcd.conf
  pkg/controller/template/test_data/templates/master/00-master/none/files/-etc-kubernetes-manifests-etcd-member.yaml
  pkg/controller/template/test_data/templates/master/00-master/openstack/files/-etc-etcd-etcd.conf
  pkg/controller/template/test_data/templates/master/00-master/openstack/files/-etc-kubernetes-manifests-etcd-member.yaml
  pkg/controller/template/test_data/templates/master/00-master/vsphere/files/-etc-etcd-etcd.conf
  pkg/controller/template/test_data/templates/master/00-master/vsphere/files/-etc-kubernetes-manifests-etcd-member.yaml
  templates/master/00-master/_base/files/etc-etcd-etcd-conf.yaml
  templates/master/00-master/_base/files/etc-kubernetes-manifests-etcd-member.yaml
Labels: approved, lgtm, size/S

#703 Two more mcc logs
  pkg/controller/node/node_controller.go
  pkg/controller/render/render_controller.go
Labels: approved, lgtm, size/S

#702 pkg/daemon: diff strings on file checks
  pkg/daemon/daemon.go
Labels: approved, lgtm, size/XS

#681 templates: increase kubelet loglevel for better troubleshooting
  pkg/controller/template/test_data/templates/master/01-master-kubelet/aws/units/kubelet.service
  pkg/controller/template/test_data/templates/master/01-master-kubelet/libvirt/units/kubelet.service
  pkg/controller/template/test_data/templates/master/01-master-kubelet/none/units/kubelet.service
  pkg/controller/template/test_data/templates/master/01-master-kubelet/vsphere/units/kubelet.service
  pkg/controller/template/test_data/templates/worker/01-worker-kubelet/aws/units/kubelet.service
  pkg/controller/template/test_data/templates/worker/01-worker-kubelet/libvirt/units/kubelet.service
  pkg/controller/template/test_data/templates/worker/01-worker-kubelet/none/units/kubelet.service
  pkg/controller/template/test_data/templates/worker/01-worker-kubelet/vsphere/units/kubelet.service
  templates/master/01-master-kubelet/_base/units/kubelet.yaml
  templates/worker/01-worker-kubelet/_base/units/kubelet.yaml
Labels: approved, lgtm, size/XS

#704 Small fixes + remove not needed mounts
  manifests/machineconfigdaemon/daemonset.yaml
  pkg/daemon/daemon.go
  pkg/daemon/update.go
  pkg/operator/assets/bindata.go
Labels: approved, lgtm, size/M

#707 pkg/daemon: lock when checking if update is active
  pkg/daemon/daemon.go
  pkg/daemon/update.go
Labels: approved, lgtm, size/S

#705 Work around bz1571183
  install/0000_80_machine-config-operator_07_etcdquorumguard_deployment.yaml
Labels: approved, lgtm, size/XS

#712 daemon: Tweak logging during updates
  pkg/daemon/daemon.go
  pkg/daemon/update.go
Labels: approved, lgtm, size/XS

#713 Bug 1707212: only log reboot command error and change it to systemd-run
  pkg/daemon/daemon.go
  pkg/daemon/update.go
Labels: approved, lgtm, size/S

#700 Bug 1706204: Fix tolerations
  install/0000_80_machine-config-operator_04_deployment.yaml
  install/0000_80_machine-config-operator_07_etcdquorumguard_deployment.yaml
  manifests/machineconfigcontroller/deployment.yaml
  manifests/machineconfigdaemon/daemonset.yaml
  manifests/machineconfigserver/daemonset.yaml
  pkg/operator/assets/bindata.go
Labels: approved, lgtm, size/M

#709 daemon: Only log rpm-ostree status once, add boot list
  pkg/daemon/daemon.go
Labels: approved, lgtm, size/S

#710 daemon: Greatly slow down rate of retries
  pkg/daemon/daemon.go
Labels: approved, lgtm, size/M

#711 pkg/daemon: log pending config to journal
  pkg/daemon/daemon.go
  pkg/daemon/update.go
Labels: approved, lgtm, size/L

#719 pkg/daemon: fix pending config logic
  pkg/daemon/update.go
Labels: approved, lgtm, size/XS

#715 Bug 1706689: pkg: Catch up to the api change introduced in openshift/api#308
  Gopkg.lock
  pkg/operator/bootstrap.go
  pkg/operator/operator.go
  vendor/github.com/openshift/api/config/v1/types_cluster_version.go
  vendor/github.com/openshift/api/config/v1/types_infrastructure.go
  vendor/github.com/openshift/api/config/v1/zz_generated.swagger_doc_generated.go
Labels: approved, lgtm, size/M

#721 daemon: Remove dummy OnceFrom Test
  pkg/daemon/daemon_test.go
Labels: approved, lgtm, size/M

#720 BUG 1703581: templates/master/00-master: bump etcd ETCD_QUOTA_BACKEND_BYTES default to 7GB
  pkg/controller/template/test_data/templates/master/00-master/aws/files/-etc-etcd-etcd.conf
  pkg/controller/template/test_data/templates/master/00-master/libvirt/files/-etc-etcd-etcd.conf
  pkg/controller/template/test_data/templates/master/00-master/none/files/-etc-etcd-etcd.conf
  pkg/controller/template/test_data/templates/master/00-master/openstack/files/-etc-etcd-etcd.conf
  pkg/controller/template/test_data/templates/master/00-master/vsphere/files/-etc-etcd-etcd.conf
  templates/master/00-master/_base/files/etc-etcd-etcd-conf.yaml
Labels: approved, lgtm, size/XS

#724 MCD: bump terminationGracePeriodSeconds
  manifests/machineconfigdaemon/daemonset.yaml
  pkg/operator/assets/bindata.go
Labels: approved, lgtm, size/XS

#701 Bug 1707212: Rework controller progress
  pkg/controller/node/node_controller.go
  pkg/controller/node/node_controller_test.go
  pkg/controller/node/status.go
  pkg/controller/node/status_test.go
  test/e2e/mcd_test.go
Labels: approved, lgtm, size/L

#728 Bug 1707928: hack/build-go.sh: use just git hashes for building
  cmd/machine-config-controller/version.go
  cmd/machine-config-daemon/version.go
  cmd/machine-config-operator/version.go
  cmd/machine-config-server/version.go
  cmd/setup-etcd-environment/version.go
  hack/build-go.sh
  pkg/controller/container-runtime-config/container_runtime_config_controller.go
  pkg/controller/kubelet-config/kubelet_config_controller.go
  pkg/controller/kubelet-config/kubelet_config_features.go
  pkg/controller/render/render_controller.go
  pkg/controller/template/render.go
  pkg/operator/status.go
  pkg/operator/sync.go
  pkg/version/version.go
Labels: approved, lgtm, size/M

#730 cmd: log version hash for components
  cmd/machine-config-controller/bootstrap.go
  cmd/machine-config-controller/start.go
  cmd/machine-config-daemon/start.go
  cmd/machine-config-operator/bootstrap.go
  cmd/machine-config-operator/start.go
  cmd/machine-config-server/bootstrap.go
  cmd/machine-config-server/start.go
  cmd/setup-etcd-environment/run.go
Labels: approved, lgtm, size/S

#732 README.md: add Security Response section
  docs/README.md
Labels: approved, lgtm, size/XS

#733 Bug 1708602: pkg/daemon: log cmd output on error
  pkg/daemon/daemon.go
  pkg/daemon/update.go
Labels: approved, lgtm, size/S

#651 DR: pkg/daemon: reconcile current on disk on boot
  pkg/daemon/daemon.go
  pkg/daemon/update.go
Labels: approved, lgtm, size/M

#735 update issue template to link to security response
  .github/ISSUE_TEMPLATE.md
Labels: approved, lgtm, size/XS

#734 Bug 1708602: pkg/daemon: workaround old util-linux logger in rhel7.6
  pkg/daemon/daemon.go
  pkg/daemon/update.go
Labels: approved, lgtm, size/L

#738 build-go.sh: use OS_GIT_COMMIT if available
  hack/build-go.sh
Labels: approved, lgtm, size/XS

#744 build-go.sh: OS_GIT_COMMIT => SOURCE_GIT_COMMIT
  hack/build-go.sh
Labels: approved, lgtm, size/XS

#708 daemon: Move chroot to very early on
  cmd/machine-config-daemon/start.go
  pkg/daemon/daemon.go
  pkg/daemon/daemon_test.go
  pkg/daemon/osrelease.go
  pkg/daemon/rpm-ostree.go
  pkg/daemon/rpm-ostree_test.go
  pkg/daemon/update_test.go
Labels: 4.2, approved, lgtm, size/L

#743 build-go.sh: use SOURCE_GIT_COMMIT if available
  hack/build-go.sh
Labels: approved, lgtm, size/XS

#657 Drop os_version label on nodes
  pkg/controller/template/test_data/templates/master/01-master-kubelet/aws/units/kubelet.service
  pkg/controller/template/test_data/templates/master/01-master-kubelet/libvirt/units/kubelet.service
  pkg/controller/template/test_data/templates/master/01-master-kubelet/none/units/kubelet.service
  pkg/controller/template/test_data/templates/master/01-master-kubelet/vsphere/units/kubelet.service
  pkg/controller/template/test_data/templates/worker/01-worker-kubelet/aws/units/kubelet.service
  pkg/controller/template/test_data/templates/worker/01-worker-kubelet/libvirt/units/kubelet.service
  pkg/controller/template/test_data/templates/worker/01-worker-kubelet/none/units/kubelet.service
  pkg/controller/template/test_data/templates/worker/01-worker-kubelet/vsphere/units/kubelet.service
  templates/master/01-master-kubelet/_base/units/kubelet.yaml
  templates/worker/01-worker-kubelet/_base/units/kubelet.yaml
Labels: 4.2, approved, lgtm, size/XS

#746 daemon: Drop unnecessary logSystem
  pkg/daemon/daemon.go
Labels: approved, lgtm, size/XS

#717 pkg/daemon: attach stdin directly
  pkg/daemon/update.go
Labels: 4.2, approved, lgtm, size/S

#653 templates: Remove empty platform directories
  pkg/controller/template/render.go
  templates/master/00-master/aws/.gitkeep
  templates/master/00-master/azure/.gitkeep
  templates/master/00-master/libvirt/.gitkeep
  templates/master/00-master/none/.gitkeep
  templates/master/00-master/openstack/.gitkeep
  templates/master/00-master/vsphere/.gitkeep
  templates/master/01-master-container-runtime/aws/.gitkeep
  templates/master/01-master-container-runtime/azure/.gitkeep
  templates/master/01-master-container-runtime/libvirt/.gitkeep
  templates/master/01-master-container-runtime/none/.gitkeep
  templates/master/01-master-container-runtime/openstack/.gitkeep
  templates/master/01-master-container-runtime/vsphere/.gitkeep
  templates/master/01-master-kubelet/aws/.gitkeep
  templates/master/01-master-kubelet/azure/.gitkeep
  templates/master/01-master-kubelet/libvirt/.gitkeep
  templates/master/01-master-kubelet/none/.gitkeep
  templates/master/01-master-kubelet/openstack/.gitkeep
  templates/master/01-master-kubelet/vsphere/.gitkeep
  templates/worker/00-worker/aws/.gitkeep
  templates/worker/00-worker/azure/.gitkeep
  templates/worker/00-worker/libvirt/.gitkeep
  templates/worker/00-worker/none/.gitkeep
  templates/worker/00-worker/openstack/.gitkeep
  templates/worker/00-worker/vsphere/.gitkeep
  templates/worker/01-worker-container-runtime/aws/.gitkeep
  templates/worker/01-worker-container-runtime/azure/.gitkeep
  templates/worker/01-worker-container-runtime/libvirt/.gitkeep
  templates/worker/01-worker-container-runtime/none/.gitkeep
  templates/worker/01-worker-container-runtime/openstack/.gitkeep
  templates/worker/01-worker-container-runtime/vsphere/.gitkeep
  templates/worker/01-worker-kubelet/aws/.gitkeep
  templates/worker/01-worker-kubelet/azure/.gitkeep
  templates/worker/01-worker-kubelet/libvirt/.gitkeep
  templates/worker/01-worker-kubelet/none/.gitkeep
  templates/worker/01-worker-kubelet/openstack/.gitkeep
  templates/worker/01-worker-kubelet/vsphere/.gitkeep
Labels: 4.2, approved, lgtm, size/XS

#752 daemon: Log high level diff between MCs
  pkg/daemon/update.go
  pkg/daemon/update_test.go
Labels: approved, lgtm, size/L

#747 Bug 1709907: pkg/daemon: drop spammy logSystem
  pkg/daemon/daemon.go
Labels: approved, lgtm, size/XS

#750 install: Use generic image placeholders
  install/0000_80_machine-config-operator_02_images.configmap.yaml
  install/0000_80_machine-config-operator_04_deployment.yaml
  install/0000_80_machine-config-operator_05_osimageurl.yaml
  install/0000_80_machine-config-operator_07_etcdquorumguard_deployment.yaml
  install/image-references
Labels: approved, lgtm, size/M

#751 mcc: refactor node controller to use error check helper function
  pkg/controller/node/node_controller.go
  pkg/controller/node/status.go
Labels: approved, lgtm, size/M

#725 server: update healthz to return 200 instead of 204
  pkg/server/api.go
  pkg/server/api_test.go
Labels: 4.2, approved, lgtm, size/S

#754 [release-4.1] Bug 1708602: pkg/daemon: workaround old util-linux logger in rhel7.6
  pkg/daemon/daemon.go
  pkg/daemon/update.go
Labels: approved, lgtm, size/L

#753 pkg/controller: calculate fault tolerance for the master pool
  pkg/controller/node/node_controller.go
  pkg/controller/node/node_controller_test.go
Labels: approved, lgtm, size/L

#756 daemon: Export Reconcilable as free function
  pkg/daemon/update.go
  pkg/daemon/update_test.go
Labels: approved, lgtm, size/L

#755 server: Add a log message when a pool is requested
  hack/cluster-push-prep.sh
  pkg/server/api.go
Labels: approved, lgtm, size/XS

#761 daemon: Reduce/clean up logging
  pkg/daemon/daemon.go
Labels: approved, lgtm, size/XS

#764 two test cleanup patches
  test/e2e/etcdquorumguard_test.go
  test/e2e/mcd_test.go
Labels: approved, lgtm, size/M

#757 JIRA PROD-1027 : templates/master/00-master: add disaster recovery tools
  templates/master/00-master/_base/files/usr-local-bin-etcd-member-recover-sh.yaml
  templates/master/00-master/_base/files/usr-local-bin-etcd-snapshot-restore-sh.yaml
  templates/master/00-master/_base/files/usr-local-bin-openshift-recovery-tools-sh.yaml
  templates/master/00-master/_base/files/usr-local-bin-tokenize-signer-sh.yaml
  templates/master/00-master/_base/files/usr-local-share-openshift-recovery-template-etcd-generate-certs-yaml-template.yaml
  templates/master/00-master/_base/files/usr-local-share-openshift-recovery-template-kube-etcd-cert-signer-yaml-template.yaml
Labels: approved, lgtm, size/XL

#741 operator: remove the cluster role binding that auto approves all node client CSRs
  manifests/machineconfigserver/csr-approver-role-binding.yaml
  pkg/operator/assets/bindata.go
  pkg/operator/bootstrap.go
  pkg/operator/sync.go
Labels: approved, lgtm, size/M

#768 Bug 1707162: Remove the cluster role binding that auto approves all node client CSRs
  manifests/machineconfigserver/csr-approver-role-binding.yaml
  pkg/operator/assets/bindata.go
  pkg/operator/bootstrap.go
  pkg/operator/sync.go
Labels: approved, lgtm, size/M

#627 templates: Add a templates/common/, move pull secret there
  pkg/controller/container-runtime-config/container_runtime_config_controller.go
  pkg/controller/kubelet-config/kubelet_config_controller.go
  pkg/controller/template/render.go
  templates/common/_base/files/pull-secret.yaml
  templates/worker/00-worker/_base/files/pull-secret.yaml
Labels: approved, lgtm, size/M

#610 *: pre-transition ign refactor
  docs/MachineConfiguration.md
  lib/resourceapply/machineconfig_test.go
  pkg/apis/machineconfiguration.openshift.io/v1/helpers.go
  pkg/apis/machineconfiguration.openshift.io/v1/machineconfig.deepcopy.go
  pkg/apis/machineconfiguration.openshift.io/v1/types.go
  pkg/controller/common/helpers.go
  pkg/controller/container-runtime-config/container_runtime_config_controller.go
  pkg/controller/container-runtime-config/container_runtime_config_controller_test.go
  pkg/controller/container-runtime-config/helpers.go
  pkg/controller/kubelet-config/helpers.go
  pkg/controller/kubelet-config/kubelet_config_controller.go
  pkg/controller/kubelet-config/kubelet_config_controller_test.go
  pkg/controller/kubelet-config/kubelet_config_features_test.go
  pkg/controller/render/render_controller_test.go
  pkg/controller/template/render.go
  pkg/controller/template/render_test.go
  pkg/controller/template/template_controller_test.go
  pkg/daemon/daemon.go
  pkg/daemon/daemon_test.go
  pkg/daemon/update.go
  pkg/daemon/update_test.go
  pkg/server/api_test.go
  pkg/server/bootstrap_server.go
  pkg/server/cluster_server.go
  pkg/server/server.go
  pkg/server/server_test.go
  test/e2e/mcd_test.go
Labels: 4.2, approved, lgtm, size/XL

#775 JIRA PROD-1027: templates/master/00-master: add a script to make etcd snapshot
  templates/master/00-master/_base/files/usr-local-bin-etcd-snapshot-backup-sh.yaml
  templates/master/00-master/_base/files/usr-local-bin-openshift-recovery-tools-sh.yaml
Labels: approved, lgtm, size/M

#776 JIRA PROD-1027: templates/master/00-master: optionally pass etcd connection string
  templates/master/00-master/_base/files/usr-local-bin-etcd-snapshot-restore-sh.yaml
  templates/master/00-master/_base/files/usr-local-bin-openshift-recovery-tools-sh.yaml
Labels: approved, lgtm, size/S

#772 Bug 1710626: kubelet: add crio dependency to systemd unit file
  templates/master/01-master-kubelet/_base/units/kubelet.yaml
  templates/worker/01-worker-kubelet/_base/units/kubelet.yaml
Labels: approved, lgtm, size/XS

#778 templates/master/00-master: use etcd certs for snapshot save
  templates/master/00-master/_base/files/usr-local-bin-etcd-snapshot-backup-sh.yaml
  templates/master/00-master/_base/files/usr-local-bin-openshift-recovery-tools-sh.yaml
Labels: approved, lgtm, size/L

#765 test/e2e: More refactoring
  test/e2e/mcd_test.go
Labels: approved, lgtm, size/L

#771 [release-4.1] templates/master/00-master: add DR tools
  pkg/controller/template/test_data/templates/master/00-master/aws/files/-usr-local-bin-etcd-member-recover.sh
  pkg/controller/template/test_data/templates/master/00-master/aws/files/-usr-local-bin-etcd-snapshot-backup.sh
  pkg/controller/template/test_data/templates/master/00-master/aws/files/-usr-local-bin-etcd-snapshot-restore.sh
  pkg/controller/template/test_data/templates/master/00-master/aws/files/-usr-local-bin-openshift-recovery-tools
  pkg/controller/template/test_data/templates/master/00-master/aws/files/-usr-local-bin-tokenize-signer.sh
  pkg/controller/template/test_data/templates/master/00-master/aws/files/-usr-local-share-openshift-recovery-template-etcd-generate-certs.yaml.template
  pkg/controller/template/test_data/templates/master/00-master/aws/files/-usr-local-share-openshift-recovery-template-kube-etcd-cert-signer.yaml.template
  pkg/controller/template/test_data/templates/master/00-master/libvirt/files/-usr-local-bin-etcd-member-recover.sh
  pkg/controller/template/test_data/templates/master/00-master/libvirt/files/-usr-local-bin-etcd-snapshot-backup.sh
  pkg/controller/template/test_data/templates/master/00-master/libvirt/files/-usr-local-bin-etcd-snapshot-restore.sh
  pkg/controller/template/test_data/templates/master/00-master/libvirt/files/-usr-local-bin-openshift-recovery-tools
  pkg/controller/template/test_data/templates/master/00-master/libvirt/files/-usr-local-bin-tokenize-signer.sh
  pkg/controller/template/test_data/templates/master/00-master/libvirt/files/-usr-local-share-openshift-recovery-template-etcd-generate-certs.yaml.template
  pkg/controller/template/test_data/templates/master/00-master/libvirt/files/-usr-local-share-openshift-recovery-template-kube-etcd-cert-signer.yaml.template
  pkg/controller/template/test_data/templates/master/00-master/none/files/-usr-local-bin-etcd-member-recover.sh
  pkg/controller/template/test_data/templates/master/00-master/none/files/-usr-local-bin-etcd-snapshot-backup.sh
  pkg/controller/template/test_data/templates/master/00-master/none/files/-usr-local-bin-etcd-snapshot-restore.sh
  pkg/controller/template/test_data/templates/master/00-master/none/files/-usr-local-bin-openshift-recovery-tools
  pkg/controller/template/test_data/templates/master/00-master/none/files/-usr-local-bin-tokenize-signer.sh
  pkg/controller/template/test_data/templates/master/00-master/none/files/-usr-local-share-openshift-recovery-template-etcd-generate-certs.yaml.template
  pkg/controller/template/test_data/templates/master/00-master/none/files/-usr-local-share-openshift-recovery-template-kube-etcd-cert-signer.yaml.template
  pkg/controller/template/test_data/templates/master/00-master/openstack/files/-usr-local-bin-etcd-member-recover.sh
  pkg/controller/template/test_data/templates/master/00-master/openstack/files/-usr-local-bin-etcd-snapshot-backup.sh
  pkg/controller/template/test_data/templates/master/00-master/openstack/files/-usr-local-bin-etcd-snapshot-restore.sh
  pkg/controller/template/test_data/templates/master/00-master/openstack/files/-usr-local-bin-openshift-recovery-tools
  pkg/controller/template/test_data/templates/master/00-master/openstack/files/-usr-local-bin-tokenize-signer.sh
  pkg/controller/template/test_data/templates/master/00-master/openstack/files/-usr-local-share-openshift-recovery-template-etcd-generate-certs.yaml.template
  pkg/controller/template/test_data/templates/master/00-master/openstack/files/-usr-local-share-openshift-recovery-template-kube-etcd-cert-signer.yaml.template
  pkg/controller/template/test_data/templates/master/00-master/vsphere/files/-usr-local-bin-etcd-member-recover.sh
  pkg/controller/template/test_data/templates/master/00-master/vsphere/files/-usr-local-bin-etcd-snapshot-backup.sh
  pkg/controller/template/test_data/templates/master/00-master/vsphere/files/-usr-local-bin-etcd-snapshot-restore.sh
  pkg/controller/template/test_data/templates/master/00-master/vsphere/files/-usr-local-bin-openshift-recovery-tools
  pkg/controller/template/test_data/templates/master/00-master/vsphere/files/-usr-local-bin-tokenize-signer.sh
  pkg/controller/template/test_data/templates/master/00-master/vsphere/files/-usr-local-share-openshift-recovery-template-etcd-generate-certs.yaml.template
  pkg/controller/template/test_data/templates/master/00-master/vsphere/files/-usr-local-share-openshift-recovery-template-kube-etcd-cert-signer.yaml.template
  templates/master/00-master/_base/files/usr-local-bin-etcd-member-recover-sh.yaml
  templates/master/00-master/_base/files/usr-local-bin-etcd-snapshot-backup-sh.yaml
  templates/master/00-master/_base/files/usr-local-bin-etcd-snapshot-restore-sh.yaml
  templates/master/00-master/_base/files/usr-local-bin-openshift-recovery-tools-sh.yaml
  templates/master/00-master/_base/files/usr-local-bin-tokenize-signer-sh.yaml
  templates/master/00-master/_base/files/usr-local-share-openshift-recovery-template-etcd-generate-certs-yaml-template.yaml
  templates/master/00-master/_base/files/usr-local-share-openshift-recovery-template-kube-etcd-cert-signer-yaml-template.yaml
Labels: approved, lgtm, size/XL

#780 Bug 1711879 : templates/master/00-master: resolve empty var when ETCD_CONNSTRING is not passed
  templates/master/00-master/_base/files/usr-local-bin-etcd-member-recover-sh.yaml
  templates/master/00-master/_base/files/usr-local-bin-openshift-recovery-tools-sh.yaml
Labels: approved, lgtm, size/M

#779 DR start_static_pods: reread a list of static pods when starting them
  templates/master/00-master/_base/files/usr-local-bin-etcd-member-recover-sh.yaml
  templates/master/00-master/_base/files/usr-local-bin-etcd-snapshot-backup-sh.yaml
  templates/master/00-master/_base/files/usr-local-bin-etcd-snapshot-restore-sh.yaml
  templates/master/00-master/_base/files/usr-local-bin-openshift-recovery-tools-sh.yaml
Labels: approved, lgtm, size/XS

#783 templates: Move more files into common/
  templates/common/_base/files/cleanup-cni-conf.yaml
  templates/common/_base/files/root-ca.yaml
  templates/common/_base/files/sysctl-forward-conf.yaml
  templates/common/_base/files/volume-plugins.yaml
  templates/worker/00-worker/_base/files/cleanup-cni-conf.yaml
  templates/worker/00-worker/_base/files/root-ca.yaml
  templates/worker/00-worker/_base/files/sysctl-forward-conf.yaml
  templates/worker/00-worker/_base/files/volume-plugins.yaml
Labels: approved, lgtm, size/S

#781 docs: Add link in the OnceFrom md file to hacking.md
  docs/OnceFrom.md
Labels: approved, kind/documentation, lgtm, ok-to-test, size/S

#787 Kubelet config fixes
  pkg/server/testdata/machine-configs/test-config.yaml
  templates/master/01-master-kubelet/_base/files/kubelet.yaml
  templates/master/01-master-kubelet/_base/units/kubelet.yaml
  templates/master/01-master-kubelet/openstack/units/kubelet.yaml
  templates/worker/01-worker-kubelet/_base/files/kubelet.yaml
  templates/worker/01-worker-kubelet/_base/units/kubelet.yaml
  templates/worker/01-worker-kubelet/openstack/units/kubelet.yaml
Labels: approved, lgtm, size/S

#786 daemon: Explicitly stop kubelet.service first before rebooting
  pkg/daemon/daemon.go
Labels: approved, lgtm, size/XS

#792 kubelet: add script to generate bootstrap recovery kubeconfig
  templates/master/00-master/_base/files/usr-local-bin-openshift-kubeconfig-gen.yaml
Labels: approved, lgtm, size/S

#789 Bug 1712507: etcdquorumguard: Respond correctly to TERM when pod shut down
  install/0000_80_machine-config-operator_07_etcdquorumguard_deployment.yaml
  install/image-references
  test/e2e/etcdquorumguard_test.go
Labels: approved, lgtm, size/M

#793 DR: add validate_environment to openshift-recovery tools
  templates/master/00-master/_base/files/usr-local-bin-etcd-member-recover-sh.yaml
  templates/master/00-master/_base/files/usr-local-bin-etcd-snapshot-restore-sh.yaml
  templates/master/00-master/_base/files/usr-local-bin-openshift-recovery-tools-sh.yaml
Labels: approved, lgtm, size/M

#788 DR: reload systemd services on disk before starting kubelet in etcd restore script
  templates/master/00-master/_base/files/usr-local-bin-openshift-recovery-tools-sh.yaml
Labels: approved, lgtm, size/XS

#762 Add KernelArguments to MachineConfig
  docs/MachineConfiguration.md
  lib/resourcemerge/machineconfig.go
  pkg/apis/machineconfiguration.openshift.io/v1/helpers.go
  pkg/apis/machineconfiguration.openshift.io/v1/types.go
  pkg/daemon/update.go
  pkg/daemon/update_test.go
  test/e2e/mcd_test.go
Labels: approved, lgtm, size/L

#773 Add a Spec.Configuration to MachineConfigPool
  pkg/apis/machineconfiguration.openshift.io/v1/types.go
  pkg/apis/machineconfiguration.openshift.io/v1/zz_generated.deepcopy.go
  pkg/controller/container-runtime-config/container_runtime_config_controller_test.go
  pkg/controller/kubelet-config/kubelet_config_controller_test.go
  pkg/controller/node/node_controller.go
  pkg/controller/node/node_controller_test.go
  pkg/controller/node/status.go
  pkg/controller/node/status_test.go
  pkg/controller/render/render_controller.go
  pkg/controller/render/render_controller_test.go
  pkg/operator/status.go
  pkg/operator/status_test.go
  test/e2e/mcd_test.go
Labels: approved, lgtm, size/M

#799 Make use of /dev/termination-log
  cmd/machine-config-controller/start.go
  cmd/machine-config-daemon/start.go
  cmd/machine-config-server/start.go
  pkg/controller/common/helpers.go
Labels: approved, lgtm, size/S

#802 Docs: Fix dead links in docs (and some typos)
  docs/HACKING.md
  docs/README.md
Labels: approved, lgtm, size/S
