Repository openshift/machine-config-operator, pull requests merged in 2020-12, with the labels that each got.

#2270 docs: Fix broken ostree url
  docs/FAQ.md
  docs/MachineConfigController.md
  docs/MachineConfigDaemon.md
  docs/PullSecret.md
Labels: approved, lgtm, retest-not-required-docs-only

#2263 Bug 1898036: Copy files from NM overlay onto /etc/NetworkManager/system-connections
  templates/common/_base/files/configure-ovs-network.yaml
Labels: approved, bugzilla/severity-urgent, bugzilla/valid-bug, lgtm

#2266 Bug 1873556: [on-prem] inject the proxy into the env for NetworkManager.service
  templates/common/on-prem/files/NetworkManager-resolv-prepender.yaml
Labels: approved, bugzilla/severity-low, bugzilla/valid-bug, lgtm

#2275 [baremetal] Add ipv6 support to static DHCP configuration
  templates/common/baremetal/files/NetworkManager-static-dhcpv6.yaml
Labels: approved, lgtm

#2259 daemon: selectively reboot based on diffs of applied MCs
  pkg/daemon/daemon.go
  pkg/daemon/update.go
  pkg/daemon/update_test.go
  test/e2e/mcd_test.go
  test/e2e/utils_test.go
  test/helpers/helpers.go
Labels: approved, lgtm, team-mco

#2188 [baremetal] Add dispatcher script to statically configure DHCP address
  templates/common/baremetal/files/NetworkManager-static-dhcp.yaml
Labels: approved, lgtm

#2268 Annotate manifests for single-node-developer cluster profile
  install/0000_80_machine-config-operator_00_clusterreader_clusterrole.yaml
  install/0000_80_machine-config-operator_00_namespace.yaml
  install/0000_80_machine-config-operator_00_service.yaml
  install/0000_80_machine-config-operator_01_containerruntimeconfig.crd.yaml
  install/0000_80_machine-config-operator_01_kubeletconfig.crd.yaml
  install/0000_80_machine-config-operator_01_machineconfig.crd.yaml
  install/0000_80_machine-config-operator_01_machineconfigpool.crd.yaml
  install/0000_80_machine-config-operator_02_images.configmap.yaml
  install/0000_80_machine-config-operator_03_rbac.yaml
  install/0000_80_machine-config-operator_04_deployment.yaml
  install/0000_80_machine-config-operator_05_osimageurl.yaml
  install/0000_80_machine-config-operator_06_clusteroperator.yaml
  install/0000_90_machine-config-operator_00_servicemonitor.yaml
  install/0000_90_machine-config-operator_01_prometheus-rules.yaml
Labels: approved, lgtm

#2217 templates: use Afterburn for setting GCP hostnames
  templates/common/_base/files/etc-networkmanager-dispatcher.d-90-long-hostname.yaml
  templates/common/gcp/units/gcp-hostname.service.yaml
Labels: approved, lgtm

#2232 templates: add apiserver-url.env file
  pkg/constants/constants.go
  pkg/controller/container-runtime-config/container_runtime_config_controller_test.go
  pkg/controller/kubelet-config/kubelet_config_controller_test.go
  pkg/controller/template/render.go
  pkg/controller/template/render_test.go
  pkg/controller/template/template_controller_test.go
  pkg/operator/render.go
  templates/master/00-master/_base/files/apiserver-url-env.yaml
Labels: approved, lgtm

#2073 [baremetal and friends] Drop unnecessary readiness probes
  manifests/on-prem/coredns.yaml
  manifests/on-prem/keepalived.yaml
  pkg/operator/assets/bindata.go
  templates/common/on-prem/files/coredns.yaml
  templates/common/on-prem/files/keepalived.yaml
Labels: 4.7, approved, lgtm

#2242 daemon: Rework operating system conditionals
  pkg/daemon/daemon.go
  pkg/daemon/kernelargs.go
  pkg/daemon/osrelease.go
  pkg/daemon/update.go
  pkg/daemon/update_test.go
Labels: approved, lgtm, team-mco

#2276 Create drop in file for ContainerRuntimeSearchRegistries
  pkg/controller/container-runtime-config/container_runtime_config_controller.go
  pkg/controller/container-runtime-config/container_runtime_config_controller_test.go
  pkg/controller/container-runtime-config/helpers.go
Labels: approved, lgtm

#2247 [release-4.5] Bug 1900013: Drop kubelet logging back down to level 3
  templates/master/01-master-kubelet/_base/units/kubelet.yaml
  templates/worker/01-worker-kubelet/_base/units/kubelet.yaml
Labels: approved, bugzilla/severity-urgent, bugzilla/valid-bug, cherry-pick-approved, lgtm

#2282 templates: Set vSphere hostname from guestinfo before NM starts
  templates/common/vsphere/files/vsphere-hostname.yaml
  templates/common/vsphere/units/vsphere-hostname.service.yaml
Labels: approved, lgtm

#2262 Bug 1903290: kubelet: refactor KUBELET_LOG_LEVEL into KubeletConfig field
  docs/KubeletConfigDesign.md
  install/0000_80_machine-config-operator_01_kubeletconfig.crd.yaml
  pkg/apis/machineconfiguration.openshift.io/v1/types.go
  pkg/apis/machineconfiguration.openshift.io/v1/zz_generated.deepcopy.go
  pkg/controller/kubelet-config/helpers.go
  pkg/controller/kubelet-config/kubelet_config_controller.go
  pkg/controller/kubelet-config/kubelet_config_controller_test.go
  templates/common/_base/files/kubelet-log-level.yaml
  templates/master/01-master-kubelet/_base/units/kubelet.service.yaml
  templates/master/01-master-kubelet/on-prem/units/kubelet.service.yaml
  templates/worker/01-worker-kubelet/_base/units/kubelet.service.yaml
  templates/worker/01-worker-kubelet/on-prem/units/kubelet.service.yaml
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, lgtm

#2264 Bug 1899350: Include dhcp client-id and bond options during ovs-configuration
  templates/common/_base/files/configure-ovs-network.yaml
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, lgtm

#2208 operator: allow kube-cloud-config cm with CA data but no cloud config
  pkg/operator/sync.go
Labels: approved, lgtm

#2285 Bug 1904124: [baremetal] Add check for default connection id to static DHCPv6 script
  templates/common/baremetal/files/NetworkManager-static-dhcpv6.yaml
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, lgtm

#2221 Add IBM Cloud managed annotations to CVO manifests
  install/0000_80_machine-config-operator_00_clusterreader_clusterrole.yaml
  install/0000_80_machine-config-operator_00_namespace.yaml
  install/0000_80_machine-config-operator_00_service.yaml
  install/0000_80_machine-config-operator_01_containerruntimeconfig.crd.yaml
  install/0000_80_machine-config-operator_01_kubeletconfig.crd.yaml
  install/0000_80_machine-config-operator_01_machineconfig.crd.yaml
  install/0000_80_machine-config-operator_01_machineconfigpool.crd.yaml
  install/0000_80_machine-config-operator_02_images.configmap.yaml
  install/0000_80_machine-config-operator_03_rbac.yaml
  install/0000_80_machine-config-operator_05_osimageurl.yaml
  install/0000_90_machine-config-operator_01_prometheus-rules.yaml
Labels: approved, lgtm

#2279 Bug 1904065: [on-prem] export proxy variables to be taken in account
  templates/common/baremetal/files/NetworkManager-resolv-prepender.yaml
  templates/common/openstack/files/NetworkManager-resolv-prepender.yaml
  templates/common/ovirt/files/NetworkManager-resolv-prepender.yaml
  templates/common/vsphere/files/NetworkManager-resolv-prepender.yaml
Labels: approved, bugzilla/severity-urgent, bugzilla/valid-bug, cherry-pick-approved, lgtm

#2156 Bug 1886636: update ctrcfg crd to make spec & containerruntimeconfig required
  install/0000_80_machine-config-operator_01_containerruntimeconfig.crd.yaml
  install/0000_80_machine-config-operator_01_kubeletconfig.crd.yaml
Labels: approved, bugzilla/severity-low, bugzilla/valid-bug, lgtm, team-mco

#2291 Bug 1888565: daemon: Explicitly start rpm-ostreed
  pkg/daemon/daemon.go
  pkg/daemon/rpm-ostree.go
  pkg/daemon/rpm-ostree_test.go
  templates/common/_base/units/machine-config-daemon-firstboot.service.yaml
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, lgtm

#2296 Revert "Bug 1888565: daemon: Explicitly start rpm-ostreed"
  pkg/daemon/daemon.go
  pkg/daemon/rpm-ostree.go
  pkg/daemon/rpm-ostree_test.go
  templates/common/_base/units/machine-config-daemon-firstboot.service.yaml
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, lgtm

#2145 Bug 1885365: daemon: properly handle unit enable/disables
  pkg/daemon/constants/constants.go
  pkg/daemon/daemon.go
  pkg/daemon/update.go
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, lgtm, team-mco

#2302 Bug 1907333: daemon: Revert code to remove rollback
  pkg/daemon/daemon.go
  pkg/daemon/update.go
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, lgtm

#1972 Bug 1907671: Handle keepalived hangs in liveness probe
  templates/common/on-prem/files/keepalived.yaml
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, lgtm

#2304 Bug 1880259: Fixes setting route metric for ovs-config
  templates/common/_base/files/configure-ovs-network.yaml
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, lgtm

#2306 Bug 1901376: Fix upgrade issue with DNS controllerconfig field
  lib/resourcemerge/machineconfig.go
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, lgtm

#2305 Bug 1908159: operator: fix error syncing cloud config with CA data but no cloud config
  pkg/operator/sync.go
  pkg/operator/sync_test.go
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, lgtm

#2256 Bug 1908648: [test] Skip TestKernelType on OKD
  test/e2e/mcd_test.go
  test/e2e/utils_test.go
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, lgtm

#2298 [release-4.6] Bug 1899622: backport bond options fixes
  templates/common/_base/files/configure-ovs-network.yaml
Labels: 4.6, approved, bugzilla/severity-high, bugzilla/valid-bug, cherry-pick-approved, lgtm
