Repository openshift/machine-config-operator, pull requests merged in 2020-01, with the labels that each got.

#1346 DR: Cleanup and comment backup and restore scripts
  templates/master/00-master/_base/files/usr-local-bin-etcd-snapshot-backup-sh.yaml
  templates/master/00-master/_base/files/usr-local-bin-etcd-snapshot-restore-sh.yaml
  templates/master/00-master/_base/files/usr-local-bin-openshift-recovery-tools-sh.yaml
Labels: approved, lgtm, size/S

#1194 Bug 1763695: [release-4.2] pkg/daemon: drain before applying changes
  pkg/daemon/daemon.go
  pkg/daemon/update.go
Labels: approved, bugzilla/valid-bug, cherry-pick-approved, lgtm, size/M

#1313 ovirt: Use the DNSVIP for workers
  templates/worker/00-worker/ovirt/files/NetworkManager-non-virtual-ip-prepender.yaml
  templates/worker/00-worker/ovirt/files/dhcp-dhclient-conf.yaml
Labels: approved, lgtm, size/M

#1360 Bug 1787581: cleanup sdn ips on reboot
  templates/common/_base/files/cleanup-cni-conf.yaml
Labels: approved, bugzilla/valid-bug, lgtm, size/XS

#1361 [release-4.3] Bug 1787635: cleanup sdn ips on reboot
  templates/common/_base/files/cleanup-cni-conf.yaml
Labels: approved, bugzilla/valid-bug, cherry-pick-approved, lgtm, size/XS

#1364 hack/build-go.sh: removed not needed eval go env
  hack/build-go.sh
Labels: approved, lgtm, size/XS

#1357 Bug 1789581: Fix osImageURL upgrade race
  install/0000_80_machine-config-operator_00_service.yaml
  install/0000_80_machine-config-operator_05_osimageurl.yaml
  pkg/operator/sync.go
Labels: approved, bugzilla/valid-bug, lgtm, size/XS

#1351 Bug 1785281: Discard audit messages from journald
  pkg/daemon/update.go
Labels: approved, bugzilla/valid-bug, lgtm, size/XS

#1368 build: do not export GOFLAGS
  Makefile
  hack/build-go.sh
Labels: approved, lgtm, size/S

#1369 Bug 1771566: [OpenStack] verify that 'old' HAProxy processes being deleted after HAProxy reload
  templates/master/00-master/openstack/files/openstack-haproxy.yaml
Labels: approved, bugzilla/valid-bug, lgtm, size/S

#1359 Bug 1786993: [release-4.3] Fix osImageURL upgrade race
  install/0000_80_machine-config-operator_00_service.yaml
  install/0000_80_machine-config-operator_05_osimageurl.yaml
  pkg/operator/sync.go
Labels: approved, bugzilla/valid-bug, cherry-pick-approved, lgtm, size/XS

#1358 Bug 1789565: [release-4.2] Fix osImageURL upgrade race
  install/0000_80_machine-config-operator_05_osimageurl.yaml
  pkg/operator/sync.go
Labels: approved, bugzilla/valid-bug, cherry-pick-approved, lgtm, size/XS

#1301 [FCOS] machine-config-daemon service improvements
  templates/common/_base/units/machine-config-daemon-pull.service
Labels: approved, lgtm, size/XS

#1374 [fcos] correct name for network-online.target
  templates/common/_base/units/machine-config-daemon-pull.service
Labels: approved, lgtm, ok-to-test, size/XS

#1370 [FCOS] Update vendor and fix small go mod issue
  hack/update-codegen.sh
  vendor/github.com/Microsoft/hcsshim/mksyscall_windows.go
  vendor/github.com/containers/storage/pkg/archive/example_changes.go
  vendor/github.com/creack/pty/types.go
  vendor/github.com/creack/pty/types_dragonfly.go
  vendor/github.com/creack/pty/types_freebsd.go
  vendor/github.com/creack/pty/types_openbsd.go
  vendor/github.com/docker/docker/profiles/seccomp/generate.go
  vendor/github.com/go-toolsmith/astcast/astcast_generate.go
  vendor/github.com/go-toolsmith/typep/simplePredicates_generate.go
  vendor/github.com/klauspost/compress/flate/gen.go
  vendor/github.com/klauspost/cpuid/private-gen.go
  vendor/github.com/ulikunitz/xz/example.go
  vendor/golang.org/x/sys/unix/mkasm_darwin.go
  vendor/golang.org/x/sys/unix/mkpost.go
  vendor/golang.org/x/sys/unix/mksyscall.go
  vendor/golang.org/x/sys/unix/mksyscall_aix_ppc.go
  vendor/golang.org/x/sys/unix/mksyscall_aix_ppc64.go
  vendor/golang.org/x/sys/unix/mksyscall_solaris.go
  vendor/golang.org/x/sys/unix/mksysctl_openbsd.go
  vendor/golang.org/x/sys/unix/mksysnum.go
  vendor/golang.org/x/sys/unix/types_aix.go
  vendor/golang.org/x/sys/unix/types_darwin.go
  vendor/golang.org/x/sys/unix/types_dragonfly.go
  vendor/golang.org/x/sys/unix/types_freebsd.go
  vendor/golang.org/x/sys/unix/types_netbsd.go
  vendor/golang.org/x/sys/unix/types_openbsd.go
  vendor/golang.org/x/sys/unix/types_solaris.go
  vendor/golang.org/x/text/unicode/bidi/gen.go
  vendor/golang.org/x/text/unicode/bidi/gen_ranges.go
  vendor/golang.org/x/text/unicode/bidi/gen_trieval.go
  vendor/golang.org/x/text/unicode/norm/maketables.go
  vendor/golang.org/x/text/unicode/norm/triegen.go
  vendor/golang.org/x/text/width/gen.go
  vendor/golang.org/x/text/width/gen_common.go
  vendor/golang.org/x/text/width/gen_trieval.go
  vendor/golang.org/x/tools/go/gcexportdata/main.go
  vendor/golang.org/x/tools/internal/imports/mkindex.go
  vendor/golang.org/x/tools/internal/imports/mkstdlib.go
  vendor/k8s.io/code-generator/generate-groups.sh
  vendor/k8s.io/code-generator/generate-internal-groups.sh
  vendor/modules.txt
Labels: approved, lgtm, size/XXL

#1382 Bug 1782153: templates: Add a "this is generated" note
  pkg/controller/template/test_data/templates/master/01-master-container-runtime/aws/files/-etc-containers-storage.conf
  pkg/controller/template/test_data/templates/master/01-master-container-runtime/libvirt/files/-etc-containers-storage.conf
  pkg/controller/template/test_data/templates/master/01-master-container-runtime/none/files/-etc-containers-storage.conf
  pkg/controller/template/test_data/templates/master/01-master-container-runtime/openstack/files/-etc-containers-storage.conf
  pkg/controller/template/test_data/templates/master/01-master-container-runtime/vsphere/files/-etc-containers-storage.conf
  pkg/controller/template/test_data/templates/worker/01-worker-container-runtime/aws/files/-etc-containers-storage.conf
  pkg/controller/template/test_data/templates/worker/01-worker-container-runtime/libvirt/files/-etc-containers-storage.conf
  pkg/controller/template/test_data/templates/worker/01-worker-container-runtime/none/files/-etc-containers-storage.conf
  pkg/controller/template/test_data/templates/worker/01-worker-container-runtime/openstack/files/-etc-containers-storage.conf
  pkg/controller/template/test_data/templates/worker/01-worker-container-runtime/vsphere/files/-etc-containers-storage.conf
  templates/master/01-master-container-runtime/_base/files/container-storage.yaml
  templates/worker/01-worker-container-runtime/_base/files/container-storage.yaml
Labels: approved, bugzilla/valid-bug, cherry-pick-approved, lgtm, size/XS

#1362 Bug 1789248: cleanup sdn ips on reboot
  templates/common/_base/files/cleanup-cni-conf.yaml
Labels: approved, bugzilla/valid-bug, cherry-pick-approved, lgtm, size/XS

#1381 Update kubelet.config for single-stack IPv6
  pkg/apis/machineconfiguration.openshift.io/v1/types.go
  pkg/operator/render.go
  pkg/operator/render_test.go
  templates/master/01-master-kubelet/_base/units/kubelet.yaml
  templates/worker/01-worker-kubelet/_base/units/kubelet.yaml
Labels: approved, lgtm, size/M

#1366 Don't enable machine-config-daemon-host.service by default
  templates/common/_base/units/machine-config-daemon-host.service
Labels: approved, lgtm, size/XS

#1394 HAProxy infra pod: Make v4/v6 compatible
  templates/master/00-master/baremetal/files/baremetal-haproxy-haproxy.yaml
  templates/master/00-master/openstack/files/openstack-haproxy-haproxy.yaml
  templates/master/00-master/ovirt/files/ovirt-haproxy-haproxy.yaml
Labels: approved, lgtm, size/S

#1390 Bug 1793144: kubelet: add log level environment variable
  templates/master/01-master-kubelet/_base/units/kubelet.yaml
  templates/worker/01-worker-kubelet/_base/units/kubelet.yaml
Labels: approved, bugzilla/valid-bug, lgtm, size/XS

#1288 *: conditionally populate the images configmap with cluster-etcd-operator image
  cmd/machine-config-operator/start.go
  install/0000_80_machine-config-operator_02_images.configmap.yaml
  install/image-references
  manifests/machineconfigcontroller/clusterrole.yaml
  pkg/operator/assets/bindata.go
  pkg/operator/operator.go
  pkg/operator/sync.go
Labels: approved, lgtm, size/M

#1376 pkg/server: save the bootstrap MC content
  pkg/server/bootstrap_server.go
  pkg/server/cluster_server.go
  pkg/server/server.go
Labels: approved, lgtm, size/M

#1316 templates: etcd-member: add waitforkube init container
  templates/master/00-master/_base/files/etc-kubernetes-manifests-etcd-member.yaml
Labels: approved, lgtm, size/S

#1330 Add kernelType to MachineConfig
  lib/resourcemerge/machineconfig.go
  manifests/machineconfig.crd.yaml
  pkg/apis/machineconfiguration.openshift.io/v1/helpers.go
  pkg/apis/machineconfiguration.openshift.io/v1/types.go
  pkg/controller/common/helpers.go
  pkg/controller/render/render_controller.go
  pkg/daemon/update.go
  pkg/operator/assets/bindata.go
Labels: approved, lgtm, size/L

#1402 test: fix units to run on osx
  Makefile
  pkg/daemon/update.go
Labels: approved, lgtm, size/XS

#1384 Fix update codegen script to be compatible with go mod vendor
  hack/update-codegen.sh
Labels: approved, lgtm, size/XS

#1396 baremetal: ipv6, switch to NM dispatcher for DNS VIP prepending
  templates/common/baremetal/files/baremetal-NetworkManager-kni-conf.yaml
  templates/master/00-master/baremetal/files/NetworkManager-resolv-prepender.yaml
  templates/master/00-master/baremetal/files/dhcp-dhclient-conf.yaml
  templates/worker/00-worker/baremetal/files/NetworkManager-non-virtual-ip-prepender.yaml
  templates/worker/00-worker/baremetal/files/NetworkManager-resolv-prepender.yaml
  templates/worker/00-worker/baremetal/files/dhcp-dhclient-conf.yaml
Labels: approved, lgtm, size/M

#1397 Bug 1780442: DR: allow use of local etcdctl plus version check
  templates/master/00-master/_base/files/usr-local-bin-openshift-recovery-tools-sh.yaml
Labels: approved, bugzilla/valid-bug, lgtm, size/S

#1398 DR: Backup should keep data and keys separate
  templates/master/00-master/_base/files/usr-local-bin-etcd-snapshot-backup-sh.yaml
  templates/master/00-master/_base/files/usr-local-bin-etcd-snapshot-restore-sh.yaml
  templates/master/00-master/_base/files/usr-local-bin-openshift-recovery-tools-sh.yaml
Labels: approved, lgtm, size/M

#1404 Bug 1792914: prevent hitting annotation max size limit on nodes
  pkg/daemon/node.go
  pkg/daemon/writer.go
Labels: approved, bugzilla/valid-bug, lgtm, size/S

#1388 Bug 1790823: [IPI][BAREMETAL] Verify that mdns-publisher starts after hostname is set
  templates/common/baremetal/files/baremetal-mdns-publisher.yaml
Labels: approved, bugzilla/valid-bug, lgtm, size/S

#1392 OpenStack: Add ca cert to disk on all nodes so kubelet can start up
  cmd/machine-config-operator/bootstrap.go
  lib/resourcemerge/machineconfig.go
  pkg/apis/machineconfiguration.openshift.io/v1/types.go
  pkg/apis/machineconfiguration.openshift.io/v1/zz_generated.deepcopy.go
  pkg/operator/bootstrap.go
  pkg/operator/sync.go
  templates/common/_base/files/cloud-provider-ca.yaml
Labels: approved, lgtm, size/M

#1395 baremetal: IPv6 add dhcp-duid to NetworkManager config
  templates/common/baremetal/files/baremetal-NetworkManager-kni-conf.yaml
Labels: approved, lgtm, size/XS

#1407 test/e2e - Add e2e test for Realtime Kernel
  test/e2e/mcd_test.go
Labels: approved, lgtm, size/M

#1044 Remove unused internal MCOConfig types and CRD
  install/0000_80_machine-config-operator_00_clusterreader_clusterrole.yaml
  install/0000_80_machine-config-operator_01_mcoconfig.crd.yaml
  pkg/apis/machineconfiguration.openshift.io/v1/register.go
  pkg/apis/machineconfiguration.openshift.io/v1/types.go
  pkg/apis/machineconfiguration.openshift.io/v1/zz_generated.deepcopy.go
  pkg/generated/clientset/versioned/typed/machineconfiguration.openshift.io/v1/fake/fake_machineconfiguration.openshift.io_client.go
  pkg/generated/clientset/versioned/typed/machineconfiguration.openshift.io/v1/fake/fake_mcoconfig.go
  pkg/generated/clientset/versioned/typed/machineconfiguration.openshift.io/v1/generated_expansion.go
  pkg/generated/clientset/versioned/typed/machineconfiguration.openshift.io/v1/machineconfiguration.openshift.io_client.go
  pkg/generated/clientset/versioned/typed/machineconfiguration.openshift.io/v1/mcoconfig.go
  pkg/generated/informers/externalversions/generic.go
  pkg/generated/informers/externalversions/machineconfiguration.openshift.io/v1/interface.go
  pkg/generated/informers/externalversions/machineconfiguration.openshift.io/v1/mcoconfig.go
  pkg/generated/listers/machineconfiguration.openshift.io/v1/expansion_generated.go
  pkg/generated/listers/machineconfiguration.openshift.io/v1/mcoconfig.go
Labels: approved, lgtm, size/XL

#1408 setup-etcd-environment/run.go: fix upgrade path
  cmd/setup-etcd-environment/run.go
Labels: approved, lgtm, size/XS

#1373 Add vSphere IPI
  install/0000_80_machine-config-operator_00_namespace.yaml
  manifests/vsphere/coredns-corefile.tmpl
  manifests/vsphere/coredns.yaml
  manifests/vsphere/keepalived.conf.tmpl
  manifests/vsphere/keepalived.yaml
  pkg/controller/template/test_data/controller_config_vsphere.yaml
  pkg/operator/assets/bindata.go
  pkg/operator/bootstrap.go
  templates/common/vsphere/files/vsphere-NetworkManager-kni-conf.yaml
  templates/common/vsphere/files/vsphere-coredns-corefile.yaml
  templates/common/vsphere/files/vsphere-coredns-db.yaml
  templates/common/vsphere/files/vsphere-coredns.yaml
  templates/common/vsphere/files/vsphere-keepalived.yaml
  templates/common/vsphere/files/vsphere-mdns-publisher.yaml
  templates/master/00-master/vsphere/files/dhcp-dhclient-conf.yaml
  templates/master/00-master/vsphere/files/vsphere-haproxy-haproxy.yaml
  templates/master/00-master/vsphere/files/vsphere-haproxy.yaml
  templates/master/00-master/vsphere/files/vsphere-keepalived-keepalived.yaml
  templates/master/00-master/vsphere/files/vsphere-mdns-config.yaml
  templates/worker/00-worker/vsphere/files/dhcp-dhclient-conf.yaml
  templates/worker/00-worker/vsphere/files/vsphere-keepalived-keepalived.yaml
  templates/worker/00-worker/vsphere/files/vsphere-mdns-config.yaml
  templates/worker/00-worker/vsphere/files/vsphere-non-virtual-ip.yaml
Labels: approved, lgtm, size/XXL

#1409 docs: Add docs for kernelType
  docs/MachineConfiguration.md
Labels: approved, lgtm, retest-not-required-docs-only, size/S

#1415 [fcos] Cherry-pick commits to enable cluster-etcd-operator
  cmd/machine-config-operator/start.go
  cmd/setup-etcd-environment/run.go
  install/0000_80_machine-config-operator_02_images.configmap.yaml
  install/image-references
  manifests/machineconfigcontroller/clusterrole.yaml
  pkg/operator/assets/bindata.go
  pkg/operator/operator.go
  pkg/operator/sync.go
  templates/master/00-master/_base/files/etc-kubernetes-manifests-etcd-member.yaml
Labels: approved, lgtm, size/L

#1412 test/e2e: Add rollback test for kernelType
  test/e2e/mcd_test.go
Labels: approved, lgtm, size/M

#1419 Bug 1796148: baremetal: Remove .template from path in dhcp-dhclient-conf.yaml
  templates/worker/00-worker/baremetal/files/dhcp-dhclient-conf.yaml
Labels: approved, bugzilla/valid-bug, lgtm, size/XS

#1421 Bug 1796147: pkg/server: serve config only to master in bootstrap server
  pkg/server/bootstrap_server.go
  pkg/server/server_test.go
  pkg/server/testdata/machine-pools/master.yaml
Labels: approved, bugzilla/valid-bug, lgtm, size/M

#1417 Bug 1796444: gcp: use readyz endpoint
  templates/master/00-master/gcp/files/etc-kubernetes-manifests-gcp-routes-controller.yaml
Labels: approved, bugzilla/valid-bug, lgtm, size/XS

#1356 Bug 1787907: use the machine config uid for the kubeletconfig finalizer name
  pkg/controller/kubelet-config/kubelet_config_controller.go
Labels: approved, bugzilla/valid-bug, lgtm, size/S

#1292 Bug 1777379: [Baremetal] add CPU and memory resources for Haproxy pod
  templates/master/00-master/baremetal/files/baremetal-haproxy.yaml
Labels: approved, bugzilla/valid-bug, lgtm, size/XS
