Repository openshift/machine-config-operator, pull requests merged in 2020-11, with the labels that each got.

#2017 [baremetal] Create and enable overlay mount point for NetworkManager
  templates/common/baremetal/files/baremetal-NetworkManager-kni-conf.yaml
  templates/common/baremetal/files/baremetal-kni-tmpfiles.yaml
  templates/common/baremetal/units/baremetal-system-connections-mount.yaml
Labels: approved, lgtm

#2177 crio: drop infra container when possible
  templates/master/01-master-container-runtime/_base/files/crio.yaml
  templates/worker/01-worker-container-runtime/_base/files/crio.yaml
Labels: approved, lgtm

#2183 templates/master/00-master/_base/files: remove etcd-root-ca
  templates/master/00-master/_base/files/etcd-root-ca.yaml
Labels: approved, lgtm

#2197 Bump to the latest Ignition 2.7.0
  go.mod
  go.sum
  vendor/github.com/coreos/ignition/v2/config/shared/errors/errors.go
  vendor/github.com/coreos/ignition/v2/config/v3_0/types/directory.go
  vendor/github.com/coreos/ignition/v2/config/v3_0/types/file.go
  vendor/github.com/coreos/ignition/v2/config/v3_0/types/node.go
  vendor/github.com/coreos/ignition/v2/config/v3_0/types/storage.go
  vendor/github.com/coreos/ignition/v2/config/v3_1/types/directory.go
  vendor/github.com/coreos/ignition/v2/config/v3_1/types/file.go
  vendor/github.com/coreos/ignition/v2/config/v3_1/types/node.go
  vendor/github.com/coreos/ignition/v2/config/v3_1/types/storage.go
  vendor/github.com/golang/mock/gomock/call.go
  vendor/github.com/golang/mock/gomock/callset.go
  vendor/github.com/golang/mock/gomock/controller.go
  vendor/github.com/golang/mock/gomock/matchers.go
  vendor/github.com/google/go-cmp/cmp/compare.go
  vendor/github.com/google/go-cmp/cmp/report_compare.go
  vendor/github.com/google/go-cmp/cmp/report_reflect.go
  vendor/github.com/google/go-cmp/cmp/report_slices.go
  vendor/golang.org/x/oauth2/README.md
  vendor/google.golang.org/appengine/internal/api.go
  vendor/modules.txt
Labels: approved, lgtm

#2203 FAQ: add entry about RHEL worker nodes
  docs/FAQ.md
Labels: approved, lgtm, retest-not-required-docs-only

#2204 Revert "crio: drop infra container when possible"
  templates/master/01-master-container-runtime/_base/files/crio.yaml
  templates/worker/01-worker-container-runtime/_base/files/crio.yaml
Labels: approved, lgtm

#2201 owners: Add mdbooth to approvers
  OWNERS_ALIASES
Labels: approved, lgtm

#2035 Bug 1873288: server: Target the spec configuration if we have at least one node
  pkg/server/cluster_server.go
Labels: 4.7, approved, bugzilla/severity-high, bugzilla/valid-bug, lgtm

#2137 Bug 1890797: Set NonVirtualIP in mdns plugin config
  manifests/openstack/coredns-corefile.tmpl
  manifests/ovirt/coredns-corefile.tmpl
  manifests/vsphere/coredns-corefile.tmpl
  pkg/operator/assets/bindata.go
  templates/common/openstack/files/openstack-coredns-corefile.yaml
  templates/common/ovirt/files/ovirt-coredns-corefile.yaml
  templates/common/vsphere/files/vsphere-coredns-corefile.yaml
Labels: 4.5, approved, bugzilla/severity-high, bugzilla/valid-bug, cherry-pick-approved, lgtm

#2174 Bug 1887596: Fix ovs-configuration detecting bond and vlan interfaces
  templates/common/_base/files/configure-ovs-network.yaml
Labels: 4.6, approved, bugzilla/severity-urgent, bugzilla/valid-bug, cherry-pick-approved, lgtm

#2211 Bug 1895385: Drop kubelet logging back down to level 3
  templates/master/01-master-kubelet/_base/units/kubelet.service.yaml
  templates/worker/01-worker-kubelet/_base/units/kubelet.service.yaml
Labels: approved, bugzilla/severity-urgent, bugzilla/valid-bug, lgtm

#2199 Bug 1894477: Fix bash in nodeip-configuration.service
  templates/common/_base/units/nodeip-configuration.service.yaml
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, lgtm

#2187 Bug 1888853: daemon: allow an extension to install group of packages
  pkg/daemon/update.go
  test/e2e/mcd_test.go
Labels: 4.6, approved, bugzilla/severity-high, bugzilla/valid-bug, cherry-pick-approved, lgtm

#2228 Bug 1896898: Fix awk syntax in configure-ovs.sh
  templates/common/_base/files/configure-ovs-network.yaml
Labels: approved, bugzilla/severity-urgent, bugzilla/valid-bug, lgtm

#2207 Bug 1895099: Fix VSphere UPI not populating PlatformStatus
  pkg/controller/template/render.go
  templates/common/on-prem/files/NetworkManager-mdns-hostname.yaml
  templates/common/on-prem/files/NetworkManager-onprem.conf.yaml
  templates/common/on-prem/files/NetworkManager-resolv-prepender.yaml
  templates/common/on-prem/files/coredns.yaml
  templates/common/on-prem/files/keepalived.yaml
  templates/common/on-prem/files/mdns-publisher.yaml
  templates/common/on-prem/units/nodeip-configuration.service.yaml
  templates/common/vsphere/files/etc-systemd-system-crio-stream-address.conf.yaml
  templates/master/00-master/on-prem/files/haproxy.yaml
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, lgtm

#2209 Move some deduped templates back to where they belong
  templates/common/on-prem/files/kni-tmpfiles.yaml
  templates/common/openstack/units/afterburn-hostname.service.yaml
Labels: approved, lgtm

#2219 FAQ: Add a "debugging node join" section
  docs/FAQ.md
Labels: approved, lgtm, retest-not-required-docs-only, team-mco

#2229 Bug 1897361: ctrcfg_test: Wait for our prior target config
  test/e2e/ctrcfg_test.go
  test/e2e/utils_test.go
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, lgtm, team-mco

#1981 controller: cleanup: Remove unnecessary patch methods
  pkg/controller/container-runtime-config/container_runtime_config_controller.go
  pkg/controller/container-runtime-config/container_runtime_config_controller_test.go
  pkg/controller/kubelet-config/kubelet_config_controller.go
  pkg/controller/kubelet-config/kubelet_config_controller_test.go
Labels: approved, lgtm

#2220 daemon: Remove rollback deployment
  pkg/daemon/daemon.go
  pkg/daemon/update.go
Labels: approved, lgtm, team-mco

#2104 Fix CRIO PidsLimit json tag
  pkg/controller/container-runtime-config/helpers.go
Labels: 4.7, approved, lgtm, ok-to-test

#2087 templates: Disable SSH keys lookup from authorized_keys.d on FCOS
  templates/common/_base/files/sshd-disable-ssh-key-dir.yaml
Labels: approved, lgtm

#2196 Bug 1895360: pkg/daemon: don't delete a file if its replaced with a dropin
  pkg/daemon/update.go
  pkg/daemon/update_test.go
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, lgtm

#2244 [release-4.6] Bug 1896329: Drop kubelet logging back down to level 3
  templates/master/01-master-kubelet/_base/units/kubelet.service.yaml
  templates/worker/01-worker-kubelet/_base/units/kubelet.service.yaml
Labels: 4.6, approved, bugzilla/severity-urgent, bugzilla/valid-bug, cherry-pick-approved, lgtm

#2098 Add kubevirt platform
  go.mod
  go.sum
  manifests/controllerconfig.crd.yaml
  pkg/controller/template/render.go
  pkg/controller/template/render_test.go
  pkg/controller/template/test_data/controller_config_kubevirt.yaml
  pkg/operator/assets/bindata.go
  pkg/operator/bootstrap.go
  pkg/operator/render.go
  templates/common/kubevirt/files/kubevirt-coredns-db.yaml
  vendor/github.com/openshift/api/config/v1/0000_00_cluster-version-operator_01_clusteroperator.crd.yaml
  vendor/github.com/openshift/api/config/v1/0000_00_cluster-version-operator_01_clusterversion.crd.yaml
  vendor/github.com/openshift/api/config/v1/0000_10_config-operator_01_infrastructure.crd.yaml
  vendor/github.com/openshift/api/config/v1/0000_10_config-operator_01_ingress.crd.yaml
  vendor/github.com/openshift/api/config/v1/types_cluster_operator.go
  vendor/github.com/openshift/api/config/v1/types_infrastructure.go
  vendor/github.com/openshift/api/config/v1/types_ingress.go
  vendor/github.com/openshift/api/config/v1/zz_generated.deepcopy.go
  vendor/github.com/openshift/api/config/v1/zz_generated.swagger_doc_generated.go
  vendor/github.com/openshift/api/operator/v1/0000_10_config-operator_01_config.crd.yaml
  vendor/github.com/openshift/api/operator/v1/0000_12_etcd-operator_01_config.crd.yaml
  vendor/github.com/openshift/api/operator/v1/0000_20_kube-apiserver-operator_01_config.crd.yaml
  vendor/github.com/openshift/api/operator/v1/0000_25_kube-controller-manager-operator_01_config.crd.yaml
  vendor/github.com/openshift/api/operator/v1/0000_25_kube-scheduler-operator_01_config.crd.yaml
  vendor/github.com/openshift/api/operator/v1/0000_30_openshift-apiserver-operator_01_config.crd.yaml
  vendor/github.com/openshift/api/operator/v1/0000_40_cloud-credential-operator_00_config.crd.yaml
  vendor/github.com/openshift/api/operator/v1/0000_40_kube-storage-version-migrator-operator_00_config.crd.yaml
  vendor/github.com/openshift/api/operator/v1/0000_50_cluster-authentication-operator_01_config.crd.yaml
  vendor/github.com/openshift/api/operator/v1/0000_50_cluster-openshift-controller-manager-operator_02_config.crd.yaml
  vendor/github.com/openshift/api/operator/v1/0000_50_cluster_storage_operator_01_crd.yaml
  vendor/github.com/openshift/api/operator/v1/0000_50_ingress-operator_00-ingresscontroller.crd.yaml
  vendor/github.com/openshift/api/operator/v1/0000_50_service-ca-operator_02_crd.yaml
  vendor/github.com/openshift/api/operator/v1/0000_70_cluster-network-operator_01_crd.yaml
  vendor/github.com/openshift/api/operator/v1/0000_70_console-operator.crd.yaml
  vendor/github.com/openshift/api/operator/v1/0000_80_csi_snapshot_controller_operator_01_crd.yaml
  vendor/github.com/openshift/api/operator/v1/0000_90_cluster_csi_driver_01_config.crd.yaml
  vendor/github.com/openshift/api/operator/v1/0000_90_cluster_csi_driver_01_config.crd.yaml-patch
  vendor/github.com/openshift/api/operator/v1/types.go
  vendor/github.com/openshift/api/operator/v1/types_csi_cluster_driver.go
  vendor/github.com/openshift/api/operator/v1/types_network.go
  vendor/github.com/openshift/api/operator/v1/zz_generated.swagger_doc_generated.go
  vendor/k8s.io/code-generator/generate-groups.sh
  vendor/k8s.io/code-generator/generate-internal-groups.sh
  vendor/modules.txt
Labels: approved, lgtm

#2136 Bug 1880259: ovs-configuration: use NM default ethernet route metric
  templates/common/_base/files/configure-ovs-network.yaml
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, lgtm

#2234 [on-prem] Move MDNS config file to common directory
  templates/common/on-prem/files/mdns-config.yaml
  templates/worker/00-worker/on-prem/files/mdns-config.yaml
Labels: approved, lgtm

#2241 Bug 1899603: daemon: do not roll back on non-*COS machines
  pkg/daemon/update.go
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, lgtm, team-mco

#2200 [release-4.6] Bug 1894483: Fix bash in nodeip-configuration.service
  templates/common/_base/units/nodeip-configuration.service.yaml
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, cherry-pick-approved, lgtm

#2243 Bug 1899600: daemon: Only switch to bfq scheduler when we have an OS update
  pkg/daemon/controlplane.go
  pkg/daemon/update.go
Labels: approved, bugzilla/severity-urgent, bugzilla/valid-bug, lgtm, team-mco

#2253 Bump openshift/api and openshift/client-go
  go.mod
  go.sum
  vendor/github.com/openshift/api/config/v1/0000_03_config-operator_01_operatorhub.crd.yaml
  vendor/github.com/openshift/api/config/v1/0000_03_config-operator_01_proxy.crd.yaml
  vendor/github.com/openshift/api/config/v1/0000_10_config-operator_01_apiserver.crd.yaml
  vendor/github.com/openshift/api/config/v1/0000_10_config-operator_01_authentication.crd.yaml
  vendor/github.com/openshift/api/config/v1/0000_10_config-operator_01_build.crd.yaml
  vendor/github.com/openshift/api/config/v1/0000_10_config-operator_01_console.crd.yaml
  vendor/github.com/openshift/api/config/v1/0000_10_config-operator_01_dns.crd.yaml
  vendor/github.com/openshift/api/config/v1/0000_10_config-operator_01_featuregate.crd.yaml
  vendor/github.com/openshift/api/config/v1/0000_10_config-operator_01_image.crd.yaml
  vendor/github.com/openshift/api/config/v1/0000_10_config-operator_01_infrastructure.crd.yaml
  vendor/github.com/openshift/api/config/v1/0000_10_config-operator_01_ingress.crd.yaml
  vendor/github.com/openshift/api/config/v1/0000_10_config-operator_01_network.crd.yaml
  vendor/github.com/openshift/api/config/v1/0000_10_config-operator_01_oauth.crd.yaml
  vendor/github.com/openshift/api/config/v1/0000_10_config-operator_01_project.crd.yaml
  vendor/github.com/openshift/api/config/v1/0000_10_config-operator_01_scheduler.crd.yaml
  vendor/github.com/openshift/api/config/v1/types_image.go
  vendor/github.com/openshift/api/config/v1/types_scheduling.go
  vendor/github.com/openshift/api/config/v1/zz_generated.deepcopy.go
  vendor/github.com/openshift/api/config/v1/zz_generated.swagger_doc_generated.go
  vendor/github.com/openshift/api/operator/v1/0000_10_config-operator_01_config.crd.yaml
  vendor/github.com/openshift/api/operator/v1/0000_12_etcd-operator_01_config.crd.yaml
  vendor/github.com/openshift/api/operator/v1/0000_20_kube-apiserver-operator_01_config.crd.yaml
  vendor/github.com/openshift/api/operator/v1/0000_25_kube-controller-manager-operator_01_config.crd.yaml
  vendor/github.com/openshift/api/operator/v1/0000_25_kube-scheduler-operator_01_config.crd.yaml
  vendor/github.com/openshift/api/operator/v1/0000_30_openshift-apiserver-operator_01_config.crd.yaml
  vendor/github.com/openshift/api/operator/v1/0000_40_kube-storage-version-migrator-operator_00_config.crd.yaml
  vendor/github.com/openshift/api/operator/v1/0000_50_cluster-openshift-controller-manager-operator_02_config.crd.yaml
  vendor/github.com/openshift/api/operator/v1/0000_50_cluster_storage_operator_01_crd.yaml
  vendor/github.com/openshift/api/operator/v1/0000_50_ingress-operator_00-ingresscontroller.crd.yaml
  vendor/github.com/openshift/api/operator/v1/0000_50_service-ca-operator_02_crd.yaml
  vendor/github.com/openshift/api/operator/v1/0000_70_cluster-network-operator_01_crd.yaml
  vendor/github.com/openshift/api/operator/v1/0000_70_console-operator.crd.yaml
  vendor/github.com/openshift/api/operator/v1/0000_70_dns-operator_00-custom-resource-definition.yaml
  vendor/github.com/openshift/api/operator/v1/0000_80_csi_snapshot_controller_operator_01_crd.yaml
  vendor/github.com/openshift/api/operator/v1/0000_90_cluster_csi_driver_01_config.crd.yaml
  vendor/github.com/openshift/api/operator/v1/0000_90_cluster_csi_driver_01_config.crd.yaml-patch
  vendor/github.com/openshift/api/operator/v1/types_csi_cluster_driver.go
  vendor/github.com/openshift/api/operator/v1/types_ingress.go
  vendor/github.com/openshift/api/operator/v1/types_network.go
  vendor/github.com/openshift/api/operator/v1/zz_generated.deepcopy.go
  vendor/github.com/openshift/api/operator/v1/zz_generated.swagger_doc_generated.go
  vendor/github.com/openshift/api/operator/v1alpha1/0000_10_config-operator_01_imagecontentsourcepolicy.crd.yaml
  vendor/k8s.io/code-generator/generate-groups.sh
  vendor/k8s.io/code-generator/generate-internal-groups.sh
  vendor/modules.txt
Labels: approved, lgtm

#2206 Bug 1879099: Inject version into controllerconfig, refuse mismatches
  manifests/machineconfigcontroller/controllerconfig.yaml
  pkg/controller/bootstrap/testdata/bootstrap/machineconfigcontroller-controllerconfig.yaml
  pkg/controller/render/render_controller.go
  pkg/controller/render/render_controller_test.go
  pkg/daemon/constants/constants.go
  pkg/operator/assets/bindata.go
  pkg/operator/sync.go
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, lgtm, team-mco

#2231 operator: prevent upgrades on degraded pools
  pkg/operator/status.go
  pkg/operator/sync.go
Labels: approved, lgtm, team-mco

#2255 Bug 1901472: Only enable unicast mode on platform that asked for it
  manifests/on-prem/keepalived.yaml
  pkg/operator/assets/bindata.go
  pkg/operator/render.go
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, lgtm
