Repository openshift/machine-config-operator, pull requests merged in 2020-06, with the labels that each got.

#1699 docs: fix ssh machineconfigs to include ignition version
  docs/Update-SSHKeys.md
Labels: approved, lgtm

#1774 Add OpenStack reviewers
  OWNERS_ALIASES
  templates/common/openstack/OWNERS
  templates/master/00-master/openstack/OWNERS
  templates/master/01-master-container-runtime/openstack/OWNERS
  templates/master/01-master-kubelet/openstack/OWNERS
  templates/worker/00-worker/openstack/OWNERS
  templates/worker/01-worker-container-runtime/openstack/OWNERS
  templates/worker/01-worker-kubelet/openstack/OWNERS
Labels: approved, lgtm

#1666 Bug 1841066: OpenStack: Remove DNS VIP
  manifests/openstack/coredns.yaml
  manifests/openstack/keepalived.conf.tmpl
  manifests/openstack/keepalived.yaml
  pkg/operator/assets/bindata.go
  templates/common/openstack/files/openstack-coredns.yaml
  templates/common/openstack/files/openstack-keepalived.yaml
  templates/common/openstack/files/openstack-mdns-publisher.yaml
  templates/master/00-master/openstack/files/NetworkManager-resolv-prepender.yaml
  templates/master/00-master/openstack/files/openstack-keepalived-keepalived.yaml
  templates/worker/00-worker/openstack/files/NetworkManager-resolv-prepender.yaml
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, lgtm

#1729 pkg/daemon: Add IgnitionVersion to Daemon
  pkg/daemon/daemon.go
Labels: approved, lgtm

#1775 Bug 1843010: Remove dns vip
  manifests/ovirt/coredns.yaml
  manifests/ovirt/keepalived.conf.tmpl
  manifests/ovirt/keepalived.yaml
  pkg/operator/assets/bindata.go
  templates/common/ovirt/files/NetworkManager-resolv-prepender.yaml
  templates/common/ovirt/files/ovirt-coredns.yaml
  templates/common/ovirt/files/ovirt-keepalived.yaml
  templates/common/ovirt/files/ovirt-mdns-publisher.yaml
  templates/master/00-master/ovirt/files/dhcp-dhclient-conf.yaml
  templates/master/00-master/ovirt/files/ovirt-keepalived-keepalived.yaml
  templates/worker/00-worker/ovirt/files/dhcp-dhclient-conf.yaml
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, lgtm

#1777 HACKING.md: Note that the machine-os-content must be digested
  docs/HACKING.md
Labels: approved, lgtm

#1518 Make sure corev1 schema is registered
  cmd/common/helpers.go
Labels: approved, lgtm, ok-to-test, size/XS

#1752 [release-4.3] Bug 1840300: kubelet: add log level environment variable
  templates/master/01-master-kubelet/_base/units/kubelet.yaml
  templates/worker/01-worker-kubelet/_base/units/kubelet.yaml
Labels: approved, bugzilla/severity-low, bugzilla/valid-bug, cherry-pick-approved, lgtm

#1753 [release-4.2] Bug 1840461: Update the crio.conf template to have log_dir
  templates/master/01-master-container-runtime/_base/files/crio.yaml
  templates/worker/01-worker-container-runtime/_base/files/crio.yaml
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, cherry-pick-approved, lgtm

#1705 mcs: Log User-Agent
  pkg/server/api.go
Labels: approved, lgtm

#1760 Bug 1780318: MCD: tolerate all taints
  manifests/machineconfigdaemon/daemonset.yaml
  pkg/operator/assets/bindata.go
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, lgtm

#1769 Bug 1834194: vsphere: 4.1 to 4.4 upgrade bug
  templates/common/vsphere/files/vsphere-NetworkManager-kni-conf.yaml
  templates/common/vsphere/files/vsphere-coredns-corefile.yaml
  templates/common/vsphere/files/vsphere-coredns-db.yaml
  templates/common/vsphere/files/vsphere-coredns.yaml
  templates/common/vsphere/files/vsphere-keepalived.yaml
  templates/common/vsphere/files/vsphere-mdns-publisher.yaml
  templates/master/00-master/vsphere/files/dhcp-dhclient-conf.yaml
  templates/master/00-master/vsphere/files/vsphere-haproxy-haproxy.yaml
  templates/master/00-master/vsphere/files/vsphere-haproxy.yaml
  templates/master/00-master/vsphere/files/vsphere-keepalived-keepalived.yaml
  templates/master/00-master/vsphere/files/vsphere-mdns-config.yaml
  templates/worker/00-worker/vsphere/files/dhcp-dhclient-conf.yaml
  templates/worker/00-worker/vsphere/files/vsphere-keepalived-keepalived.yaml
  templates/worker/00-worker/vsphere/files/vsphere-mdns-config.yaml
  templates/worker/00-worker/vsphere/files/vsphere-non-virtual-ip.yaml
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, cherry-pick-approved, lgtm

#1675 Deprecate EtcdDiscoveryDomain field on ControllerConfig CRD
  manifests/baremetal/coredns-corefile.tmpl
  manifests/controllerconfig.crd.yaml
  manifests/openstack/coredns-corefile.tmpl
  manifests/ovirt/coredns-corefile.tmpl
  manifests/vsphere/coredns-corefile.tmpl
  pkg/apis/machineconfiguration.openshift.io/v1/types.go
  pkg/controller/bootstrap/testdata/bootstrap/machineconfigcontroller-controllerconfig.yaml
  pkg/controller/container-runtime-config/container_runtime_config_controller_test.go
  pkg/controller/kubelet-config/kubelet_config_controller_test.go
  pkg/controller/render/render_controller_test.go
  pkg/controller/template/render.go
  pkg/controller/template/render_test.go
  pkg/controller/template/template_controller_test.go
  pkg/controller/template/test_data/controller_config_aws.yaml
  pkg/controller/template/test_data/controller_config_baremetal.yaml
  pkg/controller/template/test_data/controller_config_gcp.yaml
  pkg/controller/template/test_data/controller_config_libvirt.yaml
  pkg/controller/template/test_data/controller_config_none.yaml
  pkg/controller/template/test_data/controller_config_openstack.yaml
  pkg/controller/template/test_data/controller_config_ovirt.yaml
  pkg/controller/template/test_data/controller_config_vsphere.yaml
  pkg/operator/assets/bindata.go
  pkg/operator/render.go
  pkg/operator/render_test.go
  templates/common/baremetal/files/NetworkManager-resolv-prepender.yaml
  templates/common/baremetal/files/baremetal-coredns-corefile.yaml
  templates/common/openstack/files/openstack-coredns-corefile.yaml
  templates/common/openstack/files/openstack-coredns-db.yaml
  templates/common/ovirt/files/ovirt-coredns-corefile.yaml
  templates/common/ovirt/files/ovirt-coredns-db.yaml
  templates/common/vsphere/files/vsphere-coredns-corefile.yaml
  templates/master/00-master/baremetal/files/dhcp-dhclient-conf.yaml
  templates/master/00-master/openstack/files/NetworkManager-resolv-prepender.yaml
  templates/master/00-master/openstack/files/dhcp-dhclient-conf.yaml
  templates/master/00-master/ovirt/files/dhcp-dhclient-conf.yaml
  templates/master/00-master/vsphere/files/dhcp-dhclient-conf.yaml
  templates/worker/00-worker/baremetal/files/dhcp-dhclient-conf.yaml
  templates/worker/00-worker/openstack/files/NetworkManager-resolv-prepender.yaml
  templates/worker/00-worker/openstack/files/dhcp-dhclient-conf.yaml
  templates/worker/00-worker/ovirt/files/dhcp-dhclient-conf.yaml
  templates/worker/00-worker/vsphere/files/dhcp-dhclient-conf.yaml
Labels: approved, lgtm

#1772 Bug 1842952: vsphere templates check if Infra is nil
  templates/common/vsphere/files/NetworkManager-mdns-hostname.yaml
  templates/common/vsphere/files/etc-systemd-system-crio-stream-address.conf.yaml
  templates/common/vsphere/files/vsphere-NetworkManager-kni-conf.yaml
  templates/common/vsphere/files/vsphere-coredns-corefile.yaml
  templates/common/vsphere/files/vsphere-coredns.yaml
  templates/common/vsphere/files/vsphere-hostname.yaml
  templates/common/vsphere/files/vsphere-keepalived.yaml
  templates/common/vsphere/files/vsphere-mdns-publisher.yaml
  templates/common/vsphere/units/nodeip-configuration.service.yaml
  templates/common/vsphere/units/vsphere-hostname.service.yaml
  templates/master/00-master/vsphere/files/NetworkManager-resolv-prepender.yaml
  templates/master/00-master/vsphere/files/dhcp-dhclient-conf.yaml
  templates/master/00-master/vsphere/files/vsphere-haproxy-haproxy.yaml
  templates/master/00-master/vsphere/files/vsphere-haproxy.yaml
  templates/master/00-master/vsphere/files/vsphere-keepalived-keepalived.yaml
  templates/master/00-master/vsphere/files/vsphere-mdns-config.yaml
  templates/master/01-master-kubelet/vsphere/units/kubelet.service.yaml
  templates/worker/00-worker/vsphere/files/NetworkManager-resolv-prepender.yaml
  templates/worker/00-worker/vsphere/files/dhcp-dhclient-conf.yaml
  templates/worker/00-worker/vsphere/files/vsphere-keepalived-keepalived.yaml
  templates/worker/00-worker/vsphere/files/vsphere-mdns-config.yaml
  templates/worker/01-worker-kubelet/vsphere/units/kubelet.service.yaml
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, lgtm

#1776 Bug 1823967: Set the pod-infra-container-image flag in kubelet to ocp pause image
  templates/master/01-master-kubelet/_base/units/kubelet.service.yaml
  templates/worker/01-worker-kubelet/_base/units/kubelet.service.yaml
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, lgtm

#1785 Bug 1844387: Fail healthz/readyz curls on non-200 http errors
  templates/master/00-master/baremetal/files/baremetal-keepalived-keepalived.yaml
  templates/master/00-master/openstack/files/openstack-keepalived-keepalived.yaml
  templates/master/00-master/ovirt/files/ovirt-keepalived-keepalived.yaml
  templates/master/00-master/vsphere/files/vsphere-keepalived-keepalived.yaml
  templates/worker/00-worker/baremetal/files/baremetal-keepalived-keepalived.yaml
  templates/worker/00-worker/openstack/files/openstack-keepalived-keepalived.yaml
  templates/worker/00-worker/ovirt/files/ovirt-keepalived-keepalived.yaml
  templates/worker/00-worker/vsphere/files/vsphere-keepalived-keepalived.yaml
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, lgtm

#1779 pkg/operator: collect all needed resources
  install/0000_80_machine-config-operator_06_clusteroperator.yaml
  pkg/operator/status.go
Labels: approved, lgtm

#1790 daemon: Also dump systemd failed units on start
  pkg/daemon/daemon.go
Labels: approved, lgtm

#1781 Bug 1843974: daemon: fix restoring file logic to avoid unnecessary deletion
  pkg/daemon/update.go
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, lgtm

#1797 Bug 1829923: Fix quorum-guard timeouts
  install/0000_80_machine-config-operator_07_etcdquorumguard_deployment.yaml
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, lgtm

#1556 etcd: remove etcd entries from mdns
  templates/master/00-master/baremetal/files/baremetal-mdns-config.yaml
  templates/master/00-master/openstack/files/openstack-mdns-config.yaml
  templates/master/00-master/ovirt/files/ovirt-mdns-config.yaml
  templates/master/00-master/vsphere/files/vsphere-mdns-config.yaml
Labels: approved, lgtm, size/M

#1756 Bug 1826150: Bootstrap Machine Config ordering issue
  pkg/controller/common/helpers.go
  pkg/controller/container-runtime-config/container_runtime_config_controller.go
  pkg/controller/container-runtime-config/container_runtime_config_controller_test.go
  pkg/controller/container-runtime-config/helpers.go
  pkg/controller/kubelet-config/helpers.go
  pkg/controller/kubelet-config/kubelet_config_controller.go
  pkg/controller/kubelet-config/kubelet_config_controller_test.go
  pkg/controller/kubelet-config/kubelet_config_features.go
  pkg/controller/kubelet-config/kubelet_config_features_test.go
  pkg/controller/render/render_controller.go
  pkg/controller/template/render.go
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, lgtm

#1812 Revert "Bug 1844990: pkg/server: default to TLS 1.3"
  pkg/server/api.go
Labels: approved, bugzilla/severity-medium, lgtm

#1811 [FCOS] add vrutkovs and LorbusChris to owners
  OWNERS
Labels: approved, lgtm

#1800 templates: Stop renaming description of crio/kubelet and other units
  templates/common/_base/units/crio.service.yaml
  templates/common/_base/units/kubelet.service.yaml
  templates/common/_base/units/machine-config-daemon-host.service.yaml
  templates/common/_base/units/pivot.service.yaml
Labels: approved, lgtm

#1807 Bug 1842906: daemon: Remove encapsulated config when joining the cluster
  pkg/daemon/daemon.go
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, lgtm

#1818 Bug 1829923: etcd-quorum-guard: update containers section in deployment.yaml
  install/0000_80_machine-config-operator_07_etcdquorumguard_deployment.yaml
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, lgtm

#1808 Bug 1845903: gcp-routes: decrease downfile poll to be faster than LB on recovery
  templates/master/00-master/gcp/files/opt-libexec-openshift-gcp-routes-sh.yaml
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, lgtm

#1825 Bug 1841358: kubelet: retry kubeletconfigs if the MCP pool is not found
  pkg/controller/kubelet-config/kubelet_config_controller.go
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, lgtm

#1636 Start openvswitch and ovsdb-server when network is ovn/ovs
  cmd/machine-config-operator/bootstrap.go
  lib/resourcemerge/machineconfig.go
  manifests/controllerconfig.crd.yaml
  pkg/apis/machineconfiguration.openshift.io/v1/types.go
  pkg/operator/assets/bindata.go
  pkg/operator/render.go
  templates/common/_base/units/openvswitch.service
  templates/common/_base/units/ovsdb-server.service
Labels: approved, lgtm

#1694 Bug 1820785: [baremetal] Correctly handle requests for ipv4/ipv6 records
  manifests/baremetal/coredns-corefile.tmpl
  pkg/operator/assets/bindata.go
  templates/common/baremetal/files/baremetal-coredns-corefile.yaml
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, lgtm

#1817 Bug 1828250: Sync kublelet config across platforms
  templates/master/01-master-kubelet/baremetal/units/kubelet.service.yaml
  templates/master/01-master-kubelet/openstack/units/kubelet.service.yaml
  templates/master/01-master-kubelet/vsphere/units/kubelet.service.yaml
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, lgtm

#1810 [FCOS] rebase on release-4.5
  manifests/ovirt/coredns.yaml
  manifests/ovirt/keepalived.conf.tmpl
  manifests/ovirt/keepalived.yaml
  pkg/operator/assets/bindata.go
  templates/common/ovirt/files/NetworkManager-resolv-prepender.yaml
  templates/common/ovirt/files/ovirt-coredns.yaml
  templates/common/ovirt/files/ovirt-keepalived.yaml
  templates/common/ovirt/files/ovirt-mdns-publisher.yaml
  templates/master/00-master/ovirt/files/dhcp-dhclient-conf.yaml
  templates/master/00-master/ovirt/files/ovirt-keepalived-keepalived.yaml
  templates/worker/00-worker/ovirt/files/dhcp-dhclient-conf.yaml
Labels: approved, lgtm

#1823 [MCO] Ignore Windows Nodes
  pkg/controller/node/node_controller.go
  pkg/controller/node/node_controller_test.go
  pkg/controller/node/status.go
Labels: approved, lgtm

#1824 docs: custom-pools work w/o the worker role label
  docs/custom-pools.md
Labels: approved, lgtm

#1813 Bug 1845885: templates: add node-valid-hostname.service for hostname check
  templates/common/_base/units/node-valid-hostname.service
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, lgtm

#1829 vsphere nodeip-configuration.service: run node-ip binary from container
  templates/common/vsphere/files/nodeip-finder.yaml
  templates/common/vsphere/files/vsphere-non-virtual-ip.yaml
  templates/common/vsphere/units/nodeip-configuration.service.yaml
  templates/master/00-master/vsphere/files/NetworkManager-resolv-prepender.yaml
  templates/worker/00-worker/ovirt/files/ovirt-non-virtual-ip.yaml
  templates/worker/00-worker/vsphere/files/NetworkManager-resolv-prepender.yaml
Labels: approved, lgtm

#1819 [release-4.5] Bug 1845636: etcd-quorum-guard: update containers section in deployment.yaml
  install/0000_80_machine-config-operator_07_etcdquorumguard_deployment.yaml
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, group-lead-approved, lgtm

#1788 Update keepalived ingress check's endpoint
  templates/master/00-master/baremetal/files/baremetal-keepalived-keepalived.yaml
  templates/master/00-master/openstack/files/openstack-keepalived-keepalived.yaml
  templates/master/00-master/ovirt/files/ovirt-keepalived-keepalived.yaml
  templates/master/00-master/vsphere/files/vsphere-keepalived-keepalived.yaml
Labels: approved, lgtm

#1841 Bug 1848195: daemon: fix formating in eviction message
  pkg/daemon/daemon.go
Labels: approved, bugzilla/severity-low, bugzilla/valid-bug, lgtm

#1719 Bug 1810680: make file diffs more user friendly
  go.mod
  pkg/daemon/daemon.go
Labels: approved, bugzilla/severity-low, bugzilla/valid-bug, lgtm

#1830 Revert "Start openvswitch and ovsdb-server when network is ovn/ovs"
  cmd/machine-config-operator/bootstrap.go
  lib/resourcemerge/machineconfig.go
  manifests/controllerconfig.crd.yaml
  pkg/apis/machineconfiguration.openshift.io/v1/types.go
  pkg/operator/assets/bindata.go
  pkg/operator/render.go
  templates/common/_base/units/openvswitch.service
  templates/common/_base/units/ovsdb-server.service
Labels: approved, lgtm

#1836 test/old-bootimages: New test
  test/e2e/old-bootimages.sh
Labels: approved, lgtm

#1831 [fcos] vsphere nodeip-configuration.service: run node-ip binary from container
  templates/common/vsphere/files/nodeip-finder.yaml
  templates/common/vsphere/files/vsphere-non-virtual-ip.yaml
  templates/common/vsphere/units/nodeip-configuration.service.yaml
  templates/master/00-master/vsphere/files/NetworkManager-resolv-prepender.yaml
  templates/worker/00-worker/ovirt/files/ovirt-non-virtual-ip.yaml
  templates/worker/00-worker/vsphere/files/NetworkManager-resolv-prepender.yaml
Labels: approved, lgtm

#1844 Bug 1842906: pkg/daemon: run 4.4 upgrade hack on MCD cluster boot
  pkg/daemon/daemon.go
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, lgtm

#1851 Minimal DHCP fix to unblock baremetal ci
  templates/common/baremetal/files/baremetal-NetworkManager-kni-conf.yaml
Labels: approved, lgtm

#1853 *: Use {allow,deny}list vocabulary
  cmd/machine-config-daemon/pivot.go
  docs/ContainerRuntimeConfigDesign.md
  docs/KubeletConfigDesign.md
  pkg/controller/kubelet-config/kubelet_config_controller_test.go
Labels: approved, lgtm

#1858 pkg/operator: report pools statuses
  pkg/operator/status.go
  pkg/operator/status_test.go
  test/e2e/mco_test.go
Labels: approved, lgtm

#1859 Bug 1849538: kubelet: wait to requeue after mcp error
  pkg/controller/kubelet-config/kubelet_config_controller.go
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, lgtm

#1862 test/e2e/old-bootimages: Some tweaks to hopefully fix Prow
  test/e2e/old-bootimages.sh
Labels: approved, lgtm

#1416 daemon: Move "Validated on-disk state" log to only when we have
  pkg/daemon/daemon.go
Labels: approved, lgtm, size/XS

#1809 Remove pivot invocations of systemctl reboot
  cmd/machine-config-daemon/pivot.go
  pkg/daemon/rpm-ostree.go
Labels: approved, lgtm

#1857 pkg/daemon: use Golang idioms and bubble up errors
  pkg/daemon/daemon.go
  pkg/daemon/daemon_test.go
Labels: approved, lgtm

#1624 Deprecate Platform field on ControllerConfig CRD
  examples/cluster.controllerconfig.yaml
  lib/resourcemerge/machineconfig.go
  manifests/controllerconfig.crd.yaml
  pkg/apis/machineconfiguration.openshift.io/v1/types.go
  pkg/controller/bootstrap/testdata/bootstrap/machineconfigcontroller-controllerconfig.yaml
  pkg/controller/container-runtime-config/container_runtime_config_controller_test.go
  pkg/controller/kubelet-config/kubelet_config_controller_test.go
  pkg/controller/kubelet-config/kubelet_config_features_test.go
  pkg/controller/template/render.go
  pkg/controller/template/render_test.go
  pkg/controller/template/template_controller_test.go
  pkg/controller/template/test_data/controller_config_aws.yaml
  pkg/controller/template/test_data/controller_config_baremetal.yaml
  pkg/controller/template/test_data/controller_config_gcp.yaml
  pkg/controller/template/test_data/controller_config_libvirt.yaml
  pkg/controller/template/test_data/controller_config_none.yaml
  pkg/controller/template/test_data/controller_config_openstack.yaml
  pkg/controller/template/test_data/controller_config_ovirt.yaml
  pkg/controller/template/test_data/controller_config_vsphere.yaml
  pkg/operator/assets/bindata.go
  pkg/operator/render.go
  pkg/operator/render_test.go
Labels: approved, lgtm

#1865 OpenStack: Minimal DHCP fix to unblock CI
  templates/common/openstack/files/openstack-NetworkManager-conf.yaml
Labels: approved, lgtm

#1867 [fcos] Control amount of replicas in etcd-quorum-guard
  cmd/machine-config-operator/bootstrap.go
  install/0000_80_machine-config-operator_02_images.configmap.yaml
  install/0000_80_machine-config-operator_07_etcdquorumguard_pdb.yaml
  manifests/etcdquorumguard_deployment.yaml
  pkg/apis/machineconfiguration.openshift.io/v1/types.go
  pkg/operator/assets/bindata.go
  pkg/operator/images.go
  pkg/operator/render_test.go
  pkg/operator/sync.go
Labels: approved, lgtm

#1846 Start openvswitch and ovsdb-server when network is ovn/ovs
  cmd/machine-config-operator/bootstrap.go
  lib/resourcemerge/machineconfig.go
  manifests/controllerconfig.crd.yaml
  pkg/apis/machineconfiguration.openshift.io/v1/types.go
  pkg/operator/assets/bindata.go
  pkg/operator/render.go
  templates/common/_base/units/openvswitch.service
  templates/common/_base/units/ovsdb-server.service
Labels: approved, lgtm

#1863 [ovirt/vsphere] Favor EtcdDiscoveryDomain in ControllerConfig.Infra.Status
  templates/common/ovirt/files/NetworkManager-resolv-prepender.yaml
  templates/master/00-master/vsphere/files/NetworkManager-resolv-prepender.yaml
Labels: approved, lgtm

#1709 update openshift/api for IPv6DualStackNoUpgrade featureset
  go.mod
  go.sum
  templates/master/01-master-kubelet/_base/files/kubelet.yaml
  templates/worker/01-worker-kubelet/_base/files/kubelet.yaml
  vendor/github.com/openshift/api/config/v1/0000_10_config-operator_01_apiserver.crd.yaml
  vendor/github.com/openshift/api/config/v1/0000_10_config-operator_01_authentication.crd.yaml
  vendor/github.com/openshift/api/config/v1/0000_10_config-operator_01_infrastructure.crd.yaml
  vendor/github.com/openshift/api/config/v1/0000_10_config-operator_01_oauth.crd.yaml
  vendor/github.com/openshift/api/config/v1/types_apiserver.go
  vendor/github.com/openshift/api/config/v1/types_authentication.go
  vendor/github.com/openshift/api/config/v1/types_console.go
  vendor/github.com/openshift/api/config/v1/types_feature.go
  vendor/github.com/openshift/api/config/v1/types_infrastructure.go
  vendor/github.com/openshift/api/config/v1/types_oauth.go
  vendor/github.com/openshift/api/config/v1/types_operatorhub.go
  vendor/github.com/openshift/api/config/v1/zz_generated.deepcopy.go
  vendor/github.com/openshift/api/config/v1/zz_generated.swagger_doc_generated.go
  vendor/github.com/openshift/api/operator/v1/0000_10_config-operator_01_config.crd.yaml
  vendor/github.com/openshift/api/operator/v1/0000_20_etcd-operator_01.crd.yaml
  vendor/github.com/openshift/api/operator/v1/0000_50_ingress-operator_00-ingresscontroller.crd.yaml
  vendor/github.com/openshift/api/operator/v1/0000_50_ingress-operator_00-ingresscontroller.crd.yaml-merge-patch
  vendor/github.com/openshift/api/operator/v1/0000_70_console-operator.crd.yaml
  vendor/github.com/openshift/api/operator/v1/types_config.go
  vendor/github.com/openshift/api/operator/v1/types_console.go
  vendor/github.com/openshift/api/operator/v1/types_ingress.go
  vendor/github.com/openshift/api/operator/v1/types_servicecatalogapiserver.go
  vendor/github.com/openshift/api/operator/v1/types_servicecatalogcontrollermanager.go
  vendor/github.com/openshift/api/operator/v1/zz_generated.deepcopy.go
  vendor/github.com/openshift/api/operator/v1/zz_generated.swagger_doc_generated.go
  vendor/modules.txt
Labels: approved, lgtm

#1766 Use MCD binary from container in /run/bin
  cmd/machine-config-daemon/pivot.sh
  cmd/machine-config-daemon/start.go
  pkg/daemon/constants/constants.go
  pkg/daemon/rpm-ostree.go
  pkg/daemon/update.go
  pkg/server/bootstrap_server.go
  pkg/server/cluster_server.go
  pkg/server/server.go
  templates/common/_base/units/machine-config-daemon-firstboot-v42.service.yaml
  templates/common/_base/units/machine-config-daemon-firstboot.service.yaml
  templates/common/_base/units/machine-config-daemon-host.service.yaml
  templates/common/_base/units/machine-config-daemon-pull.service.yaml
Labels: approved, lgtm

#1854 Bug 1849298: Update to github.com/mtrmac/gpgme v0.1.2 [4.4]
  go.mod
  go.sum
  vendor/github.com/mtrmac/gpgme/.appveyor.yml
  vendor/github.com/mtrmac/gpgme/.travis.yml
  vendor/github.com/mtrmac/gpgme/data.go
  vendor/github.com/mtrmac/gpgme/go.mod
  vendor/github.com/mtrmac/gpgme/go_gpgme.c
  vendor/github.com/mtrmac/gpgme/go_gpgme.h
  vendor/github.com/mtrmac/gpgme/gpgme.go
  vendor/github.com/mtrmac/gpgme/unset_agent_info.go
  vendor/github.com/mtrmac/gpgme/unset_agent_info_windows.go
  vendor/k8s.io/code-generator/generate-groups.sh
  vendor/k8s.io/code-generator/generate-internal-groups.sh
  vendor/modules.txt
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, cherry-pick-approved, lgtm

#1767 [baremetal] Set NonVirtualIP in mdns plugin config
  manifests/baremetal/coredns-corefile.tmpl
  pkg/operator/assets/bindata.go
  templates/common/baremetal/files/baremetal-coredns-corefile.yaml
Labels: approved, lgtm

#1864 [FCOS] Periodic rebase on release-4.5 branch
  go.mod
  manifests/etcdquorumguard_deployment.yaml
  manifests/machineconfigdaemon/daemonset.yaml
  pkg/controller/kubelet-config/kubelet_config_controller.go
  pkg/daemon/daemon.go
  pkg/daemon/update.go
  pkg/operator/assets/bindata.go
  templates/master/00-master/baremetal/files/baremetal-keepalived-keepalived.yaml
  templates/master/00-master/gcp/files/opt-libexec-openshift-gcp-routes-sh.yaml
  templates/master/00-master/openstack/files/openstack-keepalived-keepalived.yaml
  templates/master/00-master/ovirt/files/ovirt-keepalived-keepalived.yaml
  templates/master/00-master/vsphere/files/vsphere-keepalived-keepalived.yaml
  templates/master/01-master-kubelet/_base/units/kubelet.service.yaml
  templates/master/01-master-kubelet/baremetal/units/kubelet.service.yaml
  templates/master/01-master-kubelet/openstack/units/kubelet.service.yaml
  templates/master/01-master-kubelet/vsphere/units/kubelet.service.yaml
  templates/worker/00-worker/baremetal/files/baremetal-keepalived-keepalived.yaml
  templates/worker/00-worker/openstack/files/openstack-keepalived-keepalived.yaml
  templates/worker/00-worker/ovirt/files/ovirt-keepalived-keepalived.yaml
  templates/worker/00-worker/vsphere/files/vsphere-keepalived-keepalived.yaml
  templates/worker/01-worker-kubelet/_base/units/kubelet.service.yaml
Labels: approved, lgtm

#1834 Bug 1822945: templates: add a file to load legacy iptables kernel modules
  templates/common/_base/files/iptables-modules.yaml
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, lgtm

#1880 Bug 1805019: KubeletConfig: Verify EvictionSoftGracePeriod is set when EvictionSof…
  pkg/controller/kubelet-config/helpers.go
  pkg/controller/kubelet-config/kubelet_config_controller_test.go
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, lgtm
