Repository openshift/machine-config-operator, pull requests merged in 2020-04, with the labels that each got.

#1600 Revert "cri-o: set manage_ns_lifecycle to true"
  templates/master/01-master-container-runtime/_base/files/crio.yaml
  templates/worker/01-worker-container-runtime/_base/files/crio.yaml
Labels: approved, lgtm

#1603 [fcos] machine-config-daemon-firstboot: retry podman pull
  templates/common/_base/units/machine-config-daemon-firstboot.service
Labels: approved, lgtm

#1593 Bug 1814397: fix wrongful backup of files not originally on the system
  pkg/daemon/update.go
Labels: approved, bugzilla/valid-bug, lgtm

#1610 [fcos] fix wrongful backup of files not originally on the systemackup of files not originally on the system
  pkg/daemon/update.go
Labels: approved, lgtm

#1581 Bug 1811720: Specify cgroups in kubelet.conf so cAdvisor stats will be tracked
  templates/master/01-master-kubelet/_base/files/kubelet.yaml
  templates/master/01-master-kubelet/_base/units/kubelet.yaml
  templates/worker/01-worker-kubelet/_base/files/kubelet.yaml
  templates/worker/01-worker-kubelet/_base/units/kubelet.yaml
Labels: approved, bugzilla/valid-bug, cherry-pick-approved, lgtm

#1612 Bug 1820401: daemon: better way to find installed kernel-rt packages on host
  pkg/daemon/update.go
Labels: approved, bugzilla/valid-bug, lgtm

#1598 pkg/operator: clear Degraded on task's success
  pkg/operator/status.go
  pkg/operator/sync.go
Labels: approved, lgtm

#1609 Bug 1817455: [release-4.4] fix wrongful backup of files not originally on the system
  go.sum
  pkg/daemon/update.go
Labels: approved, bugzilla/valid-bug, cherry-pick-approved, lgtm

#1601 Bug 1819484: Nodeip retry on failure
  templates/common/baremetal/files/baremetal-non-virtual-ip.yaml
  templates/common/baremetal/files/nodeip-finder.yaml
  templates/common/baremetal/units/nodeip-configuration.service
Labels: approved, bugzilla/valid-bug, lgtm

#1611 OWNERS: add BZ component name
  OWNERS
Labels: approved, lgtm

#1551 Bug 1811898: cmd/machine-config-operator: log RELEASE_VERSION when starting up
  cmd/machine-config-operator/start.go
Labels: approved, bugzilla/valid-bug, lgtm, size/XS

#1613 cri-o: set log level to info
  templates/master/01-master-container-runtime/_base/files/crio.yaml
  templates/worker/01-worker-container-runtime/_base/files/crio.yaml
Labels: approved, lgtm

#1602 pkg/daemon: Add event for drain failures
  pkg/daemon/update.go
Labels: approved, lgtm

#1606 ovirt: disable tx checksum offload for workers
  templates/worker/00-worker/ovirt/files/ovirt-disable-tx-checksum-offload.yaml
Labels: approved, lgtm

#996 Ignition types.Config (v0s2) to runtime.RawExtension conversion
  lib/resourceapply/machineconfig_test.go
  pkg/apis/machineconfiguration.openshift.io/v1/helpers.go
  pkg/apis/machineconfiguration.openshift.io/v1/machineconfig.deepcopy.go
  pkg/apis/machineconfiguration.openshift.io/v1/types.go
  pkg/apis/machineconfiguration.openshift.io/v1/zz_generated.deepcopy.go
  pkg/controller/bootstrap/bootstrap_test.go
  pkg/controller/common/constants.go
  pkg/controller/common/helpers.go
  pkg/controller/container-runtime-config/container_runtime_config_controller.go
  pkg/controller/container-runtime-config/container_runtime_config_controller_test.go
  pkg/controller/container-runtime-config/helpers.go
  pkg/controller/kubelet-config/helpers.go
  pkg/controller/kubelet-config/kubelet_config_controller.go
  pkg/controller/kubelet-config/kubelet_config_features.go
  pkg/controller/render/render_controller.go
  pkg/controller/render/render_controller_test.go
  pkg/controller/template/render.go
  pkg/controller/template/render_test.go
  pkg/controller/template/template_controller_test.go
  pkg/daemon/daemon.go
  pkg/daemon/update.go
  pkg/daemon/update_test.go
  pkg/server/api_test.go
  pkg/server/bootstrap_server.go
  pkg/server/cluster_server.go
  pkg/server/server.go
  pkg/server/server_test.go
  pkg/server/testdata/machine-configs/test-config.yaml
  test/e2e/mcd_test.go
  test/e2e/utils_test.go
  test/helpers/helpers.go
Labels: 4.5, approved, lgtm, size/XXL

#1614 Bug 1820822: sdn: ignore new ovn-kubernetes OVS internal port names ovn-k8s-gw0 and ovn-k8s-mp0
  templates/common/_base/files/nm-ignore-sdn.yaml
Labels: approved, bugzilla/valid-bug, lgtm

#1622 baremetal: static hostname to prevent DNS lookup
  templates/master/00-master/baremetal/files/NetworkManager-resolv-prepender.yaml
  templates/worker/00-worker/baremetal/files/NetworkManager-resolv-prepender.yaml
Labels: approved, lgtm

#1620 Bug 1821798: OpenStack: disable tx checksum offload for workers
  templates/worker/00-worker/openstack/files/openstack-disable-tx-checksum-offload.yaml
Labels: approved, bugzilla/valid-bug, lgtm

#1625 Makefile: Drop -mod=vendor flag
  Makefile
Labels: approved, lgtm

#1621 Bug 1821005: oVirt, fix disable tx checksum offload for workers
  templates/worker/00-worker/ovirt/files/ovirt-disable-tx-checksum-offload.yaml
Labels: approved, bugzilla/valid-bug, lgtm

#1628 Bug 1820975: oVirt, fix disable tx checksum offload for workers
  templates/worker/00-worker/ovirt/files/ovirt-disable-tx-checksum-offload.yaml
Labels: approved, bugzilla/valid-bug, cherry-pick-approved, lgtm

#1631 Bug 1821888: controller: do not error on empty Ignition configs
  pkg/controller/common/helpers.go
  pkg/controller/container-runtime-config/helpers.go
  pkg/controller/kubelet-config/helpers.go
Labels: approved, bugzilla/valid-bug, lgtm

#1633 [fcos] GCP-routes: switch to using conntrack instead of route tables
  templates/common/gcp/files/gcp-routes-sh.yaml
Labels: approved, lgtm

#1632 Makefile: Cleanup after `make verify`
  Makefile
Labels: approved, lgtm

#1637 Bug 1809007: [ctrcfg controller] Use a struct array instead of map when creating new ignitions
  pkg/controller/container-runtime-config/container_runtime_config_controller.go
  pkg/controller/container-runtime-config/helpers.go
Labels: approved, bugzilla/valid-bug, lgtm

#1630 Add containernetworking-plugin RPM's bin location to CRI-O config
  templates/master/01-master-container-runtime/_base/files/crio.yaml
  templates/worker/01-worker-container-runtime/_base/files/crio.yaml
Labels: approved, lgtm

#1623 Bug 1821833: The Multus CNI configuration file "00-multus.conf" should not be removed
  templates/common/_base/files/cleanup-cni-conf.yaml
Labels: approved, bugzilla/valid-bug, lgtm

#1604 [baremetal] Update keepalived Liveness check
  templates/common/baremetal/files/baremetal-keepalived.yaml
Labels: approved, lgtm

#1641 [fcos] rebase on recent master
  Makefile
  OWNERS
  pkg/controller/container-runtime-config/container_runtime_config_controller.go
  pkg/controller/container-runtime-config/helpers.go
  pkg/daemon/update.go
  pkg/operator/status.go
  pkg/operator/sync.go
  templates/common/_base/files/nm-ignore-sdn.yaml
  templates/common/vsphere/files/vsphere-hostname.yaml
  templates/common/vsphere/units/vsphere-hostname.yaml
  templates/master/00-master/baremetal/files/NetworkManager-resolv-prepender.yaml
  templates/master/00-master/baremetal/files/baremetal-haproxy.yaml
  templates/master/01-master-container-runtime/_base/files/crio.yaml
  templates/master/01-master-kubelet/_base/files/kubelet.yaml
  templates/master/01-master-kubelet/_base/units/kubelet.yaml
  templates/worker/00-worker/baremetal/files/NetworkManager-resolv-prepender.yaml
  templates/worker/00-worker/openstack/files/openstack-disable-tx-checksum-offload.yaml
  templates/worker/00-worker/ovirt/files/ovirt-disable-tx-checksum-offload.yaml
  templates/worker/01-worker-container-runtime/_base/files/crio.yaml
  templates/worker/01-worker-kubelet/_base/files/kubelet.yaml
  templates/worker/01-worker-kubelet/_base/units/kubelet.yaml
  vendor/k8s.io/code-generator/generate-groups.sh
  vendor/k8s.io/code-generator/generate-internal-groups.sh
Labels: approved, lgtm

#1652 spec: requires golang >=1.13
  machine-config-daemon.spec
Labels: approved, lgtm

#1648 Bug 1823677:etcdquorumguard_deployment: pass NSS_SDB_USE_CACHE=no to curl
  install/0000_80_machine-config-operator_07_etcdquorumguard_deployment.yaml
Labels: approved, bugzilla/valid-bug, lgtm

#1656 pkg/daemon: reuse rpm-ostree code to get currently booted CoreOS host info
  pkg/daemon/rpm-ostree.go
  pkg/daemon/rpm-ostree_test.go
  pkg/daemon/update.go
  pkg/daemon/update_test.go
Labels: approved, lgtm

#1644 [release-4.4] Bug 1822748: [ctrcfgcontroller] Use a struct array instead of map when creating new ignitions
  pkg/controller/container-runtime-config/container_runtime_config_controller.go
  pkg/controller/container-runtime-config/helpers.go
Labels: approved, bugzilla/valid-bug, cherry-pick-approved, lgtm

#1657 Update vSphere templates and manifests
  manifests/vsphere/coredns-corefile.tmpl
  pkg/operator/assets/bindata.go
  templates/common/vsphere/files/NetworkManager-mdns-hostname.yaml
  templates/common/vsphere/files/etc-systemd-system-crio-stream-address.conf.yaml
  templates/common/vsphere/files/nodeip-finder.yaml
  templates/common/vsphere/files/vsphere-NetworkManager-kni-conf.yaml
  templates/common/vsphere/files/vsphere-coredns-corefile.yaml
  templates/common/vsphere/files/vsphere-coredns-db.yaml
  templates/common/vsphere/files/vsphere-coredns.yaml
  templates/common/vsphere/files/vsphere-hostname.yaml
  templates/common/vsphere/files/vsphere-keepalived.yaml
  templates/common/vsphere/files/vsphere-mdns-publisher.yaml
  templates/common/vsphere/files/vsphere-non-virtual-ip.yaml
  templates/common/vsphere/units/nodeip-configuration.yaml
  templates/common/vsphere/units/vsphere-hostname.yaml
  templates/master/00-master/vsphere/files/NetworkManager-resolv-prepender.yaml
  templates/master/00-master/vsphere/files/vsphere-haproxy-haproxy.yaml
  templates/master/00-master/vsphere/files/vsphere-haproxy.yaml
  templates/master/00-master/vsphere/files/vsphere-keepalived-keepalived.yaml
  templates/master/00-master/vsphere/files/vsphere-mdns-config.yaml
  templates/master/01-master-kubelet/vsphere/units/kubelet.yaml
  templates/worker/00-worker/vsphere/files/NetworkManager-resolv-prepender.yaml
  templates/worker/00-worker/vsphere/files/vsphere-keepalived-keepalived.yaml
  templates/worker/01-worker-kubelet/vsphere/units/kubelet.yaml
Labels: approved, lgtm

#1654 docs: update HACKING doc with latest information
  docs/HACKING.md
Labels: approved, lgtm

#1662 Update vSphere IPI removing DNS VIP
  manifests/vsphere/coredns.yaml
  manifests/vsphere/keepalived.conf.tmpl
  manifests/vsphere/keepalived.yaml
  pkg/operator/assets/bindata.go
  templates/common/vsphere/files/vsphere-coredns.yaml
  templates/common/vsphere/files/vsphere-keepalived.yaml
  templates/common/vsphere/files/vsphere-mdns-publisher.yaml
  templates/master/00-master/vsphere/files/NetworkManager-resolv-prepender.yaml
  templates/master/00-master/vsphere/files/vsphere-keepalived-keepalived.yaml
  templates/worker/00-worker/vsphere/files/NetworkManager-resolv-prepender.yaml
Labels: approved, lgtm

#1569 baremetal: Remove DNS VIP
  manifests/baremetal/coredns.yaml
  manifests/baremetal/keepalived.conf.tmpl
  manifests/baremetal/keepalived.yaml
  pkg/operator/assets/bindata.go
  templates/common/baremetal/files/baremetal-coredns.yaml
  templates/common/baremetal/files/baremetal-keepalived.yaml
  templates/common/baremetal/files/baremetal-mdns-publisher.yaml
  templates/master/00-master/baremetal/files/NetworkManager-resolv-prepender.yaml
  templates/master/00-master/baremetal/files/baremetal-keepalived-keepalived.yaml
  templates/worker/00-worker/baremetal/files/NetworkManager-resolv-prepender.yaml
Labels: approved, lgtm

#1615 Bug 1820823: [4.4] sdn: ignore new ovn-kubernetes OVS internal port names ovn-k8s-gw0 and ovn-k8s-mp0
  templates/common/_base/files/nm-ignore-sdn.yaml
Labels: approved, bugzilla/valid-bug, cherry-pick-approved, lgtm

#1664 Bug 1820507: Add new crio.conf field to the template
  templates/master/01-master-container-runtime/_base/files/crio.yaml
  templates/worker/01-worker-container-runtime/_base/files/crio.yaml
Labels: approved, bugzilla/urgent, bugzilla/valid-bug, lgtm

#1663 [release 4.4] Bug 1822268: Add new crio.conf field to the template
  templates/master/01-master-container-runtime/_base/files/crio.yaml
  templates/worker/01-worker-container-runtime/_base/files/crio.yaml
Labels: approved, bugzilla/urgent, bugzilla/valid-bug, cherry-pick-approved, lgtm

#1665 Bug 1825823: Add support for reading API LB backends from KUBE-API for OpenStack and Ovirt
  templates/master/00-master/openstack/files/openstack-haproxy.yaml
  templates/master/00-master/ovirt/files/ovirt-haproxy.yaml
Labels: approved, bugzilla/high, bugzilla/valid-bug, lgtm

#1671 Bug 1825991: Remove vsphere-non-virtual-ip.yaml from worker templates
  templates/worker/00-worker/vsphere/files/vsphere-non-virtual-ip.yaml
Labels: approved, bugzilla/high, bugzilla/valid-bug, lgtm

#1645 [release-4.3] Bug 1822750: [ctrcfg controller] Use a struct array instead of map when creating new ignitions
  pkg/controller/container-runtime-config/container_runtime_config_controller.go
  pkg/controller/container-runtime-config/helpers.go
Labels: approved, bugzilla/urgent, bugzilla/valid-bug, cherry-pick-approved, lgtm

#1649 Bug 1823852: pkg/server: disable weak TLS versions
  pkg/server/api.go
Labels: approved, bugzilla/valid-bug, lgtm

#1658 Bug 1825948: cloudConfig: read cloud Config from openshift-config-managed/kube-cloud-config ConfigMap
  pkg/controller/template/render.go
  pkg/controller/template/render_test.go
  pkg/operator/sync.go
Labels: approved, bugzilla/unspecified, bugzilla/valid-bug, lgtm

#1683 Makefile: add -failfast to e2e-op
  Makefile
Labels: approved, bugzilla/valid-bug, lgtm

#1679 Bug 1826896: [release-4.4] crio: set version-file{,-persist} correctly
  templates/master/01-master-container-runtime/_base/files/crio.yaml
  templates/worker/01-worker-container-runtime/_base/files/crio.yaml
Labels: approved, bugzilla/severity-urgent, bugzilla/urgent, bugzilla/valid-bug, cherry-pick-approved, lgtm

#1685 Bug 1828106: cloudConfig: remove bare metal from platforms that require a cloud conifg
  pkg/controller/template/render.go
  pkg/operator/sync.go
Labels: approved, bugzilla/severity-urgent, bugzilla/valid-bug, lgtm

#1677 Bug 1827600: Fix crd openAPI validation regression
  go.mod
  go.sum
  manifests/machineconfig.crd.yaml
  pkg/controller/common/helpers.go
  pkg/controller/container-runtime-config/container_runtime_config_controller.go
  pkg/controller/kubelet-config/kubelet_config_controller.go
  pkg/controller/kubelet-config/kubelet_config_features.go
  pkg/controller/render/render_controller_test.go
  pkg/controller/template/render.go
  pkg/controller/template/template_controller_test.go
  pkg/daemon/update.go
  pkg/operator/assets/bindata.go
  pkg/server/api_test.go
  pkg/server/server.go
  test/helpers/helpers.go
  vendor/github.com/clarketm/json/LICENSE
  vendor/github.com/clarketm/json/README.md
  vendor/github.com/clarketm/json/decode.go
  vendor/github.com/clarketm/json/encode.go
  vendor/github.com/clarketm/json/fold.go
  vendor/github.com/clarketm/json/fuzz.go
  vendor/github.com/clarketm/json/indent.go
  vendor/github.com/clarketm/json/scanner.go
  vendor/github.com/clarketm/json/stream.go
  vendor/github.com/clarketm/json/tables.go
  vendor/github.com/clarketm/json/tags.go
  vendor/github.com/go-toolsmith/astcast/astcast_generate.go
  vendor/github.com/go-toolsmith/typep/simplePredicates_generate.go
  vendor/github.com/google/btree/btree_mem.go
  vendor/golang.org/x/sys/unix/mkasm_darwin.go
  vendor/golang.org/x/sys/unix/mkpost.go
  vendor/golang.org/x/sys/unix/mksyscall.go
  vendor/golang.org/x/sys/unix/mksyscall_aix_ppc.go
  vendor/golang.org/x/sys/unix/mksyscall_aix_ppc64.go
  vendor/golang.org/x/sys/unix/mksyscall_solaris.go
  vendor/golang.org/x/sys/unix/mksysctl_openbsd.go
  vendor/golang.org/x/sys/unix/mksysnum.go
  vendor/golang.org/x/sys/unix/types_aix.go
  vendor/golang.org/x/sys/unix/types_darwin.go
  vendor/golang.org/x/sys/unix/types_dragonfly.go
  vendor/golang.org/x/sys/unix/types_freebsd.go
  vendor/golang.org/x/sys/unix/types_netbsd.go
  vendor/golang.org/x/sys/unix/types_openbsd.go
  vendor/golang.org/x/sys/unix/types_solaris.go
  vendor/golang.org/x/text/encoding/internal/identifier/gen.go
  vendor/golang.org/x/text/unicode/bidi/gen.go
  vendor/golang.org/x/text/unicode/bidi/gen_ranges.go
  vendor/golang.org/x/text/unicode/bidi/gen_trieval.go
  vendor/golang.org/x/text/unicode/norm/maketables.go
  vendor/golang.org/x/text/unicode/norm/triegen.go
  vendor/golang.org/x/text/width/gen.go
  vendor/golang.org/x/text/width/gen_common.go
  vendor/golang.org/x/text/width/gen_trieval.go
  vendor/golang.org/x/tools/go/gcexportdata/main.go
  vendor/golang.org/x/tools/internal/imports/mkindex.go
  vendor/golang.org/x/tools/internal/imports/mkstdlib.go
  vendor/modules.txt
Labels: approved, bugzilla/unspecified, bugzilla/valid-bug, lgtm

#1672 Bug 1828622: bumps kubelet log level to 4
  templates/master/01-master-kubelet/_base/units/kubelet.yaml
  templates/worker/01-worker-kubelet/_base/units/kubelet.yaml
Labels: approved, bugzilla/severity-unspecified, bugzilla/valid-bug, lgtm

#1687 Bug 1805908: Add template for recycler pod
  templates/master/00-master/_base/files/recycler_pod.yaml
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, lgtm

#1691 Bug 1827143: daemon: consider addition of an RT kernel package as update
  pkg/daemon/update.go
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, lgtm

#1693 Bug 1816178: MCO: have the CVO create CRDs
  install/0000_80_machine-config-operator_01_containerruntimeconfig.crd.yaml
  install/0000_80_machine-config-operator_01_kubeletconfig.crd.yaml
  install/0000_80_machine-config-operator_01_machineconfig.crd.yaml
  install/0000_80_machine-config-operator_01_machineconfigpool.crd.yaml
  pkg/operator/assets/bindata.go
  pkg/operator/operator.go
  pkg/operator/sync.go
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, lgtm

#1674 Bug 1825909: baremetal - Limit the number of nameservers to 3
  templates/master/00-master/baremetal/files/NetworkManager-resolv-prepender.yaml
  templates/worker/00-worker/baremetal/files/NetworkManager-resolv-prepender.yaml
Labels: approved, bugzilla/severity-low, bugzilla/valid-bug, lgtm

#1698 [release-4.4] Bug 1829651: MC CRD: preserve unknown fields
  manifests/machineconfig.crd.yaml
  pkg/operator/assets/bindata.go
Labels: approved, bugzilla/severity-urgent, bugzilla/valid-bug, cherry-pick-approved, lgtm

#1350 Bug 1785219: [release-4.2] Discard audit messages from journald
  pkg/daemon/update.go
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, cherry-pick-approved, lgtm, size/XS
