Repository openshift/machine-config-operator, pull requests merged in 2020-02, with the labels that each got.

#1422 Bug 1780396: Get etcdctl binary from the etcd image and not from the upstream releases
  templates/master/00-master/_base/files/usr-local-bin-openshift-recovery-tools-sh.yaml
Labels: approved, bugzilla/valid-bug, lgtm, size/S

#1410 Bug 1796440: [release-4.3] DR: Cherry-pick keep keys and data separate for snapshot backup
  templates/master/00-master/_base/files/usr-local-bin-etcd-snapshot-backup-sh.yaml
  templates/master/00-master/_base/files/usr-local-bin-etcd-snapshot-restore-sh.yaml
  templates/master/00-master/_base/files/usr-local-bin-openshift-recovery-tools-sh.yaml
Labels: approved, bugzilla/valid-bug, cherry-pick-approved, lgtm, size/M

#1426 [release-4.3] Bug 1796822: Support deployment on OpenStack with self-signed certificate
  cmd/machine-config-operator/bootstrap.go
  lib/resourcemerge/machineconfig.go
  pkg/apis/machineconfiguration.openshift.io/v1/types.go
  pkg/apis/machineconfiguration.openshift.io/v1/zz_generated.deepcopy.go
  pkg/operator/bootstrap.go
  pkg/operator/sync.go
  templates/common/_base/files/cloud-provider-ca.yaml
Labels: approved, bugzilla/valid-bug, cherry-pick-approved, lgtm, priority/critical-urgent, size/M

#1353 Bug 1785718: [release-4.3] etcd: Add initial support for an IPv6 control plane
  cmd/setup-etcd-environment/run.go
  templates/common/_base/files/sysctl-forward-conf.yaml
  templates/master/00-master/_base/files/etc-kubernetes-manifests-etcd-member.yaml
Labels: approved, bugzilla/valid-bug, cherry-pick-approved, lgtm, size/M

#1399 Bug 1793253: [release-4.3] HAProxy infra pod: Make v4/v6 compatible
  templates/master/00-master/baremetal/files/baremetal-haproxy-haproxy.yaml
  templates/master/00-master/openstack/files/openstack-haproxy-haproxy.yaml
  templates/master/00-master/ovirt/files/ovirt-haproxy-haproxy.yaml
Labels: approved, bugzilla/valid-bug, cherry-pick-approved, lgtm, size/S

#1425 Bug 1794824: If PlatformStatus.VSphere is nil do not template the file
  pkg/operator/bootstrap.go
  templates/common/vsphere/files/vsphere-NetworkManager-kni-conf.yaml
  templates/common/vsphere/files/vsphere-coredns-corefile.yaml
  templates/common/vsphere/files/vsphere-coredns-db.yaml
  templates/common/vsphere/files/vsphere-coredns.yaml
  templates/common/vsphere/files/vsphere-keepalived.yaml
  templates/common/vsphere/files/vsphere-mdns-publisher.yaml
  templates/master/00-master/vsphere/files/dhcp-dhclient-conf.yaml
  templates/master/00-master/vsphere/files/vsphere-haproxy-haproxy.yaml
  templates/master/00-master/vsphere/files/vsphere-haproxy.yaml
  templates/master/00-master/vsphere/files/vsphere-keepalived-keepalived.yaml
  templates/master/00-master/vsphere/files/vsphere-mdns-config.yaml
  templates/worker/00-worker/vsphere/files/dhcp-dhclient-conf.yaml
  templates/worker/00-worker/vsphere/files/vsphere-keepalived-keepalived.yaml
  templates/worker/00-worker/vsphere/files/vsphere-mdns-config.yaml
  templates/worker/00-worker/vsphere/files/vsphere-non-virtual-ip.yaml
Labels: approved, bugzilla/valid-bug, lgtm, size/M

#1436 Bug 1798146: [baremetal] Ipv6 non virtual ip fix
  templates/worker/00-worker/baremetal/files/baremetal-non-virtual-ip.yaml
Labels: approved, bugzilla/valid-bug, lgtm, size/L

#1439 Bug 1797908: kubelet: Remove quotes from log level argument
  templates/master/01-master-kubelet/_base/units/kubelet.yaml
  templates/worker/01-worker-kubelet/_base/units/kubelet.yaml
Labels: approved, bugzilla/valid-bug, lgtm, size/XS

#1442 [fcos] GCP: add a script and a service which ensure GCP routes are set correctly
  templates/common/gcp/files/gcp-routes-sh.yaml
  templates/common/gcp/units/gcp-routes-service.yaml
Labels: approved, bugzilla/valid-bug, lgtm, size/L

#1429 Bug 1795696: templates: etcd-member: setup environment variables needed for easy etcdctl execution
  templates/master/00-master/_base/files/etc-kubernetes-manifests-etcd-member.yaml
Labels: approved, bugzilla/valid-bug, lgtm, size/XS

#1450 Bug 1800319: kubelet: add kube reservation for kubernetes components
  templates/master/01-master-kubelet/_base/files/kubelet.yaml
  templates/worker/01-worker-kubelet/_base/files/kubelet.yaml
Labels: approved, bugzilla/valid-bug, lgtm, size/S

#1453 Bug 1801466: add owners files to master and worker kubelet templates
  templates/master/01-master-kubelet/OWNERS
  templates/worker/01-worker-kubelet/OWNERS
Labels: approved, bugzilla/valid-bug, lgtm, size/S

#1451 FAQ: More about preservation of changes and the MCO
  docs/FAQ.md
Labels: approved, bugzilla/valid-bug, lgtm, retest-not-required-docs-only, size/XS

#1457 Bug 1797897: etcd-member: do not wait-for-kube or validate membership for existing members
  templates/master/00-master/_base/files/etc-kubernetes-manifests-etcd-member.yaml
Labels: approved, bugzilla/valid-bug, lgtm, size/S

#1431 Bug 1797035: Get etcdctl binary from the etcd image and not from the upstream releases
  templates/master/00-master/_base/files/usr-local-bin-openshift-recovery-tools-sh.yaml
Labels: approved, bugzilla/valid-bug, cherry-pick-approved, lgtm, size/S

#1456 Bug 1801662: baremetal: all resolvconf editing to NM dispatcher
  templates/master/00-master/baremetal/files/NetworkManager-resolv-prepender.yaml
  templates/worker/00-worker/baremetal/files/NetworkManager-resolv-prepender.yaml
Labels: approved, bugzilla/valid-bug, lgtm, size/S

#1469 Bug 1787907: kubelet: switch to ObjectMeta.UID and initialize UUID
  pkg/controller/kubelet-config/kubelet_config_controller.go
Labels: approved, bugzilla/valid-bug, lgtm, size/S

#1455 Bug 1790823: [baremetal] Verify that MDNS doesn't advertise localhost
  templates/common/baremetal/files/NetworkManager-mdns-hostname.yaml
  templates/common/baremetal/files/baremetal-mdns-publisher.yaml
Labels: approved, bugzilla/valid-bug, lgtm, size/M

#1476 Bug 1800319: kubelet: bump CPU reservation back to 500m
  templates/master/01-master-kubelet/_base/files/kubelet.yaml
  templates/worker/01-worker-kubelet/_base/files/kubelet.yaml
Labels: approved, bugzilla/valid-bug, lgtm, size/XS

#1473 bug 1801397: temporarily skip setting failures on degraded machine config pool
  pkg/operator/sync.go
Labels: approved, bugzilla/valid-bug, lgtm, size/S

#1482 Bug 1803986:Revert 1473 and skip etcd-member.yaml validation
  pkg/daemon/daemon.go
  pkg/operator/sync.go
Labels: approved, bugzilla/valid-bug, lgtm, size/S

#1465 bug 1804418: remove the etcd-member pod because we no longer need it
  templates/master/00-master/_base/files/etc-kubernetes-manifests-etcd-member.yaml
Labels: approved, bugzilla/valid-bug, lgtm, size/L

#1472 Make `mcfgv1` and `ctrlcommon` canonical names for importing
  cmd/machine-config-controller/start.go
  cmd/machine-config-daemon/start.go
  cmd/machine-config-operator/start.go
  cmd/machine-config-server/start.go
  pkg/controller/bootstrap/bootstrap.go
  pkg/controller/container-runtime-config/container_runtime_config_controller.go
  pkg/controller/container-runtime-config/container_runtime_config_controller_test.go
  pkg/controller/kubelet-config/kubelet_config_controller_test.go
  pkg/controller/kubelet-config/kubelet_config_features_test.go
  pkg/controller/render/render_controller.go
  pkg/controller/template/render.go
  pkg/controller/template/template_controller.go
  pkg/server/bootstrap_server.go
  pkg/server/server_test.go
Labels: 4.5, approved, lgtm, size/L

#1483 OpenStack: pull improvements and IPv6 fixes from BM
  templates/common/openstack/files/NetworkManager-mdns-hostname.yaml
  templates/common/openstack/files/nodeip-finder.yaml
  templates/common/openstack/files/openstack-NetworkManager-conf.yaml
  templates/common/openstack/files/openstack-mdns-publisher.yaml
  templates/common/openstack/files/openstack-non-virtual-ip.yaml
  templates/common/openstack/units/nodeip-configuration.service
  templates/master/00-master/openstack/files/NetworkManager-resolv-prepender.yaml
  templates/master/00-master/openstack/files/dhcp-dhclient-conf.yaml
  templates/master/00-master/openstack/files/openstack-haproxy-haproxy.yaml
  templates/master/00-master/openstack/files/openstack-keepalived-keepalived.yaml
  templates/master/01-master-kubelet/openstack/units/kubelet.yaml
  templates/worker/00-worker/openstack/files/NetworkManager-non-virtual-ip-prepender.yaml
  templates/worker/00-worker/openstack/files/NetworkManager-resolv-prepender.yaml
  templates/worker/00-worker/openstack/files/dhcp-dhclient-conf.yaml
  templates/worker/00-worker/openstack/files/openstack-non-virtual-ip.yaml
  templates/worker/01-worker-kubelet/openstack/units/kubelet.yaml
Labels: approved, lgtm, size/XL

#1463 Bug 1797687: docs: Document that MCO doesn't apply custom pool on master node
  docs/custom-pools.md
Labels: approved, bugzilla/valid-bug, lgtm, retest-not-required-docs-only, size/XS

#1484 make etcd quorum guard privileged to read files from etcd operator
  install/0000_80_machine-config-operator_07_etcdquorumguard_deployment.yaml
Labels: approved, lgtm, size/XS

#1418 Provide RoleLabelKey as const to be re-used by other operators
  pkg/apis/machineconfiguration.openshift.io/v1/types.go
  pkg/controller/template/render.go
  pkg/controller/template/render_test.go
  test/e2e/mcd_test.go
  test/e2e/utils_test.go
Labels: approved, lgtm, ok-to-test, size/S

#1498 [FCOS] pkg/daemon/update.go: check for nil pointers
  pkg/daemon/update.go
Labels: approved, lgtm, size/S

#1500 [fcos] remove the etcd-member pod because we no longer need it
  templates/master/00-master/_base/files/etc-kubernetes-manifests-etcd-member.yaml
Labels: approved, lgtm, size/L

#1494 Bug 1806001: [baremetal] Set hostname when DHCP6_FQDN_FQDN is set
  templates/master/00-master/baremetal/files/NetworkManager-resolv-prepender.yaml
  templates/worker/00-worker/baremetal/files/NetworkManager-resolv-prepender.yaml
Labels: approved, bugzilla/valid-bug, lgtm, size/XS

#1479 Bug 1802675: [release-4.3] baremetal: Verify that mdns start only after hostname was set
  templates/common/baremetal/files/NetworkManager-mdns-hostname.yaml
  templates/common/baremetal/files/baremetal-mdns-publisher.yaml
Labels: approved, bugzilla/valid-bug, cherry-pick-approved, lgtm, size/M

#1505 CRC: compare the correct object
  pkg/controller/container-runtime-config/container_runtime_config_controller.go
Labels: approved, lgtm, size/XS

#1509 CRI-O to set stream address in ctrl plane
  templates/common/baremetal/files/etc-systemd-system-crio-stream-address.conf.yaml
Labels: approved, lgtm, size/S

#1490 Bug 1797989: Changes to fix DR scripts with new CEO environment and manifests
  templates/master/00-master/_base/files/usr-local-bin-etcd-member-add-sh.yaml
  templates/master/00-master/_base/files/usr-local-bin-etcd-member-recover-sh.yaml
  templates/master/00-master/_base/files/usr-local-bin-etcd-member-remove-sh.yaml
  templates/master/00-master/_base/files/usr-local-bin-etcd-snapshot-backup-sh.yaml
  templates/master/00-master/_base/files/usr-local-bin-etcd-snapshot-restore-sh.yaml
  templates/master/00-master/_base/files/usr-local-bin-openshift-recovery-tools-sh.yaml
  templates/master/00-master/_base/files/usr-local-bin-tokenize-signer-sh.yaml
Labels: approved, bugzilla/valid-bug, lgtm, size/L

#1485 generate CRD manifests and fix for oc explain
  manifests/containerruntimeconfig.crd.yaml
  manifests/controllerconfig.crd.yaml
  manifests/kubeletconfig.crd.yaml
  manifests/machineconfig.crd.yaml
  manifests/machineconfigpool.crd.yaml
  pkg/apis/machineconfiguration.openshift.io/v1/types.go
  pkg/operator/assets/bindata.go
Labels: approved, lgtm, size/XXL

#1478 [FCOS] non-virtual-ip: replace the script with podman wrapper
  templates/worker/00-worker/baremetal/files/baremetal-non-virtual-ip.yaml
  templates/worker/00-worker/openstack/files/openstack-non-virtual-ip.yaml
  templates/worker/00-worker/ovirt/files/ovirt-non-virtual-ip.yaml
Labels: approved, lgtm, size/L

#1501 1790819: [baremetal] Add watcher sidecar container for Coredns static pod
  templates/common/baremetal/files/baremetal-coredns.yaml
Labels: approved, lgtm, size/M
