Repository openshift/machine-config-operator, pull requests merged in 2020-05, with the labels that each got.

#1458 [release-4.3] Bug 1801824: kubelet: add more system reservation to protect node
  templates/master/01-master-kubelet/_base/files/kubelet.yaml
  templates/worker/01-worker-kubelet/_base/files/kubelet.yaml
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, cherry-pick-approved, lgtm, size/XS

#1686 Bug 1817458: [release-4.3] fix wrongful backup of files not originally on the system
  pkg/daemon/update.go
Labels: approved, bugzilla/severity-urgent, bugzilla/valid-bug, cherry-pick-approved, lgtm

#1710 Bug 1829138: MC CRD: preserve unknown fields
  install/0000_80_machine-config-operator_01_machineconfig.crd.yaml
Labels: approved, bugzilla/severity-urgent, bugzilla/valid-bug, lgtm

#1711 Bug 1809345: templates: add etc-networkmanager-dispatcher.d-90-long-hostname.yaml
  templates/common/_base/files/etc-networkmanager-dispatcher.d-90-long-hostname.yaml
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, lgtm

#1714 Bug 1784201: lib/resourcemerge: set AdditionalTrustBundle
  lib/resourcemerge/machineconfig.go
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, lgtm

#1717 Bug 1832180: Exclude ovirt from syncing cloud-config sync
  pkg/controller/template/render.go
  pkg/operator/sync.go
Labels: approved, bugzilla/severity-urgent, bugzilla/valid-bug, lgtm

#1669 Bug 1811140: Add containernetworking-plugin RPM's bin location to CRI-O config
  templates/master/01-master-container-runtime/_base/files/crio.yaml
  templates/worker/01-worker-container-runtime/_base/files/crio.yaml
Labels: approved, bugzilla/severity-urgent, bugzilla/valid-bug, cherry-pick-approved, lgtm

#1689 Bug 1831866: cri-o: manage ns lifecycle, again!
  templates/master/01-master-container-runtime/_base/files/crio.yaml
  templates/worker/01-worker-container-runtime/_base/files/crio.yaml
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, lgtm

#1722 Bug 1834247: Add containernetworking-plugin RPM's bin location to CRI-O config
  templates/master/01-master-container-runtime/_base/files/crio.yaml
  templates/worker/01-worker-container-runtime/_base/files/crio.yaml
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, cherry-pick-approved, lgtm

#1731 Bug 1834895: pkg/daemon: Set AddFunc on the nodeInformer as well
  pkg/daemon/daemon.go
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, lgtm

#1728 bug 1834925: vsphere: check if .Infra.Status and .Infra.Status.PlatformStatus is nil
  templates/common/vsphere/files/NetworkManager-mdns-hostname.yaml
  templates/common/vsphere/files/etc-systemd-system-crio-stream-address.conf.yaml
  templates/common/vsphere/files/vsphere-NetworkManager-kni-conf.yaml
  templates/common/vsphere/files/vsphere-coredns-corefile.yaml
  templates/common/vsphere/files/vsphere-coredns.yaml
  templates/common/vsphere/files/vsphere-hostname.yaml
  templates/common/vsphere/files/vsphere-keepalived.yaml
  templates/common/vsphere/files/vsphere-mdns-publisher.yaml
  templates/master/00-master/vsphere/files/NetworkManager-resolv-prepender.yaml
  templates/master/00-master/vsphere/files/dhcp-dhclient-conf.yaml
  templates/master/00-master/vsphere/files/vsphere-haproxy-haproxy.yaml
  templates/master/00-master/vsphere/files/vsphere-haproxy.yaml
  templates/master/00-master/vsphere/files/vsphere-keepalived-keepalived.yaml
  templates/master/00-master/vsphere/files/vsphere-mdns-config.yaml
  templates/master/01-master-kubelet/vsphere/units/kubelet.yaml
  templates/worker/00-worker/vsphere/files/NetworkManager-resolv-prepender.yaml
  templates/worker/00-worker/vsphere/files/dhcp-dhclient-conf.yaml
  templates/worker/00-worker/vsphere/files/vsphere-keepalived-keepalived.yaml
  templates/worker/00-worker/vsphere/files/vsphere-mdns-config.yaml
  templates/worker/01-worker-kubelet/vsphere/units/kubelet.yaml
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, lgtm

#1724 Bug 1823950: [baremetal] Switch to /readyz for haproxy healthchecking
  templates/master/00-master/baremetal/files/baremetal-haproxy-haproxy.yaml
  templates/master/00-master/baremetal/files/baremetal-haproxy.yaml
  templates/master/00-master/openstack/files/openstack-haproxy-haproxy.yaml
  templates/master/00-master/openstack/files/openstack-haproxy.yaml
  templates/master/00-master/ovirt/files/ovirt-haproxy-haproxy.yaml
  templates/master/00-master/ovirt/files/ovirt-haproxy.yaml
  templates/master/00-master/vsphere/files/vsphere-haproxy-haproxy.yaml
  templates/master/00-master/vsphere/files/vsphere-haproxy.yaml
Labels: approved, bugzilla/severity-unspecified, bugzilla/valid-bug, lgtm

#1725 Bug 1817430: Parse the kubelet.conf data after an update
  pkg/controller/kubelet-config/helpers.go
Labels: approved, bugzilla/severity-low, bugzilla/valid-bug, lgtm

#1726 [release-4.3] Bug 1801430: Write environment variables needed for etcdctl execution into ~/.profile
  templates/master/00-master/_base/files/etc-kubernetes-manifests-etcd-member.yaml
Labels: approved, bugzilla/severity-low, bugzilla/valid-bug, cherry-pick-approved, lgtm

#1732 Bug 1825967: revert: etcd quorum guard: don't set hostNetwork
  install/0000_80_machine-config-operator_07_etcdquorumguard_deployment.yaml
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, lgtm

#1736 Bug 1828112: remove quotes around kubelet_node_ip to account for rhel7
  templates/master/01-master-kubelet/baremetal/units/kubelet.yaml
  templates/master/01-master-kubelet/openstack/units/kubelet.yaml
  templates/master/01-master-kubelet/vsphere/units/kubelet.yaml
  templates/worker/01-worker-kubelet/baremetal/units/kubelet.yaml
  templates/worker/01-worker-kubelet/openstack/units/kubelet.yaml
  templates/worker/01-worker-kubelet/vsphere/units/kubelet.yaml
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, lgtm

#1733 Bug 1835974: Update keepalived API script to monitor also LB health
  templates/master/00-master/baremetal/files/baremetal-keepalived-keepalived.yaml
  templates/master/00-master/openstack/files/openstack-keepalived-keepalived.yaml
  templates/master/00-master/ovirt/files/ovirt-keepalived-keepalived.yaml
  templates/master/00-master/vsphere/files/vsphere-keepalived-keepalived.yaml
Labels: approved, bugzilla/severity-unspecified, bugzilla/valid-bug, lgtm

#1708 [FCOS] Control amount of replicas in etcd-quorum-guard deployment
  cmd/machine-config-operator/bootstrap.go
  install/0000_80_machine-config-operator_02_images.configmap.yaml
  install/0000_80_machine-config-operator_07_etcdquorumguard_pdb.yaml
  manifests/etcdquorumguard_deployment.yaml
  pkg/apis/machineconfiguration.openshift.io/v1/types.go
  pkg/operator/assets/bindata.go
  pkg/operator/images.go
  pkg/operator/render_test.go
  pkg/operator/sync.go
Labels: approved, lgtm

#1670 Bug 1802534: gcp-routes: move to MCO, implement downfile, tweak timing
  cmd/gcp-routes-controller/README.md
  cmd/gcp-routes-controller/run.go
  pkg/controller/template/test_data/controller_config_aws.yaml
  pkg/controller/template/test_data/controller_config_baremetal.yaml
  pkg/controller/template/test_data/controller_config_gcp.yaml
  pkg/controller/template/test_data/controller_config_libvirt.yaml
  pkg/controller/template/test_data/controller_config_none.yaml
  pkg/controller/template/test_data/controller_config_openstack.yaml
  pkg/controller/template/test_data/controller_config_ovirt.yaml
  pkg/controller/template/test_data/controller_config_vsphere.yaml
  templates/master/00-master/gcp/files/etc-kubernetes-manifests-gcp-routes-controller.yaml
  templates/master/00-master/gcp/files/opt-libexec-openshift-gcp-routes-sh.yaml
  templates/master/00-master/gcp/units/gcp-routes.service
  templates/master/00-master/gcp/units/openshift-gcp-routes.service
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, lgtm

#1661 Bug 1825221: templates/master:openshift-recovery-tools pass --authfile to podman create
  templates/master/00-master/_base/files/usr-local-bin-openshift-recovery-tools-sh.yaml
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, cherry-pick-approved, lgtm

#1740 Bug 1804067: Prevent etcd-member-add.sh from running on an active master
  templates/master/00-master/_base/files/usr-local-bin-etcd-member-add-sh.yaml
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, cherry-pick-approved, lgtm

#1727 Bug 1834823: Write environment variables needed for etcdctl execution into ~/.profile
  templates/master/00-master/_base/files/etc-kubernetes-manifests-etcd-member.yaml
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, cherry-pick-approved, lgtm

#1748 Bug 1766346: docs: Workaround to properly apply kargs on new nodes created by machine-api
  docs/MachineConfiguration.md
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, kind/documentation, lgtm, retest-not-required-docs-only

#1735 Bug 1834194: vsphere: check if .Infra.Status and .Infra.Status.PlatformStatus is nil
  templates/common/vsphere/files/vsphere-NetworkManager-kni-conf.yaml
  templates/common/vsphere/files/vsphere-coredns-corefile.yaml
  templates/common/vsphere/files/vsphere-coredns-db.yaml
  templates/common/vsphere/files/vsphere-coredns.yaml
  templates/common/vsphere/files/vsphere-keepalived.yaml
  templates/common/vsphere/files/vsphere-mdns-publisher.yaml
  templates/master/00-master/vsphere/files/dhcp-dhclient-conf.yaml
  templates/master/00-master/vsphere/files/vsphere-haproxy-haproxy.yaml
  templates/master/00-master/vsphere/files/vsphere-haproxy.yaml
  templates/master/00-master/vsphere/files/vsphere-keepalived-keepalived.yaml
  templates/master/00-master/vsphere/files/vsphere-mdns-config.yaml
  templates/worker/00-worker/vsphere/files/dhcp-dhclient-conf.yaml
  templates/worker/00-worker/vsphere/files/vsphere-keepalived-keepalived.yaml
  templates/worker/00-worker/vsphere/files/vsphere-mdns-config.yaml
  templates/worker/00-worker/vsphere/files/vsphere-non-virtual-ip.yaml
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, cherry-pick-approved, lgtm

#1715 Bug 1764001: pkg/daemon: rollback dropins and units
  pkg/daemon/update.go
  templates/common/_base/files/etc-systemd-system-crio.service.d-10-default-env.conf.yaml
  templates/common/_base/files/etc-systemd-system-kubelet.service.d-10-default-env.conf.yaml
  templates/common/_base/files/etc-systemd-system-machine-config-daemon-host.service.d-10-default-env.conf.yaml
  templates/common/_base/files/etc-systemd-system-pivot.service.d-10-default-env.conf.yaml
  templates/common/_base/units/etc-systemd-system-crio.service.d-10-default-env.conf.yaml
  templates/common/_base/units/etc-systemd-system-kubelet.service.d-10-default-env.conf.yaml
  templates/common/_base/units/etc-systemd-system-machine-config-daemon-host.service.d-10-default-env.conf.yaml
  templates/common/_base/units/etc-systemd-system-pivot.service.d-10-default-env.conf.yaml
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, lgtm

#1739 Bug 1834948: increase eviction time to avoid preventable timeouts
  pkg/daemon/daemon.go
Labels: approved, bugzilla/severity-urgent, bugzilla/valid-bug, lgtm

#1762 Bug 1841255: machine-config-daemon-firstboot.service: Make idempotent and block kubelet
  templates/common/_base/units/machine-config-daemon-firstboot.service
Labels: approved, bugzilla/severity-urgent, bugzilla/valid-bug, lgtm

#1763 Bug 1841260: Make resolv.conf prepend operation atomic
  templates/common/baremetal/files/NetworkManager-resolv-prepender.yaml
  templates/master/00-master/openstack/files/NetworkManager-resolv-prepender.yaml
  templates/master/00-master/vsphere/files/NetworkManager-resolv-prepender.yaml
  templates/worker/00-worker/baremetal/files/NetworkManager-resolv-prepender.yaml
  templates/worker/00-worker/openstack/files/NetworkManager-resolv-prepender.yaml
  templates/worker/00-worker/vsphere/files/NetworkManager-resolv-prepender.yaml
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, lgtm

#1765 Bug 1841581: Ensure resolv.conf is in place in prepender before running podman
  templates/common/baremetal/files/NetworkManager-resolv-prepender.yaml
  templates/master/00-master/openstack/files/NetworkManager-resolv-prepender.yaml
  templates/master/00-master/vsphere/files/NetworkManager-resolv-prepender.yaml
Labels: approved, bugzilla/severity-urgent, bugzilla/valid-bug, lgtm
