Repository openshift/machine-config-operator, pull requests merged in 2020-07, with the labels that each got.

#1881 pkg/controller: sync pools configuration source
  pkg/controller/node/status.go
  pkg/controller/render/render_controller.go
  pkg/controller/render/render_controller_test.go
Labels: approved, lgtm

#1870 Bug 1851541: Correctly handle requests for ipv4/ipv6 records
  manifests/baremetal/coredns-corefile.tmpl
  pkg/operator/assets/bindata.go
  templates/common/baremetal/files/baremetal-coredns-corefile.yaml
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, cherry-pick-approved, lgtm

#1879 Bug 1848094: [baremetal] Set NonVirtualIP in mdns plugin config
  manifests/baremetal/coredns-corefile.tmpl
  pkg/operator/assets/bindata.go
  templates/common/baremetal/files/baremetal-coredns-corefile.yaml
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, cherry-pick-approved, lgtm

#1885 Bug 1745919: KubeletConfig: Validate kubeReserved and systemReserved for KubeletConfig
  pkg/controller/kubelet-config/helpers.go
  pkg/controller/kubelet-config/kubelet_config_controller_test.go
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, lgtm

#1890 [fcos] disable zincati on masters/workers
  templates/common/_base/files/etc-zincati-configd-90-disable-feature.yaml
  templates/common/_base/units/machine-config-daemon-firstboot.service.yaml
  templates/common/_base/units/machine-config-daemon-host.service.yaml
  templates/common/_base/units/machine-config-daemon-pull.service.yaml
Labels: approved, lgtm

#1563 Bug 1812649: split kernel arguments
  pkg/daemon/update.go
  pkg/daemon/update_test.go
  test/e2e/mcd_test.go
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, lgtm, size/M

#1889 [fcos] pkg/controller/common/helpers: replace duplicate files in ConvertIgnition2to3
  pkg/controller/common/helpers.go
Labels: approved, lgtm

#1820 [release-4.4] Bug 1845635: etcd-quorum-guard: update containers section in deployment.yaml
  install/0000_80_machine-config-operator_07_etcdquorumguard_deployment.yaml
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, cherry-pick-approved, lgtm

#1773 Bug 1853298: [openstack/vsphere] Move dispatcher script to common
  templates/common/openstack/files/NetworkManager-resolv-prepender.yaml
  templates/common/vsphere/files/NetworkManager-resolv-prepender.yaml
  templates/worker/00-worker/openstack/files/NetworkManager-resolv-prepender.yaml
  templates/worker/00-worker/vsphere/files/NetworkManager-resolv-prepender.yaml
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, lgtm

#1868 Bug 1840385: pkg/daemon: bubble up pivot errors
  cmd/machine-config-daemon/pivot.go
  pkg/controller/node/node_controller.go
  pkg/daemon/daemon.go
  pkg/daemon/pivot/types/imageinspection.go
  pkg/daemon/pivot/utils/run.go
  pkg/daemon/pivot/utils/run_test.go
  pkg/daemon/rpm-ostree.go
  pkg/daemon/update.go
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, lgtm

#1894 Bug 1843384: Remove IPI checks for vsphere hostname script and systemd unit
  templates/common/vsphere/files/vsphere-hostname.yaml
  templates/common/vsphere/units/vsphere-hostname.service.yaml
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, lgtm

#1902 Bug 1853735: crio: correct hooks directory
  templates/master/01-master-container-runtime/_base/files/crio.yaml
  templates/worker/01-worker-container-runtime/_base/files/crio.yaml
Labels: approved, bugzilla/severity-urgent, bugzilla/valid-bug, lgtm

#1898 [fcos] templates/common/_base/units: disable docker
  templates/common/_base/units/docker.socket.yml
Labels: approved, lgtm

#1906 templates: Fix for NM dispatcher script miscounting length
  templates/common/_base/files/etc-networkmanager-dispatcher.d-90-long-hostname.yaml
Labels: approved, lgtm

#1904 Bug 1854160: server: serve v2 if no user-agent is defined
  pkg/server/api.go
Labels: approved, bugzilla/severity-urgent, bugzilla/valid-bug, lgtm

#1899 Bug 1853890: pkg/daemon: preserve kargs order
  pkg/daemon/update.go
  pkg/daemon/update_test.go
  test/e2e/mcd_test.go
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, lgtm

#1891 pkg/daemon: make force use the force
  pkg/daemon/daemon.go
Labels: approved, lgtm

#1909 Bug 1854249: [On-Prem] Workaround issues with keepalived v2.0.10
  templates/master/00-master/baremetal/files/baremetal-keepalived-keepalived.yaml
  templates/master/00-master/baremetal/files/baremetal-keepalived-script.yaml
  templates/master/00-master/openstack/files/openstack-keepalived-keepalived.yaml
  templates/master/00-master/openstack/files/openstack-keepalived-script.yaml
  templates/master/00-master/ovirt/files/ovirt-keepalived-keepalived.yaml
  templates/master/00-master/ovirt/files/ovirt-keepalived-script.yaml
  templates/master/00-master/vsphere/files/vsphere-keepalived-keepalived.yaml
  templates/master/00-master/vsphere/files/vsphere-keepalived-script.yaml
Labels: approved, bugzilla/severity-urgent, bugzilla/valid-bug, lgtm

#1852 Bug 1849217: Sync kublelet config across platforms
  templates/master/01-master-kubelet/baremetal/units/kubelet.yaml
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, cherry-pick-approved, lgtm

#1878 Bug 1851226: Refactor mastersSchedulable reconciliation checks
  pkg/controller/node/node_controller.go
  test/e2e/mco_test.go
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, lgtm

#1871 Bug 1825339: [4.4] crio: manage ns lifecycle
  templates/master/01-master-container-runtime/_base/files/crio.yaml
  templates/worker/01-worker-container-runtime/_base/files/crio.yaml
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, cherry-pick-approved, lgtm

#1903 Add --release-image flag to bootstrap options
  cmd/machine-config-operator/bootstrap.go
Labels: approved, lgtm

#1882 Bug 1821800: Revert "OpenStack: disable tx checksum offload for workers"
  templates/worker/00-worker/openstack/files/openstack-disable-tx-checksum-offload.yaml
Labels: approved, bugzilla/severity-low, bugzilla/valid-bug, lgtm

#1795 Bug 1845492: daemon: fix restoring file logic to avoid unnecessary deletion
  pkg/daemon/update.go
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, cherry-pick-approved, lgtm

#1913 Bug 1826021: Fix a problem with a greedy regular expression matching more than needed
  templates/master/00-master/_base/files/usr-local-bin-openshift-recovery-tools-sh.yaml
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, cherry-pick-approved, lgtm

#1848 Add retry loop to nodeip-configuration service
  templates/common/baremetal/units/nodeip-configuration.service.yaml
  templates/common/openstack/units/nodeip-configuration.service.yaml
  templates/common/vsphere/units/nodeip-configuration.service.yaml
Labels: approved, lgtm

#1874 Bug 1851344: Pass proxy settings nodeip-configuration service for baremetal, vsphere, openstack
  templates/common/_base/units/machine-config-daemon-firstboot.service.yaml
  templates/common/baremetal/files/NetworkManager-resolv-prepender.yaml
  templates/common/baremetal/units/nodeip-configuration.service.yaml
  templates/common/openstack/files/NetworkManager-resolv-prepender.yaml
  templates/common/openstack/units/nodeip-configuration.service.yaml
  templates/common/ovirt/files/NetworkManager-resolv-prepender.yaml
  templates/common/vsphere/files/NetworkManager-resolv-prepender.yaml
  templates/common/vsphere/units/nodeip-configuration.service.yaml
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, lgtm

#1895 pkg/daemon: unexport pkg functions/structs
  pkg/daemon/update.go
  pkg/daemon/update_test.go
Labels: approved, lgtm

#1911 [baremetal & friends] Clean up keepalived script warnings
  templates/master/00-master/baremetal/files/baremetal-keepalived-keepalived.yaml
  templates/master/00-master/openstack/files/openstack-keepalived-keepalived.yaml
  templates/master/00-master/ovirt/files/ovirt-keepalived-keepalived.yaml
  templates/master/00-master/vsphere/files/vsphere-keepalived-keepalived.yaml
Labels: approved, lgtm

#1873 *: Ign spec 3 upgrade
  go.sum
  lib/resourceapply/machineconfig_test.go
  pkg/controller/bootstrap/bootstrap_test.go
  pkg/controller/bootstrap/testdata/bootstrap/99_openshift-machineconfig_master.yaml
  pkg/controller/bootstrap/testdata/bootstrap/99_openshift-machineconfig_worker.yaml
  pkg/controller/common/helpers.go
  pkg/controller/common/helpers_test.go
  pkg/controller/container-runtime-config/container_runtime_config_controller.go
  pkg/controller/container-runtime-config/container_runtime_config_controller_test.go
  pkg/controller/container-runtime-config/helpers.go
  pkg/controller/kubelet-config/helpers.go
  pkg/controller/kubelet-config/kubelet_config_controller.go
  pkg/controller/kubelet-config/kubelet_config_controller_test.go
  pkg/controller/kubelet-config/kubelet_config_features.go
  pkg/controller/kubelet-config/kubelet_config_features_test.go
  pkg/controller/render/render_controller.go
  pkg/controller/render/render_controller_test.go
  pkg/controller/template/render_test.go
  pkg/daemon/daemon.go
  pkg/daemon/daemon_test.go
  pkg/daemon/update.go
  pkg/daemon/update_test.go
  pkg/server/api.go
  pkg/server/server.go
  pkg/server/server_test.go
  test/e2e/mcd_test.go
  test/helpers/helpers.go
Labels: approved, lgtm

#1914 Bug 1853584: templates: node hostnames: ensure RHCOS hostnames are mostly valid
  templates/common/_base/files/etc-networkmanager-dispatcher.d-90-long-hostname.yaml
  templates/common/_base/files/usr-local-sbin-set-valid-hostname.yaml
  templates/common/_base/units/node-valid-hostname.service
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, lgtm

#1925 Add kernel arg tuneable allowlist for FCOS
  cmd/machine-config-daemon/pivot.go
  pkg/daemon/daemon.go
  pkg/daemon/osrelease.go
  pkg/daemon/update.go
  pkg/daemon/update_test.go
Labels: approved, lgtm

#1919 templates/common/_base/units: disable Zincati service
  templates/common/_base/units/zincati.service.yaml
Labels: approved, lgtm

#1931 cleanup: remove setup-etcd-environment
  Makefile
  cmd/machine-config-operator/bootstrap.go
  cmd/setup-etcd-environment/OWNERS
  cmd/setup-etcd-environment/main.go
  cmd/setup-etcd-environment/run.go
  cmd/setup-etcd-environment/run_test.go
  cmd/setup-etcd-environment/version.go
  go.mod
  go.sum
  vendor/github.com/joho/godotenv/.gitignore
  vendor/github.com/joho/godotenv/.travis.yml
  vendor/github.com/joho/godotenv/LICENCE
  vendor/github.com/joho/godotenv/README.md
  vendor/github.com/joho/godotenv/godotenv.go
  vendor/github.com/openshift/cluster-etcd-operator/LICENSE
  vendor/github.com/openshift/cluster-etcd-operator/pkg/operator/api/scaling.go
  vendor/modules.txt
Labels: approved, lgtm

#1930 Disable docker socket
  templates/common/_base/units/docker.socket.yaml
Labels: approved, lgtm

#1935 Bug 1858026: add nil check for infra.Status.PlatformStatus in isCloudConfigReqd
  lib/resourcemerge/machineconfig.go
  pkg/controller/template/render.go
  pkg/operator/sync.go
  pkg/operator/sync_test.go
Labels: approved, bugzilla/severity-urgent, bugzilla/valid-bug, lgtm

#1886 [fcos] Update base image in Dockerfile
  Dockerfile
  Dockerfile.rhel7
  Makefile
Labels: approved, lgtm

#1929 [fcos] templates/common/_base/units: rename docker.socket.yml
  templates/common/_base/units/docker.socket.yaml
Labels: approved, lgtm

#1934 Change manifest file mode to 0644
  pkg/operator/bootstrap.go
Labels: approved, lgtm

#1927 Bug 1854801: Make sure openvswitch related services are always restarted
  templates/common/_base/units/ovs-vswitchd.service.yaml
  templates/common/_base/units/ovsdb-server.service
Labels: approved, bugzilla/severity-urgent, bugzilla/valid-bug, lgtm

#1872 Bug 1849432: [baremetal] verify resolv.conf in HAProxy static pod synced with host resolv.conf
  templates/master/00-master/baremetal/files/baremetal-haproxy.yaml
  templates/master/00-master/openstack/files/openstack-haproxy.yaml
  templates/master/00-master/ovirt/files/ovirt-haproxy.yaml
  templates/master/00-master/vsphere/files/vsphere-haproxy.yaml
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, lgtm

#1939 [release 4.5] Bug 1855877: cherry-pick hostname fixes
  templates/common/_base/files/etc-networkmanager-dispatcher.d-90-long-hostname.yaml
  templates/common/_base/files/usr-local-sbin-set-valid-hostname.yaml
  templates/common/_base/units/node-valid-hostname.service
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, cherry-pick-approved, lgtm

#1936 Bug 1858907: add nil check for infra.Status.PlatformStatus in isCloudConfigReqd
  pkg/operator/sync.go
  pkg/operator/sync_test.go
Labels: approved, bugzilla/severity-urgent, bugzilla/valid-bug, cherry-pick-approved, lgtm

#1768 [baremetal] Update keepalived to support both multicast and unicast modes (default=multicast)
  manifests/baremetal/keepalived.conf.tmpl
  manifests/baremetal/keepalived.yaml
  pkg/operator/assets/bindata.go
  templates/common/baremetal/files/baremetal-keepalived.yaml
  templates/master/00-master/baremetal/files/baremetal-keepalived-keepalived.yaml
  templates/worker/00-worker/baremetal/files/baremetal-keepalived-keepalived.yaml
Labels: approved, lgtm

#1796 Bug 1845494: daemon: fix restoring file logic to avoid unnecessary deletion
  pkg/daemon/update.go
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, cherry-pick-approved, lgtm

#1945 Bug 1859230: operator/sync: update getIgnitionHost to account for nil PlatformStatus
  pkg/operator/sync.go
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, lgtm

#1942 Update kernel args on firstboot-complete
  cmd/machine-config-daemon/pivot.go
  go.sum
  pkg/daemon/daemon.go
  pkg/daemon/kernelargs.go
Labels: approved, lgtm

#1759 [baremetal & friends] Give coredns and mdns-publisher init containers unique names
  templates/common/baremetal/files/baremetal-coredns.yaml
  templates/common/baremetal/files/baremetal-mdns-publisher.yaml
  templates/common/openstack/files/openstack-coredns.yaml
  templates/common/openstack/files/openstack-mdns-publisher.yaml
  templates/common/ovirt/files/ovirt-coredns.yaml
  templates/common/ovirt/files/ovirt-mdns-publisher.yaml
  templates/common/vsphere/files/vsphere-coredns.yaml
  templates/common/vsphere/files/vsphere-mdns-publisher.yaml
Labels: approved, lgtm

#1884 tests/e2e: Refactor and reduce test run time
  Makefile
  test/e2e/mcd_test.go
  test/e2e/utils_test.go
Labels: approved, lgtm

#1951 vsphere: check for nil platform in getIgnitionHost
  pkg/operator/sync.go
Labels: approved, lgtm

#1944 Set NonVirtualIP in non-baremetal mdns platforms
  manifests/openstack/coredns-corefile.tmpl
  manifests/ovirt/coredns-corefile.tmpl
  manifests/vsphere/coredns-corefile.tmpl
  pkg/operator/assets/bindata.go
  templates/common/openstack/files/openstack-coredns-corefile.yaml
  templates/common/ovirt/files/ovirt-coredns-corefile.yaml
  templates/common/vsphere/files/vsphere-coredns-corefile.yaml
Labels: approved, lgtm

#1952 test/e2e: cleanup - remove commented out lines
  test/e2e/mcd_test.go
Labels: approved, lgtm

#1928 *: Remove files used for etcd-quorum-guard, as it is being migrated to...
  docs/etcd-quorum-guard.md
  install/0000_80_machine-config-operator_07_etcdquorumguard_deployment.yaml
  install/0000_80_machine-config-operator_08_etcdquorumguard_pdb.yaml
  install/image-references
  test/e2e/etcdquorumguard_test.go
Labels: approved, lgtm

#1860 Configure OVS NIC for OVN
  templates/common/_base/files/configure-ovs-network.yaml
  templates/common/_base/units/ovs-configuration.service.yaml
  templates/master/00-master/gcp/units/openshift-gcp-routes.service.yaml
Labels: approved, do-not-merge/hold, lgtm

#1947 Controlplane upgrades prep
  pkg/controller/common/constants.go
  pkg/controller/node/node_controller.go
  pkg/controller/node/node_controller_test.go
  pkg/daemon/daemon.go
  test/e2e/mco_test.go
Labels: approved, lgtm

#1959 Bug 1861876: telemetry: change MCDDrainErr from critical to warning
  install/0000_90_machine-config-operator_01_prometheus-rules.yaml
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, lgtm

#1969 test/e2e: check that kernel-rt-core pacakge is installed
  test/e2e/mcd_test.go
Labels: approved, lgtm

#1970 IgnParseWrapper: return better errors
  pkg/controller/common/helpers.go
Labels: approved, lgtm
