Repository openshift/machine-config-operator, pull requests merged in 2021-03, with the labels that each got.

#2444 Bug 1932105: pkg/operator/sync: More logging for syncRequiredMachineConfigPools
  pkg/operator/status.go
  pkg/operator/sync.go
Labels: approved, bugzilla/severity-urgent, bugzilla/valid-bug, lgtm

#2324 OCPNODE-464: add tls security profile support
  go.mod
  go.sum
  pkg/apis/machineconfiguration.openshift.io/v1/types.go
  pkg/apis/machineconfiguration.openshift.io/v1/zz_generated.deepcopy.go
  pkg/controller/kubelet-config/kubelet_config_controller.go
  templates/master/01-master-kubelet/_base/files/kubelet.yaml
  templates/worker/01-worker-kubelet/_base/files/kubelet.yaml
  vendor/github.com/openshift/library-go/pkg/crypto/crypto.go
  vendor/github.com/openshift/library-go/pkg/crypto/rotation.go
  vendor/github.com/openshift/library-go/pkg/operator/v1helpers/test_helpers.go
  vendor/k8s.io/apiserver/LICENSE
  vendor/k8s.io/apiserver/pkg/authentication/user/doc.go
  vendor/k8s.io/apiserver/pkg/authentication/user/user.go
  vendor/k8s.io/code-generator/generate-groups.sh
  vendor/k8s.io/code-generator/generate-internal-groups.sh
  vendor/modules.txt
Labels: 4.8, approved, lgtm

#2424 Bug 1931522: OVS Config: fixes detecting bond NM files with static IP
  templates/common/_base/files/configure-ovs-network.yaml
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, lgtm

#2446 Bug 1933805: Add node label to service monitor
  install/0000_90_machine-config-operator_00_servicemonitor.yaml
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, lgtm

#2435 [release-4.6] Bug 1933075: backport systemd dropin/units zero-length handling
  pkg/daemon/daemon.go
  pkg/daemon/update.go
Labels: 4.6, approved, bugzilla/severity-urgent, bugzilla/valid-bug, cherry-pick-approved, lgtm

#2448 Bug 1930636: Fix overlaySize & pidslimit ctrcfg
  pkg/apis/machineconfiguration.openshift.io/v1/types.go
  pkg/apis/machineconfiguration.openshift.io/v1/zz_generated.deepcopy.go
  pkg/controller/container-runtime-config/container_runtime_config_controller.go
  pkg/controller/container-runtime-config/container_runtime_config_controller_test.go
  pkg/controller/container-runtime-config/helpers.go
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, lgtm

#2418 [release-4.7] Bug 1927405: Fixes ovs-configuration with cloned connections
  templates/common/_base/files/configure-ovs-network.yaml
Labels: 4.7, approved, bugzilla/severity-high, bugzilla/valid-bug, cherry-pick-approved, lgtm

#2449 Bug 1934113: Improve error handling for os updates
  pkg/daemon/rpm-ostree.go
  pkg/daemon/update.go
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, lgtm

#2414 Bug 1902963: templates: add After=ostree-finalize-staged.service to kubelet.service
  templates/master/01-master-kubelet/_base/units/kubelet.service.yaml
  templates/master/01-master-kubelet/on-prem/units/kubelet.service.yaml
  templates/worker/01-worker-kubelet/_base/units/kubelet.service.yaml
  templates/worker/01-worker-kubelet/on-prem/units/kubelet.service.yaml
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, lgtm

#2452 Bug 1931615: OVS Config: fixes detecting bond NM files with static IP
  templates/common/_base/files/configure-ovs-network.yaml
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, cherry-pick-approved, lgtm

#2459 Bug 1840881: Make getting the suffix of a kubeletconfig MC more robust
  pkg/controller/kubelet-config/helpers.go
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, lgtm

#2464 Bug 1939278: Backport kubelet CA no-drain rotation
  pkg/daemon/update.go
  pkg/daemon/update_test.go
  pkg/operator/bootstrap.go
  pkg/operator/sync.go
Labels: 4.7, approved, bugzilla/severity-urgent, bugzilla/valid-bug, cherry-pick-approved, lgtm

#2462 [release-4.7] Bug 1929257: Fix 1:1 mapping for kubeletconfig:MC and some e2e test fixes
  pkg/controller/kubelet-config/helpers.go
  test/e2e/kubeletcfg_test.go
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, cherry-pick-approved, lgtm

#2457 Skip drain on Single Node deployment
  cmd/machine-config-controller/start.go
  manifests/controllerconfig.crd.yaml
  pkg/controller/node/node_controller.go
  pkg/controller/node/node_controller_test.go
  pkg/daemon/constants/constants.go
  pkg/daemon/daemon.go
  pkg/daemon/drain.go
  pkg/daemon/update.go
  pkg/operator/assets/bindata.go
Labels: approved, lgtm

#1743 Bump haproxy http-request timeout to 30 seconds
  templates/master/00-master/on-prem/files/haproxy-haproxy.yaml
Labels: approved, lgtm

#2463 Bug 1939270: pkg/operator/status: Use 'DegradedPool' reason for Upgradeable=False
  pkg/operator/status.go
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, lgtm

#2458 Bug 1825417: Make getting the suffix of an MC more robust
  pkg/controller/container-runtime-config/helpers.go
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, lgtm

#2472 Bug 1935539: vSphere: Disable tx udp_csum segmentation
  templates/common/vsphere/files/vsphere-disable-vmxnet3v4-features.yaml
Labels: approved, bugzilla/severity-urgent, bugzilla/valid-bug, lgtm

#2474 Makefile: Bump test-e2e timeout to 90 minutes
  Makefile
Labels: approved, lgtm

#2453 Bug 1931617: OVS Config: fixes detecting bond NM files with static IP
  templates/common/_base/files/configure-ovs-network.yaml
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, cherry-pick-approved, lgtm

#2485 Bug 1930636: fix error print verb
  pkg/controller/container-runtime-config/helpers.go
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, lgtm

#2483 Update Update-SSHKeys.md
  docs/Update-SSHKeys.md
Labels: approved, lgtm, ok-to-test

#2468 Bug 1938084: configure-ovs.sh:incorrect setting of cloned-mac-address field
  templates/common/_base/files/configure-ovs-network.yaml
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, lgtm, ok-to-test

#2486 Fixes: Bug 1942207: [vsphere] hostnames are changed when upgrading from 4.6 to 4.7.x causing upgrades to fail
  templates/common/vsphere/units/vsphere-hostname.service.yaml
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, lgtm

#2489 Bug 1940950: Strengthen kubelet service dependency on crio service
  templates/master/01-master-kubelet/_base/units/kubelet.service.yaml
  templates/worker/01-worker-kubelet/_base/units/kubelet.service.yaml
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, do-not-merge/hold, lgtm

#2467 Bug 1883916: [4.6z backport] Fixes setting route metric for ovs-config
  templates/common/_base/files/configure-ovs-network.yaml
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, cherry-pick-approved, lgtm

#2491 Bug 1943145: Strengthen kubelet service dependency on crio service
  templates/master/01-master-kubelet/on-prem/units/kubelet.service.yaml
  templates/worker/01-worker-kubelet/on-prem/units/kubelet.service.yaml
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, lgtm

#2477 Bug 1925698: not allow healthcheck traffic to loop through the node
  templates/master/00-master/gcp/files/opt-libexec-openshift-gcp-routes-sh.yaml
Labels: bugzilla/severity-urgent, bugzilla/valid-bug

#2482 Bug 1935539: vSphere: udp tnl workaround cannot use nmcli
  templates/common/vsphere/files/vsphere-disable-vmxnet3v4-features.yaml
Labels: approved, bugzilla/severity-urgent, bugzilla/valid-bug, lgtm

#2466 OCPNODE-367: Auto node sizing for Openshift
  docs/KubeletConfigDesign.md
  install/0000_80_machine-config-operator_01_kubeletconfig.crd.yaml
  pkg/apis/machineconfiguration.openshift.io/v1/types.go
  pkg/apis/machineconfiguration.openshift.io/v1/zz_generated.deepcopy.go
  pkg/controller/kubelet-config/helpers.go
  pkg/controller/kubelet-config/kubelet_config_controller.go
  pkg/controller/kubelet-config/kubelet_config_controller_test.go
  templates/common/_base/files/kubelet-auto-node-sizing-enabled.yaml
  templates/common/_base/files/kubelet-auto-sizing.yaml
  templates/common/_base/units/kubelet-auto-node-size.service.yaml
  templates/master/01-master-kubelet/_base/files/kubelet.yaml
  templates/master/01-master-kubelet/_base/units/kubelet.service.yaml
  templates/master/01-master-kubelet/on-prem/units/kubelet.service.yaml
  templates/worker/01-worker-kubelet/_base/files/kubelet.yaml
  templates/worker/01-worker-kubelet/_base/units/kubelet.service.yaml
  templates/worker/01-worker-kubelet/on-prem/units/kubelet.service.yaml
Labels: approved, lgtm

#2494 Bug 1941936: drop LogSizeMax and OverlaySize in ContainerRuntimeConfiguration when not used
  pkg/apis/machineconfiguration.openshift.io/v1/types.go
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, lgtm

#2470 Bug 1940939: Do "systemctl daemon-reload" after running "runtimecfg node-ip"
  templates/common/_base/units/nodeip-configuration.service.yaml
  templates/common/on-prem/units/nodeip-configuration.service.yaml
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, lgtm

#2495 Bug 1941246: vSphere: Disable tx-udp-tnl offload
  templates/common/vsphere/files/vsphere-disable-vmxnet3v4-features.yaml
Labels: approved, bugzilla/severity-urgent, bugzilla/valid-bug, cherry-pick-approved, lgtm

#2367 Bug 1920670: [Baremetal and friends] Properly handle SIGTERM - Keepalived container
  templates/common/on-prem/files/keepalived.yaml
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, lgtm

#2492 Bug 1943329: add tlsSecurityProfile to KubeletConfig manifest
  install/0000_80_machine-config-operator_01_kubeletconfig.crd.yaml
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, lgtm

#2493 Bug 1940585: conditionally set nodeip-service enabled for vSphere
  templates/common/vsphere/units/nodeip-configuration.service.yaml
Labels: approved, bugzilla/severity-urgent, bugzilla/valid-bug, cherry-pick-approved, lgtm

#2505 vSphere: Update reviewers and approvers
  OWNERS_ALIASES
Labels: approved, lgtm
