Repository openshift/machine-config-operator, pull requests merged in 2021-06, with the labels that each got.

#2579 Bug 1960035: Use host's iptables binary in keepalived container
  templates/common/on-prem/files/keepalived.yaml
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, lgtm

#2575 Bug 1921937: crio: reject /etc/hostname mount if absent
  templates/master/01-master-container-runtime/_base/files/crio.yaml
  templates/worker/01-worker-container-runtime/_base/files/crio.yaml
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, lgtm

#2413 Bug 1927042: [baremetal & friends] Don't write empty static pod manifests
  templates/common/on-prem/files/coredns.yaml
  templates/common/on-prem/files/keepalived.yaml
  templates/master/00-master/on-prem/files/haproxy.yaml
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, lgtm

#2580 Bug 1966602: Don't explicitly set the IPv6DualStack feature gate
  templates/master/01-master-kubelet/_base/files/kubelet.yaml
  templates/worker/01-worker-kubelet/_base/files/kubelet.yaml
Labels: approved, bugzilla/severity-urgent, bugzilla/valid-bug, lgtm

#2586 Bug 1916890: Stop setting nopreempt on bootstrap keepalived.conf
  manifests/on-prem/keepalived.conf.tmpl
  pkg/operator/assets/bindata.go
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, lgtm

#2545 Bug 1953493: daemon: return nil for unsupported operation on an OS
  pkg/daemon/update.go
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, cherry-pick-approved, lgtm

#2589 Bug 1942506: [4.6] Use new --prefer-ipv6 flag to "runtimecfg node-ip" as appropriate
  templates/common/_base/units/nodeip-configuration.service.yaml
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, cherry-pick-approved, lgtm

#2597 Bug 1968019: Bump drain timeout to 1h
  install/0000_90_machine-config-operator_01_prometheus-rules.yaml
  pkg/daemon/drain.go
  pkg/daemon/metrics.go
Labels: approved, bugzilla/severity-urgent, bugzilla/valid-bug, lgtm

#2603 Bug 1817075: operator/controller pods: faster leader elections
  cmd/common/helpers.go
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, lgtm

#2601 Bug 1969681: maxUnavailable of ds/machine-config-daemon isn't changed even after Bug 1899535 was fixed
  lib/resourcemerge/apps.go
  lib/resourcemerge/apps_test.go
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, lgtm

#2598 Bug 1946584: Check suffix annotation is a number
  pkg/controller/container-runtime-config/container_runtime_config_controller.go
  pkg/controller/kubelet-config/kubelet_config_controller.go
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, lgtm

#2596 Bug 1943315: daemon: make node drain logic smarter for ICSP changes
  pkg/daemon/drain.go
  pkg/daemon/drain_test.go
  pkg/daemon/update.go
Labels: approved, bugzilla/severity-urgent, bugzilla/valid-bug, lgtm

#2587 Bug 1958812: daemon: Rework rpm-ostree synchronous invocation logging
  pkg/daemon/rpm-ostree.go
  pkg/daemon/update.go
  pkg/daemon/update_test.go
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, lgtm

#2605 [release-4.7] Bug 1968759: Bump drain timeout to 1h
  Makefile
  install/0000_90_machine-config-operator_01_prometheus-rules.yaml
  pkg/daemon/metrics.go
  pkg/daemon/update.go
Labels: 4.7, approved, bugzilla/severity-urgent, bugzilla/valid-bug, cherry-pick-approved, lgtm

#2607 [release-4.7] Bug 1970154: operator/sync.go confirm renderedconfig osimageurl matches cvo
  pkg/controller/render/render_controller.go
  pkg/operator/status.go
  pkg/operator/status_test.go
  pkg/operator/sync.go
Labels: approved, bugzilla/severity-urgent, bugzilla/valid-bug, cherry-pick-approved, lgtm

#2611 Bug 1971080: daemon/drain.go: bump initial drain sleeps down to 1min
  pkg/daemon/drain.go
Labels: approved, bugzilla/severity-urgent, bugzilla/valid-bug, lgtm

#2595 Bug 1886572: [on-prem] set keepalived ingress priority to variable
  templates/master/00-master/on-prem/files/keepalived-keepalived.yaml
  templates/worker/00-worker/on-prem/files/keepalived-keepalived.yaml
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, lgtm

#2614 Remove Fedosin from Owners
  OWNERS_ALIASES
Labels: approved, lgtm

#2612 [release-4.7] Bug 1971374: daemon/drain.go: bump initial drain sleeps down to 1min
  pkg/daemon/update.go
Labels: approved, bugzilla/severity-urgent, bugzilla/valid-bug, cherry-pick-approved, lgtm

#2615 [release-4.6] Bug 1927555: [vsphere] set hostname with --static to provide consistent node name for CSR approval
  templates/common/vsphere/files/vsphere-hostname.yaml
  templates/common/vsphere/units/vsphere-hostname.service.yaml
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, cherry-pick-approved, lgtm

#2620 [release-4.7] Bug 1961341: rbac: update remaining apis to v1
  install/0000_80_machine-config-operator_03_rbac.yaml
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, cherry-pick-approved, lgtm

#2480 Bug 1940594: [baremetal and friends] Drop unnecessary readiness probes
  templates/common/baremetal/files/baremetal-coredns.yaml
  templates/common/baremetal/files/baremetal-keepalived.yaml
  templates/common/openstack/files/openstack-coredns.yaml
  templates/common/ovirt/files/ovirt-coredns.yaml
  templates/common/vsphere/files/vsphere-coredns.yaml
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, cherry-pick-approved, lgtm

#2623 Bug 1973006: daemon: cordon the node before performing drain
  pkg/daemon/daemon.go
  pkg/daemon/update.go
Labels: approved, bugzilla/severity-urgent, bugzilla/valid-bug, cherry-pick-approved, lgtm

#2618 Bug 1956836: templates: Rework node-valid-hostname to fix SELinux denial
  templates/common/_base/files/usr-local-bin-mco-hostname.yaml
  templates/common/_base/files/usr-local-sbin-set-valid-hostname.yaml
  templates/common/_base/units/node-valid-hostname.service.yaml
  templates/common/gcp/units/gcp-hostname.service.yaml
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, lgtm

#2624 Bug 1971899: match tlsSecurityProfile doc with kubelet.conf file
  install/0000_80_machine-config-operator_01_kubeletconfig.crd.yaml
Labels: approved, bugzilla/severity-low, bugzilla/valid-bug, lgtm

#2625 go.mod: switch to Go 1.16
  Dockerfile
  docs/HACKING.md
  go.mod
  go.sum
  vendor/modules.txt
Labels: approved, lgtm

#2578 Clean up keepalived log messages
  templates/master/00-master/on-prem/files/keepalived-keepalived.yaml
  templates/worker/00-worker/on-prem/files/keepalived-keepalived.yaml
Labels: approved, lgtm

#2602 Add Dockerfile for proxy test image
  Dockerfile.proxy
  docs/openshift-proxy-pull-test.md
Labels: 4.9, approved, lgtm

#2633 templates: Silence audit events from container infra by default
  templates/common/_base/files/audit-quiet-containers.yaml
Labels: approved, lgtm

#2631 Bug 1965992: Gracefully shutdown taking around 6-7 mins (libvirt provider)
  pkg/daemon/update.go
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, lgtm

#2386 [OCPCLOUD-1107] External cloud-provider support via FeatureGate in post-install
  cmd/machine-config-controller/start.go
  go.mod
  go.sum
  pkg/controller/common/constants.go
  pkg/controller/kubelet-config/helpers.go
  pkg/controller/kubelet-config/kubelet_config_controller.go
  pkg/controller/kubelet-config/kubelet_config_features.go
  pkg/controller/kubelet-config/kubelet_config_features_test.go
  pkg/controller/template/render.go
  pkg/controller/template/render_test.go
  pkg/controller/template/template_controller.go
  pkg/controller/template/template_controller_test.go
  vendor/github.com/openshift/library-go/pkg/cloudprovider/external.go
  vendor/modules.txt
Labels: approved, lgtm

#2626 Bug 1971715: configure-ovs: fix nondeterministic master in slave profiles
  templates/common/_base/files/configure-ovs-network.yaml
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, lgtm

#2401 [OCPCLOUD-1106] Add afterburn task to update AWS hostname to match instance metadata
  templates/common/_base/files/usr-local-bin-mco-hostname.yaml
  templates/common/aws/files/etc-networkmanager-conf.d-hostname.yaml
  templates/common/aws/units/aws-hostname.service.yaml
Labels: approved, lgtm

#2642 daemon: Dump systemctl status rpm-ostreed on load failure
  pkg/daemon/daemon.go
Labels: approved, lgtm

#2645 Bug 1934443: Fix team config JSON format for nmcli command
  templates/common/_base/files/configure-ovs-network.yaml
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, lgtm
