Repository openshift/machine-config-operator, pull requests merged in 2021-05, with the labels that each got.

#2548 Bug 1931505: [On-prem] - fix vip filtering syntax for Keepalived remove-vips
  templates/common/on-prem/files/keepalived.yaml
Labels: approved, bugzilla/severity-urgent, bugzilla/valid-bug, lgtm

#2559 Bug 1952358: vsphere: platform none, vmxnet3v4 fix move to base
  templates/common/_base/files/vsphere-disable-vmxnet3v4-features.yaml
Labels: approved, bugzilla/severity-urgent, bugzilla/valid-bug, lgtm

#2465 Bug 1946506: Add hosts template for monitor-based resolution
  manifests/on-prem/coredns-corefile.tmpl
  pkg/operator/assets/bindata.go
  templates/common/on-prem/files/coredns-corefile.yaml
  templates/common/on-prem/files/coredns.yaml
  templates/common/on-prem/files/mdns-publisher.yaml
  templates/common/openstack/files/coredns-corefile.yaml
  templates/common/openstack/files/openstack-coredns-db.yaml
  templates/common/ovirt/files/coredns-corefile.yaml
  templates/common/ovirt/files/ovirt-coredns-db.yaml
  templates/common/vsphere/files/coredns-corefile.yaml
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, lgtm

#2555 Bug 1953846: Subtract hugepages from memory capacity and allocatables
  install/0000_90_machine-config-operator_01_prometheus-rules.yaml
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, lgtm

#2561 Bug 1956372: gcp-routes should wait until network is stopped
  templates/master/00-master/gcp/units/openshift-gcp-routes.service.yaml
Labels: approved, bugzilla/severity-urgent, bugzilla/valid-bug, lgtm

#2566 Bug 1957015: [on-prem] Backport duplicate VIP fixes
  templates/common/on-prem/files/keepalived.yaml
Labels: approved, bugzilla/severity-urgent, bugzilla/valid-bug, cherry-pick-approved, lgtm

#2439 [release-4.6] Bug 1933206: Revert "pkg/daemon: Add IgnitionVersion to Daemon"
  pkg/daemon/daemon.go
Labels: 4.6, approved, bugzilla/severity-medium, bugzilla/valid-bug, cherry-pick-approved, lgtm

#2568 Bug 1957374: install: Automatically fill in the pod for MCDDrainError
  install/0000_90_machine-config-operator_01_prometheus-rules.yaml
Labels: approved, bugzilla/severity-low, bugzilla/valid-bug, lgtm

#2565 Bug 1947066: Allow wildcard in noProxy field
  manifests/machineconfigdaemon/daemonset.yaml
  pkg/operator/assets/bindata.go
  pkg/operator/render_test.go
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, lgtm

#2572 Bug 1947791: Switch CRDs to v1
  cmd/machine-config-operator/start.go
  docs/ContainerRuntimeConfigDesign.md
  docs/KubeletConfigDesign.md
  examples/controllerconfig.crd.yaml
  examples/machineconfig.crd.yaml
  examples/machineconfigpool.crd.yaml
  install/0000_80_machine-config-operator_01_containerruntimeconfig.crd.yaml
  install/0000_80_machine-config-operator_01_kubeletconfig.crd.yaml
  install/0000_80_machine-config-operator_01_machineconfig.crd.yaml
  install/0000_80_machine-config-operator_01_machineconfigpool.crd.yaml
  install/0000_80_machine-config-operator_03_rbac.yaml
  lib/resourceapply/apiext.go
  lib/resourcemerge/apiext.go
  lib/resourceread/apiext.go
  manifests/controllerconfig.crd.yaml
  pkg/operator/assets/bindata.go
  pkg/operator/operator.go
  pkg/operator/sync.go
  test/framework/clientset.go
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, lgtm

#2567 Bug 1948533: Add nodeip-configuration.service for oVirt
  templates/common/ovirt/units/nodeip-configuration.service.yaml
Labels: approved, bugzilla/severity-urgent, bugzilla/valid-bug, cherry-pick-approved, lgtm

#2442 Bug 1917282: Explicitly set keyfile as the default plugin of NetworkManager for RHEL7
  templates/common/_base/files/NetworkManager-keyfiles.yaml
  templates/common/_base/files/configure-ovs-network.yaml
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, lgtm

#2551 Bug 1943539: templates: order service files that use podman around crio-wipe
  templates/common/_base/units/machine-config-daemon-firstboot.service.yaml
  templates/common/_base/units/machine-config-daemon-pull.service.yaml
  templates/common/_base/units/nodeip-configuration.service.yaml
  templates/common/on-prem/units/nodeip-configuration.service.yaml
Labels: approved, bugzilla/severity-urgent, bugzilla/valid-bug, lgtm

#2584 docs/README: Useless bump to get a new commit hash
  docs/README.md
Labels: approved, bugzilla/valid-bug, cherry-pick-approved, lgtm

#2571 Bug 1957972: Remove remnants of mdns functionality
  templates/common/on-prem/files/NetworkManager-mdns-hostname.yaml
  templates/common/on-prem/files/mdns-config.yaml
Labels: approved, bugzilla/severity-low, bugzilla/valid-bug, lgtm

#2583 Bug 1958812: daemon: Change runGetOut to not intermix stdout/stderr
  pkg/daemon/rpm-ostree.go
  pkg/daemon/update_test.go
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, lgtm

#2574 Bug 1948137: crio: enable internal_wipe option
  templates/master/01-master-container-runtime/_base/files/crio.yaml
  templates/worker/01-worker-container-runtime/_base/files/crio.yaml
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, lgtm

#2570 Bug 1955517: Add cleanUpDuplicatedMC
  pkg/controller/container-runtime-config/container_runtime_config_controller.go
  pkg/controller/container-runtime-config/container_runtime_config_controller_test.go
  pkg/controller/kubelet-config/helpers.go
  pkg/controller/kubelet-config/kubelet_config_controller.go
  pkg/controller/kubelet-config/kubelet_config_controller_test.go
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, lgtm

#2585 Bug 1955929: operator/sync.go confirm renderedconfig osimageurl matches cvo
  pkg/controller/render/render_controller.go
  pkg/operator/status.go
  pkg/operator/status_test.go
  pkg/operator/sync.go
Labels: approved, bugzilla/severity-urgent, bugzilla/valid-bug, lgtm

#2573 Bug 1958391: configure kubelet with apiserver TLSSecurityProfile
  cmd/machine-config-controller/start.go
  manifests/machineconfigcontroller/clusterrole.yaml
  pkg/apis/machineconfiguration.openshift.io/v1/types.go
  pkg/controller/kubelet-config/kubelet_config_controller.go
  pkg/controller/kubelet-config/kubelet_config_controller_test.go
  pkg/operator/assets/bindata.go
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, lgtm

#2591 [release-4.7] Bug 1964568: Delete duplicated generated mc
  pkg/controller/container-runtime-config/container_runtime_config_controller.go
  pkg/controller/container-runtime-config/container_runtime_config_controller_test.go
  pkg/controller/kubelet-config/helpers.go
  pkg/controller/kubelet-config/kubelet_config_controller.go
  pkg/controller/kubelet-config/kubelet_config_controller_test.go
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, cherry-pick-approved, lgtm

#2588 Bug 1958812: daemon: Display more non-JSON text from rpm-ostree status --json
  pkg/daemon/rpm-ostree.go
  pkg/daemon/update_test.go
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, lgtm

#2428 Bug 1928147: Respect DHCP option 119 for on-prem
  templates/common/on-prem/files/NetworkManager-resolv-prepender.yaml
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, lgtm

#2581 Bug 1962288: [ovirt] Stop using db file for static internal records
  templates/common/ovirt/files/coredns-corefile.yaml
  templates/common/ovirt/files/ovirt-coredns-db.yaml
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, cherry-pick-approved, lgtm
