Repository openshift/machine-config-operator, pull requests merged in 2021-07, with the labels that each got.

#2652 Bug 1978041: templates: split unit dropins into separate files
  templates/common/_base/units/crio.service-proxy.yaml
  templates/common/_base/units/crio.service.yaml
  templates/common/_base/units/kubelet.service-proxy.yaml
  templates/common/_base/units/kubelet.service.yaml
Labels: approved, bugzilla/severity-urgent, bugzilla/valid-bug, cherry-pick-approved, lgtm

#2641 Bug 1976232: Explicitly set keyfile as the default plugin of NetworkManager for RHEL7
  templates/common/_base/files/NetworkManager-keyfiles.yaml
  templates/common/_base/files/configure-ovs-network.yaml
Labels: approved, bugzilla/severity-urgent, bugzilla/valid-bug, cherry-pick-approved, lgtm

#2651 Bump openshift/api
  go.mod
  go.sum
  vendor/github.com/openshift/api/config/v1/0000_00_cluster-version-operator_01_clusteroperator.crd.yaml
  vendor/github.com/openshift/api/config/v1/0000_00_cluster-version-operator_01_clusterversion.crd.yaml
  vendor/github.com/openshift/api/config/v1/0000_03_config-operator_01_operatorhub.crd.yaml
  vendor/github.com/openshift/api/config/v1/0000_03_config-operator_01_proxy.crd.yaml
  vendor/github.com/openshift/api/config/v1/0000_10_config-operator_01_apiserver.crd.yaml
  vendor/github.com/openshift/api/config/v1/0000_10_config-operator_01_authentication.crd.yaml
  vendor/github.com/openshift/api/config/v1/0000_10_config-operator_01_build.crd.yaml
  vendor/github.com/openshift/api/config/v1/0000_10_config-operator_01_console.crd.yaml
  vendor/github.com/openshift/api/config/v1/0000_10_config-operator_01_dns.crd.yaml
  vendor/github.com/openshift/api/config/v1/0000_10_config-operator_01_featuregate.crd.yaml
  vendor/github.com/openshift/api/config/v1/0000_10_config-operator_01_image.crd.yaml
  vendor/github.com/openshift/api/config/v1/0000_10_config-operator_01_infrastructure.crd.yaml
  vendor/github.com/openshift/api/config/v1/0000_10_config-operator_01_ingress.crd.yaml
  vendor/github.com/openshift/api/config/v1/0000_10_config-operator_01_network.crd.yaml
  vendor/github.com/openshift/api/config/v1/0000_10_config-operator_01_oauth.crd.yaml
  vendor/github.com/openshift/api/config/v1/0000_10_config-operator_01_project.crd.yaml
  vendor/github.com/openshift/api/config/v1/0000_10_config-operator_01_scheduler.crd.yaml
  vendor/github.com/openshift/api/config/v1/types_apiserver.go
  vendor/github.com/openshift/api/config/v1/types_cluster_operator.go
  vendor/github.com/openshift/api/config/v1/types_feature.go
  vendor/github.com/openshift/api/config/v1/types_infrastructure.go
  vendor/github.com/openshift/api/config/v1/zz_generated.deepcopy.go
  vendor/github.com/openshift/api/config/v1/zz_generated.swagger_doc_generated.go
  vendor/github.com/openshift/api/operator/v1/0000_10_config-operator_01_config.crd.yaml
  vendor/github.com/openshift/api/operator/v1/0000_12_etcd-operator_01_config.crd.yaml
  vendor/github.com/openshift/api/operator/v1/0000_20_kube-apiserver-operator_01_config.crd.yaml
  vendor/github.com/openshift/api/operator/v1/0000_25_kube-controller-manager-operator_01_config.crd.yaml
  vendor/github.com/openshift/api/operator/v1/0000_25_kube-scheduler-operator_01_config.crd.yaml
  vendor/github.com/openshift/api/operator/v1/0000_30_openshift-apiserver-operator_01_config.crd.yaml
  vendor/github.com/openshift/api/operator/v1/0000_40_cloud-credential-operator_00_config.crd.yaml
  vendor/github.com/openshift/api/operator/v1/0000_40_kube-storage-version-migrator-operator_00_config.crd.yaml
  vendor/github.com/openshift/api/operator/v1/0000_50_cluster-authentication-operator_01_config.crd.yaml
  vendor/github.com/openshift/api/operator/v1/0000_50_cluster-openshift-controller-manager-operator_02_config.crd.yaml
  vendor/github.com/openshift/api/operator/v1/0000_50_cluster_storage_operator_01_crd.yaml
  vendor/github.com/openshift/api/operator/v1/0000_50_ingress-operator_00-ingresscontroller.crd.yaml
  vendor/github.com/openshift/api/operator/v1/0000_50_service-ca-operator_02_crd.yaml
  vendor/github.com/openshift/api/operator/v1/0000_70_cluster-network-operator_01_crd.yaml
  vendor/github.com/openshift/api/operator/v1/0000_70_console-operator.crd.yaml
  vendor/github.com/openshift/api/operator/v1/0000_70_dns-operator_00-custom-resource-definition.yaml
  vendor/github.com/openshift/api/operator/v1/0000_80_csi_snapshot_controller_operator_01_crd.yaml
  vendor/github.com/openshift/api/operator/v1/0000_90_cluster_csi_driver_01_config.crd.yaml
  vendor/github.com/openshift/api/operator/v1/0000_90_cluster_csi_driver_01_config.crd.yaml-patch
  vendor/github.com/openshift/api/operator/v1/types_config.go
  vendor/github.com/openshift/api/operator/v1/types_console.go
  vendor/github.com/openshift/api/operator/v1/types_csi_cluster_driver.go
  vendor/github.com/openshift/api/operator/v1/types_dns.go
  vendor/github.com/openshift/api/operator/v1/types_ingress.go
  vendor/github.com/openshift/api/operator/v1/types_network.go
  vendor/github.com/openshift/api/operator/v1/zz_generated.deepcopy.go
  vendor/github.com/openshift/api/operator/v1/zz_generated.swagger_doc_generated.go
  vendor/github.com/openshift/api/operator/v1alpha1/0000_10_config-operator_01_imagecontentsourcepolicy.crd.yaml
  vendor/modules.txt
Labels: approved, lgtm

#2646 docs: update doc for conditional no drain during ICSP changes
  docs/MachineConfigDaemon.md
Labels: approved, lgtm

#2657 daemon: add log and event for uncordoning node
  pkg/daemon/daemon.go
Labels: approved, lgtm

#2661 Bug 1979297: Revert "Subtract hugepages from memory capacity and allocatables"
  install/0000_90_machine-config-operator_01_prometheus-rules.yaml
Labels: approved, bugzilla/severity-unspecified, bugzilla/valid-bug, lgtm

#2650 Bug 1980658: ON-PREM] HAProxy - Verify that NM prepender script was applied using initcontainer
  templates/master/00-master/on-prem/files/haproxy.yaml
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, lgtm

#2667 docs: document single-node upgrade support
  docs/SingleNodeOpenShift.md
Labels: approved, lgtm

#2672 [release-4.6] Bug 1975626: KubeletConfig validation warning in CRD and Docs
  docs/KubeletConfigDesign.md
  install/0000_80_machine-config-operator_01_kubeletconfig.crd.yaml
Labels: 4.6, approved, bugzilla/severity-high, bugzilla/valid-bug, cherry-pick-approved, lgtm

#2669 Update library-go for support out-of-tree Azure provider
  go.mod
  go.sum
  pkg/controller/template/render.go
  pkg/controller/template/render_test.go
  vendor/github.com/openshift/library-go/pkg/cloudprovider/external.go
  vendor/modules.txt
Labels: approved, lgtm

#2677 daemon: Explicitly start rpm-ostreed, restart if we detect active txn
  pkg/daemon/daemon.go
  pkg/daemon/rpm-ostree.go
  pkg/daemon/rpm-ostree_test.go
Labels: approved, lgtm

#2673 Bug 1981090: [ON-PREM] HAProxy - enable listening sockets retrieval from old processes
  templates/master/00-master/on-prem/files/haproxy-haproxy.yaml
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, lgtm

#2676 Bug 1982052: Handle team/bond interfaces with a more clear message
  templates/common/_base/files/configure-ovs-network.yaml
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, lgtm

#2643 Bug 1971715: configure-ovs: fix bond ifcfg backed configuration
  templates/common/_base/files/configure-ovs-network.yaml
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, lgtm, qe-approved

#2637 On-prem: add default ingress track script to Keepalived
  templates/common/on-prem/files/keepalived.yaml
  templates/master/00-master/on-prem/files/keepalived-keepalived.yaml
  templates/worker/00-worker/on-prem/files/keepalived-keepalived.yaml
Labels: approved, lgtm

#2659 pkg/daemon/drain: Clarify "cordon/uncordon" messages
  pkg/daemon/drain.go
Labels: approved, lgtm

#2210 Revert "Revert "crio: drop infra container when possible""
  templates/master/01-master-container-runtime/_base/files/crio.yaml
  templates/worker/01-worker-container-runtime/_base/files/crio.yaml
Labels: approved, lgtm

#2617 Bug 1971046: templates/master/00-master/gcp/files/opt-libexec-openshift-gcp-routes: Stderr for curl errors
  templates/master/00-master/gcp/files/opt-libexec-openshift-gcp-routes-sh.yaml
Labels: approved, bugzilla/severity-urgent, bugzilla/valid-bug, lgtm

#2662 Ovs bridge setup: Create an optional second bridge
  templates/common/_base/files/configure-ovs-network.yaml
Labels: approved, lgtm

#2678 Add CRI-O metrics collectors configuration
  templates/master/01-master-container-runtime/_base/files/crio.yaml
  templates/worker/01-worker-container-runtime/_base/files/crio.yaml
Labels: approved, lgtm

#2668 [OCPCLOUD-1209] Run KubeletConfig FeatureGate sync during bootstrap
  pkg/controller/bootstrap/bootstrap.go
  pkg/controller/bootstrap/bootstrap_test.go
  pkg/controller/kubelet-config/helpers.go
  pkg/controller/kubelet-config/kubelet_config_controller.go
  pkg/controller/kubelet-config/kubelet_config_features.go
  pkg/controller/kubelet-config/kubelet_config_features_test.go
  pkg/controller/template/template_controller.go
Labels: approved, lgtm

#2658 Bug 1986453: Check for API server and node versions skew
  cmd/machine-config-operator/start.go
  pkg/operator/operator.go
  pkg/operator/status.go
  pkg/operator/status_test.go
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, lgtm

#2679 Bug 1982766: [on-prem] Make ingress VIP more tolerant to failures
  templates/master/00-master/on-prem/files/keepalived-keepalived.yaml
  templates/worker/00-worker/on-prem/files/keepalived-keepalived.yaml
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, lgtm

#2680 Bug 1987948: OCPNODE-542: Add CPU and memory alerts for the master nodes
  install/0000_90_machine-config-operator_01_prometheus-rules.yaml
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, lgtm

#2649 [release-4.7] Bug 1977432: crio: enable internal_wipe option
  templates/master/01-master-container-runtime/_base/files/crio.yaml
  templates/worker/01-worker-container-runtime/_base/files/crio.yaml
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, cherry-pick-approved, lgtm

#2682 [release-4.7] Bug 1970166: MCO: maxUnavailable of ds/machine-config-daemon does not get updated due to missing resourcemerge check
  lib/resourcemerge/apps.go
  lib/resourcemerge/apps_test.go
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, cherry-pick-approved, lgtm
