Repository openshift/machine-config-operator, pull requests merged in 2021-08, with the labels that each got.

#2699 Bug 1975626: Fix KubeletConfig nil error
  pkg/controller/kubelet-config/helpers.go
Labels: lgtm, approved, bugzilla/valid-bug, cherry-pick-approved, bugzilla/severity-high

#2694 Bug 1986392: Persist kubelet node name for OpenStack nodes
  templates/common/_base/files/usr-local-bin-mco-hostname.yaml
  templates/common/aws/files/etc-networkmanager-conf.d-hostname.yaml
  templates/common/aws/files/usr-local-bin-aws-kubelet-nodename.yaml
  templates/common/aws/units/aws-hostname.service.yaml
  templates/common/aws/units/aws-kubelet-nodename.service.yaml
  templates/common/openstack/files/usr-local-bin-openstack-kubelet-nodename.yaml
  templates/common/openstack/units/openstack-kubelet-nodename.service.yaml
  templates/master/01-master-kubelet/_base/units/kubelet.service.yaml
  templates/master/01-master-kubelet/on-prem/units/kubelet.service.yaml
  templates/worker/01-worker-kubelet/_base/units/kubelet.service.yaml
  templates/worker/01-worker-kubelet/on-prem/units/kubelet.service.yaml
Labels: lgtm, approved, bugzilla/valid-bug, bugzilla/severity-urgent

#2712 Bug 1992557: crio: use conmon from path
  templates/master/01-master-container-runtime/_base/files/crio.yaml
  templates/worker/01-worker-container-runtime/_base/files/crio.yaml
Labels: lgtm, approved, bugzilla/valid-bug, bugzilla/severity-urgent

#2702 Bug 1990012: Update controller config openapi schema
  manifests/controllerconfig.crd.yaml
  pkg/operator/assets/bindata.go
Labels: lgtm, approved, bugzilla/valid-bug, bugzilla/severity-medium

#2716 Bug 1980844: bump SystemMemoryExceedsReservation alert threshold to 95%
  install/0000_90_machine-config-operator_01_prometheus-rules.yaml
Labels: lgtm, approved, bugzilla/valid-bug, bugzilla/severity-medium

#2707 [release-4.6] Bug 1987221: Backport drain timeout optimizations
  Makefile
  install/0000_90_machine-config-operator_01_prometheus-rules.yaml
  pkg/daemon/daemon.go
  pkg/daemon/metrics.go
  pkg/daemon/update.go
Labels: lgtm, approved, bugzilla/valid-bug, cherry-pick-approved, bugzilla/severity-high

#2720 [release-4.6] Bug 1989403: daemon: add check before updating kernelArgs
  pkg/daemon/update.go
  pkg/daemon/update_test.go
Labels: lgtm, approved, bugzilla/valid-bug, cherry-pick-approved, bugzilla/severity-high, 4.6

#2723 Bug 1995785: crio: complete crio default config
  templates/master/01-master-container-runtime/_base/files/crio.yaml
  templates/worker/01-worker-container-runtime/_base/files/crio.yaml
Labels: lgtm, approved, bugzilla/valid-bug, bugzilla/severity-high

#2690 Bug 1970129: Set ovs syslog level to info
  templates/common/_base/units/ovs-vswitchd.service.yaml
Labels: lgtm, approved, bugzilla/valid-bug, bugzilla/severity-high

#2728 Bug 1955300: operator: add event on degraded and unavailable status
  pkg/operator/status.go
Labels: lgtm, approved, bugzilla/valid-bug, bugzilla/severity-urgent

#2725 [release-4.7] Bug 1995810: crio: complete crio default config
  templates/master/01-master-container-runtime/_base/files/crio.yaml
  templates/worker/01-worker-container-runtime/_base/files/crio.yaml
Labels: lgtm, approved, bugzilla/valid-bug, cherry-pick-approved, bugzilla/severity-high

#2724 [release-4.8] Bug 1995809: crio: complete crio default config
  templates/master/01-master-container-runtime/_base/files/crio.yaml
  templates/worker/01-worker-container-runtime/_base/files/crio.yaml
Labels: lgtm, approved, bugzilla/valid-bug, cherry-pick-approved, bugzilla/severity-urgent

#2718 Bug 1994277: delete the memory manager state file before the kubelet start
  templates/master/01-master-kubelet/_base/units/kubelet.service.yaml
  templates/master/01-master-kubelet/on-prem/units/kubelet.service.yaml
  templates/worker/01-worker-kubelet/_base/units/kubelet.service.yaml
  templates/worker/01-worker-kubelet/on-prem/units/kubelet.service.yaml
Labels: lgtm, approved, bugzilla/valid-bug, bugzilla/severity-high

#2627 Bug 1973525: [on-prem] Drop runlevel from infra namespaces
  install/0000_80_machine-config-operator_00_namespace.yaml
Labels: lgtm, approved, bugzilla/valid-bug, bugzilla/severity-low

#2722 Bug 1980844: install/0000_90_machine-config-operator_01_prometheus-rules: Doc 95% for SystemMemoryExceedsReserved
  install/0000_90_machine-config-operator_01_prometheus-rules.yaml
Labels: lgtm, approved, bugzilla/valid-bug, bugzilla/severity-medium

#2697 Bug 1988102: [release-4.7] On-prem: add default ingress track script to Keepalived
  templates/common/on-prem/files/keepalived.yaml
  templates/master/00-master/on-prem/files/keepalived-keepalived.yaml
  templates/worker/00-worker/on-prem/files/keepalived-keepalived.yaml
Labels: lgtm, approved, bugzilla/valid-bug, cherry-pick-approved, bugzilla/severity-high

#2703 Bug 1986757: Set timeoutSeconds for keepalived liveness probe
  templates/common/on-prem/files/keepalived.yaml
Labels: lgtm, approved, bugzilla/valid-bug, bugzilla/severity-medium

#2743 Bug 1999593: e2e-single-node: add test for rt-kernel switch
  test/e2e-single-node/sno_mcd_test.go
Labels: lgtm, approved, bugzilla/valid-bug, bugzilla/severity-medium
