Repository openshift/machine-config-operator, pull requests merged in 2021-02, with the labels that each got.

#2362 Bug 1916363: Fix how files from system-connections-merged get copied into system-connections
  templates/common/_base/files/configure-ovs-network.yaml
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, lgtm

#2280 Add platform aliases
  OWNERS_ALIASES
  templates/common/baremetal/OWNERS
  templates/common/on-prem/OWNERS
  templates/common/ovirt/OWNERS
  templates/common/vsphere/OWNERS
  templates/master/00-master/on-prem/OWNERS
  templates/worker/00-worker/on-prem/OWNERS
Labels: approved, bugzilla/valid-bug, lgtm

#2378 Bug 1920027: templates: split crio dropins into separate files
  templates/common/_base/units/crio.service-proxy.yaml
  templates/common/_base/units/crio.service-socket.yaml
  templates/common/_base/units/crio.service.yaml
Labels: approved, bugzilla/severity-urgent, bugzilla/valid-bug, lgtm

#2383 Bug 1923874: KubeletConfig: Revert "Fix KubeletConfig validation for invalid values"
  pkg/controller/kubelet-config/helpers.go
  pkg/controller/kubelet-config/kubelet_config_controller_test.go
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, lgtm

#2377 Bug 1919271: NM resolve prepender: Update for systemd-resolved logic. systemd-resolved requires restart after dropin created
  templates/common/on-prem/files/NetworkManager-resolv-prepender.yaml
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, lgtm, ok-to-test

#2390 Bug 1923874: KubeletConfig: Drop validation for kubeletconfig
  pkg/controller/kubelet-config/helpers.go
  pkg/controller/kubelet-config/kubelet_config_controller_test.go
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, lgtm

#2391 Bug 1921248: KubeletConfig: validation warning in CRD and Docs
  docs/KubeletConfigDesign.md
  install/0000_80_machine-config-operator_01_kubeletconfig.crd.yaml
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, lgtm

#2133 Bug 1884195: etcd-quorum-guard remove toleration timeouts
  install/0000_80_machine-config-operator_07_etcdquorumguard_deployment.yaml
Labels: 4.5, approved, bugzilla/severity-low, bugzilla/valid-bug, cherry-pick-approved, lgtm

#2392 Bug 1925319: configure-ovs: fix bash syntax error
  templates/common/_base/files/configure-ovs-network.yaml
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, lgtm

#2389 Bug 1885186: handle Passwd.Users removal more gracefully
  pkg/daemon/update.go
  pkg/daemon/update_test.go
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, lgtm, team-mco

#2379 OWNERS: drop @runcom with gratitude
  OWNERS
Labels: approved, lgtm

#2356 Bug 1919272: [release-4.6] NM resolve prepender: support appending a nameserver for systemd-resolved
  templates/common/baremetal/files/NetworkManager-resolv-prepender.yaml
  templates/common/openstack/files/NetworkManager-resolv-prepender.yaml
  templates/common/ovirt/files/NetworkManager-resolv-prepender.yaml
  templates/common/vsphere/files/NetworkManager-resolv-prepender.yaml
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, cherry-pick-approved, lgtm

#2380 Bug 1920807: [vsphere] set hostname with --static to provide consistent node name for CSR approval
  templates/common/vsphere/files/vsphere-hostname.yaml
  templates/common/vsphere/units/vsphere-hostname.service.yaml
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, lgtm

#2400 Dockerfile: update reference to builder to new CI location
  Dockerfile
Labels: approved, lgtm

#2408 Bug 1840881: Fix 1:1 mapping for kubeletconfig:MC and some e2e test fixes
  pkg/controller/kubelet-config/helpers.go
  test/e2e/kubeletcfg_test.go
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, lgtm

#2402 Bug 1927366: Fixes ovs-configuration with cloned connections
  templates/common/_base/files/configure-ovs-network.yaml
Labels: approved, lgtm

#2417 vendor: update openshift/api to bring in new field controlPlaneTopology
  go.mod
  go.sum
  vendor/github.com/openshift/api/config/v1/0000_10_config-operator_01_infrastructure.crd.yaml
  vendor/github.com/openshift/api/config/v1/0000_10_config-operator_01_scheduler.crd.yaml
  vendor/github.com/openshift/api/config/v1/types_infrastructure.go
  vendor/github.com/openshift/api/config/v1/types_scheduling.go
  vendor/github.com/openshift/api/config/v1/zz_generated.deepcopy.go
  vendor/github.com/openshift/api/config/v1/zz_generated.swagger_doc_generated.go
  vendor/github.com/openshift/api/operator/v1/0000_12_etcd-operator_01_config.crd.yaml
  vendor/github.com/openshift/api/operator/v1/0000_20_kube-apiserver-operator_01_config.crd.yaml
  vendor/github.com/openshift/api/operator/v1/0000_25_kube-controller-manager-operator_01_config.crd.yaml
  vendor/github.com/openshift/api/operator/v1/0000_25_kube-scheduler-operator_01_config.crd.yaml
  vendor/github.com/openshift/api/operator/v1/0000_40_cloud-credential-operator_00_config.crd.yaml
  vendor/github.com/openshift/api/operator/v1/types.go
  vendor/github.com/openshift/api/operator/v1/types_cloudcredential.go
  vendor/github.com/openshift/api/operator/v1/types_etcd.go
  vendor/github.com/openshift/api/operator/v1/zz_generated.deepcopy.go
  vendor/github.com/openshift/api/operator/v1/zz_generated.swagger_doc_generated.go
  vendor/github.com/openshift/api/operator/v1alpha1/0000_10_config-operator_01_imagecontentsourcepolicy.crd.yaml
  vendor/github.com/openshift/api/operator/v1alpha1/types_image_content_source_policy.go
  vendor/github.com/openshift/api/operator/v1alpha1/zz_generated.swagger_doc_generated.go
  vendor/modules.txt
Labels: approved, lgtm, team-mco

#2406 pkg/daemon: Drop unnecessary select from runLoginMonitor
  pkg/daemon/daemon.go
Labels: approved, lgtm

#2395 daemon: safer signal handling for shutdown
  manifests/machineconfigdaemon/daemonset.yaml
  pkg/daemon/daemon.go
  pkg/daemon/update.go
  pkg/operator/assets/bindata.go
Labels: approved, lgtm, team-mco

#2416 controller: remove etcd quorum-guard check on master pool
  pkg/controller/node/node_controller.go
  pkg/controller/node/node_controller_test.go
Labels: approved, lgtm

#2398 Add kubelet CA to no-reboot action list/Do not drain for non-reboot actions
  docs/MachineConfigDaemon.md
  pkg/daemon/update.go
  pkg/daemon/update_test.go
  pkg/operator/bootstrap.go
  pkg/operator/sync.go
Labels: approved, lgtm, team-mco

#2425 Bug 1928473: Apply system-connections-merged to all platforms
  templates/common/_base/files/NetworkManager-keyfiles.yaml
  templates/common/_base/files/nm-tmpfiles.yaml
  templates/common/_base/units/nm-system-connections-mount.yaml
  templates/common/on-prem/files/NetworkManager-onprem.conf.yaml
Labels: approved, bugzilla/severity-urgent, bugzilla/valid-bug, lgtm

#2384 Bug 1922997: Connect default NIC to cluster network
  templates/common/_base/files/configure-ovs-network.yaml
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, lgtm

#2432 OWNERS: Surrendering membership
  OWNERS
Labels: approved, lgtm

#2429 Bug 1930620: support trace loglevel
  pkg/controller/container-runtime-config/helpers.go
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, lgtm

#2419 [release-4.6] Bug 1906298: update MCDDrainErr to reduce cardinality & fix nodename
  install/0000_90_machine-config-operator_01_prometheus-rules.yaml
  pkg/daemon/metrics.go
  pkg/daemon/update.go
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, cherry-pick-approved, lgtm, team-mco

#2420 Bug 1844990: server/api: Disable unsafe ciphers for CVE-2016-2183
  pkg/server/api.go
  pkg/server/api_test.go
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, lgtm

#2318 Bug 1896226: Remove recycler pod templates
  templates/master/00-master/_base/files/recycler_pod.yaml
  templates/master/00-master/_base/files/recycler_pod_bad.yaml
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, lgtm

#2431 Bug 1927731: Revert "pkg/daemon: Add IgnitionVersion to Daemon"
  pkg/daemon/daemon.go
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, lgtm

#2409 Bug 1871770: Remove extraneous whitespace from keepalived peer list
  templates/master/00-master/on-prem/files/keepalived-keepalived.yaml
  templates/worker/00-worker/on-prem/files/keepalived-keepalived.yaml
Labels: approved, bugzilla/severity-low, bugzilla/valid-bug, lgtm

#2440 Bug 1932105: operator/sync.go restore err when required pools not leveled
  pkg/operator/sync.go
Labels: approved, bugzilla/severity-urgent, bugzilla/valid-bug, lgtm
