Repository openshift/machine-config-operator, pull requests merged in 2021-09, with the labels that each got.

#2752 Bug 1993922: fixes 1 to 1 kubelet config mapping
  pkg/controller/kubelet-config/helpers.go
  pkg/controller/kubelet-config/kubelet_config_controller_test.go
Labels: lgtm, approved, bugzilla/valid-bug, bugzilla/severity-high

#2740 Change to owners for baremetal component
  OWNERS_ALIASES
Labels: lgtm, approved

#2757 Vendor: update library-go for ibmcloud provider
  go.mod
  go.sum
  vendor/github.com/opencontainers/runc/libcontainer/user/user.go
  vendor/github.com/openshift/api/config/v1/0000_10_config-operator_01_apiserver.crd.yaml
  vendor/github.com/openshift/api/config/v1/0000_10_config-operator_01_infrastructure.crd.yaml
  vendor/github.com/openshift/api/config/v1/types_apiserver.go
  vendor/github.com/openshift/api/config/v1/types_feature.go
  vendor/github.com/openshift/api/config/v1/types_infrastructure.go
  vendor/github.com/openshift/api/config/v1/zz_generated.deepcopy.go
  vendor/github.com/openshift/api/config/v1/zz_generated.swagger_doc_generated.go
  vendor/github.com/openshift/library-go/pkg/cloudprovider/external.go
  vendor/golang.org/x/time/rate/rate.go
  vendor/modules.txt
Labels: lgtm, approved

#2644 [release-4.8] Bug 1976110: configure-ovs: fix nondeterministic master in slave profiles
  templates/common/_base/files/configure-ovs-network.yaml
Labels: lgtm, approved, bugzilla/valid-bug, cherry-pick-approved, bugzilla/severity-urgent, qe-approved

#2748 [release-4.8] Bug 2000500: bump SystemMemoryExceedsReservation alert threshold to 95%
  install/0000_90_machine-config-operator_01_prometheus-rules.yaml
Labels: lgtm, approved, bugzilla/valid-bug, cherry-pick-approved, bugzilla/severity-medium

#2721 Bug 1955300: tighten operator availability conditions
  pkg/operator/status.go
  pkg/operator/sync.go
Labels: lgtm, approved, bugzilla/valid-bug, bugzilla/severity-urgent

#2749 [release-4.7] Bug 2000501: bump SystemMemoryExceedsReservation alert threshold to 95%
  install/0000_90_machine-config-operator_01_prometheus-rules.yaml
Labels: lgtm, approved, bugzilla/valid-bug, cherry-pick-approved, bugzilla/severity-medium

#2770 Bug 1990625: configure-ovs: Persist addr-gen-mode for ipv6 connections
  templates/common/_base/files/configure-ovs-network.yaml
Labels: lgtm, approved, bugzilla/valid-bug, bugzilla/severity-medium

#2772 Updating openshift libraries
  go.mod
  go.sum
  templates/master/01-master-kubelet/_base/files/kubelet.yaml
  templates/worker/01-worker-kubelet/_base/files/kubelet.yaml
  vendor/github.com/openshift/api/config/v1/0000_10_config-operator_01_infrastructure.crd.yaml
  vendor/github.com/openshift/api/config/v1/0000_10_config-operator_01_oauth.crd.yaml
  vendor/github.com/openshift/api/config/v1/types_cluster_operator.go
  vendor/github.com/openshift/api/config/v1/types_feature.go
  vendor/github.com/openshift/api/config/v1/types_infrastructure.go
  vendor/github.com/openshift/api/config/v1/types_oauth.go
  vendor/github.com/openshift/api/config/v1/zz_generated.deepcopy.go
  vendor/github.com/openshift/api/config/v1/zz_generated.swagger_doc_generated.go
  vendor/github.com/openshift/api/operator/v1/0000_50_ingress-operator_00-ingresscontroller.crd.yaml
  vendor/github.com/openshift/api/operator/v1/0000_90_cluster_csi_driver_01_config.crd.yaml
  vendor/github.com/openshift/api/operator/v1/0000_90_cluster_csi_driver_01_config.crd.yaml-patch
  vendor/github.com/openshift/api/operator/v1/types_csi_cluster_driver.go
  vendor/github.com/openshift/api/operator/v1/types_ingress.go
  vendor/github.com/openshift/api/operator/v1/zz_generated.swagger_doc_generated.go
  vendor/github.com/openshift/library-go/pkg/cloudprovider/external.go
  vendor/k8s.io/code-generator/generate-groups.sh
  vendor/k8s.io/code-generator/generate-internal-groups.sh
  vendor/modules.txt
Labels: lgtm, approved

#2774 Send WARN message to stderr
  templates/common/_base/files/configure-ovs-network.yaml
Labels: lgtm, approved

#2730 Bug 1991067: [on-prem] Set coredns bufsize to 512
  templates/common/on-prem/files/coredns-corefile.yaml
Labels: lgtm, approved, bugzilla/valid-bug, bugzilla/severity-high

#2771 Remove all references to mdns
  cmd/machine-config-operator/bootstrap.go
  install/0000_80_machine-config-operator_02_images.configmap.yaml
  install/image-references
  manifests/on-prem/coredns.yaml
  pkg/controller/bootstrap/testdata/bootstrap/machineconfigcontroller-controllerconfig.yaml
  pkg/controller/template/constants.go
  pkg/operator/assets/bindata.go
  pkg/operator/bootstrap.go
  pkg/operator/images.go
  pkg/operator/sync.go
  templates/common/on-prem/files/coredns.yaml
Labels: lgtm, approved
