Repository openshift/machine-config-operator, pull requests merged in 2022-11, with the labels that each got.

#3390 OCPBUGS-1761: Substitute skopeo inspect for imageInspect/podman, drop podman inspect fallback
  pkg/daemon/daemon.go
  pkg/daemon/rpm-ostree.go
Labels: lgtm, approved, bugzilla/valid-bug, jira/severity-moderate, jira/valid-bug

#3403 Unpin all pinned dependencies
  go.mod
  go.sum
  vendor/github.com/InVisionApp/go-health/.gitignore
  vendor/github.com/InVisionApp/go-health/.travis.yml
  vendor/github.com/InVisionApp/go-health/Makefile
  vendor/github.com/InVisionApp/go-health/README.md
  vendor/github.com/opencontainers/runtime-spec/specs-go/config.go
  vendor/github.com/opencontainers/runtime-spec/specs-go/state.go
  vendor/github.com/opencontainers/runtime-spec/specs-go/version.go
  vendor/modules.txt
Labels: lgtm, approved

#3041 [release-4.10] Bug 2069754: [on-prem] Add NetworkManager reload to resolv-prepender
  templates/common/on-prem/files/NetworkManager-resolv-prepender.yaml
Labels: lgtm, approved, bugzilla/valid-bug, cherry-pick-approved, bugzilla/severity-high, 4.10, backport-risk-assessed

#3412 OCPBUGS-3621: Revert "Substitute skopeo inspect for imageInspect/podman"
  pkg/daemon/daemon.go
  pkg/daemon/rpm-ostree.go
Labels: lgtm, approved, bugzilla/valid-bug, jira/valid-bug

#3415 OCPBUGS-2935: daemon: Stop setting I/O scheduler to bfq
  pkg/daemon/controlplane.go
  pkg/daemon/coreos.go
  pkg/daemon/update.go
Labels: lgtm, approved, bugzilla/valid-bug, jira/severity-critical, jira/valid-bug

#3405 Cleanup BM owner aliases
  OWNERS_ALIASES
Labels: lgtm, approved

#3394 OCPBUGS-1577: On-prem: Ensure resolv-prepender respects NM dispatcher timeout
  templates/common/on-prem/files/NetworkManager-resolv-prepender.yaml
Labels: lgtm, approved, bugzilla/valid-bug, jira/severity-important, jira/valid-bug

#3407 [release-4.9] OCPBUGS-3200: configure-ovs: avoid using 'ip -j' unavailable in RHEL7
  templates/common/_base/files/configure-ovs-network.yaml
Labels: lgtm, approved, bugzilla/valid-bug, cherry-pick-approved, qe-approved, backport-risk-assessed, jira/severity-moderate, jira/valid-bug

#3416 OCPBUGS-3508: Don't make https call to http endpoint
  templates/master/00-master/on-prem/files/keepalived-script-both.yaml
  templates/master/00-master/on-prem/files/keepalived-script.yaml
Labels: lgtm, approved, bugzilla/valid-bug, jira/severity-critical, jira/valid-bug

#3408 [release-4.10] OCPBUGS-3500: Add ephemeral storage to kubelet system reserved args
  pkg/controller/kubelet-config/helpers.go
  templates/common/_base/files/kubelet-auto-node-sizing-enabled.yaml
  templates/common/_base/files/kubelet-auto-sizing.yaml
  templates/common/_base/units/kubelet-auto-node-size.service.yaml
  templates/master/01-master-kubelet/_base/files/kubelet.yaml
  templates/master/01-master-kubelet/_base/units/kubelet.service.yaml
  templates/master/01-master-kubelet/alibabacloud/units/kubelet.service.yaml
  templates/master/01-master-kubelet/on-prem/units/kubelet.service.yaml
  templates/worker/01-worker-kubelet/_base/files/kubelet.yaml
  templates/worker/01-worker-kubelet/_base/units/kubelet.service.yaml
  templates/worker/01-worker-kubelet/alibabacloud/units/kubelet.service.yaml
  templates/worker/01-worker-kubelet/on-prem/units/kubelet.service.yaml
Labels: lgtm, approved, bugzilla/valid-bug, cherry-pick-approved, backport-risk-assessed, jira/valid-bug

#3410 [release-4.12] OCPBUGS-3504: On-prem: Ensure resolv-prepender respects NM dispatcher timeout
  templates/common/on-prem/files/NetworkManager-resolv-prepender.yaml
Labels: lgtm, approved, bugzilla/valid-bug, jira/severity-important, jira/valid-bug

#3399 OCPBUGS-1491: daemon: gate done state on uncordon completion
  pkg/daemon/daemon.go
Labels: lgtm, approved, bugzilla/valid-bug, jira/severity-important, jira/valid-bug

#3401 [release-4.8] OCPBUGS-3201: avoid using 'ip -j' as it is unavailable in RHEL7
  templates/common/_base/files/configure-ovs-network.yaml
Labels: lgtm, approved, bugzilla/valid-bug, cherry-pick-approved, qe-approved, backport-risk-assessed, jira/severity-moderate, jira/valid-bug

#3411 OCPBUGS-2921: configure-ovs: copy IP method and warn about low MTU
  templates/common/_base/files/configure-ovs-network.yaml
Labels: lgtm, approved, bugzilla/valid-bug, jira/severity-important, jira/valid-bug

#3430 OCPBUGS-4039: NM resolve prepender: remove extra quotes in OKD flow
  templates/common/on-prem/files/NetworkManager-resolv-prepender.yaml
Labels: lgtm, approved, bugzilla/valid-bug, jira/valid-bug

#3418 OCPBUGS-3756: daemon: Stop setting I/O scheduler to bfq
  pkg/daemon/controlplane.go
  pkg/daemon/coreos.go
  pkg/daemon/update.go
Labels: lgtm, approved, bugzilla/valid-bug, cherry-pick-approved, backport-risk-assessed, jira/severity-critical, jira/valid-bug
