Repository openshift/machine-config-operator, pull requests merged in 2022-12, with the labels that each got.

#3440 Add templates for required sysctls max_map_count and arp_announce
  templates/common/_base/files/sysctl-arp.conf.yaml
  templates/common/_base/files/sysctl-vm-max-map.conf.yaml
Labels: lgtm, approved

#3413 OCPBUGS-1761: Imageinspect takes type of error into account, drop podman inspect fallback
  go.mod
  go.sum
  pkg/daemon/daemon.go
  pkg/daemon/image-inspect.go
  pkg/daemon/rpm-ostree.go
  vendor/github.com/containers/common/LICENSE
  vendor/github.com/containers/common/pkg/retry/retry.go
  vendor/github.com/containers/common/pkg/retry/retry_linux.go
  vendor/github.com/containers/common/pkg/retry/retry_unsupported.go
  vendor/github.com/coreos/go-systemd/v22/unit/escape.go
  vendor/modules.txt
Labels: lgtm, approved, bugzilla/valid-bug, jira/severity-moderate, jira/valid-bug

#3451 OCPBUGS-4656: vsphere: check that /etc/hostname is not empty
  templates/common/vsphere/files/vsphere-hostname.yaml
  templates/common/vsphere/units/vsphere-hostname.service.yaml
Labels: lgtm, approved, bugzilla/valid-bug, jira/valid-bug

#3426 MCO-397: Add repo doc for using "Layering Phase 0", detail some of the tradeoffs/consequences/questions
  docs/README.md
  docs/UsingLayering.md
Labels: lgtm, approved

#3406 Bug 1853264: Fix unbound cardinality for MCDRebootErr and MCDPivotErr
  install/0000_90_machine-config-operator_01_prometheus-rules.yaml
  pkg/daemon/metrics.go
  pkg/daemon/update.go
Labels: lgtm, approved, bugzilla/valid-bug, bugzilla/severity-medium, qe-approved

#3439 OCPBUGS-4101: Do not allow empty system reserved values
  pkg/controller/kubelet-config/helpers.go
  templates/common/_base/files/kubelet-auto-sizing.yaml
Labels: lgtm, approved, bugzilla/valid-bug, qe-approved, jira/severity-moderate, jira/valid-bug

#3424 MCO-420: Migrate drain alert to drain controller
  cmd/machine-config-controller/start.go
  cmd/machine-config-daemon/start.go
  install/0000_90_machine-config-operator_01_prometheus-rules.yaml
  pkg/controller/common/metrics.go
  pkg/controller/drain/drain_controller.go
  pkg/daemon/daemon.go
  pkg/daemon/drain.go
  pkg/daemon/metrics.go
  pkg/daemon/update.go
  pkg/daemon/writer.go
Labels: lgtm, approved, qe-approved

#3449 OCPBUGS-2248: [alicloud] provider ID not being set for kubelet
  templates/common/alibabacloud/files/usr-local-lib-systemd-system-generators-alibaba-kubelet-extra-env-generator.sh.yaml
  templates/master/01-master-kubelet/alibabacloud/units/kubelet.service.yaml
  templates/worker/01-worker-kubelet/alibabacloud/units/kubelet.service.yaml
Labels: lgtm, approved, bugzilla/valid-bug, qe-approved, jira/valid-bug

#3428 move envtest helpers into framework package for easier reuse
  .gitignore
  .golangci.yml
  Makefile
  hack/bootstrap-e2e-test.sh
  hack/fetch-ext-bins.sh
  hack/golangci-lint.sh
  hack/lib
  hack/test-with-junit.sh
  test/e2e-bootstrap/bootstrap_test.go
  test/framework/envtest.go
Labels: lgtm, approved

#3462 OCPBUGS-5001: install/0000_90_machine-config-operator_01_prometheus-rules: Fix MachineConfigControllerPausedPoolKubeletCA runbook URIs
  install/0000_90_machine-config-operator_01_prometheus-rules.yaml
Labels: lgtm, approved, bugzilla/valid-bug, jira/severity-low, jira/valid-bug
