Repository openshift/machine-config-operator, pull requests merged in 2022-02, with the labels that each got.

#2909 Remove sysctl-inotify.conf.yaml
  templates/common/_base/files/sysctl-inotify.conf.yaml
Labels: lgtm, approved

#2911 templates: Change default container-runtime config to enable all CRI-O metrics
  templates/master/01-master-container-runtime/_base/files/crio.yaml
  templates/worker/01-worker-container-runtime/_base/files/crio.yaml
Labels: lgtm, approved

#2872 updates docs for config drift detection
  docs/MachineConfigDaemon.md
Labels: lgtm, approved, retest-not-required-docs-only

#2488 Bug 1929160: Add NetworkManager reload to resolv-prepender
  templates/common/on-prem/files/NetworkManager-resolv-prepender.yaml
Labels: lgtm, approved, bugzilla/valid-bug, bugzilla/severity-high

#2945 OpenStack: set transient hostname in afterburn-hostname
  templates/common/openstack/files/usr-local-bin-openstack-afterburn-hostname.yaml
  templates/common/openstack/units/afterburn-hostname.service.yaml
Labels: lgtm, approved

#2936 Bug 2041814: do not generate new KubeletConfigKey for the first kubel…
  pkg/controller/kubelet-config/helpers.go
  pkg/controller/kubelet-config/kubelet_config_controller.go
  pkg/controller/kubelet-config/kubelet_config_controller_test.go
Labels: lgtm, approved, bugzilla/valid-bug, bugzilla/severity-high

#2956 [release-4.8] Bug 2028854: Backport of SystemMemoryExceedsReservation alert rule
  install/0000_90_machine-config-operator_01_prometheus-rules.yaml
Labels: lgtm, approved, bugzilla/valid-bug, cherry-pick-approved, bugzilla/severity-urgent, backport-risk-assessed

#2968 Bug 2058626: Revert "Bump(openshift/api): to get CSI changes"
  go.mod
  go.sum
  templates/master/01-master-kubelet/_base/files/kubelet.yaml
  templates/worker/01-worker-kubelet/_base/files/kubelet.yaml
  vendor/github.com/openshift/api/Dockerfile.build
  vendor/github.com/openshift/api/config/v1/0000_00_cluster-version-operator_01_clusterversion.crd.yaml
  vendor/github.com/openshift/api/config/v1/0000_10_config-operator_01_infrastructure.crd.yaml
  vendor/github.com/openshift/api/config/v1/types_cluster_version.go
  vendor/github.com/openshift/api/config/v1/types_feature.go
  vendor/github.com/openshift/api/config/v1/types_infrastructure.go
  vendor/github.com/openshift/api/config/v1/zz_generated.deepcopy.go
  vendor/github.com/openshift/api/config/v1/zz_generated.swagger_doc_generated.go
  vendor/github.com/openshift/api/helm/v1beta1/0000_10-helm-chart-repository.crd.yaml
  vendor/github.com/openshift/api/helm/v1beta1/0000_10-project-helm-chart-repository.crd.yaml
  vendor/github.com/openshift/api/helm/v1beta1/register.go
  vendor/github.com/openshift/api/helm/v1beta1/types_helm.go
  vendor/github.com/openshift/api/helm/v1beta1/types_project_helm_chart_repository.go
  vendor/github.com/openshift/api/helm/v1beta1/zz_generated.deepcopy.go
  vendor/github.com/openshift/api/machine/v1beta1/0000_10_machine.crd.yaml
  vendor/github.com/openshift/api/machine/v1beta1/0000_10_machineset.crd.yaml
  vendor/github.com/openshift/api/machine/v1beta1/types_awsprovider.go
  vendor/github.com/openshift/api/machine/v1beta1/types_machine.go
  vendor/github.com/openshift/api/machine/v1beta1/zz_generated.swagger_doc_generated.go
  vendor/modules.txt
Labels: lgtm, approved, bugzilla/valid-bug, bugzilla/severity-high

#2966 [release-4.9] Bug 2058511: Prepend to search domains instead of replacing
  templates/common/on-prem/files/NetworkManager-resolv-prepender.yaml
Labels: lgtm, approved, bugzilla/valid-bug, cherry-pick-approved, bugzilla/severity-urgent, backport-risk-assessed

#2964 [release-4.9] Bug 2025474: annotate rendered config with OCP version
  pkg/controller/common/constants.go
  pkg/controller/render/render_controller.go
  pkg/operator/status.go
  pkg/operator/status_test.go
  pkg/operator/sync.go
Labels: lgtm, approved, bugzilla/valid-bug, cherry-pick-approved, bugzilla/severity-medium, backport-risk-assessed
