Repository openshift/machine-config-operator, pull requests merged in 2022-01, with the labels that each got.

#2902 Bug 2036577: configure-ovs: do not use overlay directory when checking and copying connections
  templates/common/_base/files/configure-ovs-network.yaml
Labels: lgtm, approved, bugzilla/valid-bug, bugzilla/severity-medium

#2903 Bug 2033953: Afterburn to try config-drive before Nova metadata
  templates/common/openstack/units/afterburn-hostname.service.yaml
Labels: lgtm, approved, bugzilla/valid-bug, bugzilla/severity-urgent

#2908 Bug 2039541: Fix duplicate prepender entries in resolv.conf
  templates/common/on-prem/files/NetworkManager-resolv-prepender.yaml
Labels: lgtm, approved, bugzilla/valid-bug, bugzilla/severity-high

#2858 Bug 2028590: Remove unneeded crio.service.d drop-in
  templates/common/baremetal/files/etc-systemd-system-crio-stream-address.conf.yaml
  templates/common/vsphere/files/etc-systemd-system-crio-stream-address.conf.yaml
Labels: lgtm, approved, bugzilla/valid-bug, bugzilla/severity-high

#2896 daemon.go/update.go: various cleanup surrounding OS updates
  pkg/daemon/daemon.go
  pkg/daemon/daemon_test.go
  pkg/daemon/update.go
  pkg/daemon/update_test.go
Labels: lgtm, approved, layering

#2916 shiftstack: Update OWNERS
  OWNERS_ALIASES
Labels: lgtm, approved, bugzilla/valid-bug

#2898 Bug 2035326: ovs-configuration - use lower than NM default ethernet route metric
  templates/common/_base/files/configure-ovs-network.yaml
Labels: lgtm, approved, bugzilla/valid-bug, bugzilla/severity-high

#2907 Bug 2036113: configure-ovs: cleanup leftovers from previous run
  templates/common/_base/files/configure-ovs-network.yaml
Labels: lgtm, approved, bugzilla/valid-bug, bugzilla/severity-medium

#2914 Bug 2035199: add support for IPv6 and multiple routes to the same destination when setting MTU on routes during MTU migration
  pkg/controller/template/render_test.go
  templates/common/_base/files/mtu-migration-conf.yaml
  templates/common/_base/files/mtu-migration-dispatcher.yaml
  templates/common/_base/files/mtu-migration.yaml
  templates/common/_base/units/mtu-migration.service.yaml
Labels: lgtm, approved, bugzilla/valid-bug, bugzilla/severity-medium

#2919 Bug 2042655: Alibaba hairpin
  cmd/apiserver-watcher/README.md
  templates/master/00-master/alibabacloud/files/etc-kubernetes-manifests-apiserver-watcher.yaml
  templates/master/00-master/alibabacloud/files/opt-libexec-openshift-alibabacloud-routes-sh.yaml
  templates/master/00-master/alibabacloud/units/openshift-alibabacloud-routes.path.yaml
  templates/master/00-master/alibabacloud/units/openshift-alibabacloud-routes.service.yaml
Labels: lgtm, approved, bugzilla/valid-bug, bugzilla/severity-urgent

#2922 Bug 1916169: storeCurrentConfigOnDisk after os changes
  pkg/daemon/update.go
Labels: lgtm, approved, bugzilla/valid-bug, bugzilla/severity-high

#2917 Bug 2041889: Explicitly configure NetworkManager keyfile
  templates/common/_base/files/NetworkManager-keyfiles.yaml
Labels: lgtm, approved, bugzilla/valid-bug, bugzilla/severity-urgent

#2910 Bug 2038240: Error if files have special bits set
  pkg/controller/common/helpers.go
  pkg/controller/common/helpers_test.go
Labels: lgtm, approved, bugzilla/valid-bug, bugzilla/severity-medium

#2886 Create PoC for booting from in-cluster built image
  Makefile
  go.mod
  go.sum
  test/constants/constants.go
  test/e2e/layering_test.go
  test/framework/clientset.go
  test/helpers/utils.go
  vendor/github.com/openshift/client-go/build/clientset/versioned/scheme/doc.go
  vendor/github.com/openshift/client-go/build/clientset/versioned/scheme/register.go
  vendor/github.com/openshift/client-go/build/clientset/versioned/typed/build/v1/build.go
  vendor/github.com/openshift/client-go/build/clientset/versioned/typed/build/v1/build_client.go
  vendor/github.com/openshift/client-go/build/clientset/versioned/typed/build/v1/buildconfig.go
  vendor/github.com/openshift/client-go/build/clientset/versioned/typed/build/v1/doc.go
  vendor/github.com/openshift/client-go/build/clientset/versioned/typed/build/v1/generated_expansion.go
  vendor/github.com/openshift/client-go/image/clientset/versioned/scheme/doc.go
  vendor/github.com/openshift/client-go/image/clientset/versioned/scheme/register.go
  vendor/github.com/openshift/client-go/image/clientset/versioned/typed/image/v1/doc.go
  vendor/github.com/openshift/client-go/image/clientset/versioned/typed/image/v1/generated_expansion.go
  vendor/github.com/openshift/client-go/image/clientset/versioned/typed/image/v1/image.go
  vendor/github.com/openshift/client-go/image/clientset/versioned/typed/image/v1/image_client.go
  vendor/github.com/openshift/client-go/image/clientset/versioned/typed/image/v1/imagesignature.go
  vendor/github.com/openshift/client-go/image/clientset/versioned/typed/image/v1/imagestream.go
  vendor/github.com/openshift/client-go/image/clientset/versioned/typed/image/v1/imagestreamimage.go
  vendor/github.com/openshift/client-go/image/clientset/versioned/typed/image/v1/imagestreamimport.go
  vendor/github.com/openshift/client-go/image/clientset/versioned/typed/image/v1/imagestreammapping.go
  vendor/github.com/openshift/client-go/image/clientset/versioned/typed/image/v1/imagestreamtag.go
  vendor/github.com/openshift/client-go/image/clientset/versioned/typed/image/v1/imagetag.go
  vendor/k8s.io/apiserver/pkg/features/OWNERS
  vendor/k8s.io/apiserver/pkg/features/kube_features.go
  vendor/k8s.io/apiserver/pkg/util/feature/feature_gate.go
  vendor/k8s.io/code-generator/generate-groups.sh
  vendor/k8s.io/code-generator/generate-internal-groups.sh
  vendor/k8s.io/component-base/featuregate/OWNERS
  vendor/k8s.io/component-base/featuregate/feature_gate.go
  vendor/k8s.io/kubernetes/LICENSE
  vendor/k8s.io/kubernetes/pkg/credentialprovider/OWNERS
  vendor/k8s.io/kubernetes/pkg/credentialprovider/config.go
  vendor/k8s.io/kubernetes/pkg/credentialprovider/doc.go
  vendor/k8s.io/kubernetes/pkg/credentialprovider/keyring.go
  vendor/k8s.io/kubernetes/pkg/credentialprovider/plugins.go
  vendor/k8s.io/kubernetes/pkg/credentialprovider/provider.go
  vendor/k8s.io/kubernetes/pkg/features/OWNERS
  vendor/k8s.io/kubernetes/pkg/features/kube_features.go
  vendor/modules.txt
Labels: lgtm, approved, layering

#2928 [release-4.9] Bug 2044503: ovs-configuration: use lower than NM default ethernet route metric
  templates/common/_base/files/configure-ovs-network.yaml
Labels: lgtm, approved, bugzilla/valid-bug, cherry-pick-approved, bugzilla/severity-low, backport-risk-assessed

#2929 Bug 2040671: Configure-ovs: Ensure DHCP finishes for both address families
  templates/common/_base/files/configure-ovs-network.yaml
Labels: lgtm, approved, bugzilla/valid-bug, bugzilla/severity-urgent

#2918 Bug 1999556: annotate rendered config with OCP version
  pkg/controller/common/constants.go
  pkg/controller/render/render_controller.go
  pkg/operator/status.go
  pkg/operator/status_test.go
  pkg/operator/sync.go
Labels: lgtm, approved, bugzilla/valid-bug, bugzilla/severity-medium

#2893 Bug 2045866: Set proper InvolvedObject when using library-go EventRecorder
  pkg/operator/operator.go
Labels: lgtm, approved, bugzilla/valid-bug, bugzilla/severity-medium

#2925 Bug 2044808: mcd pull service: use `cp` instead of `cat` to copy MCD on host
  templates/common/_base/units/machine-config-daemon-pull.service.yaml
Labels: lgtm, approved, bugzilla/valid-bug, bugzilla/severity-medium

#2913 docs: Update links from "Optimized Updates" to "Rebootless Updates"
  docs/MachineConfigDaemon.md
  docs/SingleNodeOpenShift.md
Labels: lgtm, approved, retest-not-required-docs-only

#2920 Add Christoph as a baremetal owner
  OWNERS_ALIASES
Labels: lgtm, approved

#2934 Bug 2047445: Use ip command to check for ipv6 addresses
  templates/common/_base/files/configure-ovs-network.yaml
Labels: lgtm, approved, bugzilla/valid-bug, bugzilla/severity-urgent
