Repository openshift/machine-config-operator, pull requests merged in 2022-09, with the labels that each got.

#3325 daemon: Drop mock node updater client
  pkg/daemon/rpm-ostree_test.go
  pkg/daemon/update_test.go
Labels: lgtm, approved

#3326 Hypershift: remove error message on return
  cmd/machine-config-daemon/start.go
Labels: lgtm, approved

#3306 OCPBUGS-224: Make sure there is a search domain in resolv.conf
  templates/common/on-prem/files/NetworkManager-resolv-prepender.yaml
Labels: lgtm, approved, bugzilla/valid-bug, jira/severity-moderate, jira/valid-bug

#3320 MCO-256: hypershift: add disruptionless updates to MCD
  pkg/daemon/daemon.go
Labels: lgtm, approved

#3324 OCPBUGS-825: Provide a reason if operator is unavailable
  pkg/operator/status.go
  pkg/operator/status_test.go
Labels: lgtm, approved, bugzilla/valid-bug, jira/severity-moderate, jira/valid-bug

#3332 added @engelmi, @eslutsky, @Darth-Mera to ovirt-approvers
  OWNERS_ALIASES
Labels: lgtm, approved

#3180 [release-4.8] Bug 2094765: configure-ovs: avoid restarting NetworkManager
  templates/common/_base/files/configure-ovs-network.yaml
Labels: lgtm, approved, bugzilla/valid-bug, cherry-pick-approved, bugzilla/severity-urgent, qe-approved, backport-risk-assessed

#3329 update to release.openshift.io/feature-set to match OCP 4.12
  install/0000_80_machine-config-operator_02_containerruntimeconfig.crd.yaml
Labels: lgtm, approved

#3328 TRT-540: Add privileged label to infra namespaces
  install/0000_80_machine-config-operator_00_namespace.yaml
Labels: lgtm, approved

#3311 OCPNODE-1146 Add cgroup confiuration support in MCO
  pkg/controller/kubelet-config/helpers.go
  pkg/controller/kubelet-config/kubelet_config_bootstrap.go
  pkg/controller/kubelet-config/kubelet_config_controller.go
  pkg/controller/kubelet-config/kubelet_config_features.go
  pkg/controller/kubelet-config/kubelet_config_nodes.go
  test/e2e-bootstrap/bootstrap_test.go
Labels: lgtm, approved

#3348 OCPBUGS-1616: Revert "Merge pull request #3311 from sairameshv/cgroupv2"
  pkg/controller/kubelet-config/helpers.go
  pkg/controller/kubelet-config/kubelet_config_bootstrap.go
  pkg/controller/kubelet-config/kubelet_config_controller.go
  pkg/controller/kubelet-config/kubelet_config_features.go
  pkg/controller/kubelet-config/kubelet_config_nodes.go
  test/e2e-bootstrap/bootstrap_test.go
Labels: lgtm, approved, bugzilla/valid-bug, jira/severity-critical, jira/valid-bug

#3317 MCO-289: Teach the MCO to use new format image
  Dockerfile
  cmd/machine-config-operator/bootstrap.go
  go.mod
  install/0000_80_machine-config-operator_01_machineconfig.crd.yaml
  install/0000_80_machine-config-operator_05_osimageurl.yaml
  install/image-references
  lib/resourcemerge/machineconfig.go
  manifests/controllerconfig.crd.yaml
  pkg/apis/machineconfiguration.openshift.io/v1/types.go
  pkg/controller/common/constants.go
  pkg/controller/common/helpers.go
  pkg/controller/common/helpers_test.go
  pkg/controller/render/render_controller.go
  pkg/controller/template/render.go
  pkg/daemon/daemon.go
  pkg/daemon/rpm-ostree.go
  pkg/daemon/rpm-ostree_test.go
  pkg/daemon/update.go
  pkg/operator/bootstrap.go
  pkg/operator/images.go
  pkg/operator/status.go
  pkg/operator/status_test.go
  pkg/operator/sync.go
Labels: lgtm, approved

#3233 RFE-2962: configure ovs should use node-ip-hint set by nodeip-configuration service
  templates/common/_base/files/configure-ovs-network.yaml
  templates/common/_base/units/nodeip-configuration.service.yaml
  templates/common/_base/units/ovs-configuration.service.yaml
  templates/common/on-prem/units/nodeip-configuration.service.yaml
Labels: lgtm, approved

#3354 bootstrap: Add CLI arguments for new format oscontainer
  cmd/machine-config-operator/bootstrap.go
Labels: lgtm, approved

#3356 Dockerfile: Remove SCOS extensions image references
  Dockerfile
Labels: lgtm, approved
