Repository openshift/machine-config-operator, pull requests merged in 2022-05, with the labels that each got.

#3127 Bug 2081119: drop doc overlaysize default
  install/0000_80_machine-config-operator_01_containerruntimeconfig.crd.yaml
  pkg/apis/machineconfiguration.openshift.io/v1/types.go
Labels: lgtm, approved, bugzilla/valid-bug, bugzilla/severity-low

#3128 Move Ignition file generation to controller/common, fix Compression
  pkg/controller/common/helpers.go
  pkg/controller/common/helpers_test.go
  pkg/controller/container-runtime-config/helpers.go
  pkg/controller/kubelet-config/helpers.go
  pkg/controller/node/node_controller_test.go
  pkg/daemon/update_test.go
  test/helpers/helpers.go
Labels: lgtm, approved

#3108 colin's small patches rollup
  pkg/daemon/daemon.go
  pkg/daemon/update.go
  pkg/server/server.go
  pkg/server/server_test.go
Labels: lgtm, approved

#3132 Bug 2080267: [vsphere] remove warning encountered on vSphere UPI cluster without API VIP
  pkg/operator/sync.go
Labels: lgtm, approved, bugzilla/valid-bug, bugzilla/severity-medium

#3129 removed the workerlatencyprofile status related code
  go.mod
  go.sum
  pkg/controller/kubelet-config/kubelet_config_nodes.go
  vendor/github.com/openshift/api/config/v1/0000_03_marketplace-operator_01_operatorhub.crd.yaml
  vendor/github.com/openshift/api/config/v1/0000_10_config-operator_01_node.crd.yaml
  vendor/github.com/openshift/api/config/v1/types_cluster_version.go
  vendor/github.com/openshift/api/config/v1/types_node.go
  vendor/github.com/openshift/api/config/v1/zz_generated.deepcopy.go
  vendor/github.com/openshift/api/config/v1/zz_generated.swagger_doc_generated.go
  vendor/github.com/openshift/api/machine/v1beta1/types_awsprovider.go
  vendor/github.com/openshift/api/machine/v1beta1/zz_generated.deepcopy.go
  vendor/github.com/openshift/api/machine/v1beta1/zz_generated.swagger_doc_generated.go
  vendor/github.com/openshift/api/operator/v1/0000_50_ingress-operator_00-ingresscontroller.crd.yaml
  vendor/github.com/openshift/api/operator/v1/0000_50_ingress-operator_00-ingresscontroller.crd.yaml-patch
  vendor/github.com/openshift/api/operator/v1/0000_70_dns-operator_00.crd.yaml
  vendor/github.com/openshift/api/operator/v1/types_dns.go
  vendor/github.com/openshift/api/operator/v1/types_ingress.go
  vendor/github.com/openshift/api/operator/v1/zz_generated.deepcopy.go
  vendor/github.com/openshift/api/operator/v1/zz_generated.swagger_doc_generated.go
  vendor/golang.org/x/net/http2/hpack/huffman.go
  vendor/golang.org/x/net/http2/server.go
  vendor/golang.org/x/net/http2/transport.go
  vendor/golang.org/x/net/http2/writesched.go
  vendor/golang.org/x/net/http2/writesched_random.go
  vendor/golang.org/x/net/idna/go118.go
  vendor/golang.org/x/net/idna/idna10.0.0.go
  vendor/golang.org/x/net/idna/idna9.0.0.go
  vendor/golang.org/x/net/idna/pre_go118.go
  vendor/golang.org/x/net/idna/punycode.go
  vendor/golang.org/x/term/codereview.cfg
  vendor/golang.org/x/term/term.go
  vendor/modules.txt
Labels: lgtm, approved

#3139 OWNERS: remove mkenigs, add raisaat
  OWNERS
Labels: lgtm, approved

#3093 Bug 2076355: fix MCNameSuffix when kcfg ctrrcfg after bootstrap config
  pkg/controller/container-runtime-config/container_runtime_config_bootstrap.go
  pkg/controller/container-runtime-config/container_runtime_config_bootstrap_test.go
  pkg/controller/container-runtime-config/container_runtime_config_controller.go
  pkg/controller/container-runtime-config/container_runtime_config_controller_test.go
  pkg/controller/container-runtime-config/helpers.go
  pkg/controller/kubelet-config/kubelet_config_bootstrap.go
  pkg/controller/kubelet-config/kubelet_config_bootstrap_test.go
Labels: lgtm, approved, bugzilla/valid-bug, bugzilla/severity-low

#3078 Use library-go resourcemerge helper functions
  lib/resourceapply/apps.go
  lib/resourceapply/machineconfig.go
  lib/resourcemerge/apps.go
  lib/resourcemerge/apps_test.go
  lib/resourcemerge/core.go
  lib/resourcemerge/core_test.go
  lib/resourcemerge/machineconfig.go
  lib/resourcemerge/meta.go
  lib/resourcemerge/meta_test.go
Labels: lgtm, approved

#3061 [low priority] test/helpers: fix typo hardcoded pool
  test/helpers/utils.go
Labels: lgtm, approved

#3124 RFE-2703: add prometheus rules for master memory usage
  install/0000_90_machine-config-operator_01_prometheus-rules.yaml
Labels: lgtm, approved

#3140 manifests: Lower daemon RBAC permissions on machineconfig objects
  manifests/machineconfigdaemon/clusterrole.yaml
Labels: lgtm, approved

#3131 [release-4.10] Bug 2081317: configure-ovs.sh: Provide store hint for default route interface
  templates/common/_base/files/configure-ovs-network.yaml
Labels: lgtm, approved, bugzilla/valid-bug, cherry-pick-approved, bugzilla/severity-high, qe-approved, backport-risk-assessed

#3143 daemon: Have nodeWriter maintain ref to lister and node name
  pkg/controller/common/controller_context.go
  pkg/daemon/daemon.go
  pkg/daemon/update.go
  pkg/daemon/writer.go
Labels: lgtm, approved

#3071 [layering] Separate build controller to handle builds for layered pools
  cmd/machine-config-controller/start.go
  cmd/machine-config-daemon/start.go
  docs/BuildController.md
  go.mod
  manifests/machineconfigcontroller/buildcontroller-rolebinding.yaml
  manifests/machineconfigcontroller/clusterrole.yaml
  manifests/machineconfigcontroller/localnamespacerole.yaml
  manifests/machineconfigcontroller/registry-rolebinding.yaml
  manifests/machineconfigdaemon/clusterrole.yaml
  pkg/controller/build/build_controller.go
  pkg/controller/build/pool_build_resources.go
  pkg/controller/common/constants.go
  pkg/controller/common/controller_context.go
  pkg/controller/common/helpers.go
  pkg/controller/node/node_controller.go
  pkg/controller/node/status.go
  pkg/controller/render/machine_config_to_ignition.go
  pkg/controller/render/render_controller.go
  pkg/controller/render/render_controller_test.go
  pkg/daemon/daemon.go
  pkg/daemon/daemon_test.go
  pkg/daemon/node.go
  pkg/daemon/rpm-ostree.go
  pkg/daemon/update.go
  pkg/daemon/writer.go
  pkg/operator/sync.go
  test/e2e-bootstrap/bootstrap_test.go
  vendor/github.com/openshift/client-go/build/clientset/versioned/fake/clientset_generated.go
  vendor/github.com/openshift/client-go/build/clientset/versioned/fake/doc.go
  vendor/github.com/openshift/client-go/build/clientset/versioned/fake/register.go
  vendor/github.com/openshift/client-go/build/clientset/versioned/typed/build/v1/fake/doc.go
  vendor/github.com/openshift/client-go/build/clientset/versioned/typed/build/v1/fake/fake_build.go
  vendor/github.com/openshift/client-go/build/clientset/versioned/typed/build/v1/fake/fake_build_client.go
  vendor/github.com/openshift/client-go/build/clientset/versioned/typed/build/v1/fake/fake_buildconfig.go
  vendor/github.com/openshift/client-go/build/informers/externalversions/build/interface.go
  vendor/github.com/openshift/client-go/build/informers/externalversions/build/v1/build.go
  vendor/github.com/openshift/client-go/build/informers/externalversions/build/v1/buildconfig.go
  vendor/github.com/openshift/client-go/build/informers/externalversions/build/v1/interface.go
  vendor/github.com/openshift/client-go/build/informers/externalversions/factory.go
  vendor/github.com/openshift/client-go/build/informers/externalversions/generic.go
  vendor/github.com/openshift/client-go/build/informers/externalversions/internalinterfaces/factory_interfaces.go
  vendor/github.com/openshift/client-go/build/listers/build/v1/build.go
  vendor/github.com/openshift/client-go/build/listers/build/v1/buildconfig.go
  vendor/github.com/openshift/client-go/build/listers/build/v1/expansion_generated.go
  vendor/modules.txt
Labels: lgtm, approved, layering

#2819 Allow blocking payload reg if it has mirrors configured
  pkg/controller/container-runtime-config/container_runtime_config_controller.go
  pkg/controller/container-runtime-config/container_runtime_config_controller_test.go
  pkg/controller/container-runtime-config/helpers.go
  pkg/controller/container-runtime-config/helpers_test.go
Labels: lgtm, approved

#3144 Bug 2056442: Bug fix for node drain caused by ICSP objects
  pkg/daemon/drain.go
  pkg/daemon/drain_test.go
Labels: lgtm, approved

#2975 [release-4.7] Bug 2057526: ovs-configuration: use lower than NM default ethernet route metric
  templates/common/_base/files/configure-ovs-network.yaml
Labels: lgtm, approved, bugzilla/valid-bug, cherry-pick-approved, bugzilla/severity-high, backport-risk-assessed

#3120 Bug 2078866: configure-ovs: avoid restarting NetworkManager
  templates/common/_base/files/configure-ovs-network.yaml
Labels: lgtm, approved, bugzilla/valid-bug, bugzilla/severity-urgent

#3135 Bug 2086728: Move node draining to controller. Remove MCD privs
  Makefile
  cmd/machine-config-controller/start.go
  cmd/machine-config-daemon/start.go
  manifests/machineconfigcontroller/clusterrole.yaml
  manifests/machineconfigcontroller/deployment.yaml
  manifests/machineconfigdaemon/clusterrole.yaml
  pkg/controller/drain/drain_controller.go
  pkg/daemon/daemon.go
  pkg/daemon/daemon_test.go
  pkg/daemon/drain.go
  pkg/daemon/node.go
  pkg/daemon/update.go
  pkg/daemon/writer.go
Labels: lgtm, approved, bugzilla/valid-bug, bugzilla/severity-unspecified

#3153 Bug 2012969: emit kube events for skipped and upgraded OSes
  pkg/daemon/update.go
Labels: lgtm, approved, bugzilla/valid-bug, bugzilla/severity-high

#3107 Bug 1948551: apiserver-watcher should run in a privileged namespace
  templates/master/00-master/alibabacloud/files/etc-kubernetes-manifests-apiserver-watcher.yaml
  templates/master/00-master/azure/files/etc-kubernetes-manifests-apiserver-watcher.yaml
  templates/master/00-master/gcp/files/etc-kubernetes-manifests-apiserver-watcher.yaml
Labels: lgtm, approved, bugzilla/valid-bug, bugzilla/severity-high

#3162 Bug 2084450: Add unit/file for AWS to compute instance provider-id and pass it to the kubelet
  templates/common/aws/files/usr-local-bin-aws-kubelet-providerid.yaml
  templates/common/aws/units/aws-kubelet-providerid.service.yaml
  templates/master/01-master-kubelet/_base/units/kubelet.service.yaml
  templates/worker/01-worker-kubelet/_base/units/kubelet.service.yaml
Labels: lgtm, approved, bugzilla/valid-bug, bugzilla/severity-medium
