Repository openshift/machine-config-operator, pull requests merged in 2022-04, with the labels that each got.

#2960 Create machine_config_to_ignition
  pkg/controller/common/helpers.go
  pkg/controller/render/machine_config_to_ignition.go
  pkg/controller/render/machine_config_to_ignition_test.go
  pkg/daemon/update.go
Labels: lgtm, approved, layering

#3051 Render Nutanix cloud provider as blank.
  pkg/controller/template/render.go
  pkg/controller/template/render_test.go
Labels: lgtm, approved

#3044 Bug 2069740: Avoid kubernetes node port range
  templates/master/00-master/on-prem/files/haproxy-haproxy.yaml
  templates/master/00-master/on-prem/files/haproxy.yaml
Labels: lgtm, approved, bugzilla/valid-bug, bugzilla/severity-medium

#3030 Integrate functionality from update into layered update
  docs/DemoLayering.md
  hack/layering/file.yaml
  hack/layering/layered-pool.yaml
  hack/layering/live-apply.yaml
  pkg/controller/render/render_controller.go
  pkg/daemon/daemon.go
  pkg/daemon/rpm-ostree.go
  pkg/daemon/rpm-ostree_test.go
  pkg/daemon/update.go
  pkg/daemon/writer.go
Labels: lgtm, approved

#3067 Load system cert pool for image push to accommodate direct cloud storage access
  pkg/controller/render/render_controller.go
Labels: lgtm, approved

#2953 adds zacks hack scripts
  docs/HACKING.md
  hack/get-mcd-nodes.py
  hack/lib
  hack/prep-cluster-for-mcd-push.sh
  hack/push-to-mcd-pods.sh
Labels: lgtm, approved

#3049 [release-4.10] Bug 2070492: configure-ovs: move dhcp config from br-ex to ovs-if-br-ex
  templates/common/_base/files/configure-ovs-network.yaml
Labels: lgtm, approved, bugzilla/valid-bug, cherry-pick-approved, bugzilla/severity-high, qe-approved, backport-risk-assessed

#3008 Bug 2072621: [OCPNODE-869] Create a drop-in file for cri-o's seccomp use default config
  cmd/machine-config-controller/main.go
  cmd/machine-config-controller/start.go
  pkg/controller/bootstrap/bootstrap.go
  pkg/controller/container-runtime-config/container_runtime_config_controller.go
  pkg/controller/container-runtime-config/container_runtime_config_controller_test.go
  pkg/controller/container-runtime-config/helpers.go
Labels: lgtm, approved, bugzilla/valid-bug, cherry-pick-approved, bugzilla/severity-high, backport-risk-assessed

#3080 daemon: add a comment explaining CoreOSDaemon
  pkg/daemon/daemon.go
Labels: lgtm, approved

#3068 daemon: add desiredConfigMap mode for Hypershift
  cmd/machine-config-daemon/start.go
  pkg/daemon/constants/constants.go
  pkg/daemon/daemon.go
  pkg/daemon/update.go
Labels: lgtm, approved, hypershift

#3062 check that layered nodes use CoreOS
  pkg/controller/node/node_controller.go
  pkg/daemon/daemon.go
  pkg/daemon/osrelease.go
  pkg/daemon/update.go
Labels: lgtm, approved, layering

#3087 render: Hack in symlink for `ignition-apply`
  pkg/controller/render/render_controller.go
Labels: lgtm, approved, layering

#3082 [low priority] update_test: remove redundant types
  pkg/daemon/update_test.go
Labels: lgtm, approved

#3009 mcc/node controller: order node updates by zone
  pkg/controller/node/node_controller.go
  pkg/controller/node/node_controller_test.go
Labels: lgtm, approved

#3054 [low priority] kubelet controller: rm unused userDefinedSystemReserved
  pkg/controller/kubelet-config/helpers.go
  pkg/controller/kubelet-config/kubelet_config_bootstrap.go
  pkg/controller/kubelet-config/kubelet_config_controller.go
Labels: lgtm, approved

#3064 Bug 2035005: Move removeUpdateInProgressTaint functionality to mcc
  pkg/controller/node/node_controller.go
  pkg/controller/node/node_controller_test.go
  pkg/daemon/daemon.go
Labels: lgtm, approved, bugzilla/valid-bug, bugzilla/severity-high

#3088 [ layering ] Fix ignition-apply args in dockerfile
  pkg/controller/render/render_controller.go
Labels: lgtm, approved

#2868 Deprecate the use of pkg/errors
  cmd/apiserver-watcher/run.go
  cmd/machine-config-controller/start.go
  cmd/machine-config-daemon/pivot.go
  cmd/machine-config-daemon/start.go
  internal/kubeutils.go
  lib/resourceread/machineconfig.go
  pkg/controller/bootstrap/bootstrap.go
  pkg/controller/common/helpers.go
  pkg/controller/container-runtime-config/container_runtime_config_bootstrap.go
  pkg/controller/container-runtime-config/container_runtime_config_controller.go
  pkg/controller/container-runtime-config/helpers.go
  pkg/controller/kubelet-config/helpers.go
  pkg/controller/kubelet-config/kubelet_config_bootstrap.go
  pkg/controller/kubelet-config/kubelet_config_controller.go
  pkg/controller/kubelet-config/kubelet_config_features.go
  pkg/controller/node/node_controller.go
  pkg/controller/render/hash.go
  pkg/controller/render/render_controller.go
  pkg/controller/template/render.go
  pkg/controller/template/render_test.go
  pkg/controller/template/template_controller.go
  pkg/daemon/config_drift_monitor.go
  pkg/daemon/config_drift_monitor_test.go
  pkg/daemon/controlplane.go
  pkg/daemon/coreos.go
  pkg/daemon/daemon.go
  pkg/daemon/drain.go
  pkg/daemon/image-inspect.go
  pkg/daemon/kernelargs.go
  pkg/daemon/node.go
  pkg/daemon/on_disk_validation.go
  pkg/daemon/pivot/utils/run.go
  pkg/daemon/rpm-ostree.go
  pkg/daemon/update.go
  pkg/operator/bootstrap.go
  pkg/operator/render.go
  pkg/operator/status.go
  pkg/operator/sync.go
  pkg/server/api.go
  pkg/server/bootstrap_server.go
  pkg/server/cluster_server.go
  pkg/server/server.go
  pkg/server/server_test.go
  test/e2e-single-node/sno_mcd_test.go
  test/e2e/ctrcfg_test.go
  test/e2e/kubeletcfg_test.go
  test/helpers/utils.go
Labels: lgtm, approved

#3084 Revise KubeVirt platform for hypershift usage
  pkg/controller/template/render.go
  pkg/operator/bootstrap.go
  pkg/operator/render.go
  templates/common/kubevirt/files/kubevirt-coredns-db.yaml
Labels: lgtm, approved

#3070 Bug 2073021: firstboot: Retry on failure
  cmd/machine-config-daemon/firstboot_complete_machineconfig.go
Labels: lgtm, approved, bugzilla/valid-bug, bugzilla/severity-high

#3085 Kubelet: apply default podPidsLimit
  templates/master/01-master-kubelet/_base/files/kubelet.yaml
  templates/worker/01-worker-kubelet/_base/files/kubelet.yaml
Labels: lgtm, approved

#3033 Bug 2066605: [on-prem] make Corefile api matching stricter
  manifests/on-prem/coredns-corefile.tmpl
  templates/common/on-prem/files/coredns-corefile.yaml
Labels: lgtm, approved, bugzilla/valid-bug, bugzilla/severity-medium, qe-approved

#3092 docs/DemoLayering: Update with snapshot from hackmd
  docs/DemoLayering.md
Labels: lgtm, approved, layering

#3102 daemon: Add some logging for state
  pkg/daemon/daemon.go
Labels: lgtm, approved

#3100 Bug 2076975: OVN Kubernetes configure-ovs-network set static if conversion metric
  templates/common/_base/files/configure-ovs-network.yaml
Labels: lgtm, approved, bugzilla/valid-bug, bugzilla/severity-medium

#3096 kcfg controller remove cleanupmc
  pkg/controller/kubelet-config/kubelet_config_controller.go
  pkg/controller/kubelet-config/kubelet_config_controller_test.go
Labels: lgtm, approved

#3104 nodecontroller: 3 logging patches
  pkg/controller/node/node_controller.go
Labels: lgtm, approved

#3059 Bug 2072040: Avoid NM managing patch port between br-int and br-ex
  templates/common/_base/files/nm-ignore-sdn.yaml
Labels: lgtm, approved, bugzilla/valid-bug, bugzilla/severity-low

#3065 [release-4.8] Bug 2062655: Fix bad cherry-pick at 9f7a7eb96
  templates/common/_base/files/configure-ovs-network.yaml
Labels: lgtm, approved, bugzilla/valid-bug, cherry-pick-approved, bugzilla/severity-urgent, backport-risk-assessed

#3048 [release-4.9] Bug 2070490: configure-ovs: reload NM only when necessary
  templates/common/_base/files/configure-ovs-network.yaml
Labels: lgtm, approved, bugzilla/valid-bug, cherry-pick-approved, bugzilla/severity-medium, backport-risk-assessed

#3111 Do not check for status of other operators for node config
  pkg/controller/kubelet-config/kubelet_config_nodes.go
Labels: lgtm, approved

#3106 Bug 2078945: Ensure only one apiserver-watcher process is active on a node.
  templates/master/00-master/alibabacloud/files/etc-kubernetes-manifests-apiserver-watcher.yaml
  templates/master/00-master/azure/files/etc-kubernetes-manifests-apiserver-watcher.yaml
  templates/master/00-master/gcp/files/etc-kubernetes-manifests-apiserver-watcher.yaml
Labels: lgtm, approved, bugzilla/valid-bug, bugzilla/severity-high

#2967 Bug 2057544: daemon: Explicitly start rpm-ostreed, restart if we detect active txn
  pkg/daemon/daemon.go
  pkg/daemon/rpm-ostree.go
  pkg/daemon/rpm-ostree_test.go
Labels: lgtm, approved, bugzilla/valid-bug, cherry-pick-approved, bugzilla/severity-medium, backport-risk-assessed

#3091 [release-4.10] Bug 2076308: Move removeUpdateInProgressTaint functionality to mcc
  pkg/controller/node/node_controller.go
  pkg/controller/node/node_controller_test.go
  pkg/daemon/daemon.go
Labels: lgtm, approved, bugzilla/valid-bug, cherry-pick-approved, bugzilla/severity-high, 4.10, backport-risk-assessed

#3109 [release-4.10] Bug 2072621: Fix bootstrap-unit test failure caused by #3008
  test/e2e-bootstrap/bootstrap_test.go
Labels: lgtm, approved, bugzilla/valid-bug, cherry-pick-approved, bugzilla/severity-high, 4.10, backport-risk-assessed

#3105 daemon: Validate kernel arguments
  pkg/daemon/daemon.go
Labels: lgtm, approved

#3125 Bug 2076521: mcc: update node sort to account for matching zones
  pkg/controller/node/node_controller.go
  pkg/controller/node/node_controller_test.go
Labels: lgtm, approved, bugzilla/valid-bug, bugzilla/severity-low
