Repository openshift/machine-config-operator, pull requests merged in 2022-08, with the labels that each got.

#3279 Fix typo
  templates/common/_base/files/kubelet-auto-sizing.yaml
Labels: lgtm, approved, ok-to-test

#3271 Bug 2105003: on-prem: improvements on resolv-prepender
  templates/common/on-prem/files/NetworkManager-resolv-prepender.yaml
  templates/common/on-prem/units/kubelet.service-wait-resolv.yaml
Labels: lgtm, approved, bugzilla/valid-bug, bugzilla/severity-high

#3245 [release-4.11] Bug 2104386: Fix problem with retaining data in string array in piped while loop
  templates/common/_base/files/configure-ovs-network.yaml
Labels: lgtm, approved, bugzilla/valid-bug, cherry-pick-approved, bugzilla/severity-medium, qe-approved, backport-risk-assessed

#2509 daemon: drop `systemctl stop kubelet` during node reboot
  pkg/daemon/daemon.go
Labels: lgtm, approved

#3272 Allow overriding OSImageURL with a layered image
  pkg/controller/common/helpers.go
  pkg/controller/common/helpers_test.go
  pkg/controller/render/render_controller.go
  pkg/controller/render/render_controller_test.go
  pkg/daemon/daemon.go
  pkg/daemon/rpm-ostree.go
  pkg/daemon/rpm-ostree_test.go
  pkg/daemon/update.go
Labels: lgtm, approved

#3286 Accept new image format, consume in controllerconfig, but stop there
  cmd/machine-config-operator/bootstrap.go
  install/0000_80_machine-config-operator_02_images.configmap.yaml
  install/0000_80_machine-config-operator_04_deployment.yaml
  install/0000_80_machine-config-operator_05_osimageurl.yaml
  install/image-references
  lib/resourcemerge/machineconfig.go
  manifests/controllerconfig.crd.yaml
  pkg/apis/machineconfiguration.openshift.io/v1/types.go
  pkg/controller/render/render_controller.go
  pkg/operator/bootstrap.go
  pkg/operator/images.go
  pkg/operator/sync.go
Labels: lgtm, approved

#3291 Bug 2111817: daemon: Add a workaround for bug 2111817
  pkg/daemon/rpm-ostree.go
Labels: lgtm, approved, bugzilla/valid-bug, bugzilla/severity-medium

#3292 OCPBUGS-197: daemon: Add a workaround for bug 2111817
  pkg/daemon/rpm-ostree.go
Labels: lgtm, approved, bugzilla/valid-bug, cherry-pick-approved, backport-risk-assessed, jira/severity-important, jira/valid-bug

#3280 Decompress and decode Ignition configs from ConfigMap
  pkg/controller/common/fixtures/compressed_and_encoded_ign_config.json.gz
  pkg/controller/common/fixtures/compressed_ign_config.json.gz
  pkg/controller/common/fixtures/fixtures.go
  pkg/controller/common/fixtures/ign_config.json
  pkg/controller/common/fixtures/update_fixtures.sh
  pkg/controller/common/helpers.go
  pkg/controller/common/helpers_test.go
  pkg/daemon/daemon.go
Labels: lgtm, approved

#3276 Bug-2051533: Adding day2 remote worker node requires manually approving CSRs
  templates/common/on-prem/files/NetworkManager-resolv-prepender.yaml
Labels: lgtm, approved

#3179 MCD: Add support for RHCOS9 and SCOS9
  pkg/daemon/kernelargs.go
  pkg/daemon/osrelease.go
  pkg/daemon/update.go
Labels: lgtm, approved

#3174 Remove `onPremPlatformKeepalivedEnableUnicast` function
  pkg/controller/template/render.go
  pkg/operator/render.go
Labels: lgtm, approved

#3299 Round off SYSTEM_RESERVED_MEMORY if value is in decimal
  templates/common/_base/files/kubelet-auto-sizing.yaml
Labels: lgtm, approved, ok-to-test

#3301 fixes config decompression lint issue
  pkg/controller/common/helpers.go
Labels: lgtm, approved

#3250 Bug 2107113: Fix .ssh directory not owned by core when created by Machine Config D…
  pkg/daemon/update.go
Labels: lgtm, approved, bugzilla/valid-bug, bugzilla/severity-low

#3294 OKD: Add build args for FCOS and SCOS
  Dockerfile
  cmd/machine-config-operator/bootstrap.go
  hack/build-go.sh
  pkg/version/version.go
  pkg/version/version_fcos.go
  pkg/version/version_scos.go
Labels: lgtm, approved

#3304 daemon: Use just one NodeUpdaterClient instance
  pkg/daemon/daemon.go
  pkg/daemon/update.go
  pkg/daemon/update_test.go
Labels: lgtm, approved

#3274 Add kubens.service, drop-ins, and kubensenter prefix to kubelet.service
  Makefile
  go.mod
  go.sum
  hack/update-templates.sh
  hack/verify-templates.sh
  templates/common/_base/units/crio.service-kubens.yaml
  templates/common/_base/units/kubelet.service-kubens.yaml
  templates/common/_base/units/kubens.service.yaml
  templates/master/01-master-kubelet/_base/files/kubenswrapper.yaml
  templates/master/01-master-kubelet/_base/units/kubelet.service.yaml
  templates/master/01-master-kubelet/alibabacloud/units/kubelet.service.yaml
  templates/master/01-master-kubelet/on-prem/units/kubelet.service.yaml
  templates/worker/01-worker-kubelet/_base/files/kubenswrapper.yaml
  templates/worker/01-worker-kubelet/_base/units/kubelet.service.yaml
  templates/worker/01-worker-kubelet/alibabacloud/units/kubelet.service.yaml
  templates/worker/01-worker-kubelet/on-prem/units/kubelet.service.yaml
  tools.go
  vendor/github.com/containers/kubensmnt/LICENSE
  vendor/github.com/containers/kubensmnt/utils/systemd/README.md
  vendor/github.com/containers/kubensmnt/utils/systemd/embed.go
  vendor/github.com/containers/kubensmnt/utils/systemd/kubens-dropin.conf
  vendor/github.com/containers/kubensmnt/utils/systemd/kubens.service
  vendor/modules.txt
Labels: lgtm, approved

#3315 OCPBUGS-642: Fix .ssh directory not owned by core when created by Machine Config Daemon
  pkg/daemon/update.go
Labels: lgtm, approved, bugzilla/valid-bug, cherry-pick-approved, backport-risk-assessed, jira/severity-low, jira/valid-bug

#3318 OCPBUGS-631: Pull container image as a separate step
  templates/common/on-prem/files/NetworkManager-resolv-prepender.yaml
Labels: lgtm, approved, bugzilla/valid-bug, jira/severity-important, jira/valid-bug

#3319 OCPBUGS-737: Pull container image as a separate step
  templates/common/on-prem/files/NetworkManager-resolv-prepender.yaml
Labels: lgtm, approved, cherry-pick-approved, backport-risk-assessed, jira/severity-important, jira/valid-bug
