Repository openshift/machine-config-operator, pull requests merged in 2022-07, with the labels that each got.

#3202 Bug 2096413: configure-ovs: set mac only for non fail_over_mac bonds
  templates/common/_base/files/configure-ovs-network.yaml
Labels: lgtm, approved, bugzilla/valid-bug, bugzilla/severity-high, qe-approved

#3211 Bug 2099664: daemon: initialize nodewriter before login monitor
  pkg/daemon/daemon.go
Labels: lgtm, approved, bugzilla/valid-bug, bugzilla/severity-high

#3148 Update block payload test with vendored runtime-utils
  go.mod
  go.sum
  pkg/controller/container-runtime-config/container_runtime_config_controller_test.go
  vendor/github.com/openshift/runtime-utils/pkg/registries/registries.go
  vendor/modules.txt
Labels: lgtm, approved

#3217 Bug 2101880: NS manifest: Set empty openshift.io/run-level
  install/0000_80_machine-config-operator_00_namespace.yaml
Labels: lgtm, approved, bugzilla/valid-bug, bugzilla/severity-high

#3189 Bug 2097785: Send out OSUpdateStaged event directly
  pkg/daemon/update.go
Labels: lgtm, approved, bugzilla/valid-bug, bugzilla/severity-medium

#3214 Bug 2101157: configure-ovs: fix handling of connection names with spaces and checking the connection name suffix
  templates/common/_base/files/configure-ovs-network.yaml
Labels: lgtm, approved, bugzilla/valid-bug, bugzilla/severity-medium

#3203 Bug 2099945: configure-ovs: clone inactive autoconnect slaves
  templates/common/_base/files/configure-ovs-network.yaml
Labels: lgtm, approved, bugzilla/valid-bug, bugzilla/severity-medium

#3226 Bug 2102004: pkg/controller/common/helpers: Explicitly set mode 0644
  pkg/controller/common/helpers.go
Labels: lgtm, approved, bugzilla/valid-bug, bugzilla/severity-high

#3212 Bug 2103786: drain controller: don't skip the MCC pod drain
  manifests/machineconfigcontroller/deployment.yaml
  pkg/controller/drain/drain_controller.go
Labels: lgtm, approved, bugzilla/valid-bug, bugzilla/severity-high

#3242 Bug 2101157: configure-ovs: fix handling of connection names with spaces and checking the connection name suffix
  templates/common/_base/files/configure-ovs-network.yaml
Labels: lgtm, approved, bugzilla/valid-bug, bugzilla/severity-medium

#3237 on-prem: render-config-coredns from /var/run/NetworkManager/resolv.conf
  templates/common/on-prem/files/coredns.yaml
Labels: lgtm, approved

#3197 [release-4.10] Bug 2098626: configure-ovs: improve handling of static ip and mac address configuration
  templates/common/_base/files/configure-ovs-network.yaml
Labels: lgtm, approved, bugzilla/valid-bug, cherry-pick-approved, bugzilla/severity-high, qe-approved, backport-risk-assessed

#3239 daemon: Drop workarounds for rpm-ostree bugs
  pkg/daemon/rpm-ostree.go
Labels: lgtm, approved

#3248 daemon: Drop tuneableFCOSArgsAllowlist
  pkg/daemon/kernelargs.go
Labels: lgtm, approved

#3224 [release-4.10] Bug 2100894: fix MCNameSuffix with kcfg ctrrcfg
  pkg/controller/container-runtime-config/container_runtime_config_bootstrap.go
  pkg/controller/container-runtime-config/container_runtime_config_bootstrap_test.go
  pkg/controller/container-runtime-config/container_runtime_config_controller.go
  pkg/controller/container-runtime-config/container_runtime_config_controller_test.go
  pkg/controller/container-runtime-config/helpers.go
  pkg/controller/kubelet-config/helpers.go
  pkg/controller/kubelet-config/kubelet_config_bootstrap.go
  pkg/controller/kubelet-config/kubelet_config_bootstrap_test.go
  pkg/controller/kubelet-config/kubelet_config_controller.go
  pkg/controller/kubelet-config/kubelet_config_controller_test.go
Labels: lgtm, approved, bugzilla/valid-bug, cherry-pick-approved, bugzilla/severity-medium, backport-risk-assessed

#3264 Bug 2109963: Master node in SchedulingDisabled after upgrade from 4.10.24 -> 4.11.0-rc.4
  pkg/controller/drain/drain_controller.go
Labels: lgtm, approved, bugzilla/valid-bug, bugzilla/severity-medium

#3149 ctrcfg controller remove cleanupmc()
  pkg/controller/container-runtime-config/container_runtime_config_controller.go
  pkg/controller/container-runtime-config/container_runtime_config_controller_test.go
Labels: lgtm, approved

#3266 Update approvers and reviewers list with current active members
  OWNERS
Labels: lgtm, approved

#3254 [release-4.9] Bug 2108538: configure-ovs: improve handling of static ip and mac address configuration
  templates/common/_base/files/configure-ovs-network.yaml
Labels: lgtm, approved, bugzilla/valid-bug, cherry-pick-approved, bugzilla/severity-high, qe-approved, backport-risk-assessed

#3251 Prep patches for bumping openshift/client-go
  go.mod
  go.sum
  vendor/github.com/googleapis/gnostic/compiler/README.md
  vendor/github.com/googleapis/gnostic/compiler/context.go
  vendor/github.com/googleapis/gnostic/compiler/error.go
  vendor/github.com/googleapis/gnostic/compiler/extension-handler.go
  vendor/github.com/googleapis/gnostic/compiler/extensions.go
  vendor/github.com/googleapis/gnostic/compiler/helpers.go
  vendor/github.com/googleapis/gnostic/compiler/main.go
  vendor/github.com/googleapis/gnostic/compiler/reader.go
  vendor/github.com/googleapis/gnostic/extensions/README.md
  vendor/github.com/googleapis/gnostic/extensions/extension.pb.go
  vendor/github.com/googleapis/gnostic/extensions/extension.proto
  vendor/github.com/googleapis/gnostic/extensions/extensions.go
  vendor/github.com/googleapis/gnostic/jsonschema/README.md
  vendor/github.com/googleapis/gnostic/jsonschema/base.go
  vendor/github.com/googleapis/gnostic/jsonschema/display.go
  vendor/github.com/googleapis/gnostic/jsonschema/models.go
  vendor/github.com/googleapis/gnostic/jsonschema/operations.go
  vendor/github.com/googleapis/gnostic/jsonschema/reader.go
  vendor/github.com/googleapis/gnostic/jsonschema/schema.json
  vendor/github.com/googleapis/gnostic/jsonschema/writer.go
  vendor/github.com/googleapis/gnostic/openapiv2/OpenAPIv2.go
  vendor/github.com/googleapis/gnostic/openapiv2/OpenAPIv2.pb.go
  vendor/github.com/googleapis/gnostic/openapiv2/OpenAPIv2.proto
  vendor/github.com/googleapis/gnostic/openapiv2/README.md
  vendor/github.com/googleapis/gnostic/openapiv2/document.go
  vendor/github.com/googleapis/gnostic/openapiv2/openapi-2.0.json
  vendor/k8s.io/api/autoscaling/v2beta1/types.go
  vendor/k8s.io/api/autoscaling/v2beta1/zz_generated.prerelease-lifecycle.go
  vendor/k8s.io/api/autoscaling/v2beta2/types.go
  vendor/k8s.io/api/autoscaling/v2beta2/zz_generated.prerelease-lifecycle.go
  vendor/k8s.io/api/flowcontrol/v1alpha1/types.go
  vendor/k8s.io/api/flowcontrol/v1alpha1/zz_generated.prerelease-lifecycle.go
  vendor/k8s.io/api/flowcontrol/v1beta1/types.go
  vendor/k8s.io/api/flowcontrol/v1beta1/zz_generated.prerelease-lifecycle.go
  vendor/modules.txt
Labels: lgtm, approved

#3273 [OCPNODE-709] add control-plane label
  templates/master/01-master-kubelet/_base/units/kubelet.service.yaml
  templates/master/01-master-kubelet/alibabacloud/units/kubelet.service.yaml
  templates/master/01-master-kubelet/on-prem/units/kubelet.service.yaml
Labels: lgtm, approved
