Repository openshift/machine-config-operator, pull requests merged in 2023-02, with the labels that each got.

#3467 OCPBUGS-3612: configure-ovs: optionally generate configuration in /run
  templates/common/_base/files/configure-ovs-network.yaml
Labels: lgtm, approved, bugzilla/valid-bug, qe-approved, jira/severity-important, jira/valid-bug

#3533 daemon: Add some comments on the firstboot reboot sleep
  pkg/daemon/daemon.go
Labels: lgtm, approved

#3278 [release-4.10] OCPBUGS-4830: daemon: gate done state on uncordon completion
  pkg/daemon/daemon.go
Labels: lgtm, approved, bugzilla/valid-bug, cherry-pick-approved, backport-risk-assessed, jira/severity-important, jira/valid-bug

#3516 Preserve logs from Podman executions
  templates/common/_base/units/machine-config-daemon-pull.service.yaml
Labels: lgtm, approved

#3523 OCPBUGS-5520: MCDPivotError alert fires due temporary transient failures
  install/0000_90_machine-config-operator_01_prometheus-rules.yaml
  pkg/daemon/metrics.go
  pkg/daemon/update.go
Labels: lgtm, approved, bugzilla/valid-bug, qe-approved, jira/severity-important, jira/valid-bug, jira/valid-reference

#3488 Bug 2104978: fix degraded pool state message
  pkg/apis/machineconfiguration.openshift.io/v1/helpers.go
  pkg/controller/node/node_controller.go
  pkg/controller/node/status.go
  pkg/daemon/daemon.go
  test/e2e-shared-tests/helpers.go
  test/e2e-shared-tests/mcd_config_drift.go
  test/e2e/mcd_test.go
  test/helpers/utils.go
  vendor/k8s.io/code-generator/generate-groups.sh
  vendor/k8s.io/code-generator/generate-internal-groups.sh
Labels: lgtm, approved, ok-to-test, bugzilla/valid-bug, bugzilla/severity-medium

#3422 [release-4.11] OCPBUGS-3507: On-prem: Ensure resolv-prepender respects NM dispatcher timeout
  templates/common/on-prem/files/NetworkManager-resolv-prepender.yaml
  templates/common/on-prem/units/kubelet.service-wait-resolv.yaml
Labels: lgtm, approved, bugzilla/valid-bug, cherry-pick-approved, backport-risk-assessed, jira/severity-important, jira/valid-bug

#3513 OCPBUGS-5888: Don't switch to the "live" certificate bundle until after first ControllerConfig is generated
  pkg/operator/sync.go
Labels: lgtm, approved, bugzilla/valid-bug, qe-approved, jira/severity-critical, jira/valid-bug, jira/valid-reference

#3529 OCPBUGS-6945: Fixes node OS detection
  pkg/daemon/daemon.go
  pkg/daemon/kernelargs.go
  pkg/daemon/osrelease.go
  pkg/daemon/osrelease/osrelease.go
  pkg/daemon/osrelease/osrelease_test.go
  pkg/daemon/osrelease_test.go
  pkg/daemon/rpm-ostree.go
  pkg/daemon/update_test.go
  test/e2e/node_os_test.go
  test/helpers/utils.go
Labels: lgtm, approved, bugzilla/valid-bug, qe-approved, jira/valid-bug, jira/valid-reference

#3429 [release-4.9] OCPBUGS-4051: Add ephemeral storage to kubelet system reserved args
  pkg/controller/kubelet-config/helpers.go
  pkg/controller/kubelet-config/kubelet_config_controller.go
  templates/common/_base/files/kubelet-auto-node-sizing-enabled.yaml
  templates/common/_base/files/kubelet-auto-sizing.yaml
  templates/common/_base/units/kubelet-auto-node-size.service.yaml
  templates/master/01-master-kubelet/_base/files/kubelet.yaml
  templates/master/01-master-kubelet/_base/units/kubelet.service.yaml
  templates/master/01-master-kubelet/on-prem/units/kubelet.service.yaml
  templates/worker/01-worker-kubelet/_base/files/kubelet.yaml
  templates/worker/01-worker-kubelet/_base/units/kubelet.service.yaml
  templates/worker/01-worker-kubelet/on-prem/units/kubelet.service.yaml
Labels: lgtm, approved, bugzilla/valid-bug, cherry-pick-approved, qe-approved, backport-risk-assessed, jira/valid-bug

#3507 OCPBUGS-5497: MCDRebootError alarm disappears after 15 minutes
  install/0000_90_machine-config-operator_01_prometheus-rules.yaml
  pkg/daemon/update.go
Labels: lgtm, approved, bugzilla/valid-bug, qe-approved, jira/severity-moderate, jira/valid-bug, jira/valid-reference

#3530 Add doc for IDMS and ITMS CRDs
  docs/ImageMirrorSetDesign.md
Labels: lgtm, approved

#3535 OCPBUGS-6997: Fix 4.12 art images
  .ci-operator.yaml
  Dockerfile
  Dockerfile.rhel7
  cmd/apiserver-watcher/run.go
  cmd/machine-config-daemon/pivot.go
  cmd/machine-config-operator/bootstrap.go
  pkg/controller/bootstrap/bootstrap.go
  pkg/controller/bootstrap/bootstrap_test.go
  pkg/controller/common/helpers.go
  pkg/controller/container-runtime-config/helpers_test.go
  pkg/controller/kubelet-config/kubelet_config_controller.go
  pkg/controller/kubelet-config/kubelet_config_controller_test.go
  pkg/controller/kubelet-config/kubelet_config_features.go
  pkg/controller/template/render.go
  pkg/controller/template/render_test.go
  pkg/daemon/config_drift_monitor_test.go
  pkg/daemon/coreos.go
  pkg/daemon/daemon.go
  pkg/daemon/daemon_test.go
  pkg/daemon/drain.go
  pkg/daemon/kernelargs.go
  pkg/daemon/node.go
  pkg/daemon/on_disk_validation.go
  pkg/daemon/pivot/utils/run_test.go
  pkg/daemon/rpm-ostree.go
  pkg/daemon/update.go
  pkg/daemon/update_test.go
  pkg/generated/clientset/versioned/fake/register.go
  pkg/generated/clientset/versioned/scheme/register.go
  pkg/operator/bootstrap.go
  pkg/operator/render.go
  pkg/operator/sync.go
  pkg/server/api_test.go
  pkg/server/bootstrap_server.go
  pkg/server/cluster_server.go
  pkg/server/server_test.go
  test/e2e-bootstrap/bootstrap_test.go
  test/e2e/ctrcfg_test.go
  test/e2e/kubeletcfg_test.go
  test/e2e/mcd_test.go
Labels: lgtm, approved, bugzilla/valid-bug, cherry-pick-approved, backport-risk-assessed, jira/valid-bug, jira/valid-reference

#3541 Bug 2027000: The user is ignored when we create a new file using a MachineConfig
  pkg/daemon/file_writers.go
Labels: lgtm, approved, bugzilla/valid-bug, bugzilla/severity-high

#3525 OCPBUGS-630: controller: default overwrite to true for files
  pkg/controller/common/helpers.go
  pkg/controller/common/helpers_test.go
Labels: lgtm, approved, bugzilla/valid-bug, qe-approved, jira/severity-important, jira/valid-bug, jira/valid-reference

#3545 OCPBUGS-7207: configure-ovs: fix mtu-migration cleanup
  templates/common/_base/files/configure-ovs-network.yaml
Labels: lgtm, approved, bugzilla/valid-bug, jira/severity-moderate, jira/valid-bug, jira/valid-reference

#3540 OPNET-133: Enabling remote worker feature only for baremetal platform
  templates/common/on-prem/units/nodeip-configuration.service.yaml
Labels: lgtm, approved, jira/valid-reference

#3547 Fix typo in ctrcfg,kcfg docs
  docs/ContainerRuntimeConfigDesign.md
  docs/HACKING.md
  docs/KubeletConfigDesign.md
Labels: lgtm, approved

#3342 OCPBUGS-1565: Prevent possible split-brain scenario with keepalived unicast
  templates/master/00-master/on-prem/files/keepalived-keepalived.yaml
  templates/worker/00-worker/on-prem/files/keepalived-keepalived.yaml
Labels: lgtm, approved, bugzilla/valid-bug, jira/valid-bug

#3524 OCPBUGS-6682: Switch from ifconfig to iproute2
  templates/common/_base/files/configure-ovs-network.yaml
Labels: lgtm, approved, bugzilla/valid-bug, qe-approved, jira/severity-moderate, jira/valid-bug, jira/valid-reference

#3497 [release-4.11] OCPBUGS-6002: There are not enough logs in case "oc extract" is stuck in mco first boot in mco first boot
  pkg/daemon/update.go
Labels: lgtm, approved, bugzilla/valid-bug, cherry-pick-approved, backport-risk-assessed, jira/valid-bug, jira/valid-reference

#3518 OPNET-197: Remove node-ip from kubelet for dual-stack vSphere
  templates/master/01-master-kubelet/vsphere/units/kubelet.service.yaml
  templates/worker/01-worker-kubelet/vsphere/units/kubelet.service.yaml
Labels: lgtm, approved, jira/valid-reference

#3556 OCPNODE-1501: add protectKernelDefaults to kubelet config
  templates/master/01-master-kubelet/_base/files/kubelet.yaml
  templates/worker/01-worker-kubelet/_base/files/kubelet.yaml
Labels: lgtm, approved, jira/valid-reference

#3569 OCPBUGS-7896: MCO should not add keepalived pod manifests in case of VSPHERE UPI
  pkg/controller/template/render.go
Labels: lgtm, approved, bugzilla/valid-bug, jira/valid-bug, jira/valid-reference

#3570 OCPBUGS-7909: Fix permissions on resolv.conf
  templates/common/on-prem/files/NetworkManager-resolv-prepender.yaml
  templates/common/on-prem/files/resolv-prepender.yaml
  templates/common/on-prem/units/on-prem-resolv-prepender.service.yaml
Labels: lgtm, approved, bugzilla/valid-bug, jira/valid-bug, jira/valid-reference

#3568 WRKLDS-705: Bump openshift/api to enable DynamicResourceAllocation through TechPreviewNoUpgrade
  go.mod
  go.sum
  vendor/github.com/openshift/api/config/v1/0000_10_config-operator_01_infrastructure-Default.crd.yaml
  vendor/github.com/openshift/api/config/v1/0000_10_config-operator_01_infrastructure-TechPreviewNoUpgrade.crd.yaml
  vendor/github.com/openshift/api/config/v1/stable.infrastructure.testsuite.yaml
  vendor/github.com/openshift/api/config/v1/types_feature.go
  vendor/github.com/openshift/api/config/v1/types_infrastructure.go
  vendor/github.com/openshift/api/config/v1/zz_generated.deepcopy.go
  vendor/github.com/openshift/api/config/v1/zz_generated.swagger_doc_generated.go
  vendor/github.com/openshift/api/machine/v1/types_nutanixprovider.go
  vendor/github.com/openshift/api/machine/v1/zz_generated.deepcopy.go
  vendor/github.com/openshift/api/machine/v1/zz_generated.swagger_doc_generated.go
  vendor/github.com/openshift/api/operator/v1/0000_70_cluster-network-operator_01.crd.yaml
  vendor/github.com/openshift/api/operator/v1/types_network.go
  vendor/github.com/openshift/api/operator/v1/zz_generated.swagger_doc_generated.go
  vendor/modules.txt
Labels: lgtm, approved, jira/valid-reference

#3551 OCPBUGS-7743: Adding dnsmasq config for sno
  OWNERS_ALIASES
  pkg/controller/template/render.go
  pkg/controller/template/render_test.go
  templates/common/sno/OWNERS
  templates/common/sno/files/sno-dnsmasq.conf.yaml
Labels: lgtm, approved, bugzilla/valid-bug, jira/valid-bug, jira/valid-reference

#3567 Regenerate controllerconfig.crd.yaml
  manifests/controllerconfig.crd.yaml
Labels: lgtm, approved

#3539 MCO-417: MCO-418: MCD watches/create/update password with MachineConfig
  install/0000_80_machine-config-operator_01_machineconfig.crd.yaml
  pkg/controller/common/helpers_test.go
  pkg/daemon/update.go
  pkg/daemon/update_test.go
  test/e2e/mcd_test.go
Labels: lgtm, approved, ok-to-test, qe-approved, jira/valid-reference

#3574 Fixing platform path order as platform specific path should be the last
  pkg/controller/template/render.go
Labels: lgtm, approved

#3572 OCPBUGS-7903: Pool degraded with error: rpm-ostree kargs: signal: terminated
  pkg/daemon/daemon.go
  pkg/daemon/update.go
Labels: lgtm, approved, bugzilla/valid-bug, qe-approved, jira/severity-important, jira/valid-bug, jira/valid-reference
