Repository openshift/machine-config-operator, pull requests merged in 2023-07, with the labels that each got.

#3773 OCPBUGS-15728: Fix machine config drifts when deploying with platform external
  manifests/controllerconfig.crd.yaml
  pkg/controller/container-runtime-config/container_runtime_config_controller_test.go
  pkg/controller/template/render.go
  pkg/controller/template/render_test.go
  pkg/controller/template/template_controller_test.go
  pkg/controller/template/test_data/controller_config_external.yaml
Labels: lgtm, approved, qe-approved, jira/valid-bug, jira/valid-reference

#3764 OCPBUGS-15580: 4.13: Dockerfile: update rhel7 nmstate pin
  Dockerfile.rhel7
Labels: lgtm, approved, cherry-pick-approved, backport-risk-assessed, jira/severity-important, jira/valid-bug, jira/valid-reference

#3733 OCPBUGS-14674: set pool alert back to zero in more default scenarios.
  install/0000_90_machine-config-operator_01_prometheus-rules.yaml
  pkg/controller/common/metrics.go
  pkg/controller/node/node_controller.go
Labels: lgtm, approved, qe-approved, jira/severity-moderate, jira/valid-bug, jira/valid-reference

#3779 Update 0000_90_machine-config-operator_01_prometheus-rules.yaml
  install/0000_90_machine-config-operator_01_prometheus-rules.yaml
Labels: lgtm, approved

#3781 OpenStack: restrict IPv6 configuration
  templates/common/openstack/files/ipv6-config.yaml
Labels: lgtm, approved

#3767 set MCO namespace on all events
  pkg/controller/common/helpers.go
  pkg/controller/container-runtime-config/container_runtime_config_controller.go
  pkg/controller/drain/drain_controller.go
  pkg/controller/kubelet-config/kubelet_config_controller.go
  pkg/controller/node/node_controller.go
  pkg/controller/render/render_controller.go
  pkg/controller/render/render_controller_test.go
  pkg/controller/template/template_controller.go
  pkg/daemon/writer.go
  pkg/operator/operator.go
Labels: lgtm, approved

#3776 add wasm extension
  docs/MachineConfiguration.md
  pkg/daemon/update.go
  test/e2e-single-node/sno_mcd_test.go
  test/e2e/mcd_test.go
Labels: lgtm, approved

#3802 4.13: Revert rhel9 binaries builds
  Dockerfile
  Dockerfile.rhel7
  templates/common/_base/units/machine-config-daemon-pull.service.yaml
Labels: lgtm, approved, cherry-pick-approved, backport-risk-assessed, jira/valid-bug

#3794 OCPBUGS-11997: Prevent NM from unsetting the hostname
  templates/common/_base/files/usr-local-bin-mco-hostname.yaml
Labels: lgtm, approved, jira/severity-moderate, jira/valid-bug, jira/valid-reference

#3793 OCPNODE-1717: Update config node spec while explicitly updating the cgroups mode
  pkg/controller/kubelet-config/kubelet_config_nodes.go
  pkg/controller/kubelet-config/kubelet_config_nodes_test.go
  test/e2e-bootstrap/bootstrap_test.go
Labels: lgtm, approved, cherry-pick-approved, backport-risk-assessed, jira/valid-bug, jira/valid-reference

#3785 Bug OCPBUGS-15233: OpenStack: fix IPv6 configuration
  templates/common/openstack/files/ipv6-config.yaml
Labels: lgtm, approved, jira/severity-critical, jira/valid-bug, jira/valid-reference

#3775 OCPBUGS-15613: Soften grep pattern for ingress default router
  templates/common/on-prem/files/keepalived-script-default-ingress.yaml
Labels: lgtm, approved, jira/valid-bug, jira/valid-reference

#3730 operator: Stop mounting /etc/kubernetes/ca.crt
  install/0000_80_machine-config-operator_04_deployment.yaml
Labels: lgtm, approved

#3780 kubevirt: Configure IPv6 arp proxy default gw
  OWNERS_ALIASES
  templates/common/kubevirt/OWNERS
  templates/common/kubevirt/files/001-nmstate-disable-ipv6-autoconf.yaml
  templates/common/kubevirt/files/002-nmstate-arp-proxy-ipv6-gw.yaml
Labels: lgtm, approved

#3791 MCO-596: Deprecate the login monitor
  docs/MachineConfigDaemon.md
  pkg/daemon/daemon.go
  pkg/daemon/metrics.go
  pkg/daemon/writer.go
Labels: lgtm, approved, jira/valid-reference

#3799 OCPBUGS-16128: daemon: Copy matching binary to host, re-exec with it
  Dockerfile
  Dockerfile.rhel7
  Makefile
  cmd/machine-config-daemon/firstboot_complete_machineconfig.go
  cmd/machine-config-daemon/pivot.sh
  cmd/machine-config-daemon/start.go
  hack/build-go.sh
  pkg/daemon/constants/constants.go
  pkg/daemon/daemon.go
  pkg/daemon/osrelease/osrelease.go
  templates/common/_base/units/machine-config-daemon-firstboot.service.yaml
  templates/common/_base/units/machine-config-daemon-pull.service.yaml
Labels: lgtm, approved, jira/severity-critical, jira/valid-bug, jira/valid-reference

#3774 MGMT-14843: ovs-configuration service should copy the statically configured address even if the method isn't manual.
  templates/common/_base/files/configure-ovs-network.yaml
Labels: lgtm, approved, jira/valid-reference

#3583 MCO MCO-424: daemon: Remove old legacy OS update path
  pkg/daemon/daemon.go
  pkg/daemon/rpm-ostree.go
  pkg/daemon/update.go
Labels: lgtm, approved, qe-approved, jira/valid-reference

#3813 MCO-687: Fix metrics e2e test
  test/e2e-shared-tests/helpers.go
  test/e2e/mco_test.go
  test/helpers/utils.go
Labels: lgtm, approved, jira/valid-reference

#3812 OCPBUGS-16622: daemon: Copy matching binary to host, re-exec with it
  Dockerfile
  Dockerfile.rhel7
  Makefile
  cmd/machine-config-daemon/firstboot_complete_machineconfig.go
  cmd/machine-config-daemon/pivot.sh
  cmd/machine-config-daemon/start.go
  hack/build-go.sh
  pkg/daemon/constants/constants.go
  pkg/daemon/daemon.go
  pkg/daemon/osrelease/osrelease.go
  templates/common/_base/units/machine-config-daemon-firstboot.service.yaml
  templates/common/_base/units/machine-config-daemon-pull.service.yaml
Labels: lgtm, approved, cherry-pick-approved, backport-risk-assessed, jira/severity-critical, jira/valid-bug, jira/valid-reference

#3708 OCPNODE-1655: Apply node-cluster dashboard as a config map
  install/0000_90_machine-config-operator_01_node_dashboard.yaml
Labels: lgtm, approved, jira/valid-reference

#3789 OCPNODE-1717: Make cgroupsv2 default in OCP-4.14
  pkg/controller/kubelet-config/kubelet_config_nodes.go
  pkg/controller/kubelet-config/kubelet_config_nodes_test.go
  pkg/controller/template/render.go
  test/e2e-bootstrap/bootstrap_test.go
Labels: lgtm, approved, cherry-pick-approved, qe-approved, jira/valid-reference

#3763 MCO-565: MCO-568: MCO-659: MCO-660 On-cluster build opt-in function, building machine-os-builder stub, RBAC and service acct inclusions
  Makefile
  cmd/machine-os-builder/main.go
  cmd/machine-os-builder/start.go
  cmd/machine-os-builder/version.go
  manifests/machineosbuilder/clusterrole.yaml
  manifests/machineosbuilder/clusterrolebinding-anyuid.yaml
  manifests/machineosbuilder/clusterrolebinding-service-account.yaml
  manifests/machineosbuilder/deployment.yaml
  manifests/machineosbuilder/events-clusterrole.yaml
  manifests/machineosbuilder/events-rolebinding-default.yaml
  manifests/machineosbuilder/events-rolebinding-target.yaml
  manifests/machineosbuilder/sa.yaml
  pkg/controller/common/constants.go
  pkg/operator/operator.go
  pkg/operator/sync.go
  test/e2e/mob_test.go
  test/helpers/utils.go
Labels: lgtm, approved, qe-approved, jira/valid-reference

#3811 OCPBUGS-16227: add Passwd to bootstrap served ignition
  pkg/controller/common/helpers.go
  pkg/daemon/update.go
  pkg/server/api.go
  pkg/server/server.go
  test/e2e/mcd_test.go
Labels: lgtm, approved, qe-approved, jira/severity-critical, jira/valid-bug, jira/valid-reference

#3824 OCPBUGS-16888: daemon: no need to reexec when target and source rhel version is same
  pkg/daemon/daemon.go
Labels: lgtm, approved, cherry-pick-approved, backport-risk-assessed, jira/valid-bug, jira/valid-reference

#3823 fix certExpiry description
  install/0000_80_machine-config-operator_01_machineconfigpool.crd.yaml
Labels: lgtm, approved

#3826 OCPBUGS-16888: daemon: Make binary writing idempotent
  pkg/daemon/daemon.go
Labels: approved, backport-risk-assessed, jira/valid-bug

#3822 MCO-597: Remove the MCO's dependency on journal reads
  pkg/daemon/daemon.go
Labels: lgtm, approved, jira/valid-reference

#3808 OCPBUGS-15367: The kubeconfig copied on to each node has 644 permissions
  pkg/daemon/update.go
Labels: lgtm, approved, qe-approved, jira/valid-bug, jira/valid-reference

#3828 Revert " add Passwd to bootstrap served ignition"
  pkg/controller/common/helpers.go
  pkg/daemon/update.go
  pkg/server/api.go
  pkg/server/server.go
  test/e2e/mcd_test.go
Labels: lgtm, approved

#3830 Revert "MCO-565: MCO-568: MCO-659: MCO-660 On-cluster build opt-in function, building machine-os-builder stub, RBAC and service acct inclusions"
  Makefile
  cmd/machine-os-builder/main.go
  cmd/machine-os-builder/start.go
  cmd/machine-os-builder/version.go
  manifests/machineosbuilder/clusterrole.yaml
  manifests/machineosbuilder/clusterrolebinding-anyuid.yaml
  manifests/machineosbuilder/clusterrolebinding-service-account.yaml
  manifests/machineosbuilder/deployment.yaml
  manifests/machineosbuilder/events-clusterrole.yaml
  manifests/machineosbuilder/events-rolebinding-default.yaml
  manifests/machineosbuilder/events-rolebinding-target.yaml
  manifests/machineosbuilder/sa.yaml
  pkg/controller/common/constants.go
  pkg/operator/operator.go
  pkg/operator/sync.go
  test/e2e/mob_test.go
  test/helpers/utils.go
Labels: lgtm, approved, jira/valid-reference

#3825 OCPBUGS-16921: daemon: Make binary writing idempotent
  pkg/daemon/daemon.go
  pkg/daemon/update.go
Labels: lgtm, approved, jira/valid-bug, jira/valid-reference
