Repository openshift/machine-config-operator, pull requests merged in 2023-09, with the labels that each got.

#3901 OCPBUGS-18442: MCO is degraded if not install image registry operator
  manifests/machine-os-puller/rolebinding.yaml
  pkg/operator/sync.go
Labels: lgtm, approved, qe-approved, jira/severity-critical, jira/valid-bug, jira/valid-reference, acknowledge-critical-fixes-only

#3878 OCPBUGS-9972: Fix azure routes hack for ovnk pods towards internalLB on master nodes in SGW mode
  templates/master/00-master/azure/files/opt-libexec-openshift-azure-routes-sh.yaml
Labels: lgtm, approved, jira/severity-moderate, jira/valid-bug, jira/valid-reference, acknowledge-critical-fixes-only

#3892 [release-4.10] OCPBUGS-18176: Agent-based install process the container machine-config-controller will be oom
  manifests/bootstrap-pod-v2.yaml
  pkg/controller/bootstrap/bootstrap.go
Labels: lgtm, approved, cherry-pick-approved, backport-risk-assessed, jira/severity-critical, jira/valid-bug, jira/valid-reference

#3904 OCPBUGS-18159: Ensure azure-routes hack for internalLB hairpin traffic works for SGW
  templates/master/00-master/azure/files/opt-libexec-openshift-azure-routes-sh.yaml
Labels: lgtm, approved, cherry-pick-approved, qe-approved, backport-risk-assessed, jira/severity-important, jira/valid-bug, jira/valid-reference

#3759 OCPBUGS-11437: MCO keeps the pull secret to .orig file once it replaced
  pkg/daemon/file_writers.go
  pkg/daemon/update.go
  pkg/daemon/update_test.go
Labels: lgtm, approved, qe-approved, jira/valid-bug, jira/valid-reference

#3856 MCO-708: Extract and merge kernel arguments from /proc/cmdline
  pkg/daemon/daemon.go
  pkg/daemon/daemon_test.go
  pkg/daemon/update.go
Labels: lgtm, approved, jira/valid-reference

#3858 MCO-731: Move services machine-config-daemon-pull.service and machine-config-daemon-firstboot.service before ovs-configuration.service
  templates/common/_base/units/machine-config-daemon-firstboot.service.yaml
  templates/common/_base/units/machine-config-daemon-pull.service.yaml
Labels: lgtm, approved, jira/valid-reference

#3915 MCO-765: Examine/Remove memory limits on MCO pods
  manifests/bootstrap-pod-v2.yaml
Labels: lgtm, approved, jira/valid-reference

#3895 OCPBUGS-16905: install: Recreate and delayed default ServiceAccount deletion
  install/0000_80_machine-config-operator_03_rbac.yaml
  install/0000_80_machine-config-operator_04_deployment.yaml
  install/0000_90_machine-config-operator_90_deletion.yaml
Labels: lgtm, approved, qe-approved, jira/valid-bug, jira/valid-reference

#3907 OCPBUGS-18772: resolv-prepender: avoid pulling baremetalRuntimeCfgImage again
  templates/common/on-prem/files/resolv-prepender.yaml
Labels: lgtm, approved, qe-approved, jira/valid-bug, jira/valid-reference

#3913 OCPBUGS-18906: Remove dependency on k8s.io/kubernetes packages
  go.mod
  go.sum
  pkg/controller/common/helpers.go
  pkg/operator/sync.go
  vendor/k8s.io/apiserver/pkg/features/OWNERS
  vendor/k8s.io/apiserver/pkg/features/kube_features.go
  vendor/k8s.io/apiserver/pkg/util/feature/feature_gate.go
  vendor/k8s.io/kubernetes/LICENSE
  vendor/k8s.io/kubernetes/pkg/credentialprovider/OWNERS
  vendor/k8s.io/kubernetes/pkg/credentialprovider/config.go
  vendor/k8s.io/kubernetes/pkg/credentialprovider/doc.go
  vendor/k8s.io/kubernetes/pkg/credentialprovider/keyring.go
  vendor/k8s.io/kubernetes/pkg/credentialprovider/plugins.go
  vendor/k8s.io/kubernetes/pkg/credentialprovider/provider.go
  vendor/k8s.io/kubernetes/pkg/features/OWNERS
  vendor/k8s.io/kubernetes/pkg/features/kube_features.go
  vendor/modules.txt
Labels: lgtm, approved, qe-approved, jira/valid-bug, jira/valid-reference

#3921 OCPBUGS-13044: daemon: always use `podman cp` to copy extensions container content
  pkg/daemon/update.go
Labels: lgtm, approved, jira/severity-important, jira/valid-bug, jira/valid-reference

#3924 [release-4.13] OCPBUGS-19414: The kubeconfig copied on to each node has 644 permissions
  pkg/daemon/update.go
Labels: lgtm, approved, cherry-pick-approved, backport-risk-assessed, jira/valid-bug, jira/valid-reference

#3851 OCPBUGS-18800: fix merged image registry CA behavior
  pkg/controller/template/template_controller.go
  pkg/daemon/certificate_writer.go
  pkg/operator/operator.go
  pkg/operator/sync.go
  test/e2e/mco_test.go
Labels: lgtm, approved, qe-approved, jira/valid-bug, jira/valid-reference

#3931 [release-4.12] OCPBUGS-19515: The kubeconfig copied on to each node has 644 permissions
  pkg/daemon/update.go
Labels: lgtm, approved, cherry-pick-approved, backport-risk-assessed, jira/valid-bug, jira/valid-reference

#3909 OCPBUGS-15910: After dual-stack conversion reconcile IPFamilies
  lib/resourcemerge/machineconfig.go
  lib/resourcemerge/meta.go
Labels: lgtm, approved, jira/valid-bug, jira/valid-reference

#3926 OCPBUGS-19365: Ignore invoking nbctl calls if its SDN
  templates/master/00-master/azure/files/opt-libexec-openshift-azure-routes-sh.yaml
Labels: lgtm, approved, qe-approved, jira/severity-critical, jira/valid-bug, jira/valid-reference

#3928 [release-4.14] OCPBUGS-19344: Ignore invoking nbctl calls if its SDN
  templates/master/00-master/azure/files/opt-libexec-openshift-azure-routes-sh.yaml
Labels: lgtm, approved, cherry-pick-approved, qe-approved, backport-risk-assessed, jira/severity-critical, jira/valid-bug, jira/valid-reference

#3929 [release-4.13] OCPBUGS-19509: Ignore invoking nbctl calls if its SDN
  templates/master/00-master/azure/files/opt-libexec-openshift-azure-routes-sh.yaml
Labels: lgtm, approved, cherry-pick-approved, qe-approved, backport-risk-assessed, jira/severity-critical, jira/valid-bug, jira/valid-reference

#3922 Dockerfile: update local copy to OCP 4.15 image
  Dockerfile
Labels: lgtm, approved

#3807 MCO-664: adds e2e for on-cluster build dev preview
  Makefile
  test/e2e-layering/helpers_test.go
  test/e2e-layering/onclusterbuild_test.go
  test/helpers/utils.go
Labels: lgtm, approved, jira/valid-reference

#3912 OCPBUGS-18902: Internal Registry Secrets merge causing excessive API calls
  cmd/machine-config-operator/start.go
  pkg/operator/operator.go
  pkg/operator/sync.go
Labels: lgtm, approved, qe-approved, jira/valid-bug, jira/valid-reference

#3905 MCO-746: make buildcontroller tests less flaky
  pkg/controller/build/build_controller.go
  pkg/controller/build/build_controller_test.go
  pkg/controller/build/fixtures_test.go
  pkg/controller/build/image_build_request.go
  pkg/controller/build/pool_state.go
  pkg/controller/build/pool_state_test.go
  pkg/controller/common/layered_pool_state.go
Labels: lgtm, approved, jira/valid-reference

#3890 OCPBUGS-15583: Revert "Revert "fix nodeStatusUpdateFrequency""
  templates/master/01-master-kubelet/_base/files/kubelet.yaml
  templates/worker/01-worker-kubelet/_base/files/kubelet.yaml
  test/e2e/kubeletcfg_test.go
Labels: lgtm, approved, jira/severity-moderate, jira/valid-bug, jira/valid-reference

#3938 OCPBUGS-19675: daemon: always use `podman cp` to copy extensions container content
  pkg/daemon/update.go
Labels: lgtm, approved, cherry-pick-approved, backport-risk-assessed, jira/severity-important, jira/valid-bug, jira/valid-reference

#3857 MCO-707: Strip registry transport from os image URL for comparison
  pkg/daemon/rpm-ostree.go
Labels: lgtm, approved, jira/valid-reference

#3910 OCPBUGS-18772: Use image exists in resolv-prepender instead of wc -l
  templates/common/on-prem/files/resolv-prepender.yaml
Labels: lgtm, approved, qe-approved, jira/valid-bug, jira/valid-reference, acknowledge-critical-fixes-only

#3914 Improve kubelet error log
  templates/common/on-prem/units/kubelet.service-wait-resolv.yaml
Labels: lgtm, approved, ok-to-test

#3898 OCPNODE-1799: support icsp and idms objects
  go.mod
  go.sum
  pkg/controller/container-runtime-config/container_runtime_config_controller.go
  pkg/controller/container-runtime-config/container_runtime_config_controller_test.go
  pkg/controller/container-runtime-config/helpers_test.go
  vendor/github.com/openshift/runtime-utils/pkg/registries/registries.go
  vendor/modules.txt
Labels: lgtm, approved, jira/valid-reference

#3941 [release-4.14] OCPBUGS-19703: Internal Registry Secrets merge causing excessive API calls
  cmd/machine-config-operator/start.go
  pkg/operator/operator.go
  pkg/operator/sync.go
Labels: lgtm, approved, cherry-pick-approved, qe-approved, backport-risk-assessed, jira/valid-bug, jira/valid-reference
