Repository openshift/machine-config-operator, pull requests merged in 2023-11, with the labels that each got.

#3967 OCPBUGS-20418: Introduce kubelet-dependencies.target and firstboot-osupdate.target
  templates/common/_base/units/crio.service.yaml
  templates/common/_base/units/firstboot-osupdate.target
  templates/common/_base/units/kubelet-auto-node-size.service.yaml
  templates/common/_base/units/kubelet-dependencies.target.yaml
  templates/common/_base/units/machine-config-daemon-firstboot.service.yaml
  templates/common/_base/units/machine-config-daemon-pull.service.yaml
  templates/common/_base/units/mtu-migration.service.yaml
  templates/common/_base/units/node-valid-hostname.service.yaml
  templates/common/_base/units/nodeip-configuration.service.yaml
  templates/common/_base/units/ovs-configuration.service.yaml
  templates/common/alibabacloud/units/alibaba-kubelet-nodename.service.yaml
  templates/common/aws/units/aws-kubelet-nodename.service.yaml
  templates/common/aws/units/aws-kubelet-providerid.service.yaml
  templates/common/gcp/units/gcp-hostname.service.yaml
  templates/common/on-prem/units/nodeip-configuration.service.yaml
  templates/common/openstack/units/openstack-kubelet-nodename.service.yaml
  templates/common/vsphere/units/nodeip-configuration-vsphere-upi.service.yaml
  templates/common/vsphere/units/vsphere-hostname.service.yaml
  templates/master/00-master/alibabacloud/units/openshift-alibabacloud-routes.path.yaml
  templates/master/00-master/azure/units/openshift-azure-routes.path.yaml
  templates/master/00-master/azure/units/openshift-azure-routes.service.yaml
  templates/master/01-master-kubelet/_base/units/kubelet.service.yaml
  templates/master/01-master-kubelet/alibabacloud/units/kubelet.service.yaml
  templates/master/01-master-kubelet/on-prem/units/kubelet.service.yaml
  templates/worker/01-worker-kubelet/_base/units/kubelet.service.yaml
  templates/worker/01-worker-kubelet/alibabacloud/units/kubelet.service.yaml
  templates/worker/01-worker-kubelet/on-prem/units/kubelet.service.yaml
Labels: lgtm, approved, cherry-pick-approved, qe-approved, backport-risk-assessed, jira/severity-moderate, jira/valid-bug, jira/valid-reference

#3995 [release-4.14] OCPBUGS-22275: support icsp and idms objects
  go.mod
  go.sum
  pkg/controller/container-runtime-config/container_runtime_config_controller.go
  pkg/controller/container-runtime-config/container_runtime_config_controller_test.go
  pkg/controller/container-runtime-config/helpers_test.go
  vendor/github.com/openshift/runtime-utils/pkg/registries/registries.go
  vendor/k8s.io/code-generator/generate-groups.sh
  vendor/k8s.io/code-generator/generate-internal-groups.sh
  vendor/modules.txt
Labels: lgtm, approved, cherry-pick-approved, backport-risk-assessed, jira/valid-bug, jira/valid-reference

#4015 MCO-772: controller: allow custom pool configs to take priority
  pkg/controller/common/constants.go
  pkg/controller/common/helpers.go
  pkg/controller/common/helpers_test.go
  test/helpers/helpers.go
Labels: lgtm, approved, qe-approved, jira/valid-reference

#3990 OCPBUGS-22200: Retry fetching OpenStack hostname if it fails
  templates/common/openstack/files/usr-local-bin-openstack-kubelet-nodename.yaml
  templates/common/openstack/units/kubelet-node-env.dropin.yaml
  templates/common/openstack/units/openstack-kubelet-nodename.service.yaml
Labels: lgtm, approved, jira/severity-moderate, jira/valid-bug, jira/valid-reference

#4026 OCPBUGS-23209: workaround nmstate bug by configuring ipv{4,6} addresses
  templates/common/kubevirt/files/002-nmstate-arp-proxy-ipv6-gw.yaml
Labels: lgtm, approved, jira/valid-bug, jira/valid-reference, acknowledge-critical-fixes-only

#4031 [release-4.14] OCPBUGS-23208: workaround nmstate bug by configuring ipv{4,6} addresses
  templates/common/kubevirt/files/002-nmstate-arp-proxy-ipv6-gw.yaml
Labels: lgtm, approved, cherry-pick-approved, backport-risk-assessed, jira/valid-bug, jira/valid-reference

#4037 OCPCLOUD-1609: Fix syntax in vsphere-hostname.yaml for CAPI machines
  templates/common/vsphere/files/vsphere-hostname.yaml
Labels: lgtm, approved, jira/valid-reference, acknowledge-critical-fixes-only

#4040 OCPBUGS-23432: Use shorter IP label for keepalived VIP
  manifests/on-prem/keepalived.conf.tmpl
  templates/master/00-master/on-prem/files/keepalived-keepalived.yaml
  templates/worker/00-worker/on-prem/files/keepalived-keepalived.yaml
Labels: lgtm, approved, jira/valid-bug, jira/valid-reference, acknowledge-critical-fixes-only

#4033 OCPBUGS-23255: Add FIPS information to oldconfig when checking if reboot is needed
  pkg/daemon/daemon.go
  pkg/daemon/update.go
Labels: lgtm, approved, qe-approved, jira/severity-important, jira/valid-bug, jira/valid-reference, acknowledge-critical-fixes-only

#4045 OCPBUGS-24019: Add ownership annotations to TLS artifacts
  manifests/machineconfigserver/kube-apiserver-serving-ca-configmap.yaml
Labels: lgtm, approved, jira/valid-bug, jira/valid-reference

#3965 MCO-681, OCPBUGS-20427: Add Key State Metrics, No datapoint found when querying up certain registered metrics
  pkg/controller/common/metrics.go
  pkg/controller/container-runtime-config/container_runtime_config_controller.go
  pkg/controller/drain/drain_controller.go
  pkg/controller/kubelet-config/kubelet_config_controller.go
  pkg/controller/kubelet-config/kubelet_config_features.go
  pkg/controller/kubelet-config/kubelet_config_nodes.go
  pkg/controller/node/node_controller.go
  pkg/controller/render/render_controller.go
  pkg/controller/template/template_controller.go
  pkg/daemon/daemon.go
  pkg/daemon/metrics.go
  pkg/daemon/update.go
  pkg/operator/metrics.go
Labels: lgtm, approved, qe-approved, jira/valid-bug, jira/valid-reference

#4028 OCPBUGS-22324: Wait for br-ex up event before node-valid-hostname
  templates/common/on-prem/files/NetworkManager-resolv-prepender.yaml
  templates/common/on-prem/files/wait-for-br-ex-up.yaml
  templates/common/on-prem/units/wait-for-br-ex-up.yaml
Labels: lgtm, approved, qe-approved, jira/severity-important, jira/valid-bug, jira/valid-reference

#4049 OCPBUGS-24177: fix race for MCN creation
  pkg/upgrademonitor/upgrade_monitor.go
Labels: lgtm, approved, qe-approved, jira/valid-bug, jira/valid-reference

#3885 MCO-664: adds on-cluster build dev preview docs
  docs/MachineOSBuilderDesign.md
  docs/MachineOSBuilderDiagram.svg
  docs/OnClusterBuildInstructions.md
Labels: lgtm, approved, qe-approved, jira/valid-reference

#4051 TRT-1375: Revert #3965 "MCO-681, OCPBUGS-20427: Add Key State Metrics, No datapoint found when querying up certain registered metrics"
  pkg/controller/common/metrics.go
  pkg/controller/container-runtime-config/container_runtime_config_controller.go
  pkg/controller/drain/drain_controller.go
  pkg/controller/kubelet-config/kubelet_config_controller.go
  pkg/controller/kubelet-config/kubelet_config_features.go
  pkg/controller/kubelet-config/kubelet_config_nodes.go
  pkg/controller/node/node_controller.go
  pkg/controller/render/render_controller.go
  pkg/controller/template/template_controller.go
  pkg/daemon/daemon.go
  pkg/daemon/metrics.go
  pkg/daemon/update.go
  pkg/operator/metrics.go
Labels: lgtm, approved, jira/valid-reference
