Repository openshift/machine-config-operator, pull requests merged in 2023-05, with the labels that each got.

#3691 OCPBUGS-12951: daemon: Don't traverse `/run/ostree/auth.json` symlink
  pkg/daemon/rpm-ostree.go
Labels: lgtm, approved, priority/critical-urgent, bugzilla/valid-bug, jira/valid-bug, jira/valid-reference

#3686 OCPBUGS-12456: fix duplicate RotateKubeletServerCertificate setting
  templates/master/01-master-kubelet/_base/files/kubelet.yaml
  templates/worker/01-worker-kubelet/_base/files/kubelet.yaml
Labels: lgtm, approved, bugzilla/valid-bug, jira/valid-bug, jira/valid-reference

#3689 OCPBUGS-11670: mcc_drain_err metric should not be served for removed nodes
  pkg/controller/drain/drain_controller.go
  pkg/controller/node/node_controller.go
Labels: lgtm, approved, bugzilla/valid-bug, qe-approved, jira/severity-moderate, jira/valid-bug, jira/valid-reference

#3667 [release-4.11] OCPBUGS-11556: Prevent possible split-brain scenario with keepalived unicast
  templates/master/00-master/on-prem/files/keepalived-keepalived.yaml
  templates/worker/00-worker/on-prem/files/keepalived-keepalived.yaml
Labels: lgtm, approved, bugzilla/valid-bug, cherry-pick-approved, backport-risk-assessed, jira/valid-bug, jira/valid-reference

#3694 OCPBUGS-12980: daemon: write certs in firstboot-complete path
  pkg/daemon/daemon.go
Labels: lgtm, approved, bugzilla/valid-bug, qe-approved, jira/severity-important, jira/valid-bug, jira/valid-reference

#3645 OCPBUGS-11652: kubelet: add enableSystemLogQuery
  templates/master/01-master-kubelet/_base/files/kubelet.yaml
  templates/worker/01-worker-kubelet/_base/files/kubelet.yaml
Labels: lgtm, approved, bugzilla/valid-bug, jira/valid-bug, jira/valid-reference

#3695 OCPBUGS-11304: daemon: event only on actual OS updates
  pkg/daemon/update.go
Labels: lgtm, approved, bugzilla/valid-bug, qe-approved, jira/valid-bug, jira/valid-reference

#3685 OCPBUGS-12885: daemon: stop using `nmstatectl persist-nic-names --inspect` on el9
  cmd/machine-config-daemon/firstboot_complete_machineconfig.go
  pkg/daemon/daemon.go
  pkg/daemon/drain.go
  pkg/daemon/kernelargs.go
  pkg/daemon/update.go
  templates/common/_base/units/machine-config-daemon-firstboot.service.yaml
Labels: lgtm, approved, bugzilla/valid-bug, qe-approved, jira/valid-bug, jira/valid-reference

#3701 OCPBUGS-13547: Use payload-version flag to set release version consistently across components
  cmd/machine-config-controller/main.go
  cmd/machine-config-daemon/main.go
  cmd/machine-config-operator/main.go
  cmd/machine-config-operator/start.go
  cmd/machine-config-server/main.go
  install/0000_80_machine-config-operator_04_deployment.yaml
  manifests/bootstrap-pod-v2.yaml
  manifests/machineconfigcontroller/deployment.yaml
  manifests/machineconfigdaemon/daemonset.yaml
  manifests/machineconfigserver/daemonset.yaml
  pkg/operator/operator.go
  pkg/operator/render.go
  pkg/operator/render_test.go
  pkg/operator/sync.go
  pkg/version/version.go
  test/e2e-bootstrap/bootstrap_test.go
Labels: lgtm, approved, bugzilla/valid-bug, jira/valid-bug, jira/valid-reference

#3676 OCPBUGS-3176: Disable global ipv4 and ipv6 forwarding for OVN deployments
  pkg/controller/template/render.go
  pkg/controller/template/render_test.go
  pkg/controller/template/test_data/controller_config_forwarding_ovn.yaml
  pkg/controller/template/test_data/controller_config_forwarding_sdn.yaml
  templates/common/_base/files/sysctl-forward-conf.yaml
  templates/common/on-prem/files/configure-ip-forwarding.yaml
  templates/common/on-prem/units/nodeip-configuration.service.yaml
Labels: lgtm, approved, bugzilla/valid-bug, jira/severity-moderate, jira/valid-bug, jira/valid-reference

#3713 OCPBUGS-13860: Fix missing apiVersion and kind fields for embedded resources
  pkg/operator/sync.go
Labels: lgtm, approved, bugzilla/valid-bug, qe-approved, jira/severity-moderate, jira/valid-bug, jira/valid-reference
