Repository openshift/machine-config-operator, pull requests merged in 2023-08, with the labels that each got.

#3832 OCPBUGS-17156: daemon: Always replace binary
  pkg/daemon/daemon.go
Labels: lgtm, approved, jira/valid-bug, jira/valid-reference

#3770 MCO-552: implement the ability for the MCO to handle image registry certificates
  cmd/machine-config-operator/start.go
  lib/resourcemerge/machineconfig.go
  manifests/controllerconfig.crd.yaml
  pkg/apis/machineconfiguration.openshift.io/v1/types.go
  pkg/apis/machineconfiguration.openshift.io/v1/zz_generated.deepcopy.go
  pkg/controller/template/template_controller.go
  pkg/daemon/certificate_writer.go
  pkg/daemon/daemon.go
  pkg/operator/operator.go
  pkg/operator/sync.go
  test/helpers/utils.go
Labels: lgtm, approved, qe-approved, jira/valid-reference

#3820 daemon: Remove even more dead legacy OS update code
  pkg/daemon/rpm-ostree.go
  pkg/daemon/update.go
Labels: lgtm, approved

#3833 OCPBUGS-17163: daemon: Always replace binary
  pkg/daemon/daemon.go
Labels: lgtm, approved, cherry-pick-approved, backport-risk-assessed, jira/valid-bug, jira/valid-reference

#3835 daemon: Two minor fixes for reexec
  pkg/daemon/daemon.go
Labels: lgtm, approved

#3829 OCPBUGS-16227: make sure sshKey are not emptied out on firstboot
  pkg/daemon/update.go
  test/e2e/mcd_test.go
Labels: lgtm, approved, jira/severity-critical, jira/valid-bug, jira/valid-reference

#3777 OCPNODE-1714: files: add skip_mount_home to storage.conf
  templates/common/_base/files/container-storage.yaml
Labels: lgtm, approved, jira/valid-reference

#3837 install: Fix dash-to-hyhen for 04_kube_rbac_proxy_config.yaml prefix
  install/0000_80_machine-config-operator_04_kube_rbac_proxy_config.yaml
Labels: lgtm, approved

#3746 OCPBUGS-14965: Run hostnamectl with systemd-run
  templates/common/baremetal/files/NetworkManager-static-dhcp.yaml
Labels: lgtm, approved, jira/valid-bug, jira/valid-reference

#3838 OCPBUGS-13825: The machine-config-controller pod restart in SNO+1 causing daemonsets to restart
  pkg/controller/node/node_controller.go
Labels: lgtm, approved, qe-approved, jira/valid-bug, jira/valid-reference

#3842 MCO-532: Finish lease type migration
  cmd/common/helpers.go
Labels: lgtm, approved, qe-approved, jira/valid-reference

#3845 OKD-174: Dockerfile: OKD: Reenable extensions image on SCOS
  Dockerfile
  Dockerfile.rhel7
Labels: lgtm, approved, cherry-pick-approved, backport-risk-assessed, jira/valid-bug, jira/valid-reference

#3792 OCPBUGS-14945: add HostToContainer propagation to all hostPath volume mounts
  manifests/bootstrap-pod-v2.yaml
  manifests/machineconfigdaemon/daemonset.yaml
  manifests/on-prem/coredns.yaml
  manifests/on-prem/keepalived.yaml
  templates/common/on-prem/files/coredns.yaml
  templates/common/on-prem/files/keepalived.yaml
  templates/master/00-master/alibabacloud/files/etc-kubernetes-manifests-apiserver-watcher.yaml
  templates/master/00-master/azure/files/etc-kubernetes-manifests-apiserver-watcher.yaml
  templates/master/00-master/gcp/files/etc-kubernetes-manifests-apiserver-watcher.yaml
  templates/master/00-master/on-prem/files/haproxy.yaml
Labels: lgtm, approved, qe-approved, jira/severity-important, jira/valid-bug, jira/valid-reference

#3790 MCO-654: forcefile should always trigger an OS update
  pkg/daemon/update.go
Labels: lgtm, approved, jira/valid-reference

#3663 OCPBUGS-8938: OCPBUGS-15202: MCO-555: kube-rbac-proxy addition
  Dockerfile
  cmd/machine-config-operator/bootstrap.go
  install/0000_80_machine-config-operator_04_deployment.yaml
  lib/resourcemerge/core.go
  manifests/machineconfigcontroller/deployment.yaml
  manifests/machineconfigcontroller/kube-rbac-proxy-config.yaml
  manifests/machineconfigcontroller/prometheus-rbac.yaml
  manifests/machineconfigcontroller/prometheus-rolebinding-target.yaml
  manifests/machineconfigdaemon/daemonset.yaml
  manifests/machineconfigdaemon/kube-rbac-proxy-config.yaml
  manifests/machineconfigdaemon/prometheus-rbac.yaml
  manifests/machineconfigdaemon/prometheus-rolebinding-target.yaml
  pkg/operator/images.go
  pkg/operator/render_test.go
  pkg/operator/sync.go
Labels: lgtm, approved, ok-to-test, qe-approved, jira/severity-important, jira/valid-bug, jira/valid-reference

#3846 OCPBUGS-17433: Sync featuregate controller during the node config controller sync
  pkg/controller/kubelet-config/kubelet_config_features.go
  pkg/controller/kubelet-config/kubelet_config_nodes.go
Labels: lgtm, approved, qe-approved, jira/valid-bug, jira/valid-reference

#3814 MCO-588: Update ignition spec to 3.4, disallow ignition KernelArguments for now
  lib/resourceapply/machineconfig_test.go
  pkg/controller/bootstrap/bootstrap_test.go
  pkg/controller/build/build_controller_test.go
  pkg/controller/build/fixtures_test.go
  pkg/controller/common/constants.go
  pkg/controller/common/helpers.go
  pkg/controller/common/helpers_test.go
  pkg/controller/container-runtime-config/container_runtime_config_controller.go
  pkg/controller/container-runtime-config/container_runtime_config_controller_test.go
  pkg/controller/container-runtime-config/helpers.go
  pkg/controller/kubelet-config/helpers.go
  pkg/controller/kubelet-config/kubelet_config_controller.go
  pkg/controller/kubelet-config/kubelet_config_controller_test.go
  pkg/controller/kubelet-config/kubelet_config_features_test.go
  pkg/controller/kubelet-config/kubelet_config_nodes_test.go
  pkg/controller/render/render_controller_test.go
  pkg/controller/template/render_test.go
  pkg/daemon/config_drift_monitor.go
  pkg/daemon/config_drift_monitor_test.go
  pkg/daemon/daemon.go
  pkg/daemon/daemon_test.go
  pkg/daemon/drain.go
  pkg/daemon/drain_test.go
  pkg/daemon/file_writers.go
  pkg/daemon/on_disk_validation.go
  pkg/daemon/update.go
  pkg/daemon/update_test.go
  pkg/server/api.go
  pkg/server/bootstrap_server.go
  pkg/server/cluster_server.go
  pkg/server/server.go
  pkg/server/server_test.go
  test/e2e-shared-tests/mcd_config_drift.go
  test/e2e-single-node/sno_mcd_test.go
  test/e2e/mcd_test.go
  test/e2e/osimageurl_override_test.go
  test/helpers/helpers.go
  test/helpers/utils.go
Labels: lgtm, approved, qe-approved, jira/valid-reference

#3834 MCO-565: MCO-568: MCO-659: MCO-660 On-cluster build opt-in function, building machine-os-builder stub, RBAC and service acct inclusions. Deletes deployment rather than scale down to 0 without label
  Makefile
  cmd/machine-os-builder/main.go
  cmd/machine-os-builder/start.go
  cmd/machine-os-builder/version.go
  manifests/machineosbuilder/clusterrole.yaml
  manifests/machineosbuilder/clusterrolebinding-anyuid.yaml
  manifests/machineosbuilder/clusterrolebinding-service-account.yaml
  manifests/machineosbuilder/deployment.yaml
  manifests/machineosbuilder/events-clusterrole.yaml
  manifests/machineosbuilder/events-rolebinding-default.yaml
  manifests/machineosbuilder/events-rolebinding-target.yaml
  manifests/machineosbuilder/sa.yaml
  pkg/controller/common/constants.go
  pkg/operator/operator.go
  pkg/operator/sync.go
  test/e2e/mob_test.go
  test/helpers/utils.go
Labels: lgtm, approved, qe-approved, jira/valid-reference

#3855 operator: remove metrics related log
  pkg/operator/status.go
Labels: lgtm, approved

#3854 OCPBUGS-17683 replace .. with : on registry CA file paths
  pkg/daemon/certificate_writer.go
Labels: lgtm, approved

#3859 OPNET-343: Restore node-ip for kubelet in dual-stack vSphere
  templates/master/01-master-kubelet/vsphere/units/kubelet.service.yaml
  templates/worker/01-worker-kubelet/vsphere/units/kubelet.service.yaml
Labels: lgtm, approved, jira/valid-reference

#3862 OCPBUGS-17568: Agent-based install process the container machine-config-controller will be oom
  manifests/bootstrap-pod-v2.yaml
  pkg/controller/bootstrap/bootstrap.go
Labels: lgtm, approved, jira/severity-critical, jira/valid-bug, jira/valid-reference

#3817 MCO-564: Make NodeController aware of BuildController
  pkg/controller/common/layered_node_state.go
  pkg/controller/common/layered_node_state_test.go
  pkg/controller/common/layered_pool_state.go
  pkg/controller/common/layered_pool_state_test.go
  pkg/controller/node/node_controller.go
  pkg/controller/node/node_controller_test.go
  pkg/controller/node/status.go
  pkg/controller/node/status_test.go
  pkg/daemon/writer.go
  test/helpers/nodebuilder.go
  test/helpers/poolbuilder.go
  test/helpers/utils.go
Labels: lgtm, approved, jira/valid-reference

#3847 MCO-729: BuildController should allow cluster admins to provide a custom Dockerfile
  pkg/controller/build/assets/Dockerfile.on-cluster-build-template
  pkg/controller/build/build_controller.go
  pkg/controller/build/fixtures_test.go
  pkg/controller/build/helpers.go
  pkg/controller/build/helpers_test.go
  pkg/controller/build/image_build_request.go
  pkg/controller/build/image_build_request_test.go
  pkg/controller/build/pod_build_controller.go
Labels: lgtm, approved, jira/valid-reference

#3860 OCPBUGS-17701: daemon: igmore mounting MCD pod content when target is "/"
  pkg/daemon/daemon.go
Labels: lgtm, approved, qe-approved, jira/valid-bug, jira/valid-reference

#3806 MCO-573: Wire up security/trust/pull secrets between rpm-ostree and internal registry
  go.mod
  go.sum
  lib/resourcemerge/machineconfig.go
  manifests/controllerconfig.crd.yaml
  manifests/machine-os-puller/rolebinding.yaml
  manifests/machine-os-puller/sa.yaml
  pkg/apis/machineconfiguration.openshift.io/v1/types.go
  pkg/controller/common/helpers.go
  pkg/controller/template/render.go
  pkg/controller/template/render_test.go
  pkg/controller/template/template_controller.go
  pkg/controller/template/template_controller_test.go
  pkg/daemon/image-inspect.go
  pkg/daemon/rpm-ostree.go
  pkg/daemon/update.go
  pkg/operator/sync.go
  templates/common/_base/files/internal-registry-pull-secret.yaml
  vendor/github.com/opencontainers/runc/libcontainer/user/user.go
  vendor/github.com/opencontainers/runtime-spec/specs-go/config.go
  vendor/github.com/openshift/client-go/build/clientset/versioned/fake/register.go
  vendor/github.com/openshift/client-go/image/clientset/versioned/fake/clientset_generated.go
  vendor/github.com/openshift/client-go/image/clientset/versioned/fake/doc.go
  vendor/github.com/openshift/client-go/image/clientset/versioned/fake/register.go
  vendor/github.com/openshift/client-go/image/clientset/versioned/typed/image/v1/fake/doc.go
  vendor/github.com/openshift/client-go/image/clientset/versioned/typed/image/v1/fake/fake_image.go
  vendor/github.com/openshift/client-go/image/clientset/versioned/typed/image/v1/fake/fake_image_client.go
  vendor/github.com/openshift/client-go/image/clientset/versioned/typed/image/v1/fake/fake_imagesignature.go
  vendor/github.com/openshift/client-go/image/clientset/versioned/typed/image/v1/fake/fake_imagestream.go
  vendor/github.com/openshift/client-go/image/clientset/versioned/typed/image/v1/fake/fake_imagestreamimage.go
  vendor/github.com/openshift/client-go/image/clientset/versioned/typed/image/v1/fake/fake_imagestreamimport.go
  vendor/github.com/openshift/client-go/image/clientset/versioned/typed/image/v1/fake/fake_imagestreammapping.go
  vendor/github.com/openshift/client-go/image/clientset/versioned/typed/image/v1/fake/fake_imagestreamtag.go
  vendor/github.com/openshift/client-go/image/clientset/versioned/typed/image/v1/fake/fake_imagetag.go
  vendor/github.com/openshift/client-go/image/informers/externalversions/factory.go
  vendor/github.com/openshift/client-go/image/informers/externalversions/generic.go
  vendor/github.com/openshift/client-go/image/informers/externalversions/image/interface.go
  vendor/github.com/openshift/client-go/image/informers/externalversions/image/v1/image.go
  vendor/github.com/openshift/client-go/image/informers/externalversions/image/v1/imagestream.go
  vendor/github.com/openshift/client-go/image/informers/externalversions/image/v1/interface.go
  vendor/github.com/openshift/client-go/image/informers/externalversions/internalinterfaces/factory_interfaces.go
  vendor/github.com/openshift/client-go/image/listers/image/v1/expansion_generated.go
  vendor/github.com/openshift/client-go/image/listers/image/v1/image.go
  vendor/github.com/openshift/client-go/image/listers/image/v1/imagestream.go
  vendor/github.com/openshift/client-go/image/listers/image/v1/imagestreamtag.go
  vendor/github.com/openshift/client-go/image/listers/image/v1/imagetag.go
  vendor/k8s.io/apiserver/pkg/features/OWNERS
  vendor/k8s.io/apiserver/pkg/features/kube_features.go
  vendor/k8s.io/apiserver/pkg/util/feature/feature_gate.go
  vendor/k8s.io/kubernetes/LICENSE
  vendor/k8s.io/kubernetes/pkg/credentialprovider/OWNERS
  vendor/k8s.io/kubernetes/pkg/credentialprovider/config.go
  vendor/k8s.io/kubernetes/pkg/credentialprovider/doc.go
  vendor/k8s.io/kubernetes/pkg/credentialprovider/keyring.go
  vendor/k8s.io/kubernetes/pkg/credentialprovider/plugins.go
  vendor/k8s.io/kubernetes/pkg/credentialprovider/provider.go
  vendor/k8s.io/kubernetes/pkg/features/OWNERS
  vendor/k8s.io/kubernetes/pkg/features/kube_features.go
  vendor/modules.txt
Labels: lgtm, approved, qe-approved, jira/valid-reference

#3787 MCO-605: MCO-550: Remove Certificates from MachineConfig
  pkg/controller/bootstrap/bootstrap.go
  pkg/controller/bootstrap/bootstrap_test.go
  pkg/daemon/certificate_writer.go
  pkg/daemon/daemon.go
  pkg/daemon/update.go
  pkg/operator/render.go
  pkg/operator/sync.go
  pkg/server/bootstrap_server.go
  pkg/server/cluster_server.go
  pkg/server/server.go
  pkg/server/testdata/controller-config/machine-config-controller.yaml
  templates/common/_base/files/additional-trust-bundle.yaml
  templates/common/_base/files/cloud-provider-ca.yaml
  templates/common/_base/files/kubelet-ca.yaml
  test/e2e-bootstrap/bootstrap_test.go
  test/e2e/mcd_test.go
  test/helpers/utils.go
Labels: lgtm, approved, jira/valid-reference

#3861 MCO 566: MCO 662 Wire up productionalized BuildController in Machine OS Builder binary and choosing backend image builder
  cmd/machine-os-builder/main.go
  cmd/machine-os-builder/start.go
  manifests/machineosbuilder/clusterrole.yaml
  pkg/controller/build/build_controller.go
  pkg/controller/build/fixtures_test.go
  pkg/controller/build/helpers.go
  pkg/controller/build/image_build_request.go
  pkg/controller/build/image_build_request_test.go
  pkg/controller/build/pod_build_controller.go
  pkg/operator/sync.go
  test/e2e/mob_test.go
Labels: lgtm, approved

#3848 MCO-564: Make MCD aware of on-cluster builds
  pkg/daemon/daemon.go
  pkg/daemon/daemon_test.go
  pkg/daemon/node.go
  pkg/daemon/rpm-ostree.go
  pkg/daemon/update.go
  pkg/daemon/update_test.go
  pkg/daemon/writer.go
  test/e2e-shared-tests/mcd_config_drift.go
Labels: lgtm, approved, jira/valid-reference

#3868 [release-4.13] OCPBUGS-17769: Agent-based install process the container machine-config-controller will be oom
  manifests/bootstrap-pod-v2.yaml
  pkg/controller/bootstrap/bootstrap.go
Labels: lgtm, approved, cherry-pick-approved, backport-risk-assessed, jira/severity-critical, jira/valid-bug, jira/valid-reference

#3810 OCPBUGS-11832: SSHkeys fails to write on upgrade to 4.13.rc3
  pkg/daemon/update.go
Labels: lgtm, approved, qe-approved, jira/severity-moderate, jira/valid-bug, jira/valid-reference

#3866 OCPBUGS-17810: temporarily remove cert observability fields, add storageversionmigration for machineconfigpools,controllerconfig
  install/0000_80_machine-config-operator_01_machineconfigpool.crd.yaml
  install/0000_90_machine-config-operator_01_certificate_observability_storage_migration.yaml
  manifests/controllerconfig.crd.yaml
  pkg/apis/machineconfiguration.openshift.io/v1/types.go
  pkg/controller/node/node_controller_test.go
  pkg/controller/node/status.go
  pkg/controller/template/template_controller.go
Labels: lgtm, approved, qe-approved, jira/severity-important, jira/valid-bug, jira/valid-reference

#3784 OCPBUGS-15583: fix nodeStatusUpdateFrequency
  templates/master/01-master-kubelet/_base/files/kubelet.yaml
  templates/worker/01-worker-kubelet/_base/files/kubelet.yaml
  test/e2e/kubeletcfg_test.go
Labels: lgtm, approved, jira/severity-moderate, jira/valid-bug, jira/valid-reference

#3827 OCPBUGS-16733: on-prem: run resolv-prepender on NM reapply event
  templates/common/on-prem/files/NetworkManager-resolv-prepender.yaml
Labels: lgtm, approved, jira/severity-moderate, jira/valid-bug, jira/valid-reference

#3870 OCPBUGS-17787: Fix sysctl breaking dots in paths
  templates/common/on-prem/files/configure-ip-forwarding.yaml
Labels: lgtm, approved, jira/severity-critical, jira/valid-bug, jira/valid-reference

#3887 Revert "fix nodeStatusUpdateFrequency"
  templates/master/01-master-kubelet/_base/files/kubelet.yaml
  templates/worker/01-worker-kubelet/_base/files/kubelet.yaml
  test/e2e/kubeletcfg_test.go
Labels: lgtm, approved, jira/valid-bug

#3883 OCPBUGS-16035: daemon: create /etc/systemd/network directory on node
  pkg/daemon/daemon.go
Labels: lgtm, approved, qe-approved, jira/severity-important, jira/valid-bug, jira/valid-reference

#3886 OCPBUGS-18086: Quiet controller noisiness
  pkg/controller/render/render_controller.go
  pkg/controller/template/template_controller.go
Labels: lgtm, approved, qe-approved, jira/valid-bug, jira/valid-reference

#3888 OCPBUGS-18076: daemon: create /etc/systemd/network directory on node
  pkg/daemon/daemon.go
Labels: lgtm, approved, cherry-pick-approved, backport-risk-assessed, jira/severity-important, jira/valid-bug, jira/valid-reference

#3891 OCPBUGS-18097: ensure cconfig is not updated too frequently
  pkg/operator/sync.go
Labels: lgtm, approved, jira/valid-bug, jira/valid-reference, acknowledge-critical-fixes-only
