Repository openshift/machine-config-operator, pull requests merged in 2024-10, with the labels that each got.

#4617 OCPBUGS-42546: The MCO does not properly degrade when pools are failing to render a new config
  pkg/operator/sync.go
Labels: lgtm, approved, qe-approved, jira/severity-moderate, jira/valid-bug, jira/valid-reference

#4530 OCPBUGS-38382: [release-4.12] daemon/update: disable systemd unit before overwriting
  pkg/daemon/update.go
Labels: lgtm, approved, cherry-pick-approved, backport-risk-assessed, jira/valid-bug, jira/valid-reference

#4610 OCPNODE-2633: templates/*: make crun as the default container runtime
  templates/master/01-master-container-runtime/_base/files/crio.yaml
  templates/worker/01-worker-container-runtime/_base/files/crio.yaml
Labels: lgtm, approved, jira/valid-reference

#4639 OCPBUGS-43328: remove dra manager state
  templates/master/01-master-kubelet/_base/units/kubelet-cleanup.service.yaml
  templates/worker/01-worker-kubelet/_base/units/kubelet-cleanup.service.yaml
Labels: lgtm, approved, jira/severity-critical, jira/valid-bug, jira/valid-reference

#4619 COS-2947: Add sysstat extension support
  docs/MachineConfig.md
  pkg/daemon/update.go
  test/e2e-single-node/sno_mcd_test.go
  test/e2e/mcd_test.go
Labels: lgtm, approved, jira/valid-reference

#4640 OCPBUGS-42742: set observed generation and fix pod error detection
  pkg/controller/build/build_controller.go
Labels: lgtm, approved, qe-approved, jira/valid-bug, jira/valid-reference

#4641 NO-ISSUE: OWNERS: Add umohnani8
  OWNERS
Labels: lgtm, approved, jira/valid-reference

#4643 NO-ISSUE: Add LorbusChris to OWNERS
  OWNERS
Labels: lgtm, approved, jira/valid-reference

#4644 NO-ISSUE: Add Rishabh Saini to approvers and reviewers
  OWNERS
Labels: lgtm, approved, jira/valid-reference

#4568 MCO-1326: Decouple BuildController and ImageBuildRequest
  pkg/controller/build/build_controller.go
  pkg/controller/build/build_controller_test.go
  pkg/controller/build/buildrequest/assets/Containerfile.on-cluster-build-template
  pkg/controller/build/buildrequest/assets/README.md
  pkg/controller/build/buildrequest/assets/buildah-build.sh
  pkg/controller/build/buildrequest/assets/podman-build.sh
  pkg/controller/build/buildrequest/assets/wait.sh
  pkg/controller/build/buildrequest/buildrequest.go
  pkg/controller/build/buildrequest/buildrequest_test.go
  pkg/controller/build/buildrequest/buildrequestopts.go
  pkg/controller/build/buildrequest/buildrequestopts_test.go
  pkg/controller/build/buildrequest/envvolumemount.go
  pkg/controller/build/buildrequest/fixtures_test.go
  pkg/controller/build/buildrequest/helpers.go
  pkg/controller/build/buildrequest/helpers_test.go
  pkg/controller/build/buildrequest/interfaces.go
  pkg/controller/build/buildrequest/preparer.go
  pkg/controller/build/buildrequest/preparer_test.go
  pkg/controller/build/constants/constants.go
  pkg/controller/build/constants/selectors.go
  pkg/controller/build/fixtures_test.go
  pkg/controller/build/helpers.go
  pkg/controller/build/helpers_test.go
  pkg/controller/build/image_build_request.go
  pkg/controller/build/image_build_request_test.go
  pkg/controller/build/pod_build_controller.go
  test/e2e-techpreview/helpers_test.go
  test/helpers/layeredbuilder.go
  test/helpers/machineosbuildbuilder.go
  test/helpers/machineosconfigbuilder.go
  test/helpers/poolbuilder.go
Labels: lgtm, approved, jira/valid-reference

#4632 MCO-1276: Integrate Metric Collection with MCO Daemon
  pkg/daemon/daemon.go
  pkg/daemon/metrics.go
Labels: lgtm, approved, jira/valid-reference

#4637 NO-ISSUE: pkg/operator/status: Block ClusterVersion updates until multi-arch transitions complete
  cmd/machine-config-operator/main.go
  install/0000_80_machine-config_04_deployment.yaml
  install/0000_80_machine-config_06_clusteroperator.yaml
  pkg/operator/operator.go
  pkg/version/version.go
Labels: lgtm, approved, jira/valid-reference

#4646 OCPBUGS-43428: Soften haproxy timeout for kubeapi probe
  templates/master/00-master/on-prem/files/haproxy-haproxy.yaml
Labels: lgtm, approved, jira/valid-bug, jira/valid-reference

#4531 OCPBUGS-38490: Increase connection limit for cluster loadbalancer
  templates/master/00-master/on-prem/files/haproxy-haproxy.yaml
Labels: lgtm, approved, qe-approved, jira/valid-bug, jira/valid-reference

#4587 OCPNODE-2333: Implement ImagePolicy CRD
  docs/ClusterImagePolicyAndImagePolicyDesign.md
  docs/MachineConfigDaemon.md
  manifests/machineconfigcontroller/clusterrole.yaml
  pkg/apihelpers/apihelpers.go
  pkg/controller/bootstrap/bootstrap.go
  pkg/controller/container-runtime-config/container_runtime_config_bootstrap.go
  pkg/controller/container-runtime-config/container_runtime_config_controller.go
  pkg/controller/container-runtime-config/container_runtime_config_controller_test.go
  pkg/controller/container-runtime-config/helpers.go
  pkg/controller/container-runtime-config/helpers_test.go
  pkg/daemon/constants/constants.go
Labels: lgtm, approved, jira/valid-reference

#4633 OCPBUGS-42987: Disable ESP offload for OVS attached interfaces
  templates/common/_base/files/bond-esp-offload.yaml
  templates/common/_base/units/ipsec.service.yaml
Labels: lgtm, approved, jira/valid-bug, jira/valid-reference

#4636 AUTH-482: set required-scc for openshift workloads
  templates/master/01-master-kubelet/_base/files/criometricsproxy.yaml
  templates/worker/01-worker-kubelet/_base/files/criometricsproxy.yaml
Labels: lgtm, approved, jira/valid-reference

#4654 OPNET-569: Do not run resolv-prepender from NM dispatcher
  templates/common/on-prem/files/NetworkManager-resolv-prepender.yaml
  templates/common/on-prem/units/on-prem-resolv-prepender.path.yaml
Labels: lgtm, approved, jira/valid-reference

#4621 [4.15] OCPBUGS-42110: Do not use 'restart' for 'oneshot' service
  templates/common/on-prem/units/on-prem-resolv-prepender.service.yaml
Labels: lgtm, approved, cherry-pick-approved, backport-risk-assessed, jira/severity-important, jira/valid-bug, jira/valid-reference

#4668 OCPBUGS-43893: Pinned images not working
  pkg/daemon/cri/cri.go
Labels: lgtm, approved, qe-approved, jira/severity-important, jira/valid-bug, jira/valid-reference

#4673 [release-4.14] OCPBUGS-43980: MCPs report wrong number of nodes when we move nodes from one custom MCP to another custom MCP
  pkg/controller/node/node_controller.go
Labels: lgtm, approved, cherry-pick-approved, qe-approved, backport-risk-assessed, jira/severity-moderate, jira/valid-bug, jira/valid-reference
