Repository openshift/machine-config-operator, pull requests merged in 2024-02, with the labels that each got.

#4102 OCPBUGS-25753,OCPBUGS-22721: Run resolv-prepender entirely async
  templates/common/on-prem/files/NetworkManager-resolv-prepender.yaml
  templates/common/on-prem/files/resolv-prepender.yaml
Labels: lgtm, approved, qe-approved, jira/severity-important, jira/valid-bug, jira/valid-reference

#4018 CORS-2814: Add support for in-cluster DNS on Cloud Platforms when cloud DNS cannot be used
  install/0000_80_machine-config-operator_00_namespace.yaml
  manifests/cloud-platform-alt-dns/coredns-corefile.tmpl
  manifests/cloud-platform-alt-dns/coredns.yaml
  manifests/controllerconfig.crd.yaml
  pkg/controller/template/render.go
  pkg/operator/bootstrap.go
  pkg/operator/render.go
  pkg/operator/render_test.go
  pkg/operator/status.go
  templates/common/cloud-platform-alt-dns/files/coredns-corefile.yaml
  templates/common/cloud-platform-alt-dns/files/coredns.yaml
Labels: lgtm, approved, jira/valid-reference

#4135 OCPBUGS-24705: consider currentImage and desiredImage annotations
  pkg/controller/common/layered_node_state.go
  pkg/controller/common/layered_node_state_test.go
  pkg/controller/node/node_controller_test.go
  pkg/controller/node/status_test.go
Labels: lgtm, approved, jira/valid-bug, jira/valid-reference

#4055 OCPBUGS-24356: ovs-configure: fix `vlan_parent` calculation
  templates/common/_base/files/configure-ovs-network.yaml
Labels: lgtm, approved, jira/severity-moderate, jira/valid-bug, jira/valid-reference

#4036 [OCP-4.13] OCPBUGS-24661: daemon: Add support for new nmstate logic
  Dockerfile
  Dockerfile.rhel7
  cmd/machine-config-daemon/firstboot_complete_machineconfig.go
  pkg/daemon/daemon.go
Labels: lgtm, approved, ok-to-test, cherry-pick-approved, backport-risk-assessed, jira/valid-bug, jira/valid-reference

#4164 OCPNODE-2024: crio: migrate metrics port to localhost only
  templates/master/01-master-container-runtime/_base/files/crio.yaml
  templates/worker/01-worker-container-runtime/_base/files/crio.yaml
Labels: lgtm, approved, jira/valid-reference

#4111 OCPBUGS-26557: Add existing kubeletconfig/ctrcfg mc-name-suffix annotation
  pkg/controller/container-runtime-config/container_runtime_config_controller.go
  pkg/controller/container-runtime-config/container_runtime_config_controller_test.go
  pkg/controller/container-runtime-config/helpers.go
  pkg/controller/kubelet-config/helpers.go
  pkg/controller/kubelet-config/kubelet_config_controller.go
  pkg/controller/kubelet-config/kubelet_config_controller_test.go
Labels: lgtm, approved, qe-approved, jira/valid-bug, jira/valid-reference

#4165 OCPBUGS-28969: On-prem coredns manifests should not be generated for GCP
  pkg/operator/bootstrap.go
Labels: lgtm, approved, jira/severity-critical, jira/valid-bug, jira/valid-reference

#4168 OCPBUGS-29098: Revert "OCPNODE-2024: crio: migrate metrics port to localhost only"
  templates/master/01-master-container-runtime/_base/files/crio.yaml
  templates/worker/01-worker-container-runtime/_base/files/crio.yaml
Labels: lgtm, approved, jira/valid-bug, jira/valid-reference

#4174 OCPSTRAT-1062: [4.15] crio: enable log linking by default in 4.15
  templates/master/01-master-container-runtime/_base/files/crio.yaml
  templates/worker/01-worker-container-runtime/_base/files/crio.yaml
Labels: lgtm, approved, cherry-pick-approved, backport-risk-assessed, jira/valid-bug, jira/valid-reference

#4023 docs/HACKING: Update command for building customize OCP release
  docs/HACKING.md
Labels: lgtm, approved, ok-to-test, jira/valid-reference

#4176 NO-JIRA: Fix patch comparison bug in test
  pkg/controller/container-runtime-config/container_runtime_config_controller_test.go
  pkg/controller/kubelet-config/kubelet_config_controller_test.go
Labels: lgtm, approved, jira/valid-reference

#4143 OCPBUGS-26951: annotate on-prem static pods for workload partitioning
  templates/common/on-prem/files/coredns.yaml
  templates/common/on-prem/files/keepalived.yaml
  templates/master/00-master/on-prem/files/haproxy.yaml
Labels: lgtm, approved, jira/severity-important, jira/valid-bug, jira/valid-reference

#4181 NO-JIRA: remove kube-rbac-proxy for crio port
  manifests/machineconfigdaemon/daemonset.yaml
Labels: lgtm, approved, jira/valid-reference

#4177 MCO-774: Write e2e tests for bootimage management
  Makefile
  pkg/controller/machine-set-boot-image/machine_set_boot_image_controller.go
  test/e2e-techpreview/helpers_test.go
  test/e2e-techpreview/main_test.go
  test/e2e-techpreview/msbic_test.go
  test/e2e-techpreview/onclusterbuild_test.go
  test/helpers/utils.go
Labels: lgtm, approved, jira/valid-reference

#4129 OCPBUGS-18940: Add keepalived healthcheck for machine-config-server
  templates/master/00-master/on-prem/files/keepalived-keepalived.yaml
  templates/master/00-master/on-prem/files/keepalived-mcs-script.yaml
Labels: lgtm, approved, qe-approved, jira/severity-important, jira/valid-bug, jira/valid-reference

#4133 OPNET-355: Use NM's dns-change event for resolv.conf
  templates/common/on-prem/files/NetworkManager-resolv-prepender.yaml
Labels: lgtm, approved, jira/valid-reference

#4079 OCPBUGS-22324: Revert "Revert "Merge pull request #4028 from cybertron/wait-for-br-ex""
  templates/common/on-prem/files/NetworkManager-resolv-prepender.yaml
  templates/common/on-prem/files/wait-for-br-ex-up.yaml
  templates/common/on-prem/units/wait-for-br-ex-up.yaml
Labels: lgtm, approved, jira/severity-important, jira/valid-bug, jira/valid-reference

#4146 OCPBUGS-27162: Add dependency on crio-wipe to resolv-prepender
  templates/common/on-prem/units/on-prem-resolv-prepender.service.yaml
Labels: lgtm, approved, jira/severity-moderate, jira/valid-bug, jira/valid-reference

#4183 NO-ISSUE: add e2e-techpreview-shared, remove layering test target
  Makefile
  test/e2e-techpreview-shared/README.md
  test/e2e-techpreview-shared/noop_test.go
Labels: lgtm, approved, jira/valid-reference

#3628 NO-ISSUE: OWNERS: Remove myself from reviewers
  OWNERS
Labels: lgtm, approved, jira/valid-reference

#4190 NO-JIRA: nmstate, configure nmstate to keep service yamls
  templates/common/_base/files/nmstate-service-keep-state-file-after-apply.yaml
Labels: lgtm, approved, jira/valid-reference

#4047 OCPNODE-1877: Delete image openshift/openshift-proxy-pull-test
  Dockerfile.proxy
  docs/openshift-proxy-pull-test.md
Labels: lgtm, approved, jira/valid-reference

#4201 OCPBUGS-29624: Restart resolv-prepender on failure
  templates/common/on-prem/units/on-prem-resolv-prepender.service.yaml
Labels: lgtm, approved, jira/valid-bug, jira/valid-reference, acknowledge-critical-fixes-only

#4180 OCPBUGS-29366: release-4.12: fix nodeStatusUpdateFrequency
  templates/master/01-master-kubelet/_base/files/kubelet.yaml
  templates/worker/01-worker-kubelet/_base/files/kubelet.yaml
  test/e2e/kubeletcfg_test.go
Labels: lgtm, approved, cherry-pick-approved, backport-risk-assessed, jira/severity-moderate, jira/valid-bug, jira/valid-reference

#4196 OCPBUGS-29659: Apply new DNS configuration only if changed
  templates/common/on-prem/files/resolv-prepender.yaml
Labels: lgtm, approved, jira/valid-bug, jira/valid-reference, acknowledge-critical-fixes-only

#4207 OCPBUGS-29732: Always touch resolv-prepender file at end of script
  templates/common/on-prem/files/resolv-prepender.yaml
Labels: lgtm, approved, jira/valid-bug, jira/valid-reference, acknowledge-critical-fixes-only

#4197 MCO-998: sets up MCO repository for Snyk CI scans
  .snyk
Labels: lgtm, approved, jira/valid-reference

#4204 OCPBUGS-29713: set nodeStatusReportFrequency
  templates/master/01-master-kubelet/_base/files/kubelet.yaml
  templates/worker/01-worker-kubelet/_base/files/kubelet.yaml
Labels: lgtm, approved, jira/valid-bug, jira/valid-reference

#4212 NO-JIRA: ovs-configfuration, run after nmstate.service
  templates/common/_base/units/ovs-configuration.service.yaml
  templates/common/azure/units/ovs-configuration.service.yaml
Labels: lgtm, approved, jira/valid-reference

#4218 OCPBUGS-29067: Add HostToContainer propogataion for coreDNS pods on cloud platforms
  manifests/cloud-platform-alt-dns/coredns.yaml
Labels: lgtm, approved, jira/valid-bug, jira/valid-reference
