Repository openshift/machine-config-operator, pull requests merged in 2024-03, with the labels that each got.

#4223 OCPBUGS-30090: add node owner to MCN
  pkg/operator/sync.go
  pkg/upgrademonitor/upgrade_monitor.go
Labels: lgtm, approved, jira/valid-bug, jira/valid-reference

#4216 OCPBUGS-29946: Prevent pull images in podmanCopy if they are present
  pkg/daemon/update.go
  pkg/daemon/update_test.go
Labels: lgtm, approved, qe-approved, jira/valid-bug, jira/valid-reference

#4231 OCPBUGS-30136: APIVersion and Kind sometimes are empty when listing objects
  pkg/operator/sync.go
  pkg/upgrademonitor/upgrade_monitor.go
Labels: lgtm, approved, jira/severity-important, jira/valid-bug, jira/valid-reference

#4224 OCPCLOUD-2465: Add Image Credential Provider flags for Kubelet on GCP
  pkg/controller/template/render.go
  pkg/controller/template/render_test.go
  templates/common/gcp/files/etc-kubernetes-credential-providers-gcr-credential-provider.yaml
Labels: lgtm, approved, qe-approved, jira/valid-reference

#4194 MCO-898: OCPBUGS-29857: OCPBUGS-29819: Implement an alerting mechanism for boot image update failures
  install/0000_90_machine-config-operator_01_prometheus-rules.yaml
  pkg/controller/common/metrics.go
  pkg/controller/machine-set-boot-image/machine_set_boot_image_controller.go
Labels: lgtm, approved, qe-approved, jira/valid-reference

#4106 OCPBUGS-25821: backportable version of api-int cert work
  Makefile
  cmd/machine-config-daemon/start.go
  install/0000_80_machine-config-operator_00_service.yaml
  manifests/machineconfigcontroller/clusterrole.yaml
  manifests/machineconfigdaemon/daemonset.yaml
  manifests/machineconfigdaemon/role.yaml
  manifests/machineconfigserver/clusterrole.yaml
  pkg/controller/common/constants.go
  pkg/controller/common/helpers.go
  pkg/controller/node/node_controller.go
  pkg/daemon/certificate_writer.go
  pkg/daemon/constants/constants.go
  pkg/daemon/daemon.go
  pkg/daemon/update.go
  pkg/operator/operator.go
  pkg/operator/sync.go
  pkg/server/cluster_server.go
  pkg/server/server.go
  test/e2e-shared-tests/helpers.go
  test/e2e-shared-tests/mcd_config_drift.go
  test/helpers/utils.go
Labels: lgtm, approved, qe-approved, jira/severity-critical, jira/valid-bug, jira/valid-reference

#4222 OCPCLOUD-2462: Add Image Credential Provider flags for Kubelet on Azure
  pkg/controller/template/render.go
  pkg/controller/template/render_test.go
  templates/common/azure/files/etc-kubernetes-credential-providers-acr-credential-provider.yaml
Labels: lgtm, approved, qe-approved, jira/valid-reference

#3936 [release-4.12] OCPBUGS-19659: After dual-stack conversion reconcile IPFamilies
  lib/resourcemerge/machineconfig.go
  lib/resourcemerge/meta.go
Labels: lgtm, approved, cherry-pick-approved, backport-risk-assessed, jira/valid-bug, jira/valid-reference

#4175 OCPNODE-2098: Add static pod for kube-rbac-proxy-crio
  pkg/controller/template/constants.go
  pkg/operator/bootstrap.go
  pkg/operator/sync.go
  templates/master/01-master-kubelet/_base/files/criometricsproxy-config.yaml
  templates/master/01-master-kubelet/_base/files/criometricsproxy.yaml
  templates/worker/01-worker-kubelet/_base/files/criometricsproxy-config.yaml
  templates/worker/01-worker-kubelet/_base/files/criometricsproxy.yaml
Labels: lgtm, approved, jira/valid-reference

#4234 NO-JIRA: Sync CRI-O owners
  pkg/controller/container-runtime-config/OWNERS
  templates/master/01-master-container-runtime/OWNERS
  templates/worker/01-worker-container-runtime/OWNERS
Labels: lgtm, approved, jira/valid-reference

#4252 [release-4.15] OCPBUGS-30761: add static pods for rbacproxy
  pkg/controller/template/constants.go
  pkg/operator/bootstrap.go
  pkg/operator/sync.go
  templates/master/01-master-kubelet/_base/files/criometricsproxy-config.yaml
  templates/master/01-master-kubelet/_base/files/criometricsproxy.yaml
  templates/worker/01-worker-kubelet/_base/files/criometricsproxy-config.yaml
  templates/worker/01-worker-kubelet/_base/files/criometricsproxy.yaml
Labels: lgtm, approved, cherry-pick-approved, backport-risk-assessed, jira/valid-bug, jira/valid-reference

#4206 [release-4.13] OCPBUGS-29721: Add existing kubeletconfig/ctrcfg mc-name-suffix annotation
  pkg/controller/container-runtime-config/container_runtime_config_controller.go
  pkg/controller/container-runtime-config/container_runtime_config_controller_test.go
  pkg/controller/container-runtime-config/helpers.go
  pkg/controller/kubelet-config/helpers.go
  pkg/controller/kubelet-config/kubelet_config_controller.go
  pkg/controller/kubelet-config/kubelet_config_controller_test.go
Labels: lgtm, approved, cherry-pick-approved, qe-approved, backport-risk-assessed, jira/valid-bug, jira/valid-reference

#4229 [4.15] OCPBUGS-30093: Mount /run/nodeip-configuration into coredns containers
  manifests/on-prem/coredns.yaml
  templates/common/on-prem/files/coredns.yaml
Labels: lgtm, approved, cherry-pick-approved, backport-risk-assessed, jira/severity-low, jira/valid-bug, jira/valid-reference

#4228 OCPCLOUD-2514,OCPCLOUD-2516: Remove reliance on feature gates for cloud provider flags
  cmd/machine-config-controller/start.go
  go.mod
  go.sum
  pkg/controller/bootstrap/bootstrap.go
  pkg/controller/container-runtime-config/container_runtime_config_bootstrap.go
  pkg/controller/container-runtime-config/container_runtime_config_controller.go
  pkg/controller/kubelet-config/kubelet_config_controller.go
  pkg/controller/kubelet-config/kubelet_config_features_test.go
  pkg/controller/kubelet-config/kubelet_config_nodes_test.go
  pkg/controller/template/render.go
  pkg/controller/template/render_test.go
  pkg/controller/template/template_controller.go
  pkg/controller/template/template_controller_test.go
  templates/master/01-master-kubelet/_base/units/kubelet.service.yaml
  templates/master/01-master-kubelet/alibabacloud/units/kubelet.service.yaml
  templates/master/01-master-kubelet/on-prem/units/kubelet.service.yaml
  templates/worker/01-worker-kubelet/_base/units/kubelet.service.yaml
  templates/worker/01-worker-kubelet/alibabacloud/units/kubelet.service.yaml
  templates/worker/01-worker-kubelet/on-prem/units/kubelet.service.yaml
  test/e2e-bootstrap/bootstrap_test.go
  vendor/github.com/openshift/api/annotations/annotations.go
  vendor/github.com/openshift/library-go/pkg/certs/pem.go
  vendor/github.com/openshift/library-go/pkg/certs/util.go
  vendor/github.com/openshift/library-go/pkg/cloudprovider/external.go
  vendor/github.com/openshift/library-go/pkg/crypto/crypto.go
  vendor/github.com/openshift/library-go/pkg/operator/certrotation/OWNERS
  vendor/github.com/openshift/library-go/pkg/operator/certrotation/annotations.go
  vendor/github.com/openshift/library-go/pkg/operator/certrotation/cabundle.go
  vendor/github.com/openshift/library-go/pkg/operator/certrotation/client_cert_rotation_controller.go
  vendor/github.com/openshift/library-go/pkg/operator/certrotation/config.go
  vendor/github.com/openshift/library-go/pkg/operator/certrotation/label.go
  vendor/github.com/openshift/library-go/pkg/operator/certrotation/signer.go
  vendor/github.com/openshift/library-go/pkg/operator/certrotation/target.go
  vendor/github.com/openshift/library-go/pkg/operator/resource/resourceapply/admissionregistration.go
  vendor/github.com/openshift/library-go/pkg/operator/resource/resourceapply/apiextensions.go
  vendor/github.com/openshift/library-go/pkg/operator/resource/resourceapply/apiregistration.go
  vendor/github.com/openshift/library-go/pkg/operator/resource/resourceapply/apps.go
  vendor/github.com/openshift/library-go/pkg/operator/resource/resourceapply/core.go
  vendor/github.com/openshift/library-go/pkg/operator/resource/resourceapply/migration.go
  vendor/github.com/openshift/library-go/pkg/operator/resource/resourceapply/monitoring.go
  vendor/github.com/openshift/library-go/pkg/operator/resource/resourceapply/policy.go
  vendor/github.com/openshift/library-go/pkg/operator/resource/resourceapply/rbac.go
  vendor/github.com/openshift/library-go/pkg/operator/resource/resourceapply/storage.go
  vendor/github.com/openshift/library-go/pkg/operator/resource/resourceapply/volumesnapshotclass.go
  vendor/github.com/openshift/library-go/pkg/operator/resource/resourceread/config.go
  vendor/github.com/openshift/library-go/pkg/operator/resourcesynccontroller/core.go
  vendor/github.com/openshift/library-go/pkg/operator/status/condition.go
  vendor/github.com/openshift/library-go/pkg/operator/status/status_controller.go
  vendor/github.com/openshift/library-go/pkg/operator/v1helpers/helpers.go
  vendor/github.com/openshift/library-go/pkg/operator/v1helpers/interfaces.go
  vendor/github.com/openshift/library-go/pkg/operator/v1helpers/test_helpers.go
  vendor/k8s.io/code-generator/generate-groups.sh
  vendor/k8s.io/code-generator/generate-internal-groups.sh
  vendor/modules.txt
Labels: lgtm, approved, jira/valid-reference

#4213 OCPBUGS-30239: Prevent OVS-configuration to run before kdump
  templates/common/_base/units/ovs-configuration.service.yaml
  templates/common/azure/units/ovs-configuration.service.yaml
Labels: lgtm, approved, jira/valid-bug, jira/valid-reference

#4260 OCPCLOUD-2465: Updates GCR CredentialProviderConfig
  templates/common/gcp/files/etc-kubernetes-credential-providers-gcr-credential-provider.yaml
Labels: lgtm, approved, jira/valid-reference, acknowledge-critical-fixes-only

#4189 MCO-760: add rebuild mechanism to ocb
  pkg/controller/build/build_controller.go
  pkg/controller/build/build_controller_test.go
  pkg/controller/common/constants.go
  pkg/controller/common/helpers.go
Labels: lgtm, approved, jira/valid-reference

#4280 OCPBUGS-31365: make verify should use MCO's kube version
  Makefile
Labels: lgtm, approved, jira/severity-important, jira/valid-bug, jira/valid-reference

#3698 OPNET-303,OCPBUGS-25744: Remove weights from ingress check script
  templates/common/on-prem/files/keepalived.yaml
  templates/master/00-master/on-prem/files/keepalived-keepalived.yaml
  templates/worker/00-worker/on-prem/files/keepalived-keepalived.yaml
Labels: lgtm, approved, qe-approved, jira/valid-bug, jira/valid-reference

#4042 OCPBUGS-27316: configure-ovs: generate profiles directly in /run
  templates/common/_base/files/configure-ovs-network.yaml
Labels: lgtm, approved, lifecycle/stale, jira/severity-moderate, jira/valid-bug, jira/valid-reference

#4240 OCPBUGS-9108: OCPBUGS-24228: Make MCO operator always Available, add retry to applyManifests before degrading
  pkg/operator/status.go
  pkg/operator/status_test.go
  pkg/operator/sync.go
Labels: lgtm, approved, qe-approved, jira/severity-moderate, jira/valid-bug, jira/valid-reference

#4276 OCPBUGS-31067: server: still serve kubeconfig with node-bootstrapper-token
  pkg/daemon/certificate_writer.go
  pkg/server/cluster_server.go
  pkg/server/server_test.go
Labels: lgtm, approved, qe-approved, jira/severity-moderate, jira/valid-bug, jira/valid-reference

#4257 [release-4.12] OCPBUGS-30829: Add existing kubeletconfig/ctrcfg mc-name-suffix annotation
  pkg/controller/container-runtime-config/container_runtime_config_controller.go
  pkg/controller/container-runtime-config/container_runtime_config_controller_test.go
  pkg/controller/container-runtime-config/helpers.go
  pkg/controller/kubelet-config/helpers.go
  pkg/controller/kubelet-config/kubelet_config_controller.go
  pkg/controller/kubelet-config/kubelet_config_controller_test.go
Labels: lgtm, approved, cherry-pick-approved, backport-risk-assessed, jira/valid-bug, jira/valid-reference

#4287 OCPBUGS-31376: kubelet: restorecon necessary files on kubelet's prestart
  templates/common/_base/units/kubelet-selinux-relabel.yaml
  templates/master/01-master-kubelet/_base/units/kubelet.service.yaml
  templates/master/01-master-kubelet/alibabacloud/units/kubelet.service.yaml
  templates/master/01-master-kubelet/on-prem/units/kubelet.service.yaml
  templates/worker/01-worker-kubelet/_base/units/kubelet.service.yaml
  templates/worker/01-worker-kubelet/alibabacloud/units/kubelet.service.yaml
  templates/worker/01-worker-kubelet/on-prem/units/kubelet.service.yaml
Labels: lgtm, approved, jira/severity-important, jira/valid-bug, jira/valid-reference
