Repository openshift/machine-config-operator, pull requests merged in 2024-12, with the labels that each got.

#4706 OCPBUGS-39199: clusteroperator/machine-config blips Degraded=True during upgrade test
  pkg/operator/sync.go
Labels: lgtm, approved, qe-approved, jira/valid-bug, jira/valid-reference

#4729 OCPBUGS-45306: Remove trailing periods from AWS provided hostnames
  templates/common/aws/files/usr-local-bin-aws-kubelet-nodename.yaml
Labels: lgtm, approved, jira/severity-critical, jira/valid-bug, jira/valid-reference

#4730 MCO-1416: Increase timeouts in OCL e2e tests
  test/e2e-ocl/onclusterlayering_test.go
Labels: lgtm, approved, jira/valid-reference

#4707 OCPBUGS-27477: Pausing Master MCP results in Alerts
  pkg/operator/sync.go
Labels: lgtm, approved, qe-approved, jira/severity-low, jira/valid-bug, jira/valid-reference

#4740 OCPBUGS-45860: daemon: add nil check for annotation fetching
  pkg/daemon/node.go
Labels: lgtm, approved, qe-approved, jira/severity-critical, jira/valid-bug, jira/valid-reference

#4727 OCPBUGS-42636: Wait to render for other MC generating sub-controllers
  cmd/machine-config-controller/start.go
  pkg/apihelpers/apihelpers.go
  pkg/controller/render/render_controller.go
  pkg/controller/render/render_controller_test.go
  test/e2e-bootstrap/bootstrap_test.go
Labels: lgtm, approved, jira/severity-moderate, jira/valid-bug, jira/valid-reference

#4731 MCO-113: Preserve previous boot MCD log
  pkg/daemon/daemon.go
Labels: lgtm, approved, jira/valid-reference

#4750 MCO-1416: Update timeouts & improve debuggability of ocl e2e tests
  test/e2e-ocl/helpers_test.go
  test/e2e-ocl/main_test.go
  test/e2e-ocl/onclusterlayering_test.go
  test/helpers/assertions.go
  test/helpers/assertions_test.go
  test/helpers/idempotent.go
  test/helpers/idempotent_test.go
  test/helpers/utils.go
  test/helpers/utils_test.go
Labels: lgtm, approved, jira/valid-reference

#4752 OCPBUGS-46052: machine-os-builder deployment missing openshift.io/required-scc annotation
  manifests/machineosbuilder/deployment.yaml
Labels: lgtm, approved, jira/valid-bug, jira/valid-reference

#4755 OCPBUGS-46583: [release-4.18] machine-os-builder deployment missing openshift.io/required-scc annotation
  manifests/machineosbuilder/deployment.yaml
Labels: lgtm, approved, cherry-pick-approved, qe-approved, backport-risk-assessed, jira/valid-bug, jira/valid-reference

#4765 OCPBUGS-45928,OCPBUGS-46531: crio: drop crun subcgroup
  templates/master/01-master-container-runtime/_base/files/crio.yaml
  templates/worker/01-worker-container-runtime/_base/files/crio.yaml
Labels: lgtm, approved, jira/valid-bug, jira/valid-reference

#4715 [release-4.17] OCPBUGS-38292: controller: default to runc when upgrading clusters from 4.17 to 4.18
  cmd/machine-config-controller/main.go
  cmd/machine-config-controller/start.go
  pkg/controller/bootstrap/bootstrap.go
  pkg/controller/container-runtime-config/container_runtime_config_bootstrap_test.go
  pkg/controller/container-runtime-config/container_runtime_config_controller.go
  pkg/controller/container-runtime-config/container_runtime_config_controller_test.go
  pkg/controller/container-runtime-config/helpers.go
  test/e2e-bootstrap/bootstrap_test.go
  test/framework/envtest.go
Labels: lgtm, approved, cherry-pick-approved, backport-risk-assessed, jira/severity-critical, jira/valid-bug, jira/valid-reference

#4764 OCPBUGS-38749: add timeout error to applyManifest retry list
  lib/resourceapply/apps.go
Labels: lgtm, approved, qe-approved, jira/valid-bug, jira/valid-reference, acknowledge-critical-fixes-only

#4757 OCPBUGS-33144: Add clarification to invalid maxUnavailable alert
  pkg/controller/node/node_controller.go
Labels: lgtm, approved, qe-approved, jira/severity-low, jira/valid-bug, jira/valid-reference, acknowledge-critical-fixes-only

#4770 TRT-1926: Revert #4765 "crio: drop crun subcgroup"
  templates/master/01-master-container-runtime/_base/files/crio.yaml
  templates/worker/01-worker-container-runtime/_base/files/crio.yaml
Labels: lgtm, approved, jira/valid-reference, acknowledge-critical-fixes-only
