Repository openshift/machine-config-operator, pull requests merged in 2024-08, with the labels that each got.

#4485 [release-4.14] OCPBUGS-37483: Remove weights from ingress check script
  templates/common/on-prem/files/keepalived.yaml
  templates/master/00-master/on-prem/files/keepalived-keepalived.yaml
  templates/worker/00-worker/on-prem/files/keepalived-keepalived.yaml
Labels: lgtm, approved, cherry-pick-approved, backport-risk-assessed, jira/valid-bug, jira/valid-reference

#4496 MCO-1065: MCO-1171: API bump for ManagedBootImages and NodeDisruptionPolicy GA
  go.mod
  go.sum
  hack/crds-sync.sh
  install/0000_80_machine-config_01_machineconfigurations-CustomNoUpgrade.crd.yaml
  install/0000_80_machine-config_01_machineconfigurations-Default.crd.yaml
  install/0000_80_machine-config_01_machineconfigurations-TechPreviewNoUpgrade.crd.yaml
  install/0000_80_machine-config_01_machineconfigurations.crd.yaml
  vendor/github.com/openshift/api/features.md
  vendor/github.com/openshift/api/features/features.go
  vendor/github.com/openshift/api/operator/v1/types_ingress.go
  vendor/github.com/openshift/api/operator/v1/zz_generated.crd-manifests/0000_50_ingress_00_ingresscontrollers-CustomNoUpgrade.crd.yaml
  vendor/github.com/openshift/api/operator/v1/zz_generated.crd-manifests/0000_50_ingress_00_ingresscontrollers-Default.crd.yaml
  vendor/github.com/openshift/api/operator/v1/zz_generated.crd-manifests/0000_50_ingress_00_ingresscontrollers-DevPreviewNoUpgrade.crd.yaml
  vendor/github.com/openshift/api/operator/v1/zz_generated.crd-manifests/0000_50_ingress_00_ingresscontrollers-TechPreviewNoUpgrade.crd.yaml
  vendor/github.com/openshift/api/operator/v1/zz_generated.crd-manifests/0000_80_machine-config_01_machineconfigurations-CustomNoUpgrade.crd.yaml
  vendor/github.com/openshift/api/operator/v1/zz_generated.crd-manifests/0000_80_machine-config_01_machineconfigurations-Default.crd.yaml
  vendor/github.com/openshift/api/operator/v1/zz_generated.crd-manifests/0000_80_machine-config_01_machineconfigurations-TechPreviewNoUpgrade.crd.yaml
  vendor/github.com/openshift/api/operator/v1/zz_generated.crd-manifests/0000_80_machine-config_01_machineconfigurations.crd.yaml
  vendor/github.com/openshift/api/operator/v1/zz_generated.deepcopy.go
  vendor/github.com/openshift/api/operator/v1/zz_generated.featuregated-crd-manifests.yaml
  vendor/github.com/openshift/api/operator/v1/zz_generated.swagger_doc_generated.go
  vendor/k8s.io/code-generator/generate-groups.sh
  vendor/k8s.io/code-generator/generate-internal-groups.sh
  vendor/modules.txt
Labels: lgtm, approved, do-not-merge/hold, qe-approved, jira/valid-reference

#4382 OCPBUGS-37840: [release-4.16] Introduce versioning for Auto Node Sizing feature
  templates/common/_base/files/kubelet-auto-sizing.yaml
Labels: lgtm, approved, cherry-pick-approved, backport-risk-assessed, jira/severity-important, jira/valid-bug, jira/valid-reference

#4508 NO-ISSUE: Remove openshift/api pin
  go.mod
  go.sum
  vendor/github.com/openshift/api/features.md
  vendor/github.com/openshift/api/features/features.go
  vendor/github.com/openshift/api/machine/v1/types_nutanixprovider.go
  vendor/github.com/openshift/api/machine/v1/zz_generated.deepcopy.go
  vendor/github.com/openshift/api/machine/v1/zz_generated.swagger_doc_generated.go
  vendor/github.com/openshift/api/operator/v1/types_console.go
  vendor/github.com/openshift/api/operator/v1/zz_generated.crd-manifests/0000_50_console_01_consoles.crd.yaml
  vendor/github.com/openshift/api/operator/v1/zz_generated.deepcopy.go
  vendor/github.com/openshift/api/operator/v1/zz_generated.swagger_doc_generated.go
  vendor/modules.txt
Labels: lgtm, approved, jira/valid-reference

#4507 [release-4.13] OCPBUGS-37783: Openshift uncordoned compute-node that was intentionally cordoned
  pkg/controller/node/node_controller.go
  pkg/controller/node/node_controller_test.go
Labels: lgtm, approved, cherry-pick-approved, backport-risk-assessed, jira/severity-moderate, jira/valid-bug, jira/valid-reference

#4505 [release-4.16] OCPBUGS-37759: Guard MachineOSBuild & MachineOSConfig informers with feature gates
  cmd/machine-config-controller/start.go
  pkg/controller/common/controller_context.go
  pkg/controller/node/node_controller.go
Labels: lgtm, approved, cherry-pick-approved, backport-risk-assessed, jira/valid-bug, jira/valid-reference

#4510 NO-JIRA: Fix HasOSImage function
  pkg/controller/common/layered_pool_state.go
Labels: lgtm, approved, jira/valid-reference

#4513 NO-ISSUE: Move ManagedBootImages and NodeDisruptionPolicy to default e2e suite
  test/e2e-techpreview/main_test.go
  test/e2e/msbic_test.go
  test/e2e/nodedisrupt_test.go
Labels: lgtm, approved, jira/valid-reference

#4492 MCO-1214: Enabled boot images updates for AWS
  manifests/machineconfigcontroller/update-bootimages-validatingadmissionpolicy.yaml
  pkg/controller/machine-set-boot-image/platform_helpers.go
Labels: lgtm, approved, qe-approved, jira/valid-reference

#4471 MCO-703: Lifecycle Buildah with MCO
  Dockerfile
  Dockerfile.rhel7
  cmd/machine-config-operator/bootstrap.go
  pkg/controller/build/assets/wait.sh
  pkg/controller/build/build_controller.go
  pkg/controller/build/build_controller_test.go
  pkg/controller/build/constants.go
  pkg/controller/build/fixtures_test.go
  pkg/controller/build/helpers.go
  pkg/controller/build/helpers_test.go
  pkg/controller/build/image_build_request.go
  pkg/controller/build/image_build_request_test.go
  pkg/controller/common/constants.go
  pkg/controller/common/images.go
  pkg/operator/bootstrap.go
  pkg/operator/images.go
  pkg/operator/operator.go
  pkg/operator/render.go
  pkg/operator/render_test.go
  pkg/operator/sync.go
  test/e2e-techpreview/helpers_test.go
  test/e2e-techpreview/onclusterlayering_test.go
  test/e2e/mob_test.go
  test/helpers/utils.go
Labels: lgtm, approved, jira/valid-reference

#4511 OCPBUGS-31298: Prevent no-operation patches from overloading the kube-api server with unnecessary calls
  internal/kubeutils.go
Labels: lgtm, approved, jira/severity-low, jira/valid-bug, jira/valid-reference

#4512 OCPBUGS-35800: kubelet config controller does not always propogate tlsSecurityProfile
  pkg/controller/bootstrap/bootstrap.go
  pkg/controller/bootstrap/testdata/bootstrap/apiserver.yaml
  pkg/controller/kubelet-config/kubelet_config_bootstrap.go
  pkg/controller/kubelet-config/kubelet_config_bootstrap_test.go
  pkg/controller/kubelet-config/kubelet_config_controller.go
  pkg/controller/kubelet-config/kubelet_config_controller_test.go
  pkg/controller/kubelet-config/kubelet_config_features.go
  pkg/controller/kubelet-config/kubelet_config_features_test.go
  pkg/controller/kubelet-config/kubelet_config_nodes.go
  pkg/controller/kubelet-config/kubelet_config_nodes_test.go
  pkg/controller/template/template_controller.go
  templates/master/01-master-kubelet/_base/files/kubelet.yaml
  templates/worker/01-worker-kubelet/_base/files/kubelet.yaml
  test/framework/envtest.go
Labels: lgtm, approved, qe-approved, jira/valid-bug, jira/valid-reference

#4516 NO-JIRA: crio: set min memory for crun
  templates/master/01-master-container-runtime/_base/files/crio.yaml
  templates/worker/01-worker-container-runtime/_base/files/crio.yaml
Labels: lgtm, approved, jira/valid-reference

#4437 OCPNODE-2357: templates/master/cri-o: make crun as the default container runtime
  templates/master/01-master-container-runtime/_base/files/crio.yaml
  templates/worker/01-worker-container-runtime/_base/files/crio.yaml
Labels: lgtm, approved, jira/valid-reference

#4523 OCPBUGS-38320: Revert "templates/master/cri-o: make crun as the default container runtime"
  templates/master/01-master-container-runtime/_base/files/crio.yaml
  templates/worker/01-worker-container-runtime/_base/files/crio.yaml
Labels: lgtm, jira/valid-bug, jira/valid-reference

#4524 OCPBUGS-38321: Revert "templates/master/cri-o: make crun as the default container runtime"
  templates/master/01-master-container-runtime/_base/files/crio.yaml
  templates/worker/01-worker-container-runtime/_base/files/crio.yaml
Labels: lgtm, approved, cherry-pick-approved, backport-risk-assessed, jira/valid-bug, jira/valid-reference

#4515 OCPBUGS-37534: Revert "MCD-pull: run after network-online.target in Azure"
  templates/common/azure/units/machine-config-daemon-pull.service.yaml
Labels: lgtm, approved, qe-approved, jira/severity-important, jira/valid-bug, jira/valid-reference

#4517 OCPBUGS-37984: Give keepalived-monitor necessary capabilities
  templates/common/on-prem/files/keepalived.yaml
Labels: lgtm, approved, jira/valid-bug, jira/valid-reference

#4519 OCPNODE-2482: Enable CRI-O internal repair feature as the default
  templates/master/01-master-container-runtime/_base/files/crio.yaml
  templates/worker/01-worker-container-runtime/_base/files/crio.yaml
Labels: lgtm, approved, jira/valid-reference

#4543 NO-ISSUE: Add ref link to NodeDisruptionPolicy in docs/*
  docs/MachineConfigDaemon.md
Labels: lgtm, approved, jira/valid-reference

#4533 OCPBUGS-37850: Machine-config daemon ListPools panic during tech-preview CI runs
  pkg/daemon/pinned_image_set.go
Labels: lgtm, approved, qe-approved, jira/severity-moderate, jira/valid-bug, jira/valid-reference

#4369 OCPBUGS-31777: Updates message verbs to use %q where appropriate
  pkg/daemon/daemon.go
  pkg/daemon/update.go
  pkg/server/api.go
Labels: lgtm, approved, jira/valid-bug, jira/valid-reference

#4415 OCPBUGS-29444: Rewrote TestFirstBootHasSSHKeys e2e test in pure Go
  test/e2e/mcd_test.go
  test/helpers/utils.go
Labels: lgtm, approved, qe-approved, jira/severity-low, jira/valid-bug, jira/valid-reference, acknowledge-critical-fixes-only

#4426 OCPBUGS-35509: In OCB/OCL it takes too much time to apply the new image once it has been build
  cmd/machine-config-controller/start.go
  pkg/controller/node/node_controller.go
  pkg/controller/node/node_controller_test.go
  test/e2e-bootstrap/bootstrap_test.go
Labels: lgtm, approved, qe-approved, jira/severity-moderate, jira/valid-bug, jira/valid-reference

#4556 OCPBUGS-36850: Port number 22623 exposing weak ciphers to external client from master node IP
  pkg/server/api.go
Labels: lgtm, approved, cherry-pick-approved, qe-approved, backport-risk-assessed, jira/severity-critical, jira/valid-bug, jira/valid-reference
