Repository openshift/machine-config-operator, pull requests merged in 2024-06, with the labels that each got.

#4383 OCPBUGS-17658: Controller pod is spamming unknown field "spec.dns.spec.platform" message
  manifests/controllerconfig.crd.yaml
Labels: lgtm, approved, cherry-pick-approved, qe-approved, backport-risk-assessed, jira/severity-low, jira/valid-bug, jira/valid-reference

#4347 OCPBUGS-33248: daemon: upgrade os image from local container storage if it exists
  pkg/daemon/rpm-ostree.go
  pkg/daemon/update.go
Labels: lgtm, approved, qe-approved, jira/valid-bug, jira/valid-reference

#4359 OCPBUGS-34959: ensure event handlers are registered after queue is configured
  pkg/controller/pinnedimageset/pinned_image_set.go
  pkg/daemon/pinned_image_set.go
Labels: lgtm, approved, qe-approved, jira/severity-moderate, jira/valid-bug, jira/valid-reference, acknowledge-critical-fixes-only

#4365 MCO-1152: MCO-1146: Add e2e tests for NodeDisruptionPolicy
  pkg/daemon/update.go
  pkg/operator/sync.go
  test/e2e-shared-tests/helpers.go
  test/e2e-shared-tests/mcd_config_drift.go
  test/e2e-techpreview/helpers_test.go
  test/e2e-techpreview/main_test.go
  test/e2e-techpreview/nodedisrupt_test.go
  test/helpers/utils.go
Labels: lgtm, approved, jira/valid-reference

#4396 OCPBUGS-33129: Panic when we remove an OCB infra MCP and we try to create new ones with different names
  pkg/controller/build/build_controller.go
  pkg/controller/node/node_controller.go
Labels: lgtm, approved, qe-approved, jira/severity-moderate, jira/valid-bug, jira/valid-reference

#4366 OCPBUGS-33671, OCPBUGS-34079: fix secret canonicalization
  pkg/controller/build/build_controller.go
  pkg/controller/build/build_controller_test.go
  pkg/controller/build/helpers.go
  pkg/controller/build/helpers_test.go
Labels: lgtm, approved, qe-approved, jira/valid-bug, jira/valid-reference

#4401 OCPNODE-2336: Drop ClusterImagePolicy validation on scope conflicts with release-image repo
  docs/ClusterImagePolicyDesign.md
  pkg/controller/container-runtime-config/container_runtime_config_controller.go
  pkg/controller/container-runtime-config/container_runtime_config_controller_test.go
  pkg/controller/container-runtime-config/helpers_test.go
Labels: lgtm, approved, jira/valid-reference

#4292 OCPNODE-2216: crio: migrate metrics port to localhost only [4.17]
  templates/master/01-master-container-runtime/_base/files/crio.yaml
  templates/worker/01-worker-container-runtime/_base/files/crio.yaml
Labels: lgtm, approved, jira/valid-reference

#4404 OCPBUGS-35300: Azure: add Azure specific dnsmasq ordering
  templates/common/azure/units/machine-config-daemon-pull.service.yaml
Labels: lgtm, approved, jira/valid-bug, jira/valid-reference

#4388 OCPBUGS-34050: Default ipv4 NODE_IP to 0.0.0.0
  templates/master/01-master-kubelet/_base/units/kubelet.service.yaml
  templates/master/01-master-kubelet/on-prem/units/kubelet.service.yaml
  templates/worker/01-worker-kubelet/_base/units/kubelet.service.yaml
  templates/worker/01-worker-kubelet/on-prem/units/kubelet.service.yaml
Labels: lgtm, approved, jira/severity-critical, jira/valid-bug, jira/valid-reference

#4353 OCPBUGS-33331: Fix reference to $host_file
  templates/common/baremetal/files/nmstate-configuration.yaml
Labels: lgtm, approved, jira/severity-moderate, jira/valid-bug, jira/valid-reference

#4411 OCPBUGS-35519: Revert "Azure: add Azure specific dnsmasq ordering"
  templates/common/azure/units/machine-config-daemon-pull.service.yaml
Labels: lgtm, approved, jira/severity-moderate, jira/valid-bug, jira/valid-reference

#4350 OCPBUGS-31710: Unify machineconfig file format for kubeletconfig to use YAML encoding instead of JSON encoding
  pkg/controller/kubelet-config/helpers.go
  pkg/controller/kubelet-config/kubelet_config_bootstrap_test.go
  pkg/controller/kubelet-config/kubelet_config_controller_test.go
  test/e2e/kubeletcfg_test.go
Labels: lgtm, approved, qe-approved, jira/valid-bug, jira/valid-reference

#4344 OCPBUGS-32348: Make logging configurable for on-prem components
  install/0000_80_machine-config_03_rbac.yaml
  manifests/on-prem/keepalived.yaml
  templates/common/on-prem/files/keepalived.yaml
Labels: lgtm, approved, qe-approved, jira/valid-bug, jira/valid-reference, acknowledge-critical-fixes-only

#4412 NO-JIRA: format policy.json
  pkg/controller/container-runtime-config/helpers.go
Labels: lgtm, approved, jira/valid-reference

#4427 OCPBUGS-35992: disable mglru service
  templates/common/_base/units/disable-mglru.service.yaml
  templates/common/_base/units/kubelet-dependencies.target.yaml
Labels: lgtm, jira/invalid-bug, jira/valid-reference

#4395 OCPBUGS-33913, OCPBUGS-34261: CurrentImagePullSecret should be consumed by the MCD
  cmd/machine-config-operator/start.go
  docs/NodeDisruptionPolicy.md
  manifests/machineconfigdaemon/daemonset.yaml
  pkg/apihelpers/apihelpers.go
  pkg/controller/build/build_controller_test.go
  pkg/controller/build/fixtures_test.go
  pkg/controller/build/helpers.go
  pkg/controller/build/helpers_test.go
  pkg/controller/common/dockerconfig.go
  pkg/controller/common/dockerconfig_test.go
  pkg/controller/common/helpers.go
  pkg/controller/node/node_controller.go
  pkg/controller/template/render.go
  pkg/controller/template/render_test.go
  pkg/controller/template/template_controller.go
  pkg/controller/template/template_controller_test.go
  pkg/daemon/certificate_writer.go
  pkg/daemon/certificate_writer_test.go
  pkg/daemon/daemon.go
  pkg/daemon/on_disk_validation.go
  pkg/daemon/update.go
  pkg/operator/bootstrap.go
  pkg/operator/operator.go
  pkg/operator/render.go
  pkg/operator/render_test.go
  pkg/operator/sync.go
  test/e2e-techpreview/helpers_test.go
  test/e2e-techpreview/onclusterbuild_test.go
  test/e2e/mcd_test.go
  test/helpers/utils.go
Labels: lgtm, approved, qe-approved, jira/severity-important, jira/valid-bug, jira/valid-reference

#4434 OCPBUGS-36178: remove unnecessary e2e test TestControllerConfigStuff
  test/e2e-techpreview/onclusterbuild_test.go
Labels: lgtm, approved, jira/valid-bug, jira/valid-reference

#4421 OCPBUGS-33694: daemon/update: disable systemd unit before overwriting
  pkg/daemon/file_writers.go
  pkg/daemon/update.go
Labels: lgtm, approved, jira/valid-bug, jira/valid-reference

#4429 OCPBUGS-28974, OCPBUGS-21628: daemon: Handle correctly OS Version for 4.1 and 4.2 bootimages
  pkg/daemon/osrelease/osrelease.go
Labels: lgtm, approved, jira/severity-critical, jira/valid-bug, jira/valid-reference

#4363 OCPNODE-2226: Introduce versioning in auto-node-sizing feature
  templates/common/_base/files/kubelet-auto-sizing.yaml
Labels: lgtm, approved, jira/valid-reference

#4430 OCPBUGS-36165, OCPBUGS-36166: CurrentImagePullSecret should be consumed by the MCD
  cmd/machine-config-operator/start.go
  docs/NodeDisruptionPolicy.md
  manifests/machineconfigdaemon/daemonset.yaml
  pkg/apihelpers/apihelpers.go
  pkg/controller/build/build_controller_test.go
  pkg/controller/build/fixtures_test.go
  pkg/controller/build/helpers.go
  pkg/controller/build/helpers_test.go
  pkg/controller/common/dockerconfig.go
  pkg/controller/common/dockerconfig_test.go
  pkg/controller/common/helpers.go
  pkg/controller/node/node_controller.go
  pkg/controller/template/render.go
  pkg/controller/template/render_test.go
  pkg/controller/template/template_controller.go
  pkg/controller/template/template_controller_test.go
  pkg/daemon/certificate_writer.go
  pkg/daemon/certificate_writer_test.go
  pkg/daemon/daemon.go
  pkg/daemon/on_disk_validation.go
  pkg/daemon/update.go
  pkg/operator/bootstrap.go
  pkg/operator/operator.go
  pkg/operator/render.go
  pkg/operator/render_test.go
  pkg/operator/sync.go
  test/e2e-techpreview/helpers_test.go
  test/e2e-techpreview/onclusterbuild_test.go
  test/e2e/mcd_test.go
  test/helpers/utils.go
Labels: lgtm, approved, cherry-pick-approved, backport-risk-assessed, jira/severity-important, jira/valid-bug, jira/valid-reference
