Repository openshift/machine-config-operator, pull requests merged in 2024-09, with the labels that each got.

#4542 [release-4.17] OCPBUGS-38770: SCC-pinning for openshift workloads
  manifests/on-prem/coredns.yaml
  manifests/on-prem/keepalived.yaml
  templates/common/on-prem/files/coredns.yaml
  templates/common/on-prem/files/keepalived.yaml
  templates/master/00-master/on-prem/files/haproxy.yaml
Labels: lgtm, approved, cherry-pick-approved, backport-risk-assessed, jira/valid-bug, jira/valid-reference

#4539 [release-4.16] OCPBUGS-38711: SCC-pinning for openshift workloads
  manifests/on-prem/coredns.yaml
  manifests/on-prem/keepalived.yaml
  templates/common/on-prem/files/coredns.yaml
  templates/common/on-prem/files/keepalived.yaml
  templates/master/00-master/on-prem/files/haproxy.yaml
Labels: lgtm, approved, cherry-pick-approved, backport-risk-assessed, jira/valid-bug, jira/valid-reference

#4545 OCPBUGS-39226: Enable the use of Linux Bridge as the ovs default port connection
  templates/common/_base/files/configure-ovs-network.yaml
Labels: lgtm, approved, jira/valid-bug, jira/valid-reference

#4540 [release-4.15] OCPBUGS-38712: SCC-pinning for openshift workloads
  manifests/on-prem/coredns.yaml
  manifests/on-prem/keepalived.yaml
  templates/common/on-prem/files/coredns.yaml
  templates/common/on-prem/files/keepalived.yaml
  templates/master/00-master/on-prem/files/haproxy.yaml
Labels: lgtm, approved, cherry-pick-approved, backport-risk-assessed, jira/valid-bug, jira/valid-reference

#4553 OCPBUGS-39131: fixes node scaledown for e2e tests
  test/e2e-techpreview/helpers_test.go
  test/e2e-techpreview/onclusterlayering_test.go
  test/e2e/mcd_test.go
  test/helpers/archiveartifact.go
  test/helpers/archiveartifact_test.go
  test/helpers/nodestate.go
  test/helpers/utils.go
Labels: lgtm, approved, qe-approved, jira/severity-moderate, jira/valid-bug, jira/valid-reference

#4548 OCPBUGS-37032: CVE-2024-3727 ose-machine-config-operator-container: containers/image: digest type does not guarantee valid type
  go.mod
  go.sum
  vendor/github.com/containers/image/v5/docker/docker_client.go
  vendor/github.com/containers/image/v5/docker/docker_image.go
  vendor/github.com/containers/image/v5/docker/docker_image_dest.go
  vendor/github.com/containers/image/v5/docker/docker_image_src.go
  vendor/github.com/containers/image/v5/docker/docker_transport.go
  vendor/github.com/containers/image/v5/docker/registries_d.go
  vendor/github.com/containers/image/v5/version/version.go
  vendor/modules.txt
Labels: lgtm, approved, qe-approved, jira/valid-bug, jira/valid-reference, acknowledge-critical-fixes-only

#4559 OCPBUGS-39438: Persist ethtool hw offload setting for br-ex
  templates/common/_base/files/configure-ovs-network.yaml
Labels: lgtm, approved, jira/valid-bug, jira/valid-reference

#4558 OSASINFRA-3560: OpenStack: kubelet-nodename service for IPv6
  templates/common/openstack/files/usr-local-bin-openstack-kubelet-nodename.yaml
  templates/common/openstack/units/openstack-kubelet-nodename.service.yaml
Labels: lgtm, approved, jira/valid-reference

#4494 MCO-1248: port {azure,gcp}-routes.sh from iptables to nftables
  cmd/apiserver-watcher/README.md
  templates/master/00-master/azure/files/opt-libexec-openshift-azure-routes-sh.yaml
  templates/master/00-master/gcp/files/opt-libexec-openshift-gcp-routes-sh.yaml
Labels: lgtm, approved, jira/valid-reference

#4555 OCPBUGS-39222: Do not enable on-prem-resolv-prepender.path for UPI
  templates/common/on-prem/units/on-prem-resolv-prepender.path.yaml
Labels: lgtm, approved, qe-approved, jira/valid-bug, jira/valid-reference

#4552 OCPBUGS-38632: MCPs with RHEL nodes are degraded when a userCA bundle is added to the cluster
  pkg/apihelpers/apihelpers.go
  pkg/daemon/constants/constants.go
  pkg/daemon/update.go
Labels: lgtm, approved, qe-approved, jira/severity-moderate, jira/valid-bug, jira/valid-reference

#4489 OCPBUGS-32812: When newly built images rolled out, the update progress is not displaying correctly (went 0 --> 3)
  pkg/controller/common/layered_node_state.go
  pkg/controller/node/node_controller.go
  pkg/controller/node/node_controller_test.go
  pkg/controller/node/status.go
  pkg/controller/node/status_test.go
Labels: lgtm, approved, qe-approved, jira/valid-bug, jira/valid-reference

#4514 OCPBUGS-38857: Add alert for users of deprecating the Image Registry workaround
  install/0000_90_machine-config_01_prometheus-rules.yaml
  pkg/daemon/constants/constants.go
  pkg/daemon/drain.go
  pkg/daemon/update.go
  pkg/operator/metrics.go
  pkg/operator/operator_test.go
  pkg/operator/status.go
  pkg/operator/status_test.go
Labels: lgtm, approved, qe-approved, jira/valid-bug, jira/valid-reference

#4571 NO-ISSUE: Dockerfile: update to 4.18 image
  Dockerfile
Labels: lgtm, approved, jira/valid-reference

#4574 OCPBUGS-39438: Disable ESP offload in vmxnet3 including bonds
  templates/common/_base/files/configure-ovs-network.yaml
  templates/common/_base/files/vsphere-disable-vmxnet3v4-features.yaml
Labels: lgtm, approved, jira/valid-bug, jira/valid-reference

#4590 OCPBUGS-41956: crio: force runc by default
  templates/master/01-master-container-runtime/_base/files/crio.yaml
  templates/worker/01-worker-container-runtime/_base/files/crio.yaml
Labels: lgtm, approved, jira/valid-bug, jira/valid-reference

#4575 OCPBUGS-41631: Panic seen in CI job for MCC pod
  pkg/controller/node/node_controller.go
Labels: lgtm, approved, qe-approved, jira/valid-bug, jira/valid-reference

#4586 OSASINFRA-3585: openstack: mount config drive when needed
  templates/common/openstack/files/usr-local-bin-openstack-kubelet-nodename.yaml
Labels: lgtm, approved, jira/valid-reference

#4584 [release-4.16] OCPBUGS-41806: When newly built images rolled out, the update progress is not displaying correctly (went 0 --> 3)
  pkg/controller/common/layered_node_state.go
  pkg/controller/node/node_controller.go
  pkg/controller/node/node_controller_test.go
  pkg/controller/node/status.go
  pkg/controller/node/status_test.go
Labels: lgtm, approved, cherry-pick-approved, backport-risk-assessed, jira/valid-bug, jira/valid-reference

#4592 OCPBUGS-39438: Set ESP offloads off in bonds if slaves don't support them
  templates/common/_base/files/bond-esp-offload.yaml
  templates/common/_base/files/vsphere-disable-vmxnet3v4-features.yaml
Labels: lgtm, approved, jira/valid-bug, jira/valid-reference

#4593 OCPBUGS-41920: MCPs report wrong number of nodes when we move nodes from one custom MCP to another custom MCP
  pkg/controller/node/node_controller.go
Labels: lgtm, approved, jira/severity-moderate, jira/valid-bug, jira/valid-reference

#4597 NO-JIRA: move crd management to openshift/api to ease feature promotion
  Makefile
  hack/crds-sync.sh
  install/0000_10_config-operator_01_clusterimagepolicies-CustomNoUpgrade.crd.yaml
  install/0000_10_config-operator_01_clusterimagepolicies-DevPreviewNoUpgrade.crd.yaml
  install/0000_10_config-operator_01_clusterimagepolicies-TechPreviewNoUpgrade.crd.yaml
  install/0000_80_machine-config_01_containerruntimeconfigs.crd.yaml
  install/0000_80_machine-config_01_controllerconfigs-CustomNoUpgrade.crd.yaml
  install/0000_80_machine-config_01_controllerconfigs-Default.crd.yaml
  install/0000_80_machine-config_01_controllerconfigs-DevPreviewNoUpgrade.crd.yaml
  install/0000_80_machine-config_01_controllerconfigs-TechPreviewNoUpgrade.crd.yaml
  install/0000_80_machine-config_01_kubeletconfigs.crd.yaml
  install/0000_80_machine-config_01_machineconfignodes-CustomNoUpgrade.crd.yaml
  install/0000_80_machine-config_01_machineconfignodes-DevPreviewNoUpgrade.crd.yaml
  install/0000_80_machine-config_01_machineconfignodes-TechPreviewNoUpgrade.crd.yaml
  install/0000_80_machine-config_01_machineconfigpools-CustomNoUpgrade.crd.yaml
  install/0000_80_machine-config_01_machineconfigpools-Default.crd.yaml
  install/0000_80_machine-config_01_machineconfigpools-DevPreviewNoUpgrade.crd.yaml
  install/0000_80_machine-config_01_machineconfigpools-TechPreviewNoUpgrade.crd.yaml
  install/0000_80_machine-config_01_machineconfigs.crd.yaml
  install/0000_80_machine-config_01_machineconfigurations.crd.yaml
  install/0000_80_machine-config_01_machineosbuilds-CustomNoUpgrade.crd.yaml
  install/0000_80_machine-config_01_machineosbuilds-DevPreviewNoUpgrade.crd.yaml
  install/0000_80_machine-config_01_machineosbuilds-TechPreviewNoUpgrade.crd.yaml
  install/0000_80_machine-config_01_machineosconfigs-CustomNoUpgrade.crd.yaml
  install/0000_80_machine-config_01_machineosconfigs-DevPreviewNoUpgrade.crd.yaml
  install/0000_80_machine-config_01_machineosconfigs-TechPreviewNoUpgrade.crd.yaml
  install/0000_80_machine-config_01_pinnedimagesets-CustomNoUpgrade.crd.yaml
  install/0000_80_machine-config_01_pinnedimagesets-DevPreviewNoUpgrade.crd.yaml
  install/0000_80_machine-config_01_pinnedimagesets-TechPreviewNoUpgrade.crd.yaml
Labels: lgtm, approved, jira/valid-reference

#4600 MCO-1323: Stop writing root-ca to disk
  templates/common/_base/files/root-ca.yaml
Labels: lgtm, approved, jira/valid-reference

#4589 OCPBUGS-42018: on-prem/resolv-prepender: stop leaking tmp files
  templates/common/on-prem/files/resolv-prepender.yaml
Labels: lgtm, approved, qe-approved, jira/valid-bug, jira/valid-reference

#4604 OCPBUGS-42264: Reconcile API CRD move for bootstrap unit tests
  go.mod
  go.sum
  test/framework/envtest.go
  vendor/github.com/openshift/api/.ci-operator.yaml
  vendor/github.com/openshift/api/Dockerfile.ocp
  vendor/github.com/openshift/api/README.md
  vendor/github.com/openshift/api/authorization/v1/generated.pb.go
  vendor/github.com/openshift/api/authorization/v1/generated.proto
  vendor/github.com/openshift/api/authorization/v1/types.go
  vendor/github.com/openshift/api/authorization/v1/zz_generated.deepcopy.go
  vendor/github.com/openshift/api/authorization/v1/zz_generated.swagger_doc_generated.go
  vendor/github.com/openshift/api/config/v1/types_cluster_version.go
  vendor/github.com/openshift/api/config/v1/zz_generated.crd-manifests/0000_00_cluster-version-operator_01_clusterversions-CustomNoUpgrade.crd.yaml
  vendor/github.com/openshift/api/config/v1/zz_generated.crd-manifests/0000_00_cluster-version-operator_01_clusterversions-Default.crd.yaml
  vendor/github.com/openshift/api/config/v1/zz_generated.crd-manifests/0000_00_cluster-version-operator_01_clusterversions-DevPreviewNoUpgrade.crd.yaml
  vendor/github.com/openshift/api/config/v1/zz_generated.crd-manifests/0000_00_cluster-version-operator_01_clusterversions-TechPreviewNoUpgrade.crd.yaml
  vendor/github.com/openshift/api/features.md
  vendor/github.com/openshift/api/features/features.go
  vendor/github.com/openshift/api/operator/v1/types.go
  vendor/github.com/openshift/api/operator/v1/zz_generated.crd-manifests/0000_10_config-operator_01_configs.crd.yaml
  vendor/github.com/openshift/api/operator/v1/zz_generated.crd-manifests/0000_12_etcd_01_etcds-CustomNoUpgrade.crd.yaml
  vendor/github.com/openshift/api/operator/v1/zz_generated.crd-manifests/0000_12_etcd_01_etcds-Default.crd.yaml
  vendor/github.com/openshift/api/operator/v1/zz_generated.crd-manifests/0000_12_etcd_01_etcds-DevPreviewNoUpgrade.crd.yaml
  vendor/github.com/openshift/api/operator/v1/zz_generated.crd-manifests/0000_12_etcd_01_etcds-TechPreviewNoUpgrade.crd.yaml
  vendor/github.com/openshift/api/operator/v1/zz_generated.crd-manifests/0000_20_kube-apiserver_01_kubeapiservers.crd.yaml
  vendor/github.com/openshift/api/operator/v1/zz_generated.crd-manifests/0000_25_kube-controller-manager_01_kubecontrollermanagers.crd.yaml
  vendor/github.com/openshift/api/operator/v1/zz_generated.crd-manifests/0000_25_kube-scheduler_01_kubeschedulers.crd.yaml
  vendor/github.com/openshift/api/operator/v1/zz_generated.crd-manifests/0000_30_openshift-apiserver_01_openshiftapiservers.crd.yaml
  vendor/github.com/openshift/api/operator/v1/zz_generated.crd-manifests/0000_40_cloud-credential_00_cloudcredentials.crd.yaml
  vendor/github.com/openshift/api/operator/v1/zz_generated.crd-manifests/0000_40_kube-storage-version-migrator_00_kubestorageversionmigrators.crd.yaml
  vendor/github.com/openshift/api/operator/v1/zz_generated.crd-manifests/0000_50_authentication_01_authentications.crd.yaml
  vendor/github.com/openshift/api/operator/v1/zz_generated.crd-manifests/0000_50_console_01_consoles.crd.yaml
  vendor/github.com/openshift/api/operator/v1/zz_generated.crd-manifests/0000_50_insights_00_insightsoperators.crd.yaml
  vendor/github.com/openshift/api/operator/v1/zz_generated.crd-manifests/0000_50_openshift-controller-manager_02_openshiftcontrollermanagers.crd.yaml
  vendor/github.com/openshift/api/operator/v1/zz_generated.crd-manifests/0000_50_service-ca_02_servicecas.crd.yaml
  vendor/github.com/openshift/api/operator/v1/zz_generated.crd-manifests/0000_50_storage_01_storages.crd.yaml
  vendor/github.com/openshift/api/operator/v1/zz_generated.crd-manifests/0000_70_network_01_networks-CustomNoUpgrade.crd.yaml
  vendor/github.com/openshift/api/operator/v1/zz_generated.crd-manifests/0000_70_network_01_networks-Default.crd.yaml
  vendor/github.com/openshift/api/operator/v1/zz_generated.crd-manifests/0000_70_network_01_networks-DevPreviewNoUpgrade.crd.yaml
  vendor/github.com/openshift/api/operator/v1/zz_generated.crd-manifests/0000_70_network_01_networks-TechPreviewNoUpgrade.crd.yaml
  vendor/github.com/openshift/api/operator/v1/zz_generated.crd-manifests/0000_80_csi-snapshot-controller_01_csisnapshotcontrollers.crd.yaml
  vendor/github.com/openshift/api/operator/v1/zz_generated.crd-manifests/0000_90_csi-driver_01_clustercsidrivers.crd.yaml
  vendor/github.com/openshift/api/operator/v1alpha1/zz_generated.crd-manifests/0000_10_operator-lifecycle-manager_01_olms-CustomNoUpgrade.crd.yaml
  vendor/github.com/openshift/api/operator/v1alpha1/zz_generated.crd-manifests/0000_10_operator-lifecycle-manager_01_olms-DevPreviewNoUpgrade.crd.yaml
  vendor/github.com/openshift/api/operator/v1alpha1/zz_generated.crd-manifests/0000_10_operator-lifecycle-manager_01_olms-TechPreviewNoUpgrade.crd.yaml
  vendor/github.com/openshift/api/security/v1/generated.pb.go
  vendor/github.com/openshift/api/security/v1/generated.proto
  vendor/github.com/openshift/api/security/v1/types.go
  vendor/github.com/openshift/api/security/v1/zz_generated.deepcopy.go
  vendor/github.com/openshift/api/security/v1/zz_generated.swagger_doc_generated.go
  vendor/k8s.io/code-generator/generate-groups.sh
  vendor/k8s.io/code-generator/generate-internal-groups.sh
  vendor/modules.txt
Labels: lgtm, approved, jira/severity-low, jira/valid-bug, jira/valid-reference

#4284 MCO-694: revert from layered pool to non-layered pool
  cmd/machine-config-daemon/firstboot_complete_machineconfig.go
  pkg/daemon/daemon.go
  pkg/daemon/runtimeassets/README.md
  pkg/daemon/runtimeassets/machine-config-daemon-revert.service.yaml
  pkg/daemon/runtimeassets/revertservice.go
  pkg/daemon/runtimeassets/revertservice_test.go
  pkg/daemon/runtimeassets/runtimeassets.go
  pkg/daemon/update.go
  test/e2e-techpreview/onclusterlayering_test.go
  test/e2e/osimageurl_override_test.go
  test/helpers/utils.go
Labels: lgtm, approved, jira/valid-reference

#4576 OCPBUGS-36810: When MCOS is deleted in building state configmap resources related to MOSC are not deleted.
  pkg/controller/build/build_controller.go
Labels: lgtm, approved, jira/severity-important, jira/valid-bug, jira/valid-reference

#4596 OCPBUGS-38012: Do not use 'restart' for 'oneshot' service
  templates/common/_base/units/wait-for-primary-ip.yaml
  templates/common/on-prem/units/on-prem-resolv-prepender.service.yaml
Labels: lgtm, approved, jira/severity-important, jira/valid-bug, jira/valid-reference

#4582 OCPNODE-2399: Add a condition in the config node object
  pkg/controller/kubelet-config/helpers.go
  pkg/controller/kubelet-config/kubelet_config_nodes.go
Labels: lgtm, approved, jira/valid-reference

#4606 OCPBUGS-42419: kubelet-service: provide path to restorecon command
  templates/master/01-master-kubelet/_base/units/kubelet.service.yaml
  templates/master/01-master-kubelet/on-prem/units/kubelet.service.yaml
  templates/worker/01-worker-kubelet/_base/units/kubelet.service.yaml
  templates/worker/01-worker-kubelet/on-prem/units/kubelet.service.yaml
Labels: lgtm, approved, jira/valid-bug, jira/valid-reference

#4611 OCPBUGS-42392: openstack: relax openstack-kubelet-nodename systemd dependency
  templates/common/openstack/files/usr-local-bin-openstack-kubelet-nodename.yaml
  templates/common/openstack/units/openstack-kubelet-nodename.service.yaml
Labels: lgtm, approved, jira/valid-bug, jira/valid-reference

#4594 OCPBUGS-38733: Regenerate the rendered MC in use when deleted
  pkg/controller/render/render_controller.go
Labels: lgtm, approved, qe-approved, jira/severity-important, jira/valid-bug, jira/valid-reference

#4608 OCPBUGS-42324: openstack: fix non-old systemd compatible unit
  templates/common/openstack/units/afterburn-hostname.service.yaml
Labels: lgtm, approved, qe-approved, jira/severity-important, jira/valid-bug, jira/valid-reference

#4544 MCO-1283: adds OCL quickstart and troubleshooting guides
  docs/OnClusterBuildInstructions.md
  docs/onclusterlayering-quickstart.md
  docs/onclusterlayering-troubleshooting.md
Labels: lgtm, approved, jira/valid-reference
