Repository openshift/machine-config-operator, pull requests merged in 2024-04, with the labels that each got.

#4299 OCPBUGS-31630: fix: resources were in the wrong indentation level
  templates/master/01-master-kubelet/_base/files/criometricsproxy.yaml
  templates/worker/01-worker-kubelet/_base/files/criometricsproxy.yaml
Labels: lgtm, approved, jira/severity-critical, jira/valid-bug, jira/valid-reference

#4294 OCPBUGS-18955: make sure CO degrades if OCL config is invalid
  pkg/operator/sync.go
Labels: lgtm, approved, qe-approved, jira/severity-moderate, jira/valid-bug, jira/valid-reference

#4016 OCPBUGS-22910: Remove the condition for checking the multiple ovs-if-br-ex profiles
  templates/common/_base/files/configure-ovs-network.yaml
Labels: lgtm, approved, qe-approved, jira/severity-moderate, jira/valid-bug, jira/valid-reference

#4297 [release-4.15]: OCPBUGS-31576: kubelet: restorecon necessary files on kubelet's prestart
  templates/common/_base/units/kubelet-selinux-relabel.yaml
  templates/master/01-master-kubelet/_base/units/kubelet.service.yaml
  templates/master/01-master-kubelet/alibabacloud/units/kubelet.service.yaml
  templates/master/01-master-kubelet/on-prem/units/kubelet.service.yaml
  templates/worker/01-worker-kubelet/_base/units/kubelet.service.yaml
  templates/worker/01-worker-kubelet/alibabacloud/units/kubelet.service.yaml
  templates/worker/01-worker-kubelet/on-prem/units/kubelet.service.yaml
Labels: lgtm, approved, cherry-pick-approved, qe-approved, backport-risk-assessed, jira/severity-important, jira/valid-bug, jira/valid-reference

#4241 OCPBUGS-28577: MCO-1030, MCO-910: Updating MCO base image to RHEL9
  .ci-operator.yaml
  Dockerfile
  Dockerfile.rhel7
  pkg/daemon/daemon.go
Labels: lgtm, approved, qe-approved, jira/valid-bug, jira/valid-reference

#4304 OCPBUGS-30192: Move StartLimitIntervalSec to Unit section
  templates/common/on-prem/units/on-prem-resolv-prepender.service.yaml
Labels: lgtm, approved, jira/severity-important, jira/valid-bug, jira/valid-reference

#4160 OCPNODE-1632: Support Cluster ImagePolicy CRD
  cmd/machine-config-controller/start.go
  docs/ClusterImagePolicyDesign.md
  hack/crds-sync.sh
  install/0000_10_config-operator_01_clusterimagepolicy-TechPreviewNoUpgrade.crd.yaml
  manifests/machineconfigcontroller/clusterrole.yaml
  pkg/apihelpers/apihelpers.go
  pkg/controller/bootstrap/bootstrap.go
  pkg/controller/bootstrap/testdata/bootstrap/featuregate.yaml
  pkg/controller/container-runtime-config/container_runtime_config_bootstrap.go
  pkg/controller/container-runtime-config/container_runtime_config_bootstrap_test.go
  pkg/controller/container-runtime-config/container_runtime_config_controller.go
  pkg/controller/container-runtime-config/container_runtime_config_controller_test.go
  pkg/controller/container-runtime-config/helpers.go
  pkg/controller/container-runtime-config/helpers_test.go
  pkg/daemon/constants/constants.go
  pkg/daemon/update.go
  test/e2e-bootstrap/bootstrap_test.go
Labels: lgtm, approved, jira/valid-reference

#4319 OCPBUGS-28230: enforce termination message policy on all platform pods
  templates/common/cloud-platform-alt-dns/files/coredns.yaml
  templates/common/on-prem/files/coredns.yaml
  templates/common/on-prem/files/keepalived.yaml
  templates/master/00-master/on-prem/files/haproxy.yaml
  templates/master/01-master-kubelet/_base/files/criometricsproxy.yaml
  templates/worker/01-worker-kubelet/_base/files/criometricsproxy.yaml
Labels: lgtm, approved, jira/valid-bug, jira/valid-reference

#4285 MCO-1102: OCPBUGS-32277: Add a ValidatingAdmissionPolicy for the boot images update opt-in API
  go.mod
  go.sum
  hack/crds-sync.sh
  install/0000_10_config-operator_01_clusterimagepolicies-CustomNoUpgrade.crd.yaml
  install/0000_80_machine-config_01_machineconfigurations-CustomNoUpgrade.crd.yaml
  manifests/machineconfigcontroller/update-bootimages-validatingadmissionpolicy.yaml
  manifests/machineconfigcontroller/update-bootimages-validatingadmissionpolicybinding.yaml
  pkg/operator/sync.go
  vendor/github.com/openshift/library-go/pkg/certs/pem.go
  vendor/github.com/openshift/library-go/pkg/config/leaderelection/leaderelection.go
  vendor/github.com/openshift/library-go/pkg/controller/factory/controller_context.go
  vendor/github.com/openshift/library-go/pkg/controller/factory/eventfilters.go
  vendor/github.com/openshift/library-go/pkg/controller/factory/factory.go
  vendor/github.com/openshift/library-go/pkg/crypto/crypto.go
  vendor/github.com/openshift/library-go/pkg/operator/certrotation/client_cert_rotation_controller.go
  vendor/github.com/openshift/library-go/pkg/operator/certrotation/signer.go
  vendor/github.com/openshift/library-go/pkg/operator/certrotation/target.go
  vendor/github.com/openshift/library-go/pkg/operator/configobserver/featuregates/featuregate.go
  vendor/github.com/openshift/library-go/pkg/operator/resource/resourceapply/admissionregistration.go
  vendor/github.com/openshift/library-go/pkg/operator/resource/resourceapply/apiextensions.go
  vendor/github.com/openshift/library-go/pkg/operator/resource/resourceapply/apiregistration.go
  vendor/github.com/openshift/library-go/pkg/operator/resource/resourceapply/apps.go
  vendor/github.com/openshift/library-go/pkg/operator/resource/resourceapply/core.go
  vendor/github.com/openshift/library-go/pkg/operator/resource/resourceapply/generic.go
  vendor/github.com/openshift/library-go/pkg/operator/resource/resourceapply/migration.go
  vendor/github.com/openshift/library-go/pkg/operator/resource/resourceapply/policy.go
  vendor/github.com/openshift/library-go/pkg/operator/resource/resourceapply/rbac.go
  vendor/github.com/openshift/library-go/pkg/operator/resource/resourceapply/storage.go
  vendor/github.com/openshift/library-go/pkg/operator/resource/resourcemerge/apiextensions.go
  vendor/github.com/openshift/library-go/pkg/operator/resource/resourcemerge/object_merger.go
  vendor/github.com/openshift/library-go/pkg/operator/resource/resourceread/admission.go
  vendor/github.com/openshift/library-go/pkg/operator/resourcesynccontroller/interfaces.go
  vendor/github.com/openshift/library-go/pkg/operator/resourcesynccontroller/resourcesync_controller.go
  vendor/github.com/openshift/library-go/pkg/operator/v1helpers/informers.go
  vendor/modules.txt
Labels: lgtm, approved, qe-approved, jira/valid-reference

#4323 OCPBUGS-32278: Fix configure-ip-forwarding.sh
  templates/common/on-prem/files/configure-ip-forwarding.yaml
Labels: lgtm, approved, jira/severity-moderate, jira/valid-bug, jira/valid-reference

#4296 MCO-1117: Make local MCO image builds faster
  Dockerfile
  Dockerfile.rhel7
Labels: lgtm, approved, jira/valid-reference

#4311 OCPBUGS-28545: Delete state files on reboot only
  templates/master/01-master-kubelet/_base/units/kubelet-cleanup.service.yaml
  templates/master/01-master-kubelet/_base/units/kubelet.service.yaml
  templates/master/01-master-kubelet/alibabacloud/units/kubelet.service.yaml
  templates/master/01-master-kubelet/on-prem/units/kubelet.service.yaml
  templates/worker/01-worker-kubelet/_base/units/kubelet-cleanup.service.yaml
  templates/worker/01-worker-kubelet/_base/units/kubelet.service.yaml
  templates/worker/01-worker-kubelet/alibabacloud/units/kubelet.service.yaml
  templates/worker/01-worker-kubelet/on-prem/units/kubelet.service.yaml
Labels: lgtm, approved, cherry-pick-approved, backport-risk-assessed, jira/severity-moderate, jira/valid-bug, jira/valid-reference

#4281 MCO-1029: MCO-678: Implement Boot Image update opt-in API
  cmd/machine-config-controller/start.go
  cmd/machine-config-operator/start.go
  manifests/machineconfigcontroller/clusterrole.yaml
  pkg/controller/common/constants.go
  pkg/controller/machine-set-boot-image/machine_set_boot_image_controller.go
  pkg/operator/operator.go
  pkg/operator/sync.go
  test/e2e-techpreview/msbic_test.go
Labels: lgtm, approved, jira/valid-reference

#4316 OCPBUGS-32138: add cluster fleet evaluation support to mco
  cmd/machine-config-operator/start.go
  pkg/controller/kubelet-config/helpers.go
  pkg/controller/kubelet-config/kubelet_config_controller.go
  pkg/controller/kubelet-config/kubelet_config_controller_test.go
  pkg/controller/kubelet-config/kubelet_config_features_test.go
  pkg/controller/kubelet-config/kubelet_config_nodes_test.go
  pkg/operator/operator.go
  pkg/operator/status.go
  pkg/operator/sync.go
Labels: lgtm, approved, jira/valid-bug, jira/valid-reference

#4267 MCO-1009: MCO-1008: MCO-905: Implement NodeDisruptionPolicy API
  cmd/machine-config-daemon/start.go
  manifests/machineconfigdaemon/clusterrole.yaml
  pkg/apihelpers/apihelpers.go
  pkg/controller/common/helpers.go
  pkg/daemon/constants/constants.go
  pkg/daemon/daemon.go
  pkg/daemon/daemon_test.go
  pkg/daemon/drain.go
  pkg/daemon/update.go
  pkg/daemon/upgrade_monitor_test.go
  pkg/operator/operator.go
  pkg/operator/sync.go
Labels: lgtm, approved, qe-approved, jira/valid-reference

#4163 OCPBUGS-28926: [4.15] crio: update pids limit to be -1
  templates/master/01-master-container-runtime/_base/files/crio.yaml
  templates/worker/01-worker-container-runtime/_base/files/crio.yaml
Labels: lgtm, approved, cherry-pick-approved, qe-approved, backport-risk-assessed, jira/valid-bug, jira/valid-reference

#4337 OCPBUGS-33018: pkg/daemon: Ignore watch failure unless kubelet needs a rebootstrap
  pkg/daemon/daemon.go
Labels: lgtm, approved, jira/severity-critical, jira/valid-bug, jira/valid-reference

#4332 OCPBUGS-32739: MachineConfigurations is only effective with name <cluster>
  manifests/machineconfigcontroller/machineconfiguration-guards-validatingadmissionpolicy.yaml
  manifests/machineconfigcontroller/machineconfiguration-guards-validatingadmissionpolicybinding.yaml
  pkg/operator/sync.go
Labels: lgtm, approved, jira/valid-bug, jira/valid-reference

#4334 OCPBUGS-32922: [release-4.15] add cluster fleet evaluation support to mco
  cmd/machine-config-operator/start.go
  pkg/controller/kubelet-config/helpers.go
  pkg/controller/kubelet-config/kubelet_config_controller.go
  pkg/controller/kubelet-config/kubelet_config_controller_test.go
  pkg/controller/kubelet-config/kubelet_config_features_test.go
  pkg/controller/kubelet-config/kubelet_config_nodes_test.go
  pkg/operator/operator.go
  pkg/operator/status.go
  pkg/operator/sync.go
Labels: lgtm, approved, cherry-pick-approved, backport-risk-assessed, jira/valid-bug, jira/valid-reference

#4092 OCPBUGS-11936: Wait for OpenStack Metadata service
  templates/common/openstack/units/afterburn-hostname.service.yaml
Labels: lgtm, approved, jira/severity-low, jira/valid-bug, jira/valid-reference
