Repository openshift/machine-config-operator, pull requests merged in 2025-08, with the labels that each got.

#5213 TRT-2232: Revert #5148 "OCPBUGS-58023: Prevent unnecessary systemd unit disable"
  pkg/controller/common/helpers.go
  pkg/daemon/on_disk_validation.go
  pkg/daemon/update.go
Labels: lgtm, approved, jira/valid-reference

#5222 OCPBUGS-60119: Invalid architecture value found in annotation during 4.19 update
  pkg/controller/machine-set-boot-image/machine_set_boot_image_controller_test.go
  pkg/controller/machine-set-boot-image/ms_helpers.go
Labels: lgtm, approved, qe-approved, jira/severity-important, jira/valid-bug, jira/valid-reference

#5172 MCO-1810: Support kernelType in OCL
  pkg/controller/build/buildrequest/assets/Containerfile.on-cluster-build-template
  pkg/controller/build/buildrequest/buildrequest.go
  pkg/controller/build/buildrequest/buildrequestopts.go
  pkg/controller/common/helpers.go
  pkg/daemon/update.go
  pkg/helpers/helpers.go
  test/e2e-ocl/helpers_test.go
  test/e2e-ocl/onclusterlayering_test.go
Labels: lgtm, approved, qe-approved, jira/valid-reference

#5215 OCPBUGS-59723: Add mechanism to delete MCN v1alpha1 CRD in 4.16+ clusters
  install/0000_80_machine-config_00_rbac.yaml
  install/0000_80_machine-config_00_v1alpha1-mcn-cleanup-job.yaml
Labels: lgtm, approved, qe-approved, jira/severity-critical, jira/valid-bug, jira/valid-reference

#5238 OCPBUGS-59723: Reintroduce cronjob that deletes MCN v1alpha1 CRD
  install/0000_80_machine-config_00_rbac.yaml
  install/0000_80_machine-config_00_v1alpha1-mcn-cleanup-job.yaml
Labels: lgtm, approved, jira/severity-critical, jira/valid-bug, jira/valid-reference

#5249 OCPBUGS-60559: Update the OnClusterBuild payload tests to reflect the validation rule requiring MCP & MOSC names to match
  test/extended/machineosconfig.go
  test/extended/mco_ocb.go
Labels: lgtm, approved, jira/severity-important, jira/valid-bug, jira/valid-reference

#5256 OCPBUGS-60704: operator: switch out VAP v1beta1 to v1
  go.mod
  go.sum
  manifests/machineconfigcontroller/machineconfiguration-guards-validatingadmissionpolicy.yaml
  manifests/machineconfigcontroller/machineconfiguration-guards-validatingadmissionpolicybinding.yaml
  manifests/machineconfigcontroller/update-bootimages-validatingadmissionpolicy.yaml
  manifests/machineconfigcontroller/update-bootimages-validatingadmissionpolicybinding.yaml
  manifests/machineconfigdaemon/mcn-guards-validatingadmissionpolicy.yaml
  manifests/machineconfigdaemon/mcn-guards-validatingadmissionpolicybinding.yaml
  pkg/operator/sync.go
  vendor/github.com/openshift/library-go/pkg/controller/factory/controller_context.go
  vendor/github.com/openshift/library-go/pkg/operator/certrotation/cabundle.go
  vendor/github.com/openshift/library-go/pkg/operator/certrotation/client_cert_rotation_controller.go
  vendor/github.com/openshift/library-go/pkg/operator/certrotation/signer.go
  vendor/github.com/openshift/library-go/pkg/operator/certrotation/target.go
  vendor/github.com/openshift/library-go/pkg/operator/configobserver/featuregates/featuregate.go
  vendor/github.com/openshift/library-go/pkg/operator/resource/resourceapply/admissionregistration.go
  vendor/github.com/openshift/library-go/pkg/operator/resource/resourceapply/generic.go
  vendor/github.com/openshift/library-go/pkg/operator/resource/resourceread/admission.go
  vendor/modules.txt
Labels: lgtm, approved, backport-risk-assessed, jira/valid-bug, jira/valid-reference

#5258 [release-4.19] OCPBUGS-60767: Update the OnClusterBuild payload tests to reflect the validation rule requiring MCP & MOSC names to match
  test/extended/machineosconfig.go
  test/extended/mco_ocb.go
Labels: lgtm, approved, backport-risk-assessed, jira/severity-important, jira/valid-bug, jira/valid-reference
