Repository openshift/machine-config-operator, pull requests merged in 2025-10, with the labels that each got.

#5305 OCPBUGS-62341: Ensure the node passed to RunCordonOrUncordon comes from the latest updated state
  pkg/controller/drain/drain_controller.go
Labels: lgtm, approved, ok-to-test, qe-approved, jira/severity-important, jira/valid-bug, jira/valid-reference, verified

#5245 OCPBUGS-59968: Cert Controller should live fetch SAN IPs during cert rotation
  cmd/machine-config-controller/start.go
  pkg/controller/certrotation/certrotation_controller.go
  pkg/controller/certrotation/certrotation_controller_test.go
  pkg/controller/certrotation/dynamic_serving.go
  pkg/controller/certrotation/hostnames.go
Labels: lgtm, approved, qe-approved, jira/valid-bug, jira/valid-reference, verified

#5261 MCO-1844: Remove MissingMachineConfig Alert
  install/0000_90_machine-config_01_prometheus-rules.yaml
  pkg/daemon/daemon.go
  pkg/daemon/metrics.go
Labels: lgtm, approved, jira/valid-reference, verified

#5285 OCPEDGE-2188: embed fencing validator into TNF MCO
  templates/master/00-master/two-node-with-fencing/files/fencing-validator.yaml
Labels: lgtm, approved, jira/valid-reference, verified

#5283 [release-4.19] OCPBUGS-61738: Recheck generatedByControllerVersion annotation prior to deleting a degraded MC
  pkg/controller/container-runtime-config/container_runtime_config_controller.go
  pkg/controller/container-runtime-config/container_runtime_config_controller_test.go
  pkg/controller/kubelet-config/kubelet_config_controller.go
  pkg/controller/kubelet-config/kubelet_config_controller_test.go
  pkg/controller/kubelet-config/kubelet_config_features_test.go
Labels: lgtm, approved, cherry-pick-approved, backport-risk-assessed, jira/severity-important, jira/valid-bug, jira/valid-reference, verified, verified-later

#5337 OCPBUGS-62788: Skip rpm-ostree local rebase if no PIS
  pkg/daemon/update.go
Labels: approved, qe-approved, backport-risk-assessed, jira/severity-critical, jira/invalid-bug, jira/valid-reference, verified
