Repository openshift/machine-config-operator, pull requests merged in 2025-04, with the labels that each got.

#4807 OCPBUGS-48675, OCPBUGS-48808, OCPBUGS-46421: Ensure build job is deleted when rebuild is triggered
  pkg/controller/build/buildrequest/builder.go
  pkg/controller/build/buildrequest/interfaces.go
  pkg/controller/build/buildrequest/machineosbuild.go
  pkg/controller/build/constants/constants.go
  pkg/controller/build/fixtures/objects.go
  pkg/controller/build/imagebuilder/base.go
  pkg/controller/build/imagebuilder/cleaner.go
  pkg/controller/build/imagebuilder/jobimagebuilder.go
  pkg/controller/build/imagebuilder/jobimagebuilder_test.go
  pkg/controller/build/imagebuilder/preparer_test.go
  pkg/controller/build/osbuildcontroller_test.go
  pkg/controller/build/reconciler.go
  test/e2e-ocl/helpers_test.go
  test/e2e-ocl/onclusterlayering_test.go
  test/helpers/assertions.go
  test/helpers/utils.go
Labels: lgtm, approved, qe-approved, jira/severity-important, jira/valid-bug, jira/valid-reference

#4922 OCPBUGS-38869: Update desired config in MCN on OCL update
  pkg/daemon/update.go
Labels: lgtm, approved, qe-approved, jira/severity-moderate, jira/valid-bug, jira/valid-reference, acknowledge-critical-fixes-only

#4960 MCO-1627: Get rid of setting mcn.Spec.PinnedImageSets field
  pkg/daemon/pinned_image_set.go
  pkg/upgrademonitor/upgrade_monitor.go
Labels: lgtm, approved, jira/valid-reference

#4957 [release-1.17]OCPBUGS-52188: ignore mc not found error
  pkg/controller/container-runtime-config/container_runtime_config_controller.go
Labels: lgtm, approved, cherry-pick-approved, backport-risk-assessed, jira/valid-bug, jira/valid-reference

#4964 OCPNODE-3020: Remove `cgroupv1` references
  pkg/controller/kubelet-config/helpers.go
  pkg/controller/kubelet-config/kubelet_config_nodes.go
  pkg/controller/kubelet-config/kubelet_config_nodes_test.go
  test/e2e-bootstrap/bootstrap_test.go
Labels: lgtm, approved, jira/valid-reference

#4950 [release-4.14] OCPBUGS-54228: Update ObservedGeneration in KubeletConfig
  pkg/apis/machineconfiguration.openshift.io/v1/helpers.go
  pkg/controller/kubelet-config/kubelet_config_controller.go
  pkg/controller/render/render_controller.go
Labels: lgtm, approved, cherry-pick-approved, backport-risk-assessed, jira/severity-important, jira/valid-bug, jira/valid-reference

#4931 [release-4.16] OCPBUGS-52952: Add ipsec connect wait service
  templates/common/_base/files/wait-for-ipsec-connect.yaml
  templates/common/_base/units/ipsec.service.yaml
  templates/common/_base/units/wait-for-ipsec-connect.yaml
Labels: lgtm, approved, cherry-pick-approved, qe-approved, backport-risk-assessed, jira/severity-moderate, jira/valid-bug, jira/valid-reference

#4959 CORENET-5524: Modify regex for ipsec showstates command
  templates/common/_base/files/wait-for-ipsec-connect.yaml
Labels: lgtm, approved, jira/valid-reference, acknowledge-critical-fixes-only

#4965 OCPBUGS-54570: Drop broken feature which statically configures DHCP addresses
  templates/common/baremetal/files/NetworkManager-static-dhcp.yaml
  templates/common/baremetal/files/NetworkManager-static-dhcpv6.yaml
Labels: lgtm, approved, jira/valid-bug, jira/valid-reference

#4937 [release-4.15] OCPBUGS-36688: Add ipsec connect wait service
  templates/common/_base/files/wait-for-ipsec-connect.yaml
  templates/common/_base/units/ipsec.service.yaml
  templates/common/_base/units/wait-for-ipsec-connect.yaml
Labels: lgtm, approved, cherry-pick-approved, qe-approved, backport-risk-assessed, jira/severity-moderate, jira/valid-bug, jira/valid-reference

#4948 OCPBUGS-52656: Update the MCN PIS status of only the primary pool
  pkg/daemon/pinned_image_set.go
Labels: lgtm, approved, qe-approved, jira/severity-low, jira/valid-bug, jira/valid-reference

#4955 OKD-239: Consolidate OpenStack and PowerVS hostname handling into mco-hostname script
  templates/common/_base/files/usr-local-bin-mco-hostname.yaml
  templates/common/openstack/files/usr-local-bin-openstack-afterburn-hostname.yaml
  templates/common/openstack/units/openstack-hostname.service.yaml
  templates/common/powervs/units/powervs-hostname.service.yaml
Labels: lgtm, approved, cherry-pick-approved, backport-risk-assessed, jira/valid-bug, jira/valid-reference

#4969 OCPBUGS-49737: GCP: Include the gcp-routes.service for all GCP installs
  templates/master/00-master/gcp/units/openshift-gcp-routes.service.yaml
Labels: lgtm, approved, jira/severity-critical, jira/valid-bug, jira/valid-reference

#4976 MCO-1587: Add runbook for ExtremelyHighIndividualControlPlaneMemory
  install/0000_90_machine-config_01_prometheus-rules.yaml
Labels: lgtm, approved, jira/valid-reference

#4933 OCPBUGS-54175: Add /etc/docker/certs.d to template
  templates/common/_base/files/etc-docker-certs.d.yaml
Labels: lgtm, approved, jira/severity-critical, jira/valid-bug, jira/valid-reference

#4857 OCPBUGS-54384: kubelet-service: narrow down restorecon path
  templates/arbiter/01-arbiter-kubelet/_base/units/kubelet.service.yaml
  templates/master/01-master-kubelet/_base/units/kubelet.service.yaml
  templates/master/01-master-kubelet/on-prem/units/kubelet.service.yaml
  templates/worker/01-worker-kubelet/_base/units/kubelet.service.yaml
  templates/worker/01-worker-kubelet/on-prem/units/kubelet.service.yaml
Labels: lgtm, approved, jira/severity-moderate, jira/valid-bug, jira/valid-reference

#4970 OCPBUGS-54611: pkg/operator/status: Drop kubelet skew guard
  pkg/operator/status.go
  pkg/operator/status_test.go
Labels: lgtm, approved, qe-approved, jira/valid-bug, jira/valid-reference

#4932 OCPBUGS-53425: Make mtu-migration run after wait-for-primary-ip
  templates/common/_base/units/mtu-migration.service.yaml
Labels: lgtm, approved, jira/valid-bug, jira/valid-reference

#4924 OCPBUGS-53408: wait for build and ensure OS image is actually new
  pkg/controller/common/mos_state.go
  pkg/controller/node/node_controller.go
  pkg/controller/node/node_controller_test.go
  pkg/controller/node/status.go
  pkg/daemon/update.go
Labels: lgtm, approved, qe-approved, jira/severity-important, jira/valid-bug, jira/valid-reference

#4938 OCPEDGE-1690: add dual-replica templates
  OWNERS_ALIASES
  pkg/controller/template/render.go
  pkg/daemon/daemon.go
  templates/master/00-master/two-node-with-fencing/OWNERS
  templates/master/00-master/two-node-with-fencing/extensions/two-node-ha
  templates/master/00-master/two-node-with-fencing/files/podman-etcd.yaml
  templates/master/00-master/two-node-with-fencing/units/ha-00-directories.service.yaml
  templates/master/00-master/two-node-with-fencing/units/ha-01-enable-services.service.yaml
Labels: lgtm, approved, jira/valid-reference

#4971 MCO-1509: Enable OCL for disconnected workflow
  pkg/controller/build/buildrequest/buildrequest.go
  pkg/controller/build/osbuildcontroller_test.go
  pkg/controller/build/utils/helpers.go
  test/e2e-ocl/onclusterlayering_test.go
Labels: lgtm, approved, jira/valid-reference

#4902 MCO-1584: Opt-in boot image updates for AWS & GCP by default
  pkg/apihelpers/apihelpers.go
  pkg/controller/common/constants.go
  pkg/controller/common/featuregates.go
  pkg/controller/machine-set-boot-image/helpers.go
  pkg/controller/machine-set-boot-image/machine_set_boot_image_controller.go
  pkg/operator/sync.go
  pkg/operator/sync_test.go
  test/e2e/msbic_test.go
Labels: lgtm, approved, qe-approved, jira/valid-reference

#4830 OCPBUGS-48469: Fix CoreDNS static pod bring-up on cloud platforms
  manifests/cloud-platform-alt-dns/coredns.yaml
  pkg/controller/template/render.go
  pkg/controller/template/render_test.go
  pkg/controller/template/test_data/controller_config_gcp_custom_dns.yaml
  pkg/controller/template/test_data/controller_config_gcp_default_dns.yaml
  templates/common/cloud-platform-alt-dns/files/coredns-corefile.yaml
  templates/common/cloud-platform-alt-dns/files/coredns.yaml
Labels: lgtm, approved, qe-approved, jira/severity-critical, jira/valid-bug, jira/valid-reference, acknowledge-critical-fixes-only

#4997 OCPBUGS-55234: kubelet: readonly mounts for criometricsproxy
  templates/arbiter/01-arbiter-kubelet/_base/files/criometricsproxy.yaml
  templates/master/01-master-kubelet/_base/files/criometricsproxy.yaml
  templates/worker/01-worker-kubelet/_base/files/criometricsproxy.yaml
Labels: lgtm, approved, jira/severity-low, jira/valid-bug, jira/valid-reference

#4945 [release-4.18] OCPBUGS-53278: In OCL. Cannot install extensions
  pkg/controller/build/buildrequest/assets/Containerfile.on-cluster-build-template
Labels: lgtm, approved, cherry-pick-approved, backport-risk-assessed, jira/severity-important, jira/valid-bug, jira/valid-reference

#4993 Update cluster operator's status condition message
  pkg/operator/status.go
Labels: lgtm, approved, cherry-pick-approved, backport-risk-assessed, jira/valid-bug, jira/valid-reference

#4986 OCPBUGS-49675, OCPBUGS-55039: In OCL. Usbguard service fails when we install the usbguard extension: IPsec tmpfile.d directives missing when enabling IPsec in OCL
  pkg/controller/build/buildrequest/assets/Containerfile.on-cluster-build-template
Labels: lgtm, approved, qe-approved, jira/severity-moderate, jira/valid-bug, jira/valid-reference

#4995 OCPBUGS-55231: MCO should fall back to us-east-1 for AWS bootimages if no region specific-AMI exists
  pkg/controller/machine-set-boot-image/platform_helpers.go
Labels: lgtm, approved, jira/severity-moderate, jira/valid-bug, jira/valid-reference

#4987 OCPBUGS-55043: Fix PollUntilContextTimeout in syncRenderConfig
  pkg/operator/sync.go
Labels: lgtm, approved, jira/severity-low, jira/valid-bug, jira/valid-reference

#4724 OCPBUGS-44732: Support for br-ex with DHCP and static DNS
  templates/common/_base/files/configure-ovs-network.yaml
Labels: lgtm, approved, jira/valid-bug, jira/valid-reference

#4963 OCPBUGS-51273: Don't crashloop for HAProxy init container
  templates/master/00-master/on-prem/files/haproxy.yaml
Labels: lgtm, approved, jira/severity-important, jira/valid-bug, jira/valid-reference

#4992 MCO-1519: Adapt MCO code to use V1 MCN API
  go.mod
  go.sum
  lib/resourceapply/machineconfig.go
  lib/resourcemerge/machineconfig.go
  lib/resourceread/machineconfig.go
  manifests/machineconfigdaemon/mcn-guards-validatingadmissionpolicy.yaml
  pkg/controller/drain/drain_controller.go
  pkg/controller/node/node_controller_test.go
  pkg/controller/node/status.go
  pkg/controller/node/status_test.go
  pkg/daemon/daemon.go
  pkg/daemon/drain.go
  pkg/daemon/pinned_image_set.go
  pkg/daemon/update.go
  pkg/daemon/upgrade_monitor_test.go
  pkg/operator/operator.go
  pkg/operator/sync.go
  pkg/upgrademonitor/upgrade_monitor.go
  test/e2e-techpreview/mcn_test.go
  vendor/github.com/openshift/api/config/v1/types_infrastructure.go
  vendor/github.com/openshift/api/config/v1/zz_generated.featuregated-crd-manifests.yaml
  vendor/github.com/openshift/api/features.md
  vendor/github.com/openshift/api/features/features.go
  vendor/github.com/openshift/api/machineconfiguration/v1/register.go
  vendor/github.com/openshift/api/machineconfiguration/v1/types_machineconfignode.go
  vendor/github.com/openshift/api/machineconfiguration/v1/zz_generated.crd-manifests/0000_80_machine-config_01_machineconfignodes-CustomNoUpgrade.crd.yaml
  vendor/github.com/openshift/api/machineconfiguration/v1/zz_generated.crd-manifests/0000_80_machine-config_01_machineconfignodes-DevPreviewNoUpgrade.crd.yaml
  vendor/github.com/openshift/api/machineconfiguration/v1/zz_generated.crd-manifests/0000_80_machine-config_01_machineconfignodes-TechPreviewNoUpgrade.crd.yaml
  vendor/github.com/openshift/api/machineconfiguration/v1/zz_generated.deepcopy.go
  vendor/github.com/openshift/api/machineconfiguration/v1/zz_generated.featuregated-crd-manifests.yaml
  vendor/github.com/openshift/api/machineconfiguration/v1/zz_generated.swagger_doc_generated.go
  vendor/github.com/openshift/client-go/machineconfiguration/applyconfigurations/internal/internal.go
  vendor/github.com/openshift/client-go/machineconfiguration/applyconfigurations/machineconfiguration/v1/machineconfignode.go
  vendor/github.com/openshift/client-go/machineconfiguration/applyconfigurations/machineconfiguration/v1/machineconfignodespec.go
  vendor/github.com/openshift/client-go/machineconfiguration/applyconfigurations/machineconfiguration/v1/machineconfignodespecmachineconfigversion.go
  vendor/github.com/openshift/client-go/machineconfiguration/applyconfigurations/machineconfiguration/v1/machineconfignodestatus.go
  vendor/github.com/openshift/client-go/machineconfiguration/applyconfigurations/machineconfiguration/v1/machineconfignodestatusmachineconfigversion.go
  vendor/github.com/openshift/client-go/machineconfiguration/applyconfigurations/machineconfiguration/v1/machineconfignodestatuspinnedimageset.go
  vendor/github.com/openshift/client-go/machineconfiguration/applyconfigurations/machineconfiguration/v1/mcoobjectreference.go
  vendor/github.com/openshift/client-go/machineconfiguration/applyconfigurations/utils.go
  vendor/github.com/openshift/client-go/machineconfiguration/clientset/versioned/typed/machineconfiguration/v1/fake/fake_machineconfignode.go
  vendor/github.com/openshift/client-go/machineconfiguration/clientset/versioned/typed/machineconfiguration/v1/fake/fake_machineconfiguration_client.go
  vendor/github.com/openshift/client-go/machineconfiguration/clientset/versioned/typed/machineconfiguration/v1/generated_expansion.go
  vendor/github.com/openshift/client-go/machineconfiguration/clientset/versioned/typed/machineconfiguration/v1/machineconfignode.go
  vendor/github.com/openshift/client-go/machineconfiguration/clientset/versioned/typed/machineconfiguration/v1/machineconfiguration_client.go
  vendor/github.com/openshift/client-go/machineconfiguration/informers/externalversions/generic.go
  vendor/github.com/openshift/client-go/machineconfiguration/informers/externalversions/machineconfiguration/v1/interface.go
  vendor/github.com/openshift/client-go/machineconfiguration/informers/externalversions/machineconfiguration/v1/machineconfignode.go
  vendor/github.com/openshift/client-go/machineconfiguration/listers/machineconfiguration/v1/expansion_generated.go
  vendor/github.com/openshift/client-go/machineconfiguration/listers/machineconfiguration/v1/machineconfignode.go
  vendor/modules.txt
Labels: lgtm, approved, jira/valid-reference

#5009 OCPBUGS-55388: MSBIC should not update windows machinesets
  pkg/controller/machine-set-boot-image/machine_set_boot_image_controller.go
Labels: lgtm, approved, jira/severity-important, jira/valid-bug, jira/valid-reference

#5005 MCO-1635: Add new runbook for HighOverallControlPlaneMemory to alert
  install/0000_90_machine-config_01_prometheus-rules.yaml
Labels: lgtm, approved, jira/valid-reference

#5003 NO-ISSUE: debug podman on PIS
  pkg/daemon/pinned_image_set.go
Labels: lgtm, approved, jira/valid-reference

#5010 OCPBUGS-44757: decrease leases for kubelet on azure
  templates/master/01-master-kubelet/azure/files/kubelet.yaml
  templates/worker/01-worker-kubelet/azure/files/kubelet.yaml
Labels: lgtm, approved, jira/valid-bug, jira/valid-reference

#5013 Revert "NO-ISSUE: debug podman on PIS"
  pkg/daemon/pinned_image_set.go
Labels: lgtm, approved, jira/valid-reference, acknowledge-critical-fixes-only
