Repository openshift/machine-config-operator, pull requests merged in 2025-06, with the labels that each got.

#5068 [release-4.18] OCPBUGS-56585: scope MCD node listers to current node
  cmd/machine-config-daemon/start.go
  pkg/controller/common/controller_context.go
  pkg/daemon/writer.go
Labels: lgtm, approved, cherry-pick-approved, backport-risk-assessed, jira/valid-bug, jira/valid-reference

#4966 OCPBUGS-45459: Remove trailing period from hostnames
  templates/common/_base/files/usr-local-bin-mco-hostname.yaml
Labels: lgtm, approved, jira/severity-moderate, jira/valid-bug, jira/valid-reference

#5116 NO-ISSUE: Add Jetbrains IDEs files to .gitignore
  .gitignore
Labels: lgtm, approved, jira/valid-reference

#5112 OCPBUGS-56555: openvswitch3.5-ipsec package not included with ipsec os extension
  pkg/daemon/constants/constants.go
  pkg/daemon/update.go
  pkg/daemon/update_test.go
Labels: lgtm, approved, qe-approved, jira/valid-bug, jira/valid-reference

#5100 OCPBUGS-56220: Ensure the build controller restarts on upgrade
  lib/resourcemerge/core.go
  pkg/operator/sync.go
Labels: lgtm, approved, jira/severity-important, jira/valid-bug, jira/valid-reference

#5106 OCPBUGS-57072: configure-ovs: don't escape `:` in nmcli output
  templates/common/_base/files/configure-ovs-network.yaml
Labels: lgtm, approved, jira/severity-critical, jira/valid-bug, jira/valid-reference

#5093 MCO-1282: Remove all code related to the Image Registry workaround Config Map
  install/0000_90_machine-config_01_prometheus-rules.yaml
  pkg/daemon/constants/constants.go
  pkg/daemon/daemon.go
  pkg/daemon/drain.go
  pkg/daemon/drain_test.go
  pkg/daemon/update.go
  pkg/operator/metrics.go
  pkg/operator/status.go
Labels: lgtm, approved, jira/valid-reference

#5147 OCPBUGS-58180: Add control-plane label for master nodes on legacy clusters
  pkg/controller/node/node_controller.go
Labels: lgtm, approved, jira/valid-bug, jira/valid-reference

#5138 [release-4.18] OCPBUGS-58044: Boot image controller should correctly handle marketplace boot images
  pkg/controller/machine-set-boot-image/ami.go
  pkg/controller/machine-set-boot-image/platform_helpers.go
Labels: lgtm, approved, cherry-pick-approved, backport-risk-assessed, jira/severity-critical, jira/valid-bug, jira/valid-reference

#4972 MCO-1624: Make MCN e2e tests blocking
  test/e2e/mcn_test.go
Labels: lgtm, approved, jira/valid-reference

#5146 OCPBUGS-57702: Update images to be consistent with ART
  .ci-operator.yaml
  Dockerfile
  Dockerfile.rhel7
Labels: lgtm, approved, jira/valid-bug, jira/valid-reference
