Repository openshift/machine-config-operator, pull requests merged in 2025-05, with the labels that each got.

#4978 OCPBUGS-54765: [release-4.18] kubelet-service: narrow down restorecon path
  templates/master/01-master-kubelet/_base/units/kubelet.service.yaml
  templates/master/01-master-kubelet/on-prem/units/kubelet.service.yaml
  templates/worker/01-worker-kubelet/_base/units/kubelet.service.yaml
  templates/worker/01-worker-kubelet/on-prem/units/kubelet.service.yaml
Labels: lgtm, approved, cherry-pick-approved, backport-risk-assessed, jira/severity-moderate, jira/valid-bug, jira/valid-reference

#5019 OCPBUGS-41485: Update MCD Log Output to Clarify No Configuration Change
  pkg/daemon/daemon.go
Labels: lgtm, approved, qe-approved, jira/severity-moderate, jira/valid-bug, jira/valid-reference, acknowledge-critical-fixes-only

#5030 OCPBUGS-55713: Revert "OCPBUGS-44757: decrease leases for kubelet on azure"
  templates/master/01-master-kubelet/azure/files/kubelet.yaml
  templates/worker/01-worker-kubelet/azure/files/kubelet.yaml
Labels: lgtm, approved, jira/valid-bug, jira/valid-reference, acknowledge-critical-fixes-only

#5017 OCPBUGS-55262: Use auto=start only for IPsec out connections
  templates/common/_base/files/wait-for-ipsec-connect.yaml
Labels: lgtm, approved, jira/severity-important, jira/valid-bug, jira/valid-reference, acknowledge-critical-fixes-only

#4956 OCPBUGS-53427: pkg/operator/status: Drop kubelet skew guard, add RHEL guard
  pkg/operator/status.go
  pkg/operator/status_test.go
Labels: lgtm, approved, cherry-pick-approved, backport-risk-assessed, jira/valid-bug, jira/valid-reference

#5023 OCPBUGS-55450: Only populate `Status.PinnedImageSets.CurrentGeneration` on valid generation value
  pkg/upgrademonitor/upgrade_monitor.go
Labels: lgtm, approved, qe-approved, jira/severity-important, jira/valid-bug, jira/valid-reference

#5024 OCPBUGS-55597: OWNERS: update owners file with current MCO team members
  OWNERS
Labels: lgtm, approved, jira/severity-low, jira/valid-bug, jira/valid-reference

#5016 OCPNODE-3173: Disable OCI artifact mount by default.
  templates/master/01-master-container-runtime/_base/files/crio.yaml
  templates/worker/01-worker-container-runtime/_base/files/crio.yaml
Labels: lgtm, approved, jira/valid-reference

#5033 OCPBUGS-54697: error from generateAndValidateRenderedMachineConfig function can be misleading
  pkg/controller/render/render_controller.go
Labels: lgtm, approved, qe-approved, jira/valid-bug, jira/valid-reference

#4841 OCPBUGS-49728: Adapt MCC to use LayeredNodeState and remove LayeredPoolState
  pkg/controller/common/layered_node_state.go
  pkg/controller/common/layered_node_state_test.go
  pkg/controller/common/layered_pool_state.go
  pkg/controller/common/layered_pool_state_test.go
  pkg/controller/node/node_controller.go
  pkg/controller/node/node_controller_test.go
  pkg/controller/node/status.go
  pkg/controller/node/status_test.go
  test/helpers/machineosbuildbuilder.go
  test/helpers/poolbuilder.go
Labels: lgtm, approved, jira/severity-moderate, jira/valid-bug, jira/valid-reference

#5042 MCO-1654: Add new runbook for KubeletHealthState to alert
  install/0000_90_machine-config_01_prometheus-rules.yaml
Labels: lgtm, approved, jira/valid-reference

#5041 OCPBUGS-55770: Compare the osImageURLs for OS validation check
  pkg/controller/render/render_controller.go
  pkg/daemon/daemon.go
Labels: lgtm, approved, jira/valid-bug, jira/valid-reference

#5015 OCPBUGS-55439: scope MCD node listers to current node
  cmd/machine-config-daemon/start.go
  pkg/controller/common/controller_context.go
  pkg/daemon/writer.go
Labels: lgtm, approved, jira/valid-bug, jira/valid-reference

#5037 OCPBUGS-55967: Add hot loop detection in the boot image controller
  pkg/controller/machine-set-boot-image/machine_set_boot_image_controller.go
  pkg/controller/machine-set-boot-image/machine_set_boot_image_controller_test.go
Labels: lgtm, approved, qe-approved, jira/valid-bug, jira/valid-reference

#5044 [release-4.19] OCPBUGS-56119: error from generateAndValidateRenderedMachineConfig function can be misleading
  pkg/controller/render/render_controller.go
Labels: lgtm, approved, cherry-pick-approved, backport-risk-assessed, jira/valid-bug, jira/valid-reference

#5054 OCPBUGS-53390: Fix interrupt state to account for failure correctly
  pkg/controller/build/imagebuilder/jobimagebuilder.go
Labels: lgtm, approved, jira/severity-moderate, jira/valid-bug, jira/valid-reference

#5051 OCPBUGS-56211: Boot Image Controller should not degrade when golden configmap is slow to update
  pkg/controller/machine-set-boot-image/machine_set_boot_image_controller.go
Labels: lgtm, approved, jira/severity-low, jira/valid-bug, jira/valid-reference

#5056 NO-JIRA: operator: use component annotation for ownership
  pkg/operator/sync.go
Labels: lgtm, approved, jira/valid-reference

#5052 [release-4.18] OCPBUGS-56217: Compare the osImageURLs for OS validation check
  pkg/controller/render/render_controller.go
  pkg/daemon/daemon.go
Labels: lgtm, approved, cherry-pick-approved, backport-risk-assessed, jira/valid-bug, jira/valid-reference

#5027 OCPBUGS-55638: OCPBUGS-55637: Add admin_acks handling in the MCO
  cmd/machine-config-operator/start.go
  pkg/apihelpers/apihelpers.go
  pkg/operator/admin_ack.go
  pkg/operator/admin_ack_test.go
  pkg/operator/operator.go
  pkg/operator/operator_test.go
  pkg/operator/status_test.go
  pkg/operator/sync.go
Labels: lgtm, approved, cherry-pick-approved, qe-approved, backport-risk-assessed, jira/valid-bug, jira/valid-reference

#5032 OCPBUGS-55681: Give keepalived container chroot cap
  templates/common/on-prem/files/keepalived.yaml
Labels: lgtm, approved, jira/valid-bug, jira/valid-reference

#5067 OCPBUGS-56446: daemon: fix ostree-finalize-staged race workaround for package mode RHEL workers
  pkg/daemon/daemon.go
  pkg/daemon/update.go
Labels: lgtm, approved, qe-approved, jira/valid-bug, jira/valid-reference

#4973 OCPBUGS-36859: Support NODEIP_HINT in IPI deployments too
  templates/common/on-prem/units/nodeip-configuration.service.yaml
Labels: lgtm, approved, jira/valid-bug, jira/valid-reference

#5066 NO-JIRA: OWNERS: Update team osasinfra
  OWNERS_ALIASES
Labels: lgtm, approved, jira/valid-reference

#4733 OCPBUGS-45621: Fix `dynamic-system-reserved-calc.sh` when only `true` parameter is used
  templates/common/_base/files/kubelet-auto-sizing.yaml
Labels: lgtm, approved, jira/severity-moderate, jira/valid-bug, jira/valid-reference

#5084 OCPBUGS-55830: Only update boot disks during GCP boot image updates
  pkg/controller/machine-set-boot-image/platform_helpers.go
  test/e2e/msbic_test.go
Labels: lgtm, approved, jira/severity-important, jira/valid-bug, jira/valid-reference

#5099 [release-4.20] OCPBUGS-56744: Fix typo in MCN's `MachineConfigNodePinnedImageSetsDegraded` message
  pkg/daemon/pinned_image_set.go
Labels: lgtm, approved, jira/severity-low, jira/valid-bug, jira/valid-reference
