Repository openshift/machine-config-operator, pull requests merged in 2025-09, with the labels that each got.

#5259 OCPBUGS-56558: Recheck `generatedByControllerVersion` annotation prior to deleting a degraded MC
  pkg/controller/container-runtime-config/container_runtime_config_controller.go
  pkg/controller/container-runtime-config/container_runtime_config_controller_test.go
  pkg/controller/kubelet-config/kubelet_config_controller.go
  pkg/controller/kubelet-config/kubelet_config_controller_test.go
  pkg/controller/kubelet-config/kubelet_config_features_test.go
Labels: lgtm, approved, jira/severity-important, jira/valid-bug, jira/valid-reference, acknowledge-critical-fixes-only, verified, verified-later

#5276 OCPBUGS-60537: Machine-config controller should actively manage cordon while draining
  pkg/controller/drain/drain_controller.go
  pkg/controller/drain/drain_controller_test.go
Labels: lgtm, approved, jira/valid-bug, jira/valid-reference, verified, verified-later

#5284 OCPBUGS-61695: Override NMState service definition
  templates/common/_base/units/nmstate.service.yaml
Labels: lgtm, approved, jira/severity-important, jira/valid-bug, jira/valid-reference, verified

#5239 NO-ISSUE: Add delays to reduce TestOSBuildController failures
  pkg/controller/build/osbuildcontroller_test.go
Labels: lgtm, approved, jira/valid-reference, verified

#5234 MCO-1840: Remove MCN CRD cleanup cronjob
  install/0000_80_machine-config_00_v1alpha1-mcn-cleanup-job.yaml
  install/0000_90_machine-config_90_deletion.yaml
Labels: lgtm, approved, qe-approved, jira/valid-reference, verified

#5257 MCO-1673: Add Component Readiness tests for Azure boot image updates
  test/extended/boot_image.go
  test/extended/boot_image_update_agnostic.go
  test/extended/boot_image_update_azure.go
  test/extended/const.go
  test/extended/node.go
  test/extended/resource.go
  test/extended/testdata/files/machineconfigurations/managedbootimages-all.yaml
  test/extended/testdata/files/machineconfigurations/managedbootimages-empty.yaml
  test/extended/testdata/files/machineconfigurations/managedbootimages-none.yaml
  test/extended/testdata/files/machineconfigurations/managedbootimages-partial.yaml
  test/extended/util/template.go
Labels: lgtm, approved, jira/valid-reference, verified

#5123 OCPBUGS-42303: Networking: reset ovn-remote config and allow ovnkube controller to s…
  templates/common/_base/files/configure-ovs-network.yaml
Labels: lgtm, approved, jira/severity-important, jira/valid-bug, jira/valid-reference, verified
