Repository openshift/machine-config-operator, pull requests merged in 2025-03, with the labels that each got.

#4861 OCPBUGS-44602: Set ownerReference for OCL build objects
  pkg/controller/build/buildrequest/buildrequest.go
  pkg/controller/build/imagebuilder/jobimagebuilder.go
  pkg/controller/build/reconciler.go
Labels: lgtm, approved, qe-approved, jira/severity-moderate, jira/valid-bug, jira/valid-reference

#4767 OPNET-629: Mark haproxy unhealthy if no healthy backends
  templates/master/00-master/on-prem/files/haproxy-haproxy.yaml
Labels: lgtm, approved, jira/valid-reference

#4889 [release-4.17] OCPBUGS-52257: configure-ovs workaround for ovs-if-br-ex bug
  templates/common/_base/files/configure-ovs-network.yaml
Labels: lgtm, approved, cherry-pick-approved, qe-approved, backport-risk-assessed, jira/severity-important, jira/valid-bug, jira/valid-reference

#4825 OCPBUGS-43896: add revert logic to OCL path in MCD
  pkg/daemon/daemon.go
  pkg/daemon/update.go
Labels: lgtm, approved, qe-approved, jira/severity-moderate, jira/valid-bug, jira/valid-reference

#4895 MCO-1537: Add MCDRebootError runbook to prometheus rules
  install/0000_90_machine-config_01_prometheus-rules.yaml
Labels: lgtm, approved, jira/valid-reference

#4859 [release 4.18] OCPBUGS-50954: In OCL, MCPs are reporting Updating=false while the image is being built
  pkg/controller/node/status.go
Labels: lgtm, approved, cherry-pick-approved, qe-approved, backport-risk-assessed, jira/severity-moderate, jira/valid-bug, jira/valid-reference

#4885 MCO-1485: MCO:1486: MCO-1324: Attempt stub Ignition upgrade
  pkg/controller/certrotation/certrotation_controller.go
  pkg/controller/certrotation/helpers.go
  pkg/controller/common/constants.go
  pkg/controller/machine-set-boot-image/helpers.go
  pkg/controller/machine-set-boot-image/machine_set_boot_image_controller.go
  pkg/controller/machine-set-boot-image/platform_helpers.go
  test/e2e/msbic_test.go
Labels: lgtm, approved, qe-approved, jira/valid-reference

#4866 RHEL-79554: Consolidate OpenStack and PowerVS hostname handling into mco-hostname script
  templates/common/_base/files/usr-local-bin-mco-hostname.yaml
  templates/common/openstack/files/usr-local-bin-openstack-afterburn-hostname.yaml
  templates/common/openstack/units/openstack-hostname.service.yaml
  templates/common/powervs/units/powervs-hostname.service.yaml
Labels: lgtm, approved, jira/valid-reference

#4900 OCPBUGS-52213: Update ObservedGeneration in KubeletConfig
  pkg/apihelpers/apihelpers.go
  pkg/controller/kubelet-config/kubelet_config_controller.go
  pkg/controller/render/render_controller.go
Labels: lgtm, approved, qe-approved, jira/severity-important, jira/valid-bug, jira/valid-reference

#4609 OCPBUGS-44185: Race in configure-ovs.sh affects bonding interface configuration.
  templates/common/_base/files/configure-ovs-network.yaml
Labels: lgtm, approved, ok-to-test, jira/valid-bug, jira/valid-reference

#4907 OCPBUGS-51150: daemon: ensure ostree-finalize-staged is started before rebooting
  pkg/daemon/daemon.go
Labels: lgtm, approved, qe-approved, jira/severity-critical, jira/valid-bug, jira/valid-reference

#4912 OCPBUGS-53085: Add scc label to arbitor crio-metrics-proxy
  templates/arbiter/01-arbiter-kubelet/_base/files/criometricsproxy.yaml
Labels: lgtm, approved, jira/severity-moderate, jira/valid-bug, jira/valid-reference

#4901 [release-4.16] OCPBUGS-52421: Update format verbs for alert logs
  pkg/daemon/daemon.go
  pkg/daemon/update.go
  pkg/daemon/writer.go
  pkg/server/api.go
Labels: lgtm, approved, cherry-pick-approved, backport-risk-assessed, jira/valid-bug, jira/valid-reference

#4876 MCO-1501: Add support for custom MCPs in MCN
  cmd/machine-config-controller/start.go
  cmd/machine-config-daemon/start.go
  pkg/controller/drain/drain_controller.go
  pkg/daemon/daemon.go
  pkg/daemon/daemon_test.go
  pkg/daemon/drain.go
  pkg/daemon/pinned_image_set.go
  pkg/daemon/update.go
  pkg/daemon/upgrade_monitor_test.go
  pkg/helpers/helpers.go
  pkg/operator/sync.go
  pkg/upgrademonitor/upgrade_monitor.go
  test/e2e-techpreview/mcn_test.go
Labels: lgtm, approved, qe-approved, jira/valid-reference

#4915 "NO-ISSUE: ensure that client configs are not mutable"
  test/framework/clientset.go
Labels: lgtm, approved, jira/valid-reference

#4822 OCPNODE-2842: Set Upgradeable=False when cluster is on cgroup v1
  pkg/operator/operator_test.go
  pkg/operator/status.go
  pkg/operator/status_test.go
Labels: lgtm, approved, jira/valid-reference

#4854 OCPBUGS-52280, SDN-5330: Add ipsec connect wait service
  templates/common/_base/files/wait-for-ipsec-connect.yaml
  templates/common/_base/units/ipsec.service.yaml
  templates/common/_base/units/wait-for-ipsec-connect.yaml
Labels: lgtm, approved, jira/severity-moderate, jira/valid-bug, jira/valid-reference

#4870 OCPBUGS-51130: In OCL. Cannot install extensions
  pkg/controller/build/buildrequest/assets/Containerfile.on-cluster-build-template
Labels: lgtm, approved, qe-approved, jira/severity-important, jira/valid-bug, jira/valid-reference

#4914 OCPBUGS-52827: Fixing typos for MachineConfigNode
  pkg/daemon/update.go
  pkg/upgrademonitor/upgrade_monitor.go
Labels: lgtm, approved, ok-to-test, qe-approved, jira/valid-bug, jira/valid-reference

#4921 OCPNODE-2276: Set `Upgradeable=False` when cluster is on cgroup `v1`
  pkg/operator/operator_test.go
  pkg/operator/status.go
  pkg/operator/status_test.go
Labels: lgtm, approved, cherry-pick-approved, backport-risk-assessed, jira/valid-bug, jira/valid-reference

#4926 [release-4.18] OCPBUGS-52949: Add ipsec connect wait service
  templates/common/_base/files/wait-for-ipsec-connect.yaml
  templates/common/_base/units/ipsec.service.yaml
  templates/common/_base/units/wait-for-ipsec-connect.yaml
Labels: lgtm, approved, cherry-pick-approved, qe-approved, backport-risk-assessed, jira/severity-moderate, jira/valid-bug, jira/valid-reference, acknowledge-critical-fixes-only

#4869 OCPBUGS-51132: [release-4.18] /etc/crio/crio.conf.d/00-default should contain runtime_root for runc
  templates/master/01-master-container-runtime/_base/files/crio.yaml
  templates/worker/01-worker-container-runtime/_base/files/crio.yaml
Labels: lgtm, approved, cherry-pick-approved, backport-risk-assessed, jira/severity-moderate, jira/valid-bug, jira/valid-reference

#4949 NO-ISSUE: MCN changes for API validation
  pkg/helpers/helpers.go
  pkg/upgrademonitor/upgrade_monitor.go
Labels: lgtm, approved, jira/valid-reference, acknowledge-critical-fixes-only

#4941 OCPBUGS-54161: use the same success criteria for OCL e2e tests
  pkg/controller/build/buildrequest/buildrequest.go
  pkg/controller/build/constants/constants.go
  pkg/controller/build/imagebuilder/jobimagebuilder.go
  pkg/controller/build/imagebuilder/jobimagebuilder_test.go
  test/e2e-ocl/onclusterlayering_test.go
Labels: lgtm, approved, jira/valid-bug, jira/valid-reference, acknowledge-critical-fixes-only

#4930 [release-4.17] OCPBUGS-52951: Add ipsec connect wait service
  templates/common/_base/files/wait-for-ipsec-connect.yaml
  templates/common/_base/units/ipsec.service.yaml
  templates/common/_base/units/wait-for-ipsec-connect.yaml
Labels: lgtm, approved, cherry-pick-approved, qe-approved, backport-risk-assessed, jira/severity-moderate, jira/valid-bug, jira/valid-reference
