Repository openshift/machine-config-operator, pull requests merged in 2025-02, with the labels that each got.

#4821 OCPEDGE-1585: Revert "OCPEDGE-1419 Add ksan-storage extension"
  docs/MachineConfig.md
  pkg/controller/common/helpers.go
  test/e2e-single-node/sno_mcd_test.go
  test/e2e/mcd_test.go
Labels: lgtm, approved, jira/valid-reference, acknowledge-critical-fixes-only

#4828 OCPBUGS-49731: Correct MachineConfig documentation on sysstat extension support
  docs/MachineConfig.md
Labels: lgtm, approved, jira/severity-low, jira/valid-bug, jira/valid-reference, acknowledge-critical-fixes-only

#4817 OCPBUGS-43552: maxUnavailable value is not honored when disabling OCL
  pkg/controller/node/node_controller.go
  pkg/controller/node/status.go
Labels: lgtm, approved, qe-approved, jira/severity-important, jira/valid-bug, jira/valid-reference, acknowledge-critical-fixes-only

#4832 MCO-1492: Add new runbook for SystemMemoryExceedsReservation to alert
  install/0000_90_machine-config_01_prometheus-rules.yaml
Labels: lgtm, approved, jira/valid-reference, acknowledge-critical-fixes-only

#4838 OCPBUGS-50002: MCC complains about v1 MachineOSConfig in default featureset
  Makefile
  cmd/machine-config-controller/start.go
  pkg/controller/common/controller_context.go
Labels: lgtm, approved, jira/valid-bug, jira/valid-reference, acknowledge-critical-fixes-only

#4839 OCPBUGS-31778: Update format verbs for alert logs
  pkg/daemon/update.go
  pkg/daemon/writer.go
Labels: lgtm, approved, jira/valid-bug, jira/valid-reference, acknowledge-critical-fixes-only

#4846 NO-ISSUE: Add isabella-janssen to OWNERS as approver & reviewer
  OWNERS
Labels: lgtm, approved, jira/valid-reference, acknowledge-critical-fixes-only

#4834 OCPBUGS-49959: Panic in the MCC when using OCL v1 GA
  pkg/controller/machine-set-boot-image/machine_set_boot_image_controller.go
Labels: lgtm, approved, qe-approved, jira/severity-critical, jira/valid-bug, jira/valid-reference, acknowledge-critical-fixes-only

#4824 [release-4.17] OCPBUGS-49363: Auto-recover from MC with invalid extension
  pkg/controller/common/helpers.go
  pkg/controller/common/helpers_test.go
  pkg/daemon/daemon.go
  pkg/daemon/update.go
Labels: lgtm, approved, cherry-pick-approved, backport-risk-assessed, jira/valid-bug, jira/valid-reference

#4710 OCPBUGS-44618: In OCL, MCPs are reporting Updating=false while the image is being built
  pkg/controller/node/status.go
Labels: lgtm, approved, qe-approved, jira/severity-moderate, jira/valid-bug, jira/valid-reference, acknowledge-critical-fixes-only

#4814 OCPBUGS-33894: Avoid dumping Go struct in potentially user-facing reason annotation
  internal/kubeutils.go
Labels: lgtm, approved, jira/severity-moderate, jira/valid-bug, jira/valid-reference, acknowledge-critical-fixes-only

#4810 OCPBUGS-49347: Degraded machine-config CO due to ManagedBootImages update when upgrading an OCL cluster
  pkg/operator/sync.go
Labels: lgtm, approved, qe-approved, jira/severity-moderate, jira/valid-bug, jira/valid-reference, acknowledge-critical-fixes-only

#4844 OCPBUGS-50599: Enforce VIPs to be collocated at the same host
  templates/master/00-master/on-prem/files/keepalived-keepalived.yaml
  templates/worker/00-worker/on-prem/files/keepalived-keepalived.yaml
Labels: lgtm, approved, jira/severity-important, jira/valid-bug, jira/valid-reference, acknowledge-critical-fixes-only

#4863 OCPBUGS-49394: Fix SELinux failures running afterburn-hostname
  templates/common/openstack/files/usr-local-bin-openstack-afterburn-hostname.yaml
  templates/common/openstack/units/afterburn-hostname.service.yaml
Labels: lgtm, approved, jira/valid-bug, jira/valid-reference, acknowledge-critical-fixes-only

#4778 OCPBUGS-45459: Remove trailing period from Openstack provided hostnames
  templates/common/openstack/files/usr-local-bin-openstack-kubelet-nodename.yaml
Labels: lgtm, approved, jira/severity-moderate, jira/valid-bug, jira/valid-reference

#4823 OCPBUGS-47743: Update cluster-reader ClusterRole permissions
  install/0000_80_machine-config_00_clusterreader_clusterrole.yaml
Labels: lgtm, approved, qe-approved, jira/severity-important, jira/valid-bug, jira/valid-reference

#4864 OCPBUGS-51009: OSUpdateStarted event should only be emitted on actual OS updates
  pkg/daemon/update.go
Labels: lgtm, approved, qe-approved, jira/severity-moderate, jira/valid-bug, jira/valid-reference, acknowledge-critical-fixes-only

#4873 NO-ISSUE: increase WaitForPoolComplete() timeout
  test/helpers/utils.go
Labels: lgtm, approved, jira/valid-reference

#4856 OCPBUGS-50849: add RHEL variant to IsEL() check
  pkg/daemon/osrelease/osrelease.go
  pkg/daemon/update.go
Labels: lgtm, approved, jira/severity-critical, jira/valid-bug, jira/valid-reference, acknowledge-critical-fixes-only

#4843 OCPEDGE-1493: Add 2no-ha extension support required by Two Node OpenShift
  docs/MachineConfig.md
  pkg/controller/common/helpers.go
  pkg/controller/common/helpers_test.go
  test/e2e-single-node/sno_mcd_test.go
  test/e2e/mcd_test.go
Labels: lgtm, approved, ok-to-test, jira/valid-reference

#4868 No-Issue: Remove OCL Extensions test
  test/e2e-ocl/onclusterlayering_test.go
Labels: lgtm, approved, jira/valid-reference

#4811 OCPBUGS-48810: Ensure that build jobs are always reconciled
  pkg/apihelpers/machineosbuild.go
  pkg/controller/build/helpers.go
  pkg/controller/build/helpers_test.go
  pkg/controller/build/imagebuilder/base.go
  pkg/controller/build/imagebuilder/base_test.go
  pkg/controller/build/imagebuilder/jobimagebuilder.go
  pkg/controller/build/imagebuilder/jobimagebuilder_test.go
  pkg/controller/build/osbuildcontroller.go
  pkg/controller/build/osbuildcontroller_test.go
  pkg/controller/build/reconciler.go
  pkg/controller/common/mos_state.go
  pkg/controller/common/mos_state_test.go
  test/e2e-ocl/helpers_test.go
  test/e2e-ocl/onclusterlayering_test.go
Labels: lgtm, approved, qe-approved, jira/severity-important, jira/valid-bug, jira/valid-reference
